### PR TITLE
Now the right mysql part is a function fix #3986

### LINKED ISSUE #3986: Installer - "Fatal error: Function name must be a string in install.php on line 971"
Installer cannot execute.   

I was attempting to reproduce the issue reported in the support forum - "Error when uploading large files to forum":
http://www.simplemachines.org/community/index.php?topic=552909.msg3919460#msg3919460

### PR DESCRIPTION
**Pull request by albertlast**
Did modified the wrong mysql part...
this fix now #3986

### CODE REVIEW

**Comment by sbulen** [comment]
I was able to test this just now & all looks OK.   Thanks!

**Comment by albertlast** [comment]
@colinschoen please hav a look

**Comment by colinschoen** [comment]
Will review soon.

**Review by colinschoen — APPROVED** [review]
Thanks for fixing. LGTM, approval

**Pull request merged**
