### PR TITLE
added random_bytes

### PR DESCRIPTION
**Pull request by albertlast**
to protect that we got the depracted message of this function: http://php.net/manual/de/function.mcrypt-create-iv.php
i added the new one random_bytes() function on the the place before we call mcrypt-create-iv().

### CODE REVIEW

**Review by Sesquipedalian — APPROVED** [review]
LGTM

**Comment by jdarwood007** [comment]
Would changing this require any needed password upgrades?

**Comment by Sesquipedalian** [comment]
No, it's just a method for generating the password salt.

**Comment by jdarwood007** [comment]
Thanks, LGTM.

**Pull request merged**
