### PR TITLE
Add remove link to the finished uninstall window

### PR DESCRIPTION
**Pull request by albertlast**
I hope it fit somehow the base idea:
grafik

issue: #5731

### CODE REVIEW

**Comment by LexArma** [comment]
Looks good, but I think from a usability point of view, it might be good if the text was altered to explain the button. For example "The package has been successfully uninstalled, you may now delete the package".

**Comment by Sesquipedalian** [comment]
Just to prevent possible confusion, let’s have a “Delete Package” button and a “Keep Package” button. The second would really just be a link to the Browse Packages page, but it would help admins to know that they don’t have to delete the package. If there is only one button, some admins might think deleting the package is mandatory rather than optional.

**Comment by MissAllSunday** [comment]
@albertlast Can you address the point Sesquipedalian make so this can be merged.

**Comment by albertlast** [comment]
done
grafik

**Review by MissAllSunday — APPROVED** [review]

**Pull request merged**
