### PR TITLE
Only show attachments remaining message

### PR DESCRIPTION
**Pull request by colinschoen**
Per discussion in #4001 only show the number of attachments prior to file selection. 

screen shot 2017-04-06 at 00 26 41

Signed-off-by: Colin Schoen <cschoen@berkeley.edu>

### CODE REVIEW

**Comment by colinschoen** [comment]
@albertlast can you give a quick 👍

**Comment by albertlast** [comment]
ther are no database stuff included and the talk i'm not included.
so i believe that your mean @sbulen .

**Comment by colinschoen** [comment]
Whoops, yes sorry @sbulen

**Comment by sbulen** [comment]
LGTM!

**Comment by colinschoen** [comment]
Thanks for reviewing.

**Pull request merged**
