### PR TITLE
!Bug fix default author email $thisPackage->fetch to $listing->fetch

### PR DESCRIPTION
**Pull request by VBGAMER45**
!Bug fix default author email $thisPackage->fetch to $listing->fetch

Signed-off-by: Jonathan Valentin vbgamer45@gmail.com

### CODE REVIEW

**Comment by live627** [comment]
Looks good to me, but please remember to keep related changes in future requests.
(Each commit here seems unrelated)

Thanks.

**Comment by VBGAMER45** [comment]
Yeah I don't know how that happened. I committed each one separately. I did the pull request online at github after the first commit. Then it seems to have grouped the next two commits in the same request...

**Comment by Oldiesmann** [comment]
Git operates on the assumption that anything committed to a particular branch is related, so if you commit multiple things to the same branch, they'll all get attached to the most recent open PR (regardless of when that PR is opened relative to when things are committed). In order to avoid this, create a separate branch for each set of related changes (or just focus on one thing at a time and wait for the PR to be handled before committing anything else to that branch).

**Comment by VBGAMER45** [comment]
Ok thanks that helps will do that for the future.

**Pull request merged**
