### PR TITLE
Fixes some BBC and Markdown bugs

### LINKED ISSUE #8360: Some Markdown bugs
source fille https://github.com/live627/smf-ultimate-menu/blob/master/README.md

Screenshot 2024-12-15 at 02-08-30 lorem ipsum egestas integer
Screenshot 2024-12-15 at 02-08-30 lorem ipsum egestas integer

### PR DESCRIPTION
**Pull request by Sesquipedalian**
- Fixes #8360 
    - Fixes issue where nested Markdown lists were parsed incorrectly
    - Go back to parsing smileys while parsing BBCode (fixes issue where smileys appeared inside code blocks)
    - Don't interrupt fenced code blocks when code is indented more than four spaces
    - Parses Markdown images correctly
- Smarter list item markers for nested Markdown lists
- Shows line breaks correctly in output from Parser::highlightPhpCode()
- Fixes a bug when a [code] BBC contained the literal string `[code]`
- Correctly parses Markdown emphasis wrapped around inline code, etc.
- Fixes some issues displaying tab characters
- Prevents overflow in code blocks in WYSIWYG editor mode

### CODE REVIEW

**Comment by live627** [comment]
Only remaining problem is images. Still see raw Markdown. Do I need to enable some setting? This fixes all other reported issues.

**Comment by Sesquipedalian** [comment]
Oops. I overlooked the images issues. Thanks for bringing it to my attention.

**Comment by Sesquipedalian** [comment]
Should now be fixed, @live627. Please confirm as soon as you are able. 🙂

**Comment by live627** [comment]
That fixed it. I'm mow  looking at malformed BBCode from https://github.com/live627/smf-custom-forms/blob/master/src/install.txt

Screenshot 2024-12-19 at 00-32-54 Preview of Re lorem ipsum egestas integer

**Comment by Sesquipedalian** [comment]
> That fixed it. 

Excellent.

> I'm mow  looking at malformed BBCode from https://github.com/live627/smf-custom-forms/blob/master/src/install.txt
> 
> 
> 
> Screenshot 2024-12-19 at 00-32-54 Preview of Re lorem ipsum egestas integer
> 
> 

Let's deal with that as a distinct issue.

**Pull request merged**
