### PR TITLE
BBC font tag

### LINKED ISSUE #1768: Text pasted into post can create bad font BBC
I copied the Chrome version from another browser window into the WYSIWYG post editor.
The result was 
[font='Segoe UI', Tahoma, sans-serif]33.0.1750.146, Windows 7[/font]

Which rendered as shown above, because the font BBC cannot accept parameters in that format.
It kind of spoils the wysiwyg thing.  It always looks fine in the wysiwyg editor, but never after parse_BBC gets hold of it.

http://test2.turtleshellprod.com/index.php?topic=34.0

### PR DESCRIPTION
**Pull request by MissAllSunday**
Uses Sam Clark's approach and removes all apostrophes form the tag so parse_bbc can handle it.

fixes #1768

Signed-off-by: Suki suki@missallsunday.com

### CODE REVIEW

**Comment by XinYenFon** [comment]
I paste following (see ss1), then I use source (toggle) things gets fixed (see ss2), also note, if i just paste & post it posts like ss1, if i toggle and post then posts the fixed one.

font-1

font-2

```
[color=#303942][size=2][font='Segoe UI', Tahoma, sans-serif]33.0.1750.146, Windows 7[/font][/size][/color] becomes 33.0.1750.146, Windows 7

Version 33.0.1750.146 -- Original
[font="Segoe UI",Tahoma,sans-serif]Version 33.0.1750.146[/font] -- Try double-quotes instead of single.
[font='Segoe UI' Tahoma sans-serif]Version 33.0.1750.146[/font] -- With an extra layer of quotes
[font=Segoe UI,Tahoma,sans-serif]Version 33.0.1750.146[/font] -- With enclosing double quotes
[font=Segoe UI,Tahoma,sans-serif]Version 33.0.1750.146[/font] -- With enclosing single quotes

[font=Segoe UI, Tahoma, sans-serif]Version 33.0.1750.146[/font] -- No quotes: 
Version 33.0.1750.146 -- No font tag:
[font=Segoe UI]Version 33.0.1750.146[/font] -- Segoe UI only
[font=Segoe UI, Tahoma, sans-serif]Version 33.0.1750.146[/font] -- No quotes:
[font=Tahoma]Version 33.0.1750.146[/font] -- Tahoma
[font=sans-serif]Version 33.0.1750.146[/font] -- sans-serif
Version 33.0.1750.146 -- No font tag
```

**Comment by MissAllSunday** [comment]
The code I added doesn't really fix the multi font issue, it merely strips out any single comma.  SMF still doesn't handle multi font tags and I'm not even sure we have to add support for it since we don't really use them anywhere.

**Comment by XinYenFon** [comment]
oh... then things working (I never ever used font tag in my entire forum life). I literally have no idea if SMF 2.1 should have it or not... If you think its rarely used feature then don't.

**Comment by MissAllSunday** [comment]
I dunno, it would be nice to have parse_bbc to accept multi font tags but I honestly don't know what would be the benefit or if there is any real benefit of adding support for it.

Do we know if there has been a request for this on the forums?

**Comment by XinYenFon** [comment]
Not that I know any.

**Pull request merged**
