### PR TITLE
partly fixes #2885

### LINKED ISSUE #2885: Remove duplicate and obsolete bbcodes and possibly modify others.
While answering an user for a list of all bbcodes for the board, I found many duplicate and obsolete bbcodes in SMF

Worser, these bbcodes are are also included on SMF 2.1. And more horrible changes are made. :(

`[acronym]` = It's a duplicate of `[abbr]` and marked as obsolete on HTML5. on SMF 2.1, it uses <abbr title="$1"> instead of removing the tag. :(

`[br]` = This shouldn't be in SMF. We automatically replace newlines with br tag. Furthermore this also brokes our code too. Newline limitation on signatures are not applied if this code used as newline.

`[black]`, `[white]`, `[red]`, `[green]`, `[blue]` = Another useless and duplicate tag. `[color]` tag should be used instead of this tags. Ironically they somehow set a css value on SMF 2.1.

`[tt]` = Exactly the same as color ones `[font=monospace]` should be used instead, and on SMF 2.1 it's replaced with a CSS value.

`[ltr]`, `[rtl]`, `[bdo]` = Either remove `[bdo]` and keep `[ltr]`, `[rtl]` or remove `[ltr]`, `[rtl]` and keep `[bdo]` instead.
Suggestion: use `[ltr]` and `[rtl]`

`[email]`, `[ftp]`, `[iurl]`, `[url]` = 4 tags, all makes links with different protocols. Why? No one knows. 

`[flash]` = noembed tag is not an w3c standard and they recommend to not use it. See: http://www.w3.org/TR/html5/obsolete.html#obsolete 
Also, play="true" loop="true" quality="high" are not needed, imo.

`[flash]`, `[img]` = validate section should validate ftp:// and ftps:// too.

`[quote]` = Remove `<div class="quotefooter"></div>` It's not used on SMF 2.0 and SMF 2.1. It's also not used on custom themes. 

`[li]` = Should work like `[*]` if the end tag is not properly closed.
`[@]`, `[*]` = Duplicate
`[O]`, `[0]`, `[o]` = Another duplicate
`[+]`, `[x]`, `[#]` = Wow. Another one.

`[chrissy]`, `[kissy]` = ???

### PR DESCRIPTION
**Pull request by Rupurudu**
partly fixes #2885

Signed-off-by: Mustafa Can Elmacı mustafacan@elmaci.net

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Why are we removing the quotefooter div, the browser-specific code for Flash and the browser-specific code for the code tag?

**Comment by XinYenFon** [comment]
we should remove flash support tbh, Facebook & Mozilla (Firefox) already started to complain about it. Firefox blocked flash two times afaik (patched fastly but still).

**Comment by live627** [comment]
> we should remove flash support

+1

**Comment by Rupurudu** [comment]
@Oldiesmann 
Quotefooter div is not used on the theme anymore.
Embed tag is now part of the HTML5 spec, and object is not needed. See here: https://developer.mozilla.org/docs/Web/HTML/Element/embed
I tested the code tag on the mozilla and can't replicate the issue.

@Antes then we need to find another way to add videos to SMF. Some forums still use Flash tag to embed youtube and other video sites.

**Comment by XinYenFon** [comment]
YouTube allows HTML5. Beside SCEditor has YT bbcode support, so there is literally no way we need to support Flash (BBC) inside SMF anymore.

**Comment by live627** [comment]
Why remove the teletype bbcode?

**Comment by Rupurudu** [comment]
Teletype is removed on HTML5 and we can achieve same results with font=monospace

**Comment by Oldiesmann** [comment]
A few more thoughts on this...

First, I'm still not sure why we need to remove tags. I've never seen anyone refer to the large number of tags or things such as glow/shadow as reasons to not use SMF, or why SMF is outdated, etc.

Second, we need to get a plan together here before we start removing tags. For the tags where we're keeping the same functionality but just changing how it's done (colors, email/ftp, etc.), we're probably best off pulling the info from the database and doing a preg_replace on it before sticking it back in there (pretty much similar to how we parse bbcode when displaying things). For the tags which we're just completely removing (shadow, etc.), we should create mods to add them back, and make sure these mods are available when we go final (ideally doing our best to make sure users are aware of the changes and how to get the mods, so we don't get as many complaints and such).

Finally, we're also going to need to make changes to the editor to support this. I haven't looked at the editor code in a while so I don't know offhand how much work is involved, but that's something we can look into.

**Comment by live627** [comment]
> we can achieve same results with font=monospace

That tag already does that.

**Comment by Rupurudu** [comment]
@live627 It's a duplicate.

@Oldiesmann I already said this multiple times, I'm not trying to remove any tag. I'm just eliminating the duplicates. instead of `[green]this text is green[/green]` you just type `[color=green]this text is green[/color]` or instead of typing [tt]monospaced text[/tt] you type [font=monospace]monospaced text[/font]

**Comment by live627** [comment]
This now says there's some conflict somewhere.  @MustafaCan if you fix it I'll merge this in.

**Comment by Rupurudu** [comment]
Done.

**Comment by Oldiesmann** [comment]
We still need to add code to the upgrade to handle replacing the removed tags in posts and PMs...
color tags - replace with [color={color}] and [/color]
bdo and br - replace with empty string (or space?). Not sure if anyone actually used either of these
acronym - replace with abbr

**Comment by Rupurudu** [comment]
Unfortunately, I don't know too much about sql. :disappointed: 

Here's a draft, this should work.

``` sql
UPDATE smf_messages SET body = REPLACE(body, '[br]', '<br>');
UPDATE smf_messages SET body = REPLACE(body, '[acronym=', '[abbr=');
UPDATE smf_messages SET body = REPLACE(body, '[/acronym]', '[/abbr]');
UPDATE smf_messages SET body = REPLACE(body, '[tt', '[font=monospace');
UPDATE smf_messages SET body = REPLACE(body, '[/tt]', '[font]');
UPDATE smf_messages SET body = REPLACE(body, '[bdo=', '[');
UPDATE smf_messages SET body = REPLACE(body, '[/bdo]', '[/ltr][/rtl]');
UPDATE smf_messages SET body = REPLACE(body, '[black]', '[color=#000]');
UPDATE smf_messages SET body = REPLACE(body, '[white]', '[color=#fff]');
UPDATE smf_messages SET body = REPLACE(body, '[red]', '[color=#f00]');
UPDATE smf_messages SET body = REPLACE(body, '[green]', '[color=#f0f]');
UPDATE smf_messages SET body = REPLACE(body, '[blue]', '[color=#00f]');
UPDATE smf_messages SET body = REPLACE(body, '[/black]', '[/color]');
UPDATE smf_messages SET body = REPLACE(body, '[/white]', '[/color]');
UPDATE smf_messages SET body = REPLACE(body, '[/red]', '[/color]');
UPDATE smf_messages SET body = REPLACE(body, '[/green]', '[/color]');
UPDATE smf_messages SET body = REPLACE(body, '[/blue]', '[/color]');

UPDATE smf_personal_messages SET body = REPLACE(body, '[br]', '<br>');
UPDATE smf_personal_messages SET body = REPLACE(body, '[acronym=', '[abbr=');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/acronym]', '[/abbr]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[tt', '[font=monospace');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/tt]', '[font]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[bdo=', '[');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/bdo]', '[/ltr][/rtl]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[black]', '[color=#000]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[white]', '[color=#fff]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[red]', '[color=#f00]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[green]', '[color=#f0f]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[blue]', '[color=#00f]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/black]', '[/color]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/white]', '[/color]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/red]', '[/color]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/green]', '[/color]');
UPDATE smf_personal_messages SET body = REPLACE(body, '[/blue]', '[/color]');
```

**Pull request merged**
