### PR TITLE
(partially) fix #139

### LINKED ISSUE #139: Drafts doesn't seem to auto save.
I set the drafts auto save to 60 seconds, made a new topic and waited a few minutes however no auto save. Didn't seem to auto save, and when I navigated away it didn't have a draft in the show drafts section.

### PR DESCRIPTION
**Pull request by NanoSector**

### CODE REVIEW

**Comment by emanuele45** [comment]
The changes for the upgrade should go into upgrade_2-1_{dbms}.sql ;)

**Comment by NanoSector** [comment]
Was very limited on time, sorry. I'll take a look tomorrow.

**Comment by NanoSector** [comment]
Hope I did it right now manny? :)

**Comment by Oldiesmann** [comment]
Going to close this since it's not signed off and you don't want to redo them

**Pull request closed without merging**
