### PR TITLE
Small change - CLOSED

### PR DESCRIPTION
**Pull request by ghost**
quick way for users to decide if they want icons in nav tabs

### CODE REVIEW

**Comment by MissAllSunday** [comment]
- May be better to change the if condition with a ternary, for simplicity.
- We cannot merge your commit as you didn't sign it.

**Comment by XinYenFon** [comment]
Is this setting really needed theme authors can remove icons if they don't want it in their themes.

-----Original Message-----

**Comment by MissAllSunday** [comment]
I'll be more inclined towards a theme setting, defined in index.template, that way themers doesn't have to manually remove the icons. Just define and set the var.

**Comment by ghost** [comment]
modify it as you wish not a massive issue, giving users more flexibility will save them having to edit the code.  End of day if you dont include easy to make it a mod as alot of people will ask for this.

**Comment by MissAllSunday** [comment]
@Pouvik  This really isn't an user UI, you are assuming all themes will have icons which will not always be the case.

This will be better if there was a var defining if the the current theme uses icons and then and only then show that setting to the users.  Your PR is fine it just lacks the necessary logic to handle all possible cases.

Your last sentence didn't made much sense.

**Comment by ghost** [comment]
Then why dont you respect the fact I have closed this, and add the var yourself and submit this idea in a fix of your own, its not like its hard to do.  Now please respect the fact that this has been CLOSED!

**Comment by MissAllSunday** [comment]
The PR itself is closed yes, the conversation is not, while it is your right to close this, the conversation might still going on since more people can be interested on sharing ideas and/or improvements.

You can chose not to receive notifications for this conversation, thats within your rights too.

**Comment by ghost** [comment]
well I am requesting you drop it, if you like idea then work on it yourself!

**Comment by MissAllSunday** [comment]
Don't see the need to drop this since we are already discussing this idea here. If we agree then a new PR will be submitted, meanwhile discussions will be held right here. Thank you for the idea.

Anyway... back on topic, the $setting var to declare icons usage should be done, dunno about the user setting though, that might be overkilled.

**Comment by ghost** [comment]
discussion has not been on that until now discussion has been on you being ignorant and failing to comply with a request!

**Comment by MissAllSunday** [comment]
Your whole message didn't make any sense.

**Pull request closed without merging**
