### PR TITLE
Changes to spelling of the word smileys

### PR DESCRIPTION
**Pull request by illori**
Signed-off-by: illori illori@simplemachines.org

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Is there really any good reason to change this? We've used the "smileys" spelling since the beginning of SMF (almost 10 years now).

**Comment by illori** [comment]
smileys is not spelled correctly, we should fix it.

**Comment by butch2k** [comment]
Not according to the Oxford dictionnary.

smiley
Pronunciation: /ˈsmʌɪli/
(also smily)

adjective (smilier, smiliest)
informal
smiling; cheerful:
he drew a smiley face

noun (plural smileys or smilies)

(in electronic communications) a symbol that represents a smiling face, typically formed by the characters :-) and used to indicate that the writer is pleased or joking.

**Comment by illori** [comment]
well according to http://www.merriam-webster.com/dictionary/smileys it does not exist

**Comment by butch2k** [comment]
hummmm...
no smilies either ;)
http://www.merriam-webster.com/dictionary/smilies

**Comment by butch2k** [comment]
Using the Google frequency analysis:
http://books.google.com/ngrams/graph?content=smileys%2Csmilies&year_start=1980&year_end=2013

smileys is the most common form.

**Comment by illori** [comment]
VB uses smilie not even smiley

according the wiki [our wiki] smileys is spelled incorrectly, so this is an attempt to fix that so that the wiki can use the correct spelling of the word smilies.

**Comment by Oldiesmann** [comment]
Several sources say "smileys" is correct, and it's been in use for about 10 years now (the entire time SMF has been around), so there's no point in changing it.

**Pull request closed without merging**
