### PR TITLE
Makes [url], not [iurl], when adding a link to selected text in editor

### LINKED ISSUE #4703: iurl
iurl is still present in the editor. Please see this post at SMF

https://www.simplemachines.org/community/index.php?topic=542792.msg3968271#msg3968271

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #4703

Please test this, @smfbigguy.

### CODE REVIEW

**Comment by smfbigguy** [comment]
Works like a charm for me on FF.

**Comment by smfbigguy** [comment]
oops hold on.

**Comment by smfbigguy** [comment]
Yup it works for me. No problems at all.

**Comment by Sesquipedalian** [comment]
Excellent

**Pull request merged**
