### PR TITLE
Bugfix: Responsive Members List

### PR DESCRIPTION
**Pull request by liviuroman**

### CODE REVIEW

**Comment by illori** [comment]
you need to sign off your commits or they can not be merged.

**Comment by liviuroman** [comment]
It hides only the head table.

http://i.imgur.com/xYTEdhY.png

**Comment by illori** [comment]
Does not matter. You still need to sign off on the commit.

**Comment by Oldiesmann** [comment]
@liviuroman You need to sign off on the commit or we cannot accept this.

**Pull request closed without merging**
