### PR TITLE
Add boolean as datatype for tables #5096

### PR DESCRIPTION
**Pull request by albertlast**
i woud like to use boolean on pg side,
but it would create many confusion so i defined the mysql way for pg as default....

issue: #5096

### CODE REVIEW

**Review by tinoest — COMMENTED** [review]
This doesn’t work with UPDATE SET column = NOT column in PGSQL says type must be Boolean

**Comment by albertlast** [comment]
you cant use not.
in pg you would write "update foobar set col = false"
but you can't doit because mysql wouldn't understand this.
so you had to use 0.

**Comment by tinoest** [comment]
When you want to toggle a value you can use NOT in both MySQL and PGSQL, this is accepted for both. Please leave the type as boolean for pgsql to allow this.

**Comment by albertlast** [comment]
Not is not allowed: https://www.postgresql.org/docs/11/static/datatype-boolean.html

**Comment by tinoest** [comment]
> Not is not allowed: https://www.postgresql.org/docs/11/static/datatype-boolean.html

It's not a datatype, its a logical operator.

https://www.postgresql.org/docs/9.6/static/functions-logical.html

As I said UPDATE tableName SET columnName = NOT columnName WHERE id = 1 

Will toggle the value in columName as shown in the table in that link. 


a | NOT a
TRUE | FALSE
FALSE | TRUE
NULL | NULL

**Comment by albertlast** [comment]
i'm sure that you will got no fun out of this,
because the return type are different between mysql and pg which will lead your in issue on php side.

generic style woulde be to use case.

**Comment by tinoest** [comment]
> i'm sure that you will got no fun out of this,
> because the return type are different between mysql and pg which will lead your in issue on php side.
> 
> generic style woulde be to use case.

https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_not

They are the same, other than the handling of values which are not 0 or 1. Although boolean should limit it to null, 0 or 1 anyway in both database engines.

**Comment by albertlast** [comment]
they are not the same,
when you insert/update a field you had to use '1' as string for both systems and
the output of mysql is 1 and on pg side it's t.

**Comment by tinoest** [comment]
PHP treats true and 1 the same aslong as you don't use the === operator. 

This all works other than smf_db_replacement__callback also doesn't support boolean / bool. So you have to use raw instead.

**Comment by albertlast** [comment]
you should use string and as value 0 or 1.

**Comment by tinoest** [comment]
That doesn’t work with pgsql ( or I dont think it does )

**Comment by albertlast** [comment]
http://sqlfiddle.com/#!9/3fe4c8/1/0

works with both rdbms

**Comment by tinoest** [comment]
That doesnt have it in a where clause. It also crashes for me when I try that.

**Comment by albertlast** [comment]
https://www.db-fiddle.com/f/rtPa3h5odAv3bj14YghioM/0
here alternative,
end of the day it work.

**Comment by albertlast** [comment]
@Sesquipedalian the related issue is rc2 please fix it

**Comment by Sesquipedalian** [comment]
According to [this](http://www.mysqltutorial.org/mysql-boolean/), MySQL treats BOOLEAN as a synonym for TINYINT(1), so if we tell it to change a column's type to BOOLEAN, it will transparently set the column to TINYINT(1) without any extra work on our part.

I think that means that all we need to do to solve #5096 is to add a line to smf_db_calculate_type() in DbPackages-mysql.php to set $type_size to null if $type_name is boolean. If so, then something like the following is all we should need, right?

```
function smf_db_calculate_type($type_name, $type_size = null, $reverse = false)
{
	// MySQL is actually the generic baseline.

	$type_name = strtolower($type_name);
	// Generic => Specific.
	if (!$reverse)
	{
		$types = array(
			'inet' => 'varbinary',
		);
	}
	else
	{
		$types = array(
			'varbinary' => 'inet',
		);
	}

	// Got it? Change it!
	if (isset($types[$type_name]))
	{
		if ($type_name == 'inet' && !$reverse)
		{
			$type_size = 16;
			$type_name = 'varbinary';
		}
		elseif ($type_name == 'varbinary' && $reverse && $type_size == 16)
		{
			$type_name = 'inet';
			$type_size = null;
		}
		elseif ($type_name == 'varbinary')
			$type_name = 'varbinary';
		else
			$type_name = $types[$type_name];
	}
	elseif ($type_name == 'boolean')
		$type_size = null;

	return array($type_name, $type_size);
}
```

**Comment by albertlast** [comment]
Would be nice if you think on postgres too.
The changes are the minimum for both db.

Side note tinyint didn't got any size value.

**Comment by albertlast** [comment]
Maybe i got you wrong...
but the code work already in the way like you mention.

i define here how to translate the boolean type:
https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L564

here is than true:
https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L575

and then the boolean get translated to tinyint:
https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L590

**Comment by Sesquipedalian** [comment]
> Maybe i got you wrong...
> but the code work already in the way like you mention.
> 
> i define here how to translate the boolean type:
> 
> [SMF2.1/Sources/DbPackages-mysql.php](https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L564)
> Line 564 in [00a1d62](/SimpleMachines/SMF2.1/commit/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc)
>  			'boolean' => 'tinyint', 
> here is than true:
> 
> [SMF2.1/Sources/DbPackages-mysql.php](https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L575)
> Line 575 in [00a1d62](/SimpleMachines/SMF2.1/commit/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc)
>  	if (isset($types[$type_name])) 
> and then the boolean get translated to tinyint:
> 
> [SMF2.1/Sources/DbPackages-mysql.php](https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L590)
> Line 590 in [00a1d62](/SimpleMachines/SMF2.1/commit/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc)
>  			$type_name = $types[$type_name];

What I am saying is that I don't think we need to do any of that for MySQL. According to the link I gave earlier, MySQL is fine with being told to set a columns type to BOOLEAN, and will happily set and retrieve true and false values from that column. *Internally*, MySQL will convert BOOLEAN to TINYINT(1) when saving data, and covert the 0 or 1 back to a boolean value when retrieving the data. 

So, we don't need to do anything in PHP to convert between BOOLEAN and TINYINT(1). MySQL will take care of all that automatically for us. The only thing we need to do is to make sure that in this function, if the column type is boolean, then `$type_size` is set to null so that we don't end up trying to change the automatic TINYINT(1) into TINYINT(16) or something.

**Comment by albertlast** [comment]
you see the behavior here: https://www.db-fiddle.com/f/ocnZpTzsQmxEadG4Mv9vas/1
yes boolean get converted to tinyint (mysql ingore size value on int datatypes).

But the output get complex (mysql return the values sometimes in 0 and 1, sometimes true and false and pg return this in true and false or t and f,
so the coder need to know what he is doing.

**Comment by albertlast** [comment]
What do we want to do with this pr? @Sesquipedalian

**Comment by Sesquipedalian** [comment]
I'm not sure yet. I'll take a fresh look at it soon and see what I think.

**Comment by albertlast** [comment]
@Sesquipedalian how the fresh look looks like?

**Comment by Sesquipedalian** [comment]
Having looked again, I still think that what I said in https://github.com/SimpleMachines/SMF2.1/pull/5097#issuecomment-468130527 is correct. The best way to solve #5096 is to set $type_size to null when $type_name is boolean. This only applies to the MySQL version.

**Comment by MissAllSunday** [comment]
So, what's the status on this? are we going with setting $type_size to null for mysql when $type_name is boolean?  If so, @albertlast can you do the change?

**Comment by albertlast** [comment]
i can do this,
but we all accept the fact that we got no chance on mysql to reverse the datatype from tinyint to boolean, right?

**Comment by MissAllSunday** [comment]
I'm afraid I'm not following you, are you saying there's some kind of backwards compatibility issue?

**Comment by albertlast** [comment]
when you use this function here: https://github.com/SimpleMachines/SMF2.1/blob/00a1d623a7e2c86c4f9d9b4dfdf96d967618cddc/Sources/DbPackages-mysql.php#L567-L572
you can't detect a boolean field.

**Comment by MissAllSunday** [comment]
Do we need to?  is there a specific case where this can happen?

**Comment by albertlast** [comment]
When the mod try to check if the column is boolean and
use for this the api,
than you would need this function.

**Comment by MissAllSunday** [comment]
I'm afraid I still don't know why we cannot apply the change that @Sesquipedalian suggested.

**Comment by albertlast** [comment]
Since his solution is more complex than my solution (got one line of code) i see no need to change it.

**Comment by MissAllSunday** [comment]
Well, I'm taking about what should be the correct way to handle this issue, if the solution turns out to be more than one line of code or too complex we still need to  do it.

**Comment by albertlast** [comment]
From my POV I would implanted this version and
Wait what happen,
Since it's very special use case, 
I see no issue for the core.

**Comment by MissAllSunday** [comment]
What will happen with the case @tinoest mentioned?

**Pull request closed without merging**
