### PR TITLE
The top topic starters list didn't show everyone correctly

### PR DESCRIPTION
**Pull request by live627**
- Make the code just a little bit cleaner. This codebase could always use some cleanup.
- Optimize a query to remove the filesort and to not use a temporary table. Makes little difference on a SSD, but there you have it.

Fixes issue discussed in https://www.simplemachines.org/community/index.php?topic=562849.msg3993413#msg3993413

### CODE REVIEW

**Comment by albertlast** [comment]
Did you really test you solution?
This solution is slower,
because php needs to do more stuff.

```
<?php
$db_server = 'localhost';
$db_name = 'smf';
$db_user = 'postgres';
$db_passwd = 'asdf';
$connection = @pg_pconnect((empty($db_server) ? '' : 'host=' . $db_server . ' ') . 'dbname=' . $db_name . ' user=\'' . $db_user . '\' password=\'' . $db_passwd . '\'' . (empty($db_options['port']) ? '' : ' port=\'' . $db_options['port'] . '\''));
$loop  = 100;


$start = microtime(true);
for($i = 0; $i < $loop; $i++)
{
    // old
    $sql = '
    SELECT id_member_started, COUNT(*) AS hits
    FROM smf_topics
    GROUP BY id_member_started
    ORDER BY hits DESC
    LIMIT 20';
    $request = @pg_query($connection, $sql);
    $rows = smf_db_fetch_all($request);
    $members = array();
    pg_free_result($request);
    ksort($rows);
}
	
$time_old = microtime(true) - $start;


$start = microtime(true);

for($i = 0; $i < $loop; $i++)
    // new
    {
        $sql =  '
        SELECT id_member_started, COUNT(*)
        FROM smf_topics
        GROUP BY id_member_started';
        $request = @pg_query($connection, $sql);
        //print_r($rows);
        $members = array();
		while ($row = @pg_fetch_row($request))
			$members[$row[0]] = $row[1];
		arsort($members);
		$members = array_slice($members, 0, 10, true);
        pg_free_result($request);;
    }

$time_new = microtime(true) - $start;



var_dump($time_old);
var_dump($time_new);

/**
 * Fetches all rows from a result as an array
 *
 * @param resource $request A PostgreSQL result resource
 * @return array An array that contains all rows (records) in the result resource
 */
function smf_db_fetch_all($request)
{
	// Return the right row.
	return @pg_fetch_all($request);
}
```

D:\Programme\xampp2\htdocs\test13.php:53:float 1.4927799701691

D:\Programme\xampp2\htdocs\test13.php:54:float 1.8526408672333

--> you loose
stop trying to make stuff slower please...

Why you both think php can be faster than a database?

Maybe some addiotion infos for this query the explain look like so:
"Limit  (cost=2198.66..2198.71 rows=20 width=12) (actual time=17.334..17.336 rows=20 loops=1)"
"  ->  Sort  (cost=2198.66..2203.66 rows=2001 width=12) (actual time=17.334..17.335 rows=20 loops=1)"
"        Sort Key: (count(*)) DESC"
"        Sort Method: top-N heapsort  Memory: 26kB"
"        ->  HashAggregate  (cost=2125.41..2145.42 rows=2001 width=12) (actual time=16.938..17.162 rows=2001 loops=1)"
"              Group Key: id_member_started"
"              ->  Seq Scan on smf_topics  (cost=0.00..1739.27 rows=77227 width=4) (actual time=0.011..3.799 rows=77234 loops=1)"
"Planning time: 0.131 ms"
"Execution time: 17.498 ms"

Important for you is that the "temp table" is not written on the hdd,
it's written to the memory like you did in php,
but since your solution transfer more data AND is not optimize for doing this stuff,
your are not able to be fast with this kind of solution.

**Comment by albertlast** [comment]
This pr and pr: https://github.com/SimpleMachines/SMF2.1/pull/5091
fix both the same issue.

**Comment by albertlast** [comment]
I asked my self why you reopen this,
Like I shown, your logic is wrong from the start.

**Comment by live627** [comment]
I accidentally deleted the branch.

**Comment by albertlast** [comment]
I already show you that your pr doesn't tweak anything(because the problem doesn't exists).
So to close this was the right way.

**Comment by live627** [comment]
Oink! I'm a pig!

https://www.simplemachines.org/community/index.php?topic=562849.msg3993583#msg3993583

This is the change there. Note that people have said that this solves their issue.

I'm done arguing with you over this one.

**Review by albertlast — CHANGES_REQUESTED** [review]
This pr is not a improvment.

**Pull request closed without merging**
