### PR TITLE
Fix issue when a time bbc tag is not parsed

### PR DESCRIPTION
**Pull request by dragomano**
If we use any language (except English) we have not worked parsing for time tag:

How to see this problem:

1. Select any language, except English.
2. Post a message with a time BBC tag.
3. Edit this message and view it again.

Signed-off-by: Bugo <bugo@dragomano.ru>

### CODE REVIEW

**Review by BrickOzp — APPROVED** [review]
This problem exists even if english is selected as language.
I have verified that this fix solves the issue.

However this also adds < strong > tags to time. Is that what we want?

**Comment by dragomano** [comment]
We can add any other tag (`span`, etc), it is just for attraction. I thought that if someone uses a timestamp in a text, he would still want to highlight it.

**Comment by BrickOzp** [comment]
After investigated this further it is related to the selected time format, and not the language.
If using a known time format when writing the tag e.g. [time]1973-11-27, 08:43:00[/time], [time]12234345[/time] or [time]yesterday[/time] it works, but not when using [time]14 December 2020 kl. 00:00[/time]

If the date can be parsed it is stored in the db as unix timestamp [time]12234345[/time].
When viewing and modifying it is displayed in the date time format selected e.g. [time]1973-11-27, 08:43:00[/time] or [time]14 December 2020 kl. 00:00[/time].

One solution could be to use use a different date format when modifying so it could be parsed again.

**Comment by BrickOzp** [comment]
The parsing is done in Subs-Post.php and uses strtotime.
Manual says "The function expects to be given a string containing an English date format and will try to parse that format into a Unix timestamp"
I guess that's why it doesn't work with other languages or time formats.

**Comment by BrickOzp** [comment]
But that is another fix and your change is needed anyway.

**Comment by dragomano** [comment]
Should I change `strong` to `span` or `span class="time"`?

**Comment by MissAllSunday** [comment]
The time class adds a float: right instruction that can cause issues with the rest of the posting template, might be good to change it to something new like bbc_time so theme authors can use it if they want to.

As for strtotime for parsing time tags it is indeed another issue

**Review by BrickOzp — APPROVED** [review]

**Review by MissAllSunday — APPROVED** [review]

**Pull request merged**
