### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Randem06**
[Packages.zip](https://github.com/SimpleMachines/SMF2.1/files/4184747/Packages.zip)
Corrected issue in Package Manager that showed that multiple Packages were installed when only one package was installed when the packages had the same package_id but different version numbers.

### CODE REVIEW

**Comment by jdarwood007** [comment]
This is not even close to mergeable in its current state.

**Comment by MissAllSunday** [comment]
Hello @Randem06 we currently use branch "release-2.1" as our main branch, if you want to contribute to this project please make a branch from release-2.1 and make a pull request to it as well:

```
git checkout release-2.1
git checkout -b my_new_branch_from_release
git push my_repo my_new_branch_from_release
```

**Comment by sbulen** [comment]
I suspect this is automated & random.  Gitspam.

**Comment by MissAllSunday** [comment]
Its valid: https://www.simplemachines.org/community/index.php?topic=571775.msg4046007#msg4046007

Just wrong way to contribute.

**Pull request closed without merging**
