### PR TITLE
[WIP] Slight cleanup of CSS

### PR DESCRIPTION
**Pull request by NanoSector**
Doing a few touchups here and there. These will mostly be minor.

### CODE REVIEW

**Comment by jdarwood007** [comment]
@Gwenwyfar or @Antes  This good?

**Comment by Gwenwyfar** [comment]
The padding is aligned with the one in boardindex category description (possibly something else too). Everything else is good.

**Comment by jdarwood007** [comment]
@Yoshi2889 Is this ready to merge?

**Comment by NanoSector** [comment]
Yeah I wanted to do more but I can create new PRs for that, might be easier with merge conflicts too. Go ahead.

**Pull request merged**
