### PR TITLE
Adding HTML support for email templates

### PR DESCRIPTION
**Pull request by asmith20002**
http://www.simplemachines.org/community/index.php?topic=542885.0

As mentioned in the thread, if someone wants to make HTML template, they just need to add _html key to the template set, example:

$txt['admin_approve_remind_html'] = true;
$txt['admin_approve_remind_subject'] = 'Registration Reminder';
$txt['admin_approve_remind_body'] = 'Message body now can have < strong>HTML content!< /strong>';

Also has been tested.

### CODE REVIEW

**Comment by live627** [comment]
Can you sign this off?

**Comment by asmith20002** [comment]
I'm new to git. Having trouble to sign off. Tried editing previous commit description but failed.

**Comment by asmith20002** [comment]
Signed-off-by: asmith20002 asmith_20002@yahoo.com

I'm new to git. Tried to edit the previous commit description but failed.

**Comment by Sesquipedalian** [comment]
You'll need to sign all the commits in your pull request. Directions are [here](https://help.github.com/articles/changing-a-commit-message/). In your case, you'll need to follow the directions under the heading "Amending the message of older or multiple commit messages"

**Pull request closed without merging**
