### PR TITLE
Default avatar not showing in the topheader miniprofile #2360

### PR DESCRIPTION
**Pull request by ahrasis**
This is to fix issue #2360 where default avatar not showing in the
topheader miniprofile.

https://github.com/SimpleMachines/SMF2.1/issues/2360

Fix is not at the theme level as suggested earlier but Subs.php. IMO
this will ensure that no bug for having no avatar since default avatar
is supposed to be always in place.

Do check.

### CODE REVIEW

**Comment by Oldiesmann** [comment]
You need to sign off on your commits or we can't accept them.

**Comment by ahrasis** [comment]
Signed-off-by: Ahmad Rasyid Ismail ahrasis@gmail.com

**Comment by Oldiesmann** [comment]
Unfortunately you've now added completely unrelated commits to this PR. Unless the commits are related, you should either work on one thing at a time or create a separate branch for each thing you want to work on, so you can create separate PRs for each thing.

**Comment by ahrasis** [comment]
I think I better delete this and create branches for each one of them. I am still learning how github actually works

**Pull request closed without merging**
