### PR TITLE
Allow themes to show the latest poster's avatar on board index

### PR DESCRIPTION
**Pull request by marcusforsberg**
Something I wanted to do with my theme Calix but can't since avatars aren't loaded for topics and boards. They should be, IMO, like IPB does it, so themers can choose to show them.

I feel this should be the theme designer's choice, and not done globally as with the available mod(s).

### CODE REVIEW

**Comment by beratdogan** [comment]
Cool. There is a mod for this. But I think this should be theme designer's choice, as well. ;)

http://custom.simplemachines.org/mods/index.php?mod=1103

**Comment by joshuaadickerson** [comment]
I haven't tested it so I'm not going to merge it but it looks good by looking at the code. Hopefully someone merges this.

**Comment by marcusforsberg** [comment]
@grafitus Indeed :)
@joshuaadickerson Thanks for looking at it!

Another thing I want to do with [Calix](https://github.com/marcusforsberg/smf-themes) is display the message icons along with the recent posts in the info centre so I might add something for that as well.

**Comment by eurich** [comment]
ups, you're right.. should have checked the entire file (the related line is hidden in github's interface :P )
.

**Comment by marcusforsberg** [comment]
:D

This is such a small edit I don't think even I would manage to mess it up too bad :P

**Comment by emanuele45** [comment]
I was wondering: since the function is not used in SMF itself and since it's yet another left join, why not make it dependent on a theme setting?
So if the theme wants it it is grabbed, otherwise it is simply avoided.

**Comment by marcusforsberg** [comment]
Good point, works for me!

**Pull request merged**
