### PR TITLE
Popup_container vs sceditor

### LINKED ISSUE #6573: Menu shines through login box
#### Description
The main menu shines through the dimming and the login box.

### Steps to reproduce
1. Logout
2. Click Login
3. Notice the main menu shines through the dimming, and the login box.
menu shines through

### Environment (complete as necessary)
- Version/Git revision: 89c3980d3
- Database Type: MySql
- Database Version:
- PHP Version: 5.6

### Additional information/references
Related to https://github.com/SimpleMachines/SMF2.1/pull/6502/commits/e81ea07a862ec3e7f445db537e901b630c8f0e1a and 
https://github.com/SimpleMachines/SMF2.1/commit/52334481ed17645f07e72d875e928ab1f3d8d61a

Reverting those fixes the problem.

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Should fix this pesky issue this time.
PS: Fixes #6573 

@BrickOzp

### CODE REVIEW

**Comment by BrickOzp** [comment]
Both admin menu and login box works ok with this fix. I don't know what the original problem was, but I have found no new issues after a quick test.

**Review by BrickOzp — APPROVED** [review]

**Comment by DiegoAndresCortes** [comment]
Could we merge this one, should be in before rc4

**Comment by BrickOzp** [comment]
I agree, this bug affects the login box and will be the first thing seen after install for new smf users. This must be merged before rc4. @MissAllSunday?

**Comment by MissAllSunday** [comment]
yep!

**Comment by MissAllSunday** [comment]
Looks good although we will have to be very careful when updating the editor not to remove the change on its css file. Perhaps we can also take a look at some other alternatives like overwriten the css rules

**Comment by jdarwood007** [comment]
If our index.css includes a more specific rule than the sceditor, then it should take presence over the built in sceditor rule.

I wonder if "div. sceditor-container div.sceditor-dropdown div" would work?

**Comment by BrickOzp** [comment]
That fixes the login box shine through and alse https://github.com/SimpleMachines/SMF2.1/issues/6546.
But it is still not clear to me what the original problem was.

**Comment by DiegoAndresCortes** [comment]
Do you want to overwrite this on the index.css instead?? not clear.

Fixes a very hidden issue originally caused by #4885

**Comment by MissAllSunday** [comment]
Yes, this will also mean we will have to make sure index.css is loaded after the editor css file.  We could also see if inline styles can be used too or even !important

**Comment by jdarwood007** [comment]
You don't need to move index.css.  Just make the rule more specific.

```
div.sceditor-container div.sceditor-dropdown div {
	z-index: 4;
}
```
adding ```div.sceditor-container``` makes it more specific than the one in the sceditor.css and now it overrides it.

**Comment by DiegoAndresCortes** [comment]
done

**Review by BrickOzp — APPROVED** [review]
Looks good to me

**Pull request merged**
