### PR TITLE
Updates time zone data to match current TZDB

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Release 2022b of the TZDB includes a rename of `Europe/Kiev` to `Europe/Kyiv`. This PR updates SMF to match.

See https://data.iana.org/time-zones/tzdb/NEWS

Also expands our coverage for time zone fallbacks. This helps to improve time zone support on forums running on older versions of PHP and therefore of the time zone database.

### CODE REVIEW

**Comment by sbulen** [comment]
@Sesquipedalian - is this one ready for review?  (I see you added some changes.)

**Comment by Sesquipedalian** [comment]
Actually, I think a few fixes are still needed. My previous testing missed some things. I'll @ you when it is ready. 🙂

**Comment by Sesquipedalian** [comment]
@sbulen, this is ready for review now. I suggest testing on PHP 7.0.0 (or the earliest version after 7.0.0 that you have available to you), since the relevant code will only kick in when using an outdated version of the TZDB.

**Review by sbulen — APPROVED** [review]
LGTM.

Tested on php 7.1/mysql 5.7.   Kyiv would come up as EEST/EET.

(For some reason couldn't get my php7.0.33 env up & running...🙄)

**Pull request merged**
