### PR TITLE
Third level menus cannot have subsections

### PR DESCRIPTION
**Pull request by live627**
My new theme uses arrows on .subsections, and this fix prevents them from going on the third level menus, as that is the deepest level of nesting that SMF allows.

### CODE REVIEW

**Comment by Arantor** [comment]
I'm curious about whether this will have any repercussions in SMF, or indeed why you need what seems to be a 4th level menu (which is usually bad for usability)? Or have I missed the point?

**Comment by live627** [comment]
Eh what? 4th level?

Currently, SMF 2.1 always adds that class to 3rd level because the condition will always return true.

**Comment by Arantor** [comment]
Surely a third level menu having a subsection would create a fourth level menu?

**Comment by Arantor** [comment]
OK, so I had a look at this again. I'm still not seeing what benefit this provides. I don't get why you need to change core SMF code to achieve this... if the arrows are in CSS, use CSS to select the right thing, if it's JS, use selectors to select the right thing.

I guess I'm just not seeing how this benefits the core. :(

**Comment by Oldiesmann** [comment]
Although SMF shouldn't be adding the subsections class there, the fact that it's causing arrows to show up in your theme but not the default theme indicates that it's a problem with your CSS that's causing the bug to appear.

**Comment by deliciousbamboo** [comment]
> I guess I'm just not seeing how this benefits the core. :(

Thats because there are none, this is a fix the core because of poor theme coding, nothing else

**Comment by Arantor** [comment]
That's what I thought.

**Comment by live627** [comment]
> Thats because there are none, this is a fix the core because of poor theme coding, nothing else

Pretty much the gist (no pun intended) of it.

See my latest commit; my theme does not have that hack, which is why the problem shows.

**Comment by live627** [comment]
Bump. Is this going into the codebase?

**Comment by Arantor** [comment]
Can't be automatically merged for some reason.

**Comment by live627** [comment]
#1396

**Pull request closed without merging**
