### PR TITLE
Search fixes

### PR DESCRIPTION
**Pull request by live627**
This fixes what @Spuds noted in my previous commit on the search engine.

### CODE REVIEW

**Comment by emanuele45** [comment]
Can be merged?

/me knows nothing about search...

/me knows nothing about many things... lol

**Comment by Spuds** [comment]
Its fixes one area of search that is now completely broken in the current repo  .. my other two comments were for items that are also broken in the current repo (e.g. this commit does not break them, nor does it fix them) ... just need to make another commit to fix those relevance constructs (you actually fixed one of them, unfortunately there are two more).

tldr ... I'd say yes, but a couple of more tweaks are still needed, but then again /me can't even get comments right anymore :P

**Comment by Spuds** [comment]
There is still something not right here, TBH I'm not sure all of this is worth doing for adding an integration hook that will not really be used ... Anyway need to look at this a bit more before its merged ...

**Comment by live627** [comment]
Let's say there was a mod to like posts. Should likes get weighted, just as replies are?

**Comment by Spuds** [comment]
Probably dis-likes should get penalized ... but fair enough :)

The current issue is that the code has things like
$main_query['weights']['subject'] = 'some pita query';  defined outside of the arrays you created up top in the code.

These are not going to place nice with
foreach ($main_query['weights'] as $type => $value) 
since they are not arrays.  

Do a search in the code for $main_query['weights'] .. those will need to be changed to the new array key => value structure.

**Pull request merged**
