### PR TITLE
Substitute for array_column() for php 5.4

### LINKED ISSUE #5301: Upgrader - problem with php 5.4 - usage of array_column()
#### Description
Upgrader - problem with php 5.4 - usage of array_column() here:
https://github.com/SimpleMachines/SMF2.1/blob/3f92b91bfec21917d27afa787cf3a7c90cf2949e/other/upgrade_2-1_mysql.sql#L2610

That's my code...  I wasn't aware array_column() was only supported in php 5.5+...  

### Steps to reproduce
1. Attempt a 2.1 upgrade using php 5.4.  It will hang on the new smiley logic.

### Environment (complete as necessary)
- Version/Git revision: Today's
- Database Type: Mysql
- Database Version: 5.7
- PHP Version: 5.4

### Additional information/references

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #5301 

Testing thus far looks good.  Doing further tests.  Getting this out there for visibility/review.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Nice, but it doesn't include any error checking. I recommend pasting [this bit of code](http://php.net/manual/en/function.array-column.php#118831) into upgrade-helper.php instead of that function. Then you won't even need to remove array_column() from the SQL files.

**Comment by Sesquipedalian** [comment]
For the sake of time, I went ahead and implemented that change myself, @sbulen, so don't worry about it.

**Comment by sbulen** [comment]
ACK!  I've been testing a new version all morning...

**Comment by Sesquipedalian** [comment]
Oh. Sorry. 🙁

**Comment by Sesquipedalian** [comment]
For what it's worth, here is what was ultimately merged in: 98d5cfd. I took this PR and then made another commit (0880e56) on top of it.

**Comment by sbulen** [comment]
NP.

I'll do another round of testing with all the new logic to be safe.

**Comment by Sesquipedalian** [comment]
Okay, great. Thanks!

**Pull request merged**
