### PR TITLE
Update Subs.php

### PR DESCRIPTION
**Pull request by grdenrique**
added open reports in moderate menu

Signed-off-by: ElPlayer

### CODE REVIEW

**Comment by live627** [comment]
Please sign this commit off.

**Comment by Oldiesmann** [comment]
@ElPlayer Please sign-off on this commit. We can't use it if you don't sign-off on it.

**Comment by grdenrique** [comment]
sorry, its my first time using github.
i think its done.

**Comment by Oldiesmann** [comment]
Unfortunately it has to be the individual commit, not the entire PR.

Since that was your last commit to your SMF 2.1 repo, you can run this command from the shell to sign off on it without having to submit it again:

```
git commit --append -s
```

**Pull request merged**
