### PR TITLE
Handle 4-byte utf8 in script.js

### LINKED ISSUE #5804: preview didn't support mb4 chars
#### Description
When the preview of replay used,
the mb4 char get filtert out,
when preview of quickreplay is used everything works fine

### Steps to reproduce
1. 🤔
2. 

### Environment (complete as necessary)
- Version/Git revision: head
- Database Type: pg
- Database Version: 11
- PHP Version: 7.3

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=569620
did not testet if the issue exists with mysql.

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #5804 

Tests good so far...  Would appreciate help from different folks trying different things.

(Note when you have a new .js, you usually need to shift-f5 to force reload the page for the new .js to be used...)

### CODE REVIEW

**Comment by sbulen** [comment]
Done testing, in both pg & mysql.  Looked good.  No more erroneous empty message errors & everything was displayed correctly.

I found a separate, similar issue in that BBC and smileys were not honored for subjects in previews or posts.  I will log that separately.

**Comment by sbulen** [comment]
@albertlast - Could you test this one?  You logged the original issue, #5804 .

**Review by albertlast — APPROVED** [review]
works fine

**Comment by jdarwood007** [comment]
@sbulen Is any of the feedback from the similar changes in SMF 2.0 related to any fixes needed for this before merging?

**Comment by sbulen** [comment]
No - this works.  This is the code I back-ported to 2.0 to address.  See # 124

**Pull request merged**
