### PR TITLE
jQuery 3.6.3

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**

### CODE REVIEW

**Review by Sesquipedalian — APPROVED** [review]

**Comment by DiegoAndresCortes** [comment]
New release is now 3.6.3, I'll update the PR later

**Comment by DiegoAndresCortes** [comment]
The newest version is still not served in google cdn yet. It's only a week old or so, I'll wait some more until it's up, but I find it odd that they are two versions behind already.

I updated it regardless as by the time the patch comes out, it might be updated (hopefully).

**Comment by DiegoAndresCortes** [comment]
Seems it can finally be merged, Google added it to the cdn.

**Comment by sbulen** [comment]
Diego - This PR has a merge conflict that needs to be resolved.

**Comment by sbulen** [comment]
Thanks, @DiegoAndresCortes !

**Comment by peteruoi** [comment]
3.6.4 is up on google

**Comment by DiegoAndresCortes** [comment]
Thanks

**Pull request merged**
