### PR TITLE
News fader fix

### PR DESCRIPTION
**Pull request by live627**
This fixes the news fader so it fades items, not cuts them. Also optimised the class for size and speed. In the Javascript world, size and speed do matter. Renamed the class to smc_NewsFader, hopefully for consistency.

### CODE REVIEW

**Comment by marcusforsberg** [comment]
Nice work, I'm actually working on all the JS files right now in an attempt to reduce their size and take advantage of JQuery, nice t see you handled this one! :)

**Comment by live627** [comment]
That one fixed a bug, too.

I also started on optimising the JS, but I'll stop, knowing you're doing it. I only did three functions, so no biggie. :)

**Comment by marcusforsberg** [comment]
I only just started, too, but I've gone over a few files and optimised their file size a bit. I'm sure once I'm done you'll have stuff to comment on, knowing I'm not the best JS author in the world! :D

**Comment by live627** [comment]
mmk. I'll be sure to review your changes.

**Comment by emanuele45** [comment]
Just a reminder about JS: if you change it try to not break backward compatibility (in the end this is not a major release and we would like to keep it as much as possible compatible with work done for 2.0. I know we will break (and we have already broken) some backward compat (that's normal), just let's not break everything ;))

**Comment by emanuele45** [comment]
Forgot to add: the smc VS smf prefix I think was intended, smc was related to what should've been the "common" framework (or whatever), while smf was used for things used only in SMF.
The news fader was probably intended to be part of SMF but not SMC...BTW, at the moment it's just a conjecture, I have no idea if this is the truth or not.

**Pull request merged**
