### PR TITLE
[2.1] Add JS color picker for color input type fields

### PR DESCRIPTION
**Pull request by dragomano**
sshot-4

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
I like https://github.com/mdbassit/Coloris a bit more

**Comment by dragomano** [comment]
Any such script is better than nothing.

**Comment by albertlast** [comment]
the script use gpl, could be a licence issue?
also no mobile/touchscreen version,
which would be less optimal than the default color picker of the browser?

**Comment by dragomano** [comment]
Answer with screenshots from the official site :)

2023-03-24 03_53_25-Download   License - jscolor_ JavaScript Color picker - Vivaldi

2023-03-24 03_55_47-jscolor_ JavaScript Color picker with Opacity (alpha channel) - Vivaldi

You can test it on [the sandbox](https://jscolor.com/sandbox/) page.

**Comment by jdarwood007** [comment]
For 2.1 I do not see us adding this.  Maybe in a future release

**Comment by albertlast** [comment]
> Answer with screenshots from the official site :)
> 
> 2023-03-24 03_53_25-Download License - jscolor_ JavaScript Color picker - Vivaldi
> 
> 2023-03-24 03_55_47-jscolor_ JavaScript Color picker with Opacity (alpha channel) - Vivaldi
> 
> You can test it on [the sandbox](https://jscolor.com/sandbox/) page.

yea so possible license issue and "mobile view" doesn't exists.

not the best sollution in my pov

**Comment by Sesquipedalian** [comment]
SMF is released under a BSD-3 licence, which means SMF can't include code released under the GPL. GPL code can include BSD-3 code, but not the other way around.

**Comment by DiegoAndresCortes** [comment]
> "mobile view" doesn't exists.

It works fine on mobile, not sure what you mean, behaves like any other input.

**Comment by dragomano** [comment]
Ok, I can change this to https://github.com/mdbassit/Coloris. It uses the MIT license.

**Comment by live627** [comment]
- Closing this in favor of #8172

**Pull request closed without merging**
