### PR TITLE
Fix delete of fulltext index for pg

### PR DESCRIPTION
**Pull request by albertlast**
PG got different syntax for deleting index.

Atm we can't delete the ftx.

### CODE REVIEW

**Comment by jdarwood007** [comment]
Its hard coded?

**Comment by albertlast** [comment]
It's same the code from above, where the index get deleted.

**Comment by frandominguezl** [comment]
I don't remember the coding standards, but I believe you should actually use curly braces if the if/else have more than one line

**Comment by albertlast** [comment]
@sbulen should this not be a part of the next release?

**Review by sbulen — APPROVED** [review]
LGTM.  Tested adds & deletes in pg (14) & mysql (8.0)

**Comment by sbulen** [comment]
& thanks for the contributions, @albertlast !

**Pull request merged**
