### PR TITLE
 Fixes moderation menu item showing when warning system has been disable...

### PR DESCRIPTION
**Pull request by jdarwood007**
...d

Signed off by me

### CODE REVIEW

**Comment by live627** [comment]
Sign off.

**Comment by jdarwood007** [comment]
Yeah, I forgot to.  I did sign the agreements in the past though so I am still good.

**Comment by live627** [comment]
The CLA still applies? I was told it didn't anymore...

**Comment by emanuele45** [comment]
Oh, who knows what applies... not even the Doctor can know that. lol

**Comment by illori** [comment]
CLA does not apply to what is sent on github, it would be best for you to sign off your commits anyway.

**Comment by jdarwood007** [comment]
Don't make me recommit to just do +s.  The fixed code isn't even mine, it comes from the ManageSettings.php file where we detect if we allow access to that section or not.

**Comment by illori** [comment]
i believe in the past it has been accepted to edit the initial post for the PR and sign it, or i believe it is possible to edit the commit messages. i believe @emanuele45  knows about that

**Comment by XinYenFon** [comment]
I also want to add, this changes also included in PR #548

**Comment by jdarwood007** [comment]
Yea that was by accident.  I don't want to try and fix it.

**Comment by jdarwood007** [comment]
Eeh.. I'm not sure..

**Comment by Oldiesmann** [comment]
GitHub is apparently messing things up. Because the commit from this one got added to #548 as well (though that change was later undone further along in that PR), it's marking this one as having been merged in, when in fact it wasn't.

@jdarwood007 You'll have to submit a new PR for this (and please sign off on it this time :stuck_out_tongue: ) since GitHub decided it knows better than I do :smile:

**Comment by jdarwood007** [comment]
Hmm, it won't let me submit it again.  I will have to rebranch it again most likely and issue that request.

**Pull request merged**
