### PR TITLE
! [Upgrade] Closures caused syntax errors in upgrade.php for php < 5.3.8

### PR DESCRIPTION
**Pull request by AngelinaBelle**
ref: #1798 

However, there is still an error: QueryString.php is loaded before the php version check is done, causing syntax error for php v 5.2.

Signed-off-by: Angelina Belle angelinabelle@hotmail.com

### CODE REVIEW

**Comment by live627** [comment]
Sooo, status?

**Comment by AngelinaBelle** [comment]
I was told this fix was not wanted.

**Comment by live627** [comment]
Mind blown.

**Comment by Dragooon** [comment]
No it's wanted but this fix alone won't fix for < PHP 5.3, a file or two needs to be included after ensuring the requirements are met. Although by this time they've already overwritten all the file so most of the things are messed up but we can still prevent the DB changes

**Comment by AngelinaBelle** [comment]
http://www.simplemachines.org/community/index.php?topic=523980.msg3709746
Neither the PM nor the lead dev weighed in, but seems to be the general consensus among the participants.
This much is tested, and I coded the next bit, but did not test it.

The point seemed to be that, if anyone has gone so far as to upload all the files, their website is already messed up, so it hardly matters that the upgrades fails on a php syntax error rather than gracefully explaining to them that they need to upgrade php, and so it would be a waste of the team 's time to test this.

I don't agree, but it is not worth my time to fight a decision that seems already to have been made.
And it is possible that this is currently seen as a low priority that might be taken up later.  Who knows.  

The other bit of work I did is in https://github.com/AngelinaBelle/SMF2.1/tree/patch-2

**Comment by AngelinaBelle** [comment]
Oops.  Was typing while you posted, dragoon. 
Ok then.  A second pull request #1910  should finish that off.  But I have not tested #1910

**Comment by BitFros7y** [comment]
Why just not require 5.3.8 (or even never?) Every host has at least 5.3.29 as PHP version, just because many people use closures. And most hosts even have 5.4.31 version as its one of the latest stable releases. And current official stable release is 5.5.15 (at least atm). Many frameworks pushed their required version for php to 5.3.8 just because of the closures, so why apply these fix if we can just push php version requirements and use all new stuff in the same time? If you ask me, i would even skip 5.3 and jump right to 5.4 as when the 2.1 comes to beta, PHP 5.3 would be old and 5.4 will be supported everywhere (If it isnt already...)

**Comment by Dragooon** [comment]
@qICEp: We are PHP 5.3.8+, this PR was exclusively for upgrade.php to support PHP 5.0+ so that if an user is upgrading on a server that doesn't have PHP 5.3, it can notify them instead of throwing a parse error.

**Comment by Oldiesmann** [comment]
Due to the way PHP works, this is really the only way we can properly tell them their version is too old. It's ugly, but it's probably the best solution.

**Comment by Oldiesmann** [comment]
Is this something we still want to fix? If so we should probably do so before we release Beta 1.

**Comment by Dragooon** [comment]
Closing this, see #2535

**Pull request closed without merging**
