### PR TITLE
Integrate personal message

### PR DESCRIPTION
**Pull request by ghost**
Changes to the Integrate personal message hook.

Change $from['username'] to $from
Move the hook near the end to gain more data.
Send more data to the hook, the pm ID and the $log array.

### CODE REVIEW

**Comment by emanuele45** [comment]
MAS could you please change the target branch of the PR to development or release-2.1?
The one on the SMF repo, when you send the pull request, on the left.
You should be able to change it from here:
https://github.com/MissAllSunday/SMF2.1/pull/new/SimpleMachines:master...MissAllSunday:integrate_personal_message

Thanks! ;)

**Comment by ghost** [comment]
OK I think I got it, is this a special occasion or should I send all pull request to this branch? 

mmm, looks like it created another one rather than updating this one :(

**Comment by emanuele45** [comment]
All pull requests should be sent to release-2.1 (from now on bug fixes) or development (new features and work for future releases), master is here only to hold releases (i.e. when a release is ready it will be merged to master).

**Comment by ghost** [comment]
OK, good to know :P  might as well close this one while I'm here.

**Pull request closed without merging**
