### PR TITLE
Fixes found while pack + language files version to 2.1

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by emanuele45** [comment]
Now that I've sent the PR I'm wondering: is that a good moment to update the version of the language files or is it better to wait until ...?

**Comment by Trekkie101** [comment]
I wouldn't have them sent for translation for a little bit yet. If it's ok I'd like to go through them and look for more oddities?

**Comment by emanuele45** [comment]
For me it's the same, I just changed them because I noticed the upgrade was complaining it was not able to find the proper language files. :)

**Comment by emanuele45** [comment]
@Trekkie101, re-reading your comment I feel I didn't explain well what I wanted to say: I was just asking if it was a good time to change the line in the language files that defines the version of the language file itself [this commit](https://github.com/emanuele45/playpen/commit/c1c63e65466b568d761cc277acf1c983bea1bfcd) in particular.

Send the files for translation could be something for the beta.

**Comment by Trekkie101** [comment]
Ah right, no effect to me then :)

**Pull request merged**
