### PR TITLE
delete Errrors, change filter type based on column fixes #6087

### LINKED ISSUE #6087: Database error: ERROR:  operator does not exist: inet ~~ unknown
#### Description
Using a revision from 6 months ago.
Had a couple of errors caused by a single (guest) user. Clicked on the IP filter icon in the ACP Error Log screen, then clicked the "<s>Remove selected</s>Remove all filtered results" button. Result:
```
Type of error: Database error
Database error: ERROR:  operator does not exist: inet ~~ unknown
LINE 3:    WHERE ip LIKE '1.2.3.4'
                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
https://forum.[...].de/index.php?action=admin;area=logs;sa=errorlog;desc;start=15;filter=ip;value=1.2.3.4
/home/[...]/public_html/Sources/ManageErrors.php (line 358)
```

### Environment (complete as necessary)
- Version/Git revision: Github version from around 2019-10-11, maybe af31e402a6d5172304dae403b8268ebd8ccff75d
- Database Type: postgres
- Database Version: 9.4.26-0+deb8u1
- PHP Version: 5.6.40+dfsg-0+deb8u10

### PR DESCRIPTION
**Pull request by albertlast**
Fixes #6087

### CODE REVIEW

**Comment by m4z** [comment]
You're awesome! Thanks!

**Comment by albertlast** [comment]
well look like i did used the wrong var for the check...

**Comment by m4z** [comment]
Hmm, basically the same problem:
```
ERROR: operator does not exist: inet ~~ inet
LINE 3: WHERE ip LIKE '1.2.3.4'::inet
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
File: /home/[…]/public_html/Sources/ManageErrors.php
Line: 360
```

**Comment by m4z** [comment]
Works wonderfully, thanks again!

**Pull request merged**
