### PR TITLE
Tweaks CSS for insert menu for small images

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Closes #7735

Rather than changing the min-height of the preview wrapper, this adjusts the z-index of the menu div and the overflow properties of the relevant container divs. It also adjusts the border-radius on the corners of the file size progress bar, because I was formerly relying on the overflow properties to take care of hiding those corners where they would otherwise spill outside the rounded corners of the container.

### CODE REVIEW

**Comment by sbulen** [comment]
@Sesquipedalian - I'm testing & comparing this to the other solution.

I don't think this one fixes the typo on line ~33 that is causing console warnings (and invalidates the css).

**Comment by Sesquipedalian** [comment]
I'll add a fix for that later today.

**Comment by Sesquipedalian** [comment]
@sbulen: Done.

**Comment by sbulen** [comment]
After comparing the two, I prefer the alternate approach.  Looks less cluttered.

**Comment by Sesquipedalian** [comment]
As you wish.

**Review by DiegoAndresCortes — APPROVED** [review]

**Comment by jdarwood007** [comment]
Is this still making 2.1.5?  I forgot if another decision was made.

**Comment by sbulen** [comment]
Yes.  We've seen other examples of overflow reported on the forum.  This acts as a safety net...

**Comment by Sesquipedalian** [comment]
> Yes.  We've seen other examples of overflow reported on the forum.  This acts as a safety net...

In light of @DiegoAndresCortes approval and this statement, I will go ahead and merge now.

**Pull request merged**
