### PR TITLE
Clarify file type

### PR DESCRIPTION
**Pull request by colinschoen**
http://www.simplemachines.org/community/index.php?topic=505692.0

### CODE REVIEW

**Comment by matthew-kerle** [comment]
Yeah, I read the thread. I still think it might be best to put "ie." or something similar so it doesn't appear to be the only file type.

**Comment by illori** [comment]
@colinschoen please update your PR per the suggestion in the thread

**Comment by matthew-kerle** [comment]
Colin, any word here? I'd like to get this in.

**Comment by Arantor** [comment]
Well, there are only two formats accepted in the bowels of the package system (which this sort of reuses), which means you're either dealing with .zip or .tar.gz/.tgz (which are the same thing with a different name)

You could just list all three, or as a best compromise, .zip/.tar.gz even though pretty much every theme does say .zip on it. (And technically, it would be e.g. not i.e. if you're getting picky. e.g. is for giving an example, i.e. is for stating 'that is to say' for a definite answer rather than an example)

**Comment by Arantor** [comment]
I actually took the comments above into consideration to reword it, and also in future please note that we cannot merge in commits that are not signed off. Signing off constitutes providing a DCO for the commit in question.

**Comment by illori** [comment]
thanks arantor.

**Pull request closed without merging**
