### PR TITLE
Droped reconnect logic in mysql fixes #4516

### LINKED ISSUE #4516: Persistent connection issue (2.0 & 2.1)
This was reported by the forum user nend earlier, but I think it's important enough to put here.   

$db_persist is not declared as a global in smf_db_query, and it is needed to support persistent connections:
```
		// Fall back to the regular username and password if need be
		if (!$db_connection)
		{
			if (empty($db_persist))
				$db_connection = @mysqli_connect($db_server, $db_user, $db_passwd);
			else
				$db_connection = @mysqli_connect('p:' . $db_server, $db_user, $db_passwd);
		}
```

In a related issue, sessionWrite ends up creating new db connections using this logic, since the connection seems to be getting closed before the session is written.  Persistent connections may help reduce the # of db connections.  (I have confirmed this in 2.0, I believe it will be an issue in 2.1 as well.)

### PR DESCRIPTION
**Pull request by albertlast**
Since the reconnect didn't exists in mysql_* world and smf 2.0.x works fine with it and
i see more issues then solutions about this logic.
So i came to the idea to drop the logic.
Issue: #4516

### CODE REVIEW

**Comment by sbulen** [comment]
I gave this one a shot but I'm now getting lots of errors, just bringing up posts:
```
Warning
: mysqli_prepare() expects parameter 1 to be mysqli, null given in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\Sources\Subs-Db-mysql.php
on line
973


Warning
: mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, null given in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\Sources\Subs-Db-mysql.php
on line
981


Warning
: mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, null given in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\Sources\Subs-Db-mysql.php
on line
982
```

**Comment by albertlast** [comment]
Oops didn't notice that this is the open pr...
But like i ask in the issue:

@sbulen are ther more warning from other files/line of code?
Or ways to reproduce this.

**Comment by sbulen** [comment]
I just did a vanilla 2.1 install, & navigated to the Welcome message.

**Comment by albertlast** [comment]
Moved the install file from others,
install smf4 fresh
jump to welcome post
nothing happen

only the firstindex error appears,
because this got fixed in a different pr.

**Comment by albertlast** [comment]
@Sesquipedalian @colinschoen can we merge this?

**Comment by sbulen** [comment]
I have retested, & this looks OK now.

**Pull request merged**
