### PR TITLE
Makes language clearer #4699

### PR DESCRIPTION
**Pull request by frandominguezl**

### CODE REVIEW

**Comment by frandominguezl** [comment]
I just realized that the string I replaced this one for is "Show Drafts", with the 'D' of drafts' uppercase. The rest in the language file are not uppercase I wonder if I should replace them all with the 'D' in upper or replace just the first one with the lowercase.

**Comment by Sesquipedalian** [comment]
Change the string to "Show drafts" (lowercase "d"). For consistency's sake in the profile summary view, please also change the values of `$txt['showPosts']`, `$txt['statPanel']`, `$txt['buddy_add']`, and `$txt['buddy_remove']` to use lowercase on their second words.

**Comment by frandominguezl** [comment]
Done, thanks for revieweing this. I believe there are a lot of language strings that needs to be fixed to gain consistency. Let's see if I can find some time and review a bunch of them.

**Review by Sesquipedalian — APPROVED** [review]

**Comment by Sesquipedalian** [comment]
Can you also do `$txt['buddy_add']`, and `$txt['buddy_remove']`?

**Comment by frandominguezl** [comment]
Is it needed for this PR? As I said I have thoughts of doing a language strings review.

**Comment by Sesquipedalian** [comment]
I'd prefer it. I'm trying to make things consistent here:
screen shot 2018-06-27 at 12 34 05 pm

A broader review of the strings is a great idea for later, but for now I just want to make everything consistent in that one place.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
