### PR TITLE
font family Signed-off-by: snrj <snrj_od_@hotmail.com>

### PR DESCRIPTION
**Pull request by snrj**
fix
Signed-off-by: snrj snrj_od_@hotmail.com

### CODE REVIEW

**Comment by MissAllSunday** [comment]
I get a Warning: preg_match(): Compilation failed: unmatched parentheses  on PHP 5.5.12 when I apply this change

**Comment by MissAllSunday** [comment]
Is there any specific reason as to why we aren't using the old regex from 2.0? Seems to still do the trick, less convulsive, easier to read too.

Been searching but cannot find anything, I suppose is because the way the new editor works or some compatibility with old BBC with simple commas?

**Comment by live627** [comment]
The one in 2.0 does not support commas.

**Comment by MissAllSunday** [comment]
And where does this commas come from? Why was it necessary to add support for commas? is there any bug report you can link?

Again, I'm trying to find any relevant info so I can fix this, if you have any relevant info, please provide as much details as you can.

**Comment by Oldiesmann** [comment]
See #1768...

**Comment by MissAllSunday** [comment]
It seems that is a different issue?  the tag font has been broken for way longer than that bug report.

If the change to the font tag was made to address that issue, I would assume whoever did that would had closed the bug report on a commit or something like that.

**Pull request closed without merging**
