### PR TITLE
Add default alt for toggle collapse

### LINKED ISSUE #7607: Tooltip on Category buttons on hover
#### Description
The upshrink/downshrink buttons attempt to show "Show Category" when collapsed & "Hide Category" when not.

But it always says "Show Category"...

### Steps to reproduce
1. Hover over the Show/Hide Category buttons
2. Expand/Collapse

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL
- Database Version: 8
- PHP Version: 8.1

 ### Additional information/references
https://www.smfhelper.com/index.php?topic=1194.0

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Fixes #7607

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
PS: Moderation didn't have the titles, so wasn't displaying them until you change their state.

**Comment by sbulen** [comment]
How do we normally do these hovers?  Is this consistent with others?

**Comment by DiegoAndresCortes** [comment]
With script tags in the template.
With this it will always have a default value for them.

**Review by sbulen — APPROVED** [review]
LGTM.  Thanks, Diego!

**Pull request merged**
