### PR TITLE
Fixes errors about undefined variables during install

### LINKED ISSUE #8221: [3.0] Installer needs General language file?
The installer uses formatMessage for `$txt['install_welcome_desc']` but this method will fail when it attempts to get $txt['lang_locale'] because the general language file is not loaded in the installer.

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #8221

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
`Uncaught TypeError: Cannot assign null to property SMF\User::$smiley_set of type string in \Sources\Theme.php:2610 Stack trace: #0\Sources\Theme.php(2375): SMF\Theme->fixSmileySet() #1 \Sources\Theme.php(260): SMF\Theme->initialize() #2 \Sources\ErrorHandler.php(605): SMF\Theme::load() #3 \Sources\ErrorHandler.php(296): SMF\ErrorHandler::setupFatalContext('Please try agai...') #4 \Sources\Db\APIs\MySQL.php(267): SMF\ErrorHandler::fatal('Please try agai...', false) #5 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #6 \install.php(179): DatabasePopulation() #7 {main} thrown in \Sources\Theme.php on line 2610`

**Comment by Sesquipedalian** [comment]
Can you try again now?

**Comment by DiegoAndresCortes** [comment]
I get this:
`Table 'smf_calendar' doesn't exist`
I have 71 tables and I'm supposed to have 72? Odd

**Comment by Sesquipedalian** [comment]
Latest commit should fix that.

**Comment by DiegoAndresCortes** [comment]
Finally reached step 3 but got this:

`Some of the queries were not executed properly. This could be caused by an unsupported (development or old) version of your database software.`

   ```
 Line #1612: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO smf_categories
    VALUES (1, 0, 'General Category', '', 1)' at line 33
```
I'm running MySQL 8.0.36

And then after completing all of the steps:
`Uncaught TypeError: Cannot assign null to property SMF\Category::$name of type string in \Sources\DynamicPropertyHelper.php:197 Stack trace: #0 \Sources\DynamicPropertyHelper.php(122): SMF\Category->customPropertySet('name', NULL) #1 \Sources\DynamicPropertyHelper.php(110): SMF\Category->__set('name', NULL) #2 \Sources\Category.php(819): SMF\Category->set(Array) #3 \Sources\Category.php(318): SMF\Category->__construct(1, Array) #4 \Sources\Actions\BoardIndex.php(384): SMF\Category::init(1, Array) #5 \Sources\Actions\BoardIndex.php(63): SMF\Actions\BoardIndex::get(Array) #6 \Sources\ActionTrait.php(55): SMF\Actions\BoardIndex->execute() #7 [internal function]: SMF\Actions\BoardIndex::call() #8 \Sources\Forum.php(263): call_user_func('SMF\\Actions\\Boa...') #9 \index.php(146): SMF\Forum->execute() #10 {main} thrown in \Sources\DynamicPropertyHelper.php on line 197`

**Comment by Sesquipedalian** [comment]
Bleh. Apparently I messed up many semicolons in the .sql files.

Can you try one more time now?

**Comment by DiegoAndresCortes** [comment]
I got this oddball but it's TEXT type... ?

`Field 'exdates' doesn't have a default value`

Other than this, success.

**Comment by Sesquipedalian** [comment]
> I got this oddball but it's TEXT type... ?
> 
> `Field 'exdates' doesn't have a default value`

image

That makes no sense whatsoever.

> Other than this, success.

Good. I'm going to merge this now. We can figure out whatever the heck that weird error was afterward.

**Pull request merged**
