### PR TITLE
#7601 Check is exist template_layers.

### PR DESCRIPTION
**Pull request by vsc55**

### CODE REVIEW

**Comment by sbulen** [comment]
See comments in issue writeup.

We need to see steps to reproduce, so we can properly test before/after fix.

**Comment by jdarwood007** [comment]
For a fix I would suggest:
```foreach ($context['template_layers'] ?? [] as $layer)```

**Comment by sbulen** [comment]
The problem here is we don't know what the actual issue is.  Both the issue & PR writeup are blank.

I believe we were seeing this error early in the attachment changes, i.e., I believe this was a 2.1.1 or early 2.1.2 issue that has since been resolved.  

To confirm this, we need more info, e.g., steps to reproduce.  And to confirm it still exists with current code.

**Comment by vsc55** [comment]
Hi @sbulen,
The version of smf is 2.1.2.
I don't know exactly how it happened, I saw it in the error logs.
It could be caused by creating a new subforum but I can't confirm it.

**Pull request closed without merging**
