### PR TITLE
Update .scrutinizer.yml

### PR DESCRIPTION
**Pull request by live627**
This will tell Scrutinizer CI how we want our whitespace and braces.

### CODE REVIEW

**Comment by jdarwood007** [comment]
Mind adding this change in as well?
https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/migrate_to_new_php_analysis

It is supposed to improve the run time.

**Comment by live627** [comment]
Let's see how it works...

**Comment by live627** [comment]
it failed... the machines plot against us.

**Comment by jdarwood007** [comment]
Looking good.  Any other changes?  That build ran in 5 minutes, versus the 30+ minutes the old builds ran.

**Comment by jdarwood007** [comment]
May want to adjust spacing: https://scrutinizer-ci.com/g/SimpleMachines/SMF2.1/inspections/fcd30b73-c591-4c21-af2a-247b3a3d00fc/patches

**Comment by live627** [comment]
aaand it finished in the time it took me to pack and install a new  light bulb.

**Pull request merged**
