### PR TITLE
theme.js jQuery Conversion

### PR DESCRIPTION
**Pull request by ghost**
Since jQuery is being used in 2.1, we might as well take full advantage of that. There should be more  conversions coming in the future.

### CODE REVIEW

**Comment by ghost** [comment]
What the HECK!! Don't worry, I'll get the hang of this yet. :angry:

**Comment by live627** [comment]
Protip: Create a new remote from the main repo and base your branch off it.

**Comment by joshuaadickerson** [comment]
Looks good. I haven't tested it but it looks a lot nicer than pure JS. Definitely easier to read and should be easier for users.

**Comment by ghost** [comment]
Thanks, guys.

**Pull request closed without merging**
