### PR TITLE
Enable file_hash for people requires to do thing with attachment

### PR DESCRIPTION
**Pull request by XinYenFon**
Dunno if this posses any security risk directly but, this will enable people to do some modules (like MarkDown parsing via Attachments etc...)

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
Maybe add **fileext** too?

**Comment by XinYenFon** [comment]
afaik SMF holds all attachments in .dat format, not in original format.

**Comment by DiegoAndresCortes** [comment]
Well not sure really, but it's still a value in the database for when you download the attachment I think

**Comment by SychO9** [comment]
> afaik SMF holds all attachments in .dat format, not in original format.

that's not what he meant, smf saves the extension of the attachment in the `fileext` column

**Comment by Sesquipedalian** [comment]
Can you give a bit more explanation of why you'd need the file hash, @XinYenFon? That's really only meant for internal processing, and I'm having trouble imagining a situation in which something like a Markdown parsing mod would need the hash rather than just the URL. I'm not saying no, but I'll need some more info before I can decide whether to say yes.
> Maybe add **fileext** too?

That sounds like a reasonable idea, sure.

**Comment by XinYenFon** [comment]
SMF pushed items to download not to view, you can't use PDF viewer via attachments for a reason, and parser can't parse the content since it forces to download, that's why you need to go root folders and access directly.

**Comment by SychO9** [comment]
So it's so that you can directly access the file from the browser using the file hash ??

**Comment by XinYenFon** [comment]
> So it's so that you can directly access the file from the browser using the file hash ??

No, I use path to access the files, -just double checked- SMF already disallows you to do direct access to attachment files even if you know the full path
> eg: ../attachments/1_8239ba7c49e755371598e8290f884a0804ba5483.dat

This should give better idea, how I do it -warning eye bleeding moment-

```
	// I have good & bad ideas, this one seems orrible!
	if (!empty($message['attachment']))
	{
		global $boarddir;

		foreach ($message['attachment'] as $attachment)
		{
			// I have good ideas and bad ideas, this feel like horrible but oh well...
			if ($attachment['file_ext'] == "md" || $attachment['file_ext'] == "mdx") {
				require_once("./parsedown.php");
				$guide_raw_file = $boarddir. '/attachments/' . $attachment['id'] . '_' . $attachment['file_hash'] . '.dat';
				$guide = file_get_contents($guide_raw_file);
				$guide_output[] = Parsedown::instance()->text($guide);
			}
		}
	}
```

**Comment by SychO9** [comment]
Ah, in that case we do not need to load `file_hash` for that, just use the `getAttachmentFilename()` function, use it like so:

```php
$filepath = getAttachmentFilename($attachment['filename'], $attachment['id_attach'], $attachment['id_folder']);
```

it will give you the full path to the attachment file.

**Comment by XinYenFon** [comment]
well, single_post does not load those options but, nvm I'll handle this via custom query.

**Pull request closed without merging**
