### PR TITLE
Better looking error log

### PR DESCRIPTION
**Pull request by albertlast**
I saw this version from @live627 at elkarte: https://www.elkarte.net/community/index.php?topic=4910.0
and i liked so i created a smf version.

Old:
grafik
New:
grafik

I removed the magnifier from the file and place the filter function on the word "File"

Maybe @Antes or @Gwenwyfar could say about this something.

### CODE REVIEW

**Comment by XinYenFon** [comment]
with all due respect but new one looks more complicated.

**Comment by albertlast** [comment]
Where is in your eyes the complexity?
I mean the time formation are on the right,
the content on the left.
Less space used in the height.

**Comment by Gwenwyfar** [comment]
Looks better for me. What exactly is "::1" supposed to be, though?

**Comment by albertlast** [comment]
::1 is the ip address and ich1 is my nickname in my test bord.

**Review by Gwenwyfar — APPROVED** [review]

**Comment by frandominguezl** [comment]
Can't test this right now, but just to check, does it keeps responsive the design, right?

**Comment by Gwenwyfar** [comment]
Yeah, pretty much everything in Curve2 is in percentages, so it scales to a fair amount. Any smaller details can be sorted out later.

**Comment by albertlast** [comment]
Old:
grafik
New:
grafik

But i got not so mutch knowledg about design stuff,
so maybe some improvment we could also here

**Comment by frandominguezl** [comment]
Fine by me.

**Comment by live627** [comment]
the icons should be unselectable

**Comment by albertlast** [comment]
the icons(magnifier?) are needed to filter one session/user/etc...
i see no alternative way to implement this.

**Comment by albertlast** [comment]
Possible alternative solution would be to replace the "File:" with the icon.
grafik
The user experience could be here more consistent.

**Comment by albertlast** [comment]
The last commit move the line number into the file:
grafik

**Comment by illori** [comment]
i assume that is the session id on the right side? why do we need that logged in the first place? IMO to most admin that is not necessary to figure out the errors cause.

even to a point the IP address is not that much required.

**Comment by Sesquipedalian** [comment]
I would keep the IP address. It can be relevant for certain types of errors. But the session id is useless. It would be much more useful to include the member id of the member who triggered the error.

**Comment by Sesquipedalian** [comment]
> It would be much more useful to include the member id of the member who triggered the error.

Derp. We already record that in the log. Never mind. 😅

**Comment by albertlast** [comment]
Since you can get multiple sesson from on ip i see no advantage to removed this.
Also the session id is already on last position and
with the free space we win nothing,
BUT we could work like git and only show the last/first x chars.

Old:
grafik
New:
grafik

**Comment by XinYenFon** [comment]
For better responsiveness, add the following after (responsive.css);
```
	#admincenter input[type="text"], #quick_search input[type="search"],
	#admincenter select, #quick_search select {
		width: 90%;
	}
```
```
	.error_info {
		width: 100% !important;
		padding: 0 !important;
		float: none;
	}
```

**Review by colinschoen — APPROVED** [review]
LGTM approval

**Pull request merged**
