### PR TITLE
Detect database version in `checkChange()`

### PR DESCRIPTION
**Pull request by live627**
Not sure how this was missed before

### CODE REVIEW

**Comment by albertlast** [comment]
Instead of eval maybe a function call () would be better?
Also the mysql check the client version not the server version.

**Comment by sbulen** [comment]
Yikes...  Yeah, how has this worked at all...  

Can you reproduce the original issue reported in #7060 ?  If so, how?

**Comment by sbulen** [comment]
I can reproduce #7060 using php8 and current github code.  

I tested with this PR, and I am seeing this error - though it appears to run to completion:
 *  +++  Renaming table columns.Error: Undefined array key 1 File: yada\yada\upgrade.php Line: 2572Error: Undefined array key 1 File: yada\yada\upgrade.php Line: 2572 done.

**Comment by sbulen** [comment]
I think that fixing this will actually break something...

Note that this logic _clearly_ has never worked properly...  For 10 yrs+...  Its purpose is to NOT change the data type of certain fields (passwordSalt, memberGroups) when renaming them (an early 2.0 upgrade step).  Currently, it returns early under all circumstances, meaning, today, it always ensures the column matches the expected data type.  

So...  If we fix it, it may actually leave those fields with an unusual/unexpected datatype going forward.  

At this point, I believe it is safer to remove this function altogether, rather than fix it.

**Comment by sbulen** [comment]
& BTW, the same is true over in SMF 2.0...

**Review by Sesquipedalian — DISMISSED** [review]

**Comment by Sesquipedalian** [comment]
@live627, how much of this still relevant since #7077 was merged? If any is, could you please resolve the conflicts?

**Pull request closed without merging**
