### PR TITLE
Checking in Fix for #2904 and other minor fixes for OS:X

### PR DESCRIPTION
**Pull request by tinoest**
Upgrade.php fails on The PostgreSQL user you have set in Settings.php
does not have proper privileges. Due to smf_db_change_column not
returning true.
#2904

Signed-off-by: tinoest tinoest@gmail.com

### CODE REVIEW

**Comment by XinYenFon** [comment]
You have to sign-off the commit :( not with post or something.

**Comment by tinoest** [comment]
I can't seem to edit the commit message. Any clue on how you do that?

**Comment by XinYenFon** [comment]
you can't edit commit messages, you have to do it while doing the commit.

**Comment by tinoest** [comment]
Hopefully I got there eventually! Sorry for the messing around.

**Comment by live627** [comment]
> you can't edit commit messages

Actuality you can edit the last commit. https://www.google.com/search?q=edit+commit+message+github

**Comment by live627** [comment]
Note to self: cherry pick the last two commits.

**Comment by live627** [comment]
> cherry pick the last two commits

Done #2925

**Pull request closed without merging**
