### PR TITLE
Fix  #4701

### LINKED ISSUE #4701: Shortcuts: shift+alt+s save/post, shift+alt+p preview, shift+alt+d save draft
i think we should remove the save in save/post as we are posting it and may actually be able to save it as a draft as a separate action/function.

### PR DESCRIPTION
**Pull request by live627**

### CODE REVIEW

**Comment by SychO9** [comment]
Don't think that changes things, the same strings are re-declared in the Post language file, not sure why though

```
$ git grep "'shortcut" -- ./Themes/default/languages
Themes/default/languages/Post.english.php:$txt['shortcuts'] = 'Shortcuts: ALT+S save/post or ALT+P preview';
Themes/default/languages/Post.english.php:$txt['shortcuts_drafts'] = 'Shortcuts: ALT+S save/post, ALT+P preview, ALT+D save draft';
Themes/default/languages/Post.english.php:$txt['shortcuts_firefox'] = 'Shortcuts: SHIFT+ALT+S save/post, SHIFT+ALT+P preview';
Themes/default/languages/Post.english.php:$txt['shortcuts_drafts_firefox'] = 'Shortcuts: SHIFT+ALT+S save/post, SHIFT+ALT+P preview, SHIFT+ALT+D save draft';
Themes/default/languages/Post.english.php:$txt['shortcuts_mac'] = 'Shortcuts: ⌃⌥S save/post or ⌃⌥P preview';
Themes/default/languages/Post.english.php:$txt['shortcuts_drafts_mac'] = 'Shortcuts: ⌃⌥S save/post, ⌃⌥P preview, ⌃⌥D save draft';
Themes/default/languages/index.english.php:$txt['shortcuts'] = 'Shortcuts: alt+s save/post, alt+p preview';
Themes/default/languages/index.english.php:$txt['shortcuts_firefox'] = 'Shortcuts: shift+alt+s save/post, shift+alt+p preview';
Themes/default/languages/index.english.php:$txt['shortcuts_mac'] = 'Shortcuts: ⌃⌥S save/post, ⌃⌥P preview';
Themes/default/languages/index.english.php:$txt['shortcuts_drafts'] = ', alt+d save draft';
Themes/default/languages/index.english.php:$txt['shortcuts_drafts_firefox'] = ', shift+alt+d save draft';
Themes/default/languages/index.english.php:$txt['shortcuts_drafts_mac'] = ', ⌃⌥D save draft';
```

**Comment by live627** [comment]
Then should one  set go? I don't like duplicate code.

**Comment by SychO9** [comment]
As far as I can see, the only spot where these strings are being used are in the editor where the **Post** language file is loaded, so I do think the ones in the **index** lang file are duplicates and should be removed, unless I'm missing something here.

```
 git grep "'shortcuts_"
Sources/Subs-Editor.php:                $context['shortcuts_text'] = $txt['shortcuts' . (!empty($context['drafts_save']) ? '_drafts' : '') . (stripos($_SERVER['HTTP_USER_AGENT'], 'Macintosh') !== false ? '_mac' : (isBrowser('is_firefox') ? '_firefox' : ''))];
Themes/default/GenericControls.template.php:                    ', $context['shortcuts_text'], '
```

**Comment by live627** [comment]
my thoughts exactly. I'll  do that soon.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
