### PR TITLE
Allow multiple extensions for smileys

### LINKED ISSUE #4919: Smileys - Non-.png smileys not displayed properly in editor & smiley settings
Non-png smileys are not displayed properly in a few places:

Editor:
smileys-post-upgr-editor-prob

Edit Smileys:
smileys-post-upgr-edit-prob

Edit Smiley Order:
smileys-post-upgr-order-prob

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #4919 

Extensions are removed from the DB altogether.  There is a new row in the settings table, called smiley_sets_exts that is closely tied to smiley_sets_known & smiley_sets_names.  All 3 of these settings will contain comma-delimited entries, and together, these 3 settings describe the installed smiley sets.   Applying the extension to the filename is done at runtime.  The benefit of this approach is that most of the code is already aligned with it; so many key updates are trivial.  

_As an example:_
 - smiley_sets_known:  fugue, alienine, android   (folders)
 - smiley_sets_names: Fugues's Set, Alienine's Set, Android Set    (user friendly names)
 - smiley_sets_exts: .png,.png,.gif   (extensions)

Limitations:
 - Only one extension per folder/set
 - Didn't update all of the deprecated functions, so they still have hard-coded extensions 
 - Removed the 'copy smiley to all folders' function as it wouldn't work given one extension per set 

Remaining work (updated 8/27/18):
 - None

Have tested on WAMP & on LAMP.

### CODE REVIEW

**Comment by sbulen** [comment]
I seem to have sprouted a conflict...   Need to rebase...

**Comment by sbulen** [comment]
Conflicts resolved but now EditSmileys doesn't work.  Will need some time to research.

**Comment by sbulen** [comment]
Fixed & retested, all is good.   Problem was sneaky...   Some $txt messages used `\\\'` to represent a single quote, but this didn't work.  I tried fixing it to `\'`, as is used throughout $txt.   This did NOT work when the $txt was used in javascript - it caused javascript syntax errors.  Converted to using `&#39;` and now javascript likes it AND it displays properly...  At the same time...

Problem $txt was here: https://github.com/SimpleMachines/SMF2.1/blob/16d9e9c70758b9bf924b3c0d12345fe6c619a8a7/Themes/default/languages/ManageSmileys.english.php#L71

Problem usage was here:
https://github.com/SimpleMachines/SMF2.1/blob/16d9e9c70758b9bf924b3c0d12345fe6c619a8a7/Sources/ManageSmileys.php#L1109

**Comment by jdarwood007** [comment]
JavaScriptEscape exists for this purpose.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
