### PR TITLE
Optionally pass BBC params to validate function

### PR DESCRIPTION
**Pull request by Sesquipedalian**
- If a BBCode's validate function is written to accept a fourth parameter, it can receive the final, calculated values of the $params array. This is especially useful if the values the user entered for the BBCode's parameters are required in the validate function.
- If a BBCode's validate function does not expect the fourth parameter, it will of course be ignored by PHP. So this is fully backwards compatible.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
FYI, this is in preparation for a PR to add support for image parameters (e.g. width, height) to the attach BBCode. I'm submitting these changes in two separate PRs because passing the BBCode parameters to the validate function is a significant change in its own right. It opens a lot of new possibilities for what can be done with BBCode. I expect that mod authors will find these new possibilities quite intriguing.

**Comment by MissAllSunday** [comment]
Is this ready for merging @Sesquipedalian ?

**Comment by Sesquipedalian** [comment]
Yes. Once it is merged, I will submit a separate pull request for the attachment params code that builds on this PR

**Comment by MissAllSunday** [comment]
cool, thanks!

**Pull request merged**
