### PR TITLE
Typo and Alignment Issue

### PR DESCRIPTION
**Pull request by colinschoen**

### CODE REVIEW

**Comment by colinschoen** [comment]
Before
before

After

after

**Comment by mikemill** [comment]
Check your file line endings.  You've changed every line in those files

**Comment by matthew-kerle** [comment]
Beyond that Mike said, note that you're not running the latest revision of the release-2.1 branch as I have already resolved and committed the fix for the profile display issue: https://github.com/SimpleMachines/SMF2.1/commit/37d58be787ff11de9caeec7907de51b4d681a4c9

Furthermore (and I'm going to sound like a hypocrite saying this,) but you need to sign-off commits. There's a note about it in the readme that explains how it should be done. Let me clarify this so I don't sound as much like a hypocrite, I have forgotten to sign-off some of my PR's (like my last) but I'm saying this because I do know it should be done, I just forgot.

**Comment by colinschoen** [comment]
Yep, right after I sent these I consulted Ema and advised him this was my first time using Github. He advised me of the issues and I am correcting them as I write this. Lab, can you reject this PR and I will send in the correct one? Thanks for the help guys.

**Comment by matthew-kerle** [comment]
Not a problem! :) Nice to see you jumping in here.

Closing, as requested.

**Pull request closed without merging**
