### PR TITLE
Bump required PHP version to 5.3.7

### PR DESCRIPTION
**Pull request by Dragooon**
Signed-off-by: Shitiz Garg mail@dragooon.net

### CODE REVIEW

**Comment by Arantor** [comment]
I would not require 5.3.7. I would require 5.3.8. Specifically because I know crypt() is used internally for things and 5.3.7's implementation is broken.

See http://php.net/releases/5_3_8.php

**Comment by Dragooon** [comment]
Only md5 is broken in 5.3.7, we only use blowfish.

**Comment by Arantor** [comment]
There are instances of crypt() in the bowels of SMF unrelated to password hashing.

**Comment by Dragooon** [comment]
Ah crap you're right

**Pull request merged**
