### PR TITLE
Displays the number of posts by reference to the list of posts

### PR DESCRIPTION
**Pull request by Pavel-II**
Signed-off-by: Pavel-II pavel-klimenko@yandex.ru

### CODE REVIEW

**Comment by Pavel-II** [comment]
I must fix spaces arounds concatenation?

**Comment by MissAllSunday** [comment]
Yes please.

**Comment by colinschoen** [comment]
The `width` attribute of the `<td>` tag is deprecated in HTML5. Please also remove the attribute and add it back in the `CSS`.

**Comment by MissAllSunday** [comment]
Hello @Pavel-II are you still interested on making the proposed changes?

**Comment by Pavel-II** [comment]
Hello @MissAllSunday 
yes, but don't understand how. I do not know very well git. I did everything I could and knew.

**Comment by MissAllSunday** [comment]
Well, you can close this PR and start another one one and apply the  
proposed changes to that.

I believe you can do a new PR for small changes directly on github but I  
haven't really tried so I can't really give you any advice on it.

## 

Jessica González, missallsunday.com

**Pull request closed without merging**
