### PR TITLE
Fixes #3749

### LINKED ISSUE #3749: Errors with Calendar
Alright, so I started testing Calendar and I got a couple of errors.

- 1. Every time I enter into "Post Event" (under Calendar Tab), I got this error:
8: Only variables should be passed by reference
Sources/Subs.php
Line 5030

After I press the "Post Button" to post an event, I get this screen error:
- 2. An Error Has Occurred
The database value you're trying to insert does not exist: id_board

And also got this 2 errors in error log:
- 3. The database value you're trying to insert does not exist: id_board
Function: insertEvent
Sources/Subs_Calendar.php
Line 919

- 4. 2: array_combine(): Both parameters should have an equal number of elements
Sources/Subs-Db-mysqli.php
Line 800

Event though, the event topic is created.

Couldn't go any further @Sesquipedalian 

**Version Information:**
Forum version: SMF 2.1 Beta 3 (more detailed)
Current SMF version: SMF 2.1 Beta 2
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.0.20-MariaDB 
PHP: 7.0.6 (more detailed) 
Server version: Apache

### PR DESCRIPTION
**Pull request by Sesquipedalian**

### CODE REVIEW

**Comment by frandominguezl** [comment]
Again, when entering "Post Event" got 2 errors:

- 1. array_multisort(): Argument #1 is expected to be an array or a sort flag
Sources/Subs.php
Line 5035
- 2. Only variables should be passed by reference
Sources/Subs.php
Line 5030

No more errors after publishing the Event

**Comment by Sesquipedalian** [comment]
That's after you changed the following?

Subs.php, line 5030:
```
		$zones[$tzkey]['locations'][] = str_replace(array('St_', '_'), array('St. ', ' '), array_pop(explode('/', $tzid)));
```

to 

```
		$tzlocation = array_pop(explode('/', $tzid));
		$zones[$tzkey]['locations'][] = str_replace(array('St_', '_'), array('St. ', ' '), $tzlocation);
```

I ask because once that change has been made, the array_mulitsort() gets bumped down from line 5035 to line 5036.

**Comment by frandominguezl** [comment]
Yes

**Comment by Sesquipedalian** [comment]
But once that change has been made, the error message about array_multisort() should mention line 5036, not line 5035.

**Comment by Sesquipedalian** [comment]
screen shot 2016-12-28 at 4 59 06 am

**Comment by frandominguezl** [comment]
My bad, I accidentally removed line 5032.

Now the error is in line 5036.

**Comment by Sesquipedalian** [comment]
Okay, that makes more sense. If line 5032 was missing, then array_multisort would definitely complain, since `$offsets` would be empty.

**Comment by frandominguezl** [comment]
Okay, @Sesquipedalian my fault again, I wrote $offset instead of $offsets (heh)

Now that error is gone, but this one is still happening: "Only variables should be passed by reference" Subs.php Line 5030

**Comment by frandominguezl** [comment]
Done, great job :+1:

**Comment by Sesquipedalian** [comment]
> Now that error is gone, but this one is still happening: "Only variables should be passed by reference" Subs.php Line 5030

That's because I moved the entire `array_pop(explode('/', $tzid))` when I meant to only move the `explode('/', $tzid)` part. Should be properly fixed as of the latest commit. :)

EDIT: Ninja'd

**Review by frandominguezl — APPROVED** [review]
Fixed

**Comment by frandominguezl** [comment]
Alright, just a question. When I enter to Post Event and check the "All Day" box everything is fine, but after clicking "Post", it redirects me to the board where I want to publish the event and the "All Day" box is unchecked. Is this the expected behaviour? Or it should remain checked?

**Comment by Sesquipedalian** [comment]
That's an oversight. It can probably be fixed fairly easily. Please file a new bug report for it.

**Pull request merged**
