### PR TITLE
handle empty message_labels array

### PR DESCRIPTION
**Pull request by albertlast**
Catch ``count(): Parameter must be an array or an object that implements Countable``
on line 1000 and 1072

### CODE REVIEW

**Comment by albertlast** [comment]
Issue: https://www.simplemachines.org/community/index.php?topic=559398.0

**Review by colinschoen — APPROVED** [review]
LGTM

Let's verify this fixes the issue for the user.

**Comment by albertlast** [comment]
Since the issue exists also in pg (was mitigated by the db layer),
i was able to reproduce this error on pg and notice after changing the sql issue was gone (no workaround needed).

**Comment by albertlast** [comment]
@colinschoen pr got verify at sm.org

**Pull request merged**
