### PR TITLE
Allow us to hide the unread links

### PR DESCRIPTION
**Pull request by jdarwood007**
This may be used in cases where we are using the forum theme from SSI and using our own link tree.

Just a minor thing that would be nice.

### CODE REVIEW

**Comment by live627** [comment]
This feels like it may belong in `$settings`; what do you think?

**Comment by jdarwood007** [comment]
I thought $settings was more for the theme settings that can be changed.  If there is no way to toggle this on the settings page, does it still make sense?

**Comment by DiegoAndresCortes** [comment]
I'm not a fan of this idea with a themer perspective.
I personally would move the unread links somewhere else as soon as I start working on a theme, so really I wouldn't even bring `$context['hide_unread_links']` with them

**Comment by Sesquipedalian** [comment]
I think #7260 has made this unnecessary. Would you agree, @jdarwood007?

**Comment by jdarwood007** [comment]
technically no, but i've got this customization in our site theme so it works still.

**Pull request closed without merging**
