### PR TITLE
Make the post moderation center obey max posts

### PR DESCRIPTION
**Pull request by NanoSector**
As reported here:
http://www.simplemachines.org/community/index.php?topic=504033.msg3546394#msg3546394

Hereby a fix is provided.

### CODE REVIEW

**Comment by matthew-kerle** [comment]
Make sure to sign off your commits so they can be merged :smile:

**Comment by NanoSector** [comment]
Well fuck this, I'm not doing my commits over again.

**Comment by eurich** [comment]
just a note: you can  modify your latest commit message by using --amend

Untested, but should work
`git commit --amend  -s`
http://nathanhoad.net/git-amend-your-last-commit

**Comment by norv** [comment]
The proposed fix won't work. Afaics $options and $modSettings are not in global scope.

**Pull request closed without merging**
