### PR TITLE
Fix mark-up of README.md

### PR DESCRIPTION
**Pull request by sstok**
Minor correction of the mark-up, this should make the header be displayed correctly 👍

### CODE REVIEW

**Comment by NanoSector** [comment]
LGTM :)

**Comment by XinYenFon** [comment]
commit missing sign-off ?

**Review by colinschoen — CHANGES_REQUESTED** [review]
Thanks for your contribution. All commits must be signed off. To amend your previous commit to include the signed-off text please use: `git commit --amend --signoff`

**Comment by sstok** [comment]
> commit missing sign-off ?

That's what I get for being lazy and using the GitHub UI :)

**Comment by sstok** [comment]
Should be good now 👍

**Review by Sesquipedalian — APPROVED** [review]

**Review by colinschoen — APPROVED** [review]
LGTM approval

**Pull request merged**
