### PR TITLE
Update Attachment.php

### PR DESCRIPTION
**Pull request by RainRat**
A thinko? Seems it would make more sense to refer to the parameter.

### CODE REVIEW

**Comment by jdarwood007** [comment]
@RainRat Looks like it.  Unless I missed it, I don't see you signed off on the commit.  Can you please sign your commit.
Thanks!

**Comment by RainRat** [comment]
Signed-off-by: RainRat <rainrat78@yahoo.ca>

**Comment by jdarwood007** [comment]
@RainRat
I checked with the team to be sure, but the sign-off needs to be on the commit message.  Can you append the git message, please?

**Comment by RainRat** [comment]
ok, i amended the commit message

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
