### PR TITLE
Css/jsstuff

### PR DESCRIPTION
**Pull request by MissAllSunday**
oops, forgot to add a description... this basically covers #1392 whenever possible.

There are some instances where the loaders cannot be used so I added $modSettings['browser_cache'] to them

### CODE REVIEW

**Comment by Xarcell** [comment]
Good work.

**Comment by Oldiesmann** [comment]
This looks good, but why do we have a function to reset $modSettings['browser_cache'] and why is it being called on every page load? We just need to set it during the install/upgrade and that's it - there should be no reason to reset it afterwards.

**Comment by MissAllSunday** [comment]
Yep, thats true, the reason why theres a function (or at least what I understood from the old bugtracker talk) was to force the browser to call the files directly when a mod or something else added new css/js files, that was the original intention, the original code didn't added the current forum version, it added a random generated seed.

It all depends if we want to use this and follow the original intention or just use it to identify the files.

**Comment by Oldiesmann** [comment]
If mods need to add their own files with different caching requirements, they should be using their own setting rather than trying to change the one used by SMF. It's best to just let us use our own and then mods can either use the same one or set their own if they want to do it differently (since some portal mods might want to set it based on portal version instead).

**Comment by MissAllSunday** [comment]
Yep, fair enough, I'll do the change.

**Pull request merged**
