### PR TITLE
Added sceditor undo js fixes #5035

### LINKED ISSUE #5035: sceditor.undo.js
took a download today of recent file getting error message when visiting posts, The file "sceditor.undo.js" could not be located on the current or the default theme and therefore it wasn't included in the minified file.

No changes made to coding and its using most up todate version took it about 15 mins ago

### PR DESCRIPTION
**Pull request by albertlast**
On the issue #5035 i see two ways to fix this:
remove the line or add the file again.

This pr take the last approache.
I guess the disabling of this plugin is somekind of temp solution and files removing and adding
could hurt in the upgrade process...
keep the file and update this when undo is fixed is a good way i guess.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
No, adding the plugin back in at this point will only bring back the bug in #4749. We can add it once a fixed version is available from SCEditor, but not until then.

**Comment by albertlast** [comment]
When I read the config right,
Then the plugin keeps disabled,
Even this files get loaded.

**Comment by Sesquipedalian** [comment]
Why would we want to load an unused, malfunctioning file?

**Comment by jdarwood007** [comment]
I would not mind seeing it readded once https://github.com/samclarke/SCEditor/issues/711 has been fixed.  This is the underlaying bug that caused its removal.

The bug seems related to the SCEditor itself having had adaption changes and the plugin not being updated to handle those changes.  Basically sounds like the plugin is technically not compatible with SCEditor in its current version.

**Comment by Sesquipedalian** [comment]
Thanks @jdarwood007. Once the plugin has been fixed and released, I'll be glad to add it back in again.

**Pull request closed without merging**
