### PR TITLE
Curve drop down improvement

### PR DESCRIPTION
**Pull request by marcusforsberg**
No offence to whoever updated the navigation menus in Curve, but they didn't look good at all. :( Here's a more visually pleasing version. Pretty much a remake of the original drop down's but a little improved and using CSS3.

Also updated the ACP icons. Looks better to me...?

Preview
Preview

### CODE REVIEW

**Comment by DrDeejay** [comment]
I think they look amazing. :) Great work =)

**Comment by XinYenFon** [comment]
Awesome work marcus :)

**Comment by live627** [comment]
Those look MUCH better!

**Comment by Trekkie101** [comment]
Very nice Nas!

**Comment by marcusforsberg** [comment]
Thanks a lot, both of you! :D Just waiting to have this merged in so I can commit my new progress bars and help/PM popups, too... :P

**Comment by Oldiesmann** [comment]
I like those Oxygen icons as well.

**Comment by emanuele45** [comment]
The menu has changed (again).
Is this PR still valid?

**Comment by marcusforsberg** [comment]
Nope, looks like the other ones won. :P They're broken, though, but this PR doesn't fix that. Still should update those icons, though, but I'll leave that to @Spuds with those lovely Oxygen icons!

**Comment by Spuds** [comment]
I just did the request for the Oxygen icons so it did not get lost :P .... Although the rest of this PR is no longer valid it was the inspiration to get the menu fixed !

**Comment by marcusforsberg** [comment]
Awesome! :)

**Pull request closed without merging**
