### PR TITLE
! add seed option to loadxxfile, on by default

### PR DESCRIPTION
**Pull request by Spuds**
Signed-off-by: Spuds spuds@simplemachines.org

One of many ways to do this ...
Auto adds ?alp21 to js and css files loaded by loadXXfile() by default

Supports:
shorthand loadXXXfile('blabla?xyz') (ignores $options['seed'] then)
['seed'] => false turn off auto seeding
['seed'] => true, same as null, adds it
['seed'] => string (in ?xyz12 or xyz12 formats)

Need to update the calls at some point if we want to add this feature (per the previous comments)

### CODE REVIEW

**Comment by live627** [comment]
$options is also the name of a global variable - may confuse some new programmers... hypothetical, though.

**Comment by Spuds** [comment]
TBH I thought the same thing when I was updating the function, not the greatest name due to the $options global.  When the calls are updated to make use of this, the name should be changed, maybe  $params will do.

**Comment by Fustrate** [comment]
"seed" isn't the proper name for this - it's actually called "cache busting". I'd recommend changing it to "buster" or something similar.

**Comment by Spuds** [comment]
how about dingleberry ?

**Pull request merged**
