### PR TITLE
Confirmation to mark as read, as suggested here:

### PR DESCRIPTION
**Pull request by margarett**
http://www.simplemachines.org/community/index.php?topic=512029.0

### CODE REVIEW

**Comment by Arantor** [comment]
There's two problems with this.

Firstly, all of the image definitions in create-button calls should be using png not gif, though I'm not sure why we still do that.

Secondly and more importantly, we cannot accept commits that have not been signed off. I'm not sure what tool you're using for git, though.

**Comment by margarett** [comment]
Howdy :)

Yeah, that's what was used in 2.0, didn't even look at that :P Anyway, I have no idea what is that for... There are no images involved but that's probably something beyond my knowledge :P

As for sign the package, well I am using SourceTree to update my repo and then used GH (the site) to create the pull request.
This was really my first try so pleace be nice to me :)

**Comment by margarett** [comment]
OK, so now I think I got both corrected.

**Comment by Arantor** [comment]
The way Git works, only your second commit was signed off, not the first one :(

(I'm not the world's biggest fan of Git, it should be noted... I honestly don't know how to fix that part.)

**Comment by margarett** [comment]
OK, I can reset that. Is it possible to delete this PR?

**Comment by illori** [comment]
i dont think you can easily fix it now that another commit was made. would be easier IMO to create a new branch and make the changes again making sure to sign off.

**Comment by margarett** [comment]
That's what I'm doing :)

**Comment by emanuele45** [comment]
> i dont think you can easily fix it now that another commit was made.
> would be easier IMO to create a new branch and make the changes again
> making sure to sign off.

```
git rebase -i HEAD~2
i
s/pick/e/ <= perl version of replace pick with e (read the page you are
presented with for more into)
:wq
git commit --amend -s
git commit --amend -s
git push -f origin release-2.1
```

Do note: work on your own "master" (that in the case of this repo is in
fact release-2.1) is the best way to get the whole repo messed up.
git/github workflow is:
1. pull remote master
2. create a branch
3. work on the branch (i.e. commit here)
4. push the branch
5. send PR
6. PR gets accepted
7. restart from 1.

**Comment by margarett** [comment]
Part 1: WTF? :smile: 

Part 2: Thanks :wink: Will remember that.

**Pull request closed without merging**
