### PR TITLE
Fix visual brokenness of the Ignore Boards profile area

### PR DESCRIPTION
**Pull request by NanoSector**
Signed-off-by: NanoSector <rick.2889@gmail.com>

Before:
image

After:
image

### CODE REVIEW

**Comment by NanoSector** [comment]
Adding WIP tag because there are more places where this is used.

**Comment by NanoSector** [comment]
image

This should do... However it does not work well when on mobile/small resolutions.

**Comment by jdarwood007** [comment]
screen shot 2018-08-13 at 6 08 12 pm

**Comment by NanoSector** [comment]
I've changed it to a grid, but I'm not sure if I'm happy with this...
image

**Review by jdarwood007 — APPROVED** [review]

**Pull request merged**
