### PR TITLE
Everything back

### PR DESCRIPTION
**Pull request by emanuele45**
Here it is, everything back on display.

### CODE REVIEW

**Comment by Arantor** [comment]
Heh, interesting.

Personally I'm not averse to hiding some things, I just don't like the lack of UI hinting or the presentation of it... there really is something to the minimalism aspect of it.

**Comment by emanuele45** [comment]
Arantor wrote:

> Heh, interesting.
> 
> Personally I'm not averse to hiding some things, I just don't like the
> lack of UI hinting or the presentation of it... there really is
> something to the minimalism aspect of it.

Personally I heard so many complains about this that I'm tired of
receiving notifications about it... lol
So, even if I would let the themer/s do his/their work and create the
theme the way he/they wants, I squashed it so that complains will stop
once and for all.

**Comment by Arantor** [comment]
The sad fact is you know as well as I do that themers won't change it much, they'll just leave it how the default does it :(

I'm actually thinking we should leave it as it is and letting the broader community comment on it when it's in public beta; right now, the people who are using the alpha are the hardcore SMF folks who've been using SMF for years and for whom any significant change is unpleasant.

**Comment by Arantor** [comment]
So, who would like to see this branch merged? Or should I just close it and leave it for reference?

**Comment by illori** [comment]
cant hurt to merge it, or wait until 2.1 is released and see what the general public thinks.

**Comment by Arantor** [comment]
I think I'll wait until 2.1 reaches a public beta and we'll go from there.

**Comment by Arantor** [comment]
In the interim I still didn't hear anything positive :( So I guess we can just merge it after all.

**Pull request merged**
