### PR TITLE
Fix topic notifications if user subscribe to both topic and board

### PR DESCRIPTION
**Pull request by BrickOzp**
Combine the topic and board record into one.

Fixes: #8180

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

### CODE REVIEW

**Comment by sbulen** [comment]
This issue was addressed earlier:
https://github.com/SimpleMachines/SMF/pull/7691

**Comment by BrickOzp** [comment]
Issue still exists in 2.1.4

**Comment by Sesquipedalian** [comment]
Does it still exist in 5da827a?

**Comment by BrickOzp** [comment]
> Does it still exist in [5da827a](https://github.com/SimpleMachines/SMF/commit/5da827a6dc2e96a2e3f2221779f351541aba3c20)?

Yes it does

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
