### PR TITLE
Fix possessive form

### PR DESCRIPTION
**Pull request by m4z**
Adresses issue 2/3 and 3/3 described in #7805

### CODE REVIEW

**Review by DiegoAndresCortes — APPROVED** [review]

**Comment by jdarwood007** [comment]
Crowdin won't blow up and get this wrong because of the escaped character right?

**Comment by DiegoAndresCortes** [comment]
We have others like
https://github.com/SimpleMachines/SMF/blob/fd30b3714c17b30bb0821d79268caa8b9462a9c9/Themes/default/languages/ManageBoards.english.php#L92

So probably safe.

**Comment by sbulen** [comment]
The gotcha with escaping & control characters in language strings is I recall .js vs .php needing things a bit different.  And email templates might be different as well...

We have had "LeT's mAKe tHinGs ConSIsTEnt!!!" PRs break things in the past.

Testing is critical.

I only believe it's working when I see it...

Screenshots, please.

**Comment by m4z** [comment]
* `$txt['maintain_backup_info']`:
Apparently, the backup functionality was completely removed in 63f90bfa813bddf7f885f953d64387d4755b0e91. Should I change this PR to remove all `maintain_backup*` strings or do a separate PR? Should I undo touching the string in this PR?


* `$txt['custom_profile_desc']`:
Screenshot_20230727_075426

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
