### PR TITLE
Allow access to loaded member's data 

### PR DESCRIPTION
**Pull request by MissAllSunday**
Just move the hook call a few lines below to get access to the sender's data.

Signed-off-by: Suki suki@missallsunday.com

### CODE REVIEW

**Comment by live627** [comment]
Should $senders be passed to the hook as well?

**Comment by MissAllSunday** [comment]
Well, $memberContext is already available on global scope and as much as it kills me to see that behavior, i seems its the preferred way to go.

**Comment by MissAllSunday** [comment]
Oh you mean the $senders var? I dunno, that data is already included in $alerts, seems $senders was created just to gather all the senders IDs

**Comment by Oldiesmann** [comment]
SMF does that so we don't have to call loadMemberData individually for each sender. There's no need to pass it to the hook since the sender IDs will already be available in $alerts.

**Pull request merged**
