### PR TITLE
Update the upgrade for smileys

### LINKED ISSUE #4531: Undefined variable: firstIndex
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MySQL
MySQLi version: 5.6.26
Alternative PHP Cache: 5.1.2
PHP: 7.1.10 (more detailed)
Server version: Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10

Upgrade with Pull Request #4526 

>  Franky
>  Today at 13:40
>  ::1  f84c511352d0e03394e642e70d194371
>  Type of error: Undefined
> 8: Undefined variable: firstIndex
> http://localhost/smfbeta/index.php?topic=17.0
> File: C:/xampp/htdocs/smfbeta/Sources/Display.php
> Line: 1213

If I reverse this change there is no error message https://github.com/SimpleMachines/SMF2.1/pull/4522/commits/b29f32be604d9f076f8bfd52e51b84da0caf40d5

### PR DESCRIPTION
**Pull request by albertlast**
Only a addation

### CODE REVIEW

**Comment by wintstar** [comment]
And how about after release  to 2.1 at Upgrade from 2.0.* with old posts where the smileys have the ending .gif?

**Comment by albertlast** [comment]
Ooops the pr doesn't fix the #4531 adds only a upgrade path.

**Comment by albertlast** [comment]
To your question @wintstar the smileys are saved as ``:)`` not as lough.gif -> no need to update the messages.

**Comment by wintstar** [comment]
> To your question @wintstar the smileys are saved as :) not as lough.gif -> no need to update the messages.

I hadn't found that. Thank you for the info 👍

**Comment by wintstar** [comment]
Error by  upgrade

> !!Error!
> Truncated incorrect DOUBLE value: 'default,aaron,akyhne,fugue'

**Comment by albertlast** [comment]
Try this version:

```
---# Update Settings sets_known
UPDATE {$db_prefix}settings
SET value = CONCAT(value ,',alienine')
WHERE variable = 'smiley_sets_known';
UPDATE {$db_prefix}settings
SET value = replace (value, ',aaron', '')
WHERE variable = 'smiley_sets_known';
UPDATE {$db_prefix}settings
SET value = replace (value, ',akyhne', '')
WHERE variable = 'smiley_sets_known';
UPDATE {$db_prefix}settings
SET value = replace (value, ',fugue', '')
WHERE variable = 'smiley_sets_known';
---#

---#  Update Settings sets_names
UPDATE {$db_prefix}settings
SET value =CONCAT(value, '\n{$default_alienine_smileyset_name}')
WHERE variable = 'smiley_sets_names';
UPDATE {$db_prefix}settings
SET value = replace (value, '\n{$default_aaron_smileyset_name}', '')
WHERE variable = 'smiley_sets_names';
UPDATE {$db_prefix}settings
SET value = replace (value, '\n{$default_akyhne_smileyset_name}', '')
WHERE variable = 'smiley_sets_names';
UPDATE {$db_prefix}settings
SET value = replace (value, '\n{$default_fugue_smileyset_name', '')
WHERE variable = 'smiley_sets_names';
---#
```

**Comment by wintstar** [comment]
Upgrade ok, no errors. But

> :blank: | blank.gif | Post form | blankSmiley not found in set(s): default, alienine

smileys_broken3

**Comment by albertlast** [comment]
:blank: doesn't exists in the install file,
but blank.png exists in the directory...
@Gwenwyfar i didn't understand this.

**Comment by albertlast** [comment]
Setup files from 2.1, 2.0 and 1.1 showes that ``:blank:`` shouldn't exists.

**Comment by Gwenwyfar** [comment]
blank has always been there (or at least since 2.0), I think it's not supposed to be a smiley, just part of the files in case someone wants to edit them. Though I wonder if there's actually any real use to doing this.

**Comment by wintstar** [comment]
If I understand correctly, smileys have been changed from .gif to .png. But there are still some places in the code with smiley. gif Is that right?

https://github.com/SimpleMachines/SMF2.1/search?utf8=%E2%9C%93&q=smiley.gif&type=

**Comment by albertlast** [comment]
The gifs in template look wrong:
https://github.com/SimpleMachines/SMF2.1/blob/1b305c3a9e0bb1158bcbf2e128559ebb5c5e420c/Themes/default/Profile.template.php

**Comment by wintstar** [comment]
And how could this be solved with blank. .gif /smiley blank?

**Comment by albertlast** [comment]
delete the entry in the table of smileys

**Comment by wintstar** [comment]
Shouldn't this be done with the upgrade system? I think that after the release, upgrade 2.0. * to 2.1.

**Comment by albertlast** [comment]
Like i mention before,
this was never part of the setup in smf 2.1, 2.0.x and 1.1.
--> :blank: is a custome smiley and the task of the upgrader is not touch custom settings.

**Comment by wintstar** [comment]
I understand that, but it's included in the Smiley package of version 2.0. With an upgrade from 2.0.15 to 2.1 it is included and I think many people will report this as a bug in the support forum.

**Comment by albertlast** [comment]
It's only included in the directory but in the database setup is this not included.
So you 2.0.x setup which you take as bade for the upgrade got a minor mistake in the database.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
