### PR TITLE
Some Posts & Theme pages UI Adjustments

### PR DESCRIPTION
**Pull request by SychO9**

### CODE REVIEW

**Comment by Gwenwyfar** [comment]
Looks good, as always :)

I wonder if it wouldn't be better to put "report to admin" under a "more" tab like in posts though. It takes quite a bit of space and attention.

**Review by Gwenwyfar — APPROVED** [review]

**Comment by SychO9** [comment]
yea I think you're right, it does take space :/
I'll move it there

**Comment by SychO9** [comment]
I wonder why no one has made a generic **quickbuttons** template with a hook to it, the layout is used in many places and all of them require manual edit to add button to :/

**Comment by Gwenwyfar** [comment]
Yeah, there's too many things used in the theme that we could have a generic template for :/

There haven't been a lot of front end devs working on 2.1 for much of the development though, so that's one reason.

**Comment by Sesquipedalian** [comment]
> I wonder why no one has made a generic **quickbuttons** template with a hook to it, the layout is used in many places and all of them require manual edit to add button to :/

Make it so

**Comment by SychO9** [comment]
See #5918

**Pull request closed without merging**
