### PR TITLE
Checking in changes to support STARTTLS

### PR DESCRIPTION
**Pull request by tinoest**
Added Support for STARTTLS command if using port 587 and the server supports it. 
Updated server_response params to reflect change. 

Signed-off-by: tinoest@gmail.com

### CODE REVIEW

**Comment by jdarwood007** [comment]
Instead of auto assuming port 587 will use TLS.  This should go in as a modSetting requiring the admin to check use STARTTLS

**Comment by tinoest** [comment]
STARTTLS is supported on port 587 (RFC 3207) and possibly port 25 (mentioned in RFC 2476)

I can add the option of it being a config but in its current form it'll only work if the server responds and says it can deal with it anyway.

**Comment by jdarwood007** [comment]
Well you also get the problems where people are running on non-standard ports.  So assuming that 587 will always be used for TLS would cause problems there.  Standards are not always followed, some people even run them on 465 as well.

**Comment by tinoest** [comment]
465 is an encrypted port already when you connect. So its not valid for STARTTLS, the only two I know off are port 25 and port 587, where you could use STARTTLS. 

I'll ammend as you suggest, although I don't think its required personally. At least if its not returned then it will get ignored in its current implementation even if the user enables it.

**Comment by jdarwood007** [comment]
Well we try to be compliant with RFCs, but not everyone follows RFCs and some setups do use different ports for various reasons. I've seen STARTTLS used on port 465 and other random ports. So changing this prevents it from becoming an issue for those who want to use non standard ports with STARTTLS.

**Comment by ColdrickSotK** [comment]
I came to check if anyone had created an issue or PR for this with a view to writing one myself if not. This one works nicely!

**Comment by MissAllSunday** [comment]
Are the changes good @jdarwood007 ?  I don't know much about ports and supported mail standards so I leave it up to yo guys to decide.

**Comment by jdarwood007** [comment]
Yes.   The changes do allow for non standard ports to be used.  So I see no issue here.

**Comment by MissAllSunday** [comment]
cool, thanks!

**Pull request merged**
