### PR TITLE
Add Info Center Permission

### PR DESCRIPTION
**Pull request by ahrasis**
If this is useful, I wish to commit the info center permission for SMF 2.1.

Signed-off-by: ahrasis ahrasis@gmail.com

### CODE REVIEW

**Comment by XinYenFon** [comment]
I'd rather avoid adding new settings, better we look ways to remove some existing ones.

**Comment by Oldiesmann** [comment]
I don't think this is necessary either. We have enough permissions as it is and I don't think many people will find this one useful.

**Comment by ahrasis** [comment]
You may be right. It is just my thought that this could reduce support after seeing this mod http://custom.simplemachines.org/mods/index.php?mod=1335 was in high demand anyway.

**Comment by Oldiesmann** [comment]
Is there still a high demand for it? That mod hasn't been updated in 2 years. I haven't seen any support requests for that sort of thing recently either.

**Comment by Dragooon** [comment]
Yeah I'd like to avoid this as well, this is best as a mod.

**Pull request closed without merging**
