### PR TITLE
Update sceditor to latest version

### PR DESCRIPTION
**Pull request by Oldiesmann**
This PR takes the changes made to SCEditor 1.3.7 (or whatever version we currently have in 2.1) and applies them to the latest version (1.4.3 as of this PR). A complete list of changes applied is available at http://smfgit.oldiesmann.us/index.php?topic=4.0. A brief test on my forum indicates that this should work fine, but I'd like others to test it as well before we pull this in, especially since three blocks of code which we modified in jquery.sceditor.bbcode.js weren't found in the new version.

I have not made any changes to SMF itself for this, so other tweaks may be required as well.

Ref: #93

Signed-off-by: Michael Eshom oldiesmann@oldiesmann.us

### CODE REVIEW

**Comment by XinYenFon** [comment]
After the patch

patch

**Comment by Oldiesmann** [comment]
I'll look into that and see why the code I added to handle rows isn't working.

I am also seeing a couple errors in the JS:

`[01:29:11.667] TypeError: $.sceditor.setCommand is not a function @ http://smfgit.oldiesmann.us/Themes/default/scripts/jquery.sceditor.js?alph21:5397`

`[01:29:12.376] TypeError: $(...).data(...).createPermanentDropDown is not a function @ http://smfgit.oldiesmann.us/index.php?action=post;topic=4.0;last_msg=13:431`

I'll have to see what's going on with those as well.

**Comment by Oldiesmann** [comment]
Not sure what the issues are here...

It seems to be using its own toolbar (with our buttons) rather than ours, so no rows are being defined. It also seems to be ignoring the fact that setCommand and createPermanentDropDown are defined.

@norv, @Spuds or @emanuele45 - any help on this?

**Comment by emanuele45** [comment]
mmm...assuming what you want are the two lines of icons, that's one of the few changes that must be done to the core of the editor.
At the moment I don't have the code handy, will check later.

**Comment by Spuds** [comment]
TypeError: $.sceditor.setCommand (  ... this was replaced with $.sceditor.command.set(  in the 1.4 branch

TypeError: $(...).data(...).createPermanentDropDown ... not sure, if you are sure its initialized then it could simply be in the wrong namespace.

two lines of icons ... that was emanuales thing ... you could try (this is a guess) placing all of the top row ones in to a single group by only using the array(), where you want the new row, then target the css groups "sceditor-group" to flow as you want

**Comment by Oldiesmann** [comment]
Closing this one in favor of #526.

**Pull request closed without merging**
