### PR TITLE
Removing sqlite support

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: ziycon ziycon.eire@gmail.com
This is just a start to remove sqlite support from future versions.

### CODE REVIEW

**Comment by emanuele45** [comment]
xref #40

**Comment by Oldiesmann** [comment]
When did we decide we weren't going to support SQLite anymore? I don't think it's a good idea to just drop it, especially as there's no reason we can't keep supporting it. If it's because 2.8 is outdated, we should look into adding support for 3.x as well.

**Comment by ghost** [comment]
I was starting off with this work, not that it has to be merged but gave it a start anyway, the next step would be to update the upgrader to take the sqlite database on upgrade to 2.1 and convert it to mysql, a bit of discussion would need to take place with emanuele around the licensing of his converter.

http://www.simplemachines.org/community/index.php?topic=507820.msg3577612#msg3577612

**Comment by Arantor** [comment]
I can give you two good reasons not to continue supporting it.

Firstly, lack of use. Hardly anyone uses SQLite currently - and that's not just related to limited/no support for SQLite 3 in the system (I see code in 2.1 that mentions it). SMF 2.x has had SQLite support for years but even going back to RC days, hardly anyone used it. It seems a bit silly to pour all the time and effort into checking compatibility with every change that gets made knowing full well that almost no-one will use it.

Secondly, even taking into account the potential userbase, there is a much larger problem with SQLite: it just doesn't scale. It cannot scale up to the levels that MySQL and PostgreSQL can do. Given that, I do not ever recommend its use; I cannot think of a single application where SQLite would actually be appropriate (and before anyone suggests 'running it off a USB stick for specialised applications', you already have Apache and PHP to deal with and you can already get MySQL in a portable form that would suit)

To me, the benefit just doesn't outweigh the maintenance or development time requirements.

**Comment by jdarwood007** [comment]
I am going to agree with removing Sqlite support.  Although I would love to see us pick up another database engine then.
I am not talking about Percona or MariaDB as those will be supported due to their current drop in replacement status for MySQL and will possibly someday need their own database layers, not at the moment though unless their is changes in the horizon that will break MySQL compatibility with them.

**Comment by Arantor** [comment]
I would note that there is SQLite 3 support code in 2.1's current state, which muddies the problem even more.

That said, at this stage I'm tempted to say leave SQLite where it is unless there are major breaking issues with it; we don't really want to be doing huge overhauls at this stage of the day.

**Comment by jdarwood007** [comment]
Sounds fine to me.  We leave it for the period of 2.1 and announce its removal during SMF 2.1 Final announcement, which should give enough time for any forums (I said any) to migrate away.

**Comment by Arantor** [comment]
Works for me. @Oldiesmann what's your take on this?

**Comment by Oldiesmann** [comment]
"Announce its removal during the final 2.1 announcement" - this means we'll be removing it in 2.2/3.0, right? If so I'm fine with that.

**Comment by Arantor** [comment]
Yup that's what we're talking about.

**Comment by Oldiesmann** [comment]
Sounds good to me.

**Comment by ghost** [comment]
Based on the over all consensus do you want this PR removed?

**Comment by Arantor** [comment]
I don't think it needs to be removed, though I think we can just close the issue for now? It may be useful in future for review purposes :)

**Comment by XinYenFon** [comment]
No need to remove get this PR as patch and store it we/you can apply it on 2.2 and/or 3.0

https://github.com/SimpleMachines/SMF2.1/pull/545.patch

**Comment by NanoSector** [comment]
If we aren't removing this, can we at least close this so it doesn't show up in the list?

**Comment by Arantor** [comment]
Yeah, I think we should do that, just close it for now - we can always find it later.

**Pull request closed without merging**
