### PR TITLE
Index files for consistency

### PR DESCRIPTION
**Pull request by sbulen**
This should address:  Inconsistency in folder navigation protections #3737

I think it's really this simple...   Let me know if I'm off track.

### CODE REVIEW

**Comment by XinYenFon** [comment]
well you forgot to sign off your commit.

**Comment by sbulen** [comment]
Signed off by Shawn Bulen, bulens@pacbell.net

Is that sufficient, or do I need to submit a different pull request?

Still struggling with git...

**Comment by XinYenFon** [comment]
Unfortunately you need to amend last commit sign off and push again, if you are not good with Git, yes you need to open new PR.

**Comment by sbulen** [comment]
Thanks for the assistance.   Off to read more about git...

**Review by XinYenFon — APPROVED** [review]

**Comment by sbulen** [comment]
Will try this again...

**Comment by XinYenFon** [comment]
This was actually valid :)

**Pull request closed without merging**
