### PR TITLE
Some hook stuff

### PR DESCRIPTION
**Pull request by marcusforsberg**
I have no friggin idea what I'm doing, I must say.... :P This pull request thingie is probably a lot messier than it should be but if I try a new one in the future I now know what to do and what not to do... Heh.

Commit e416592 wasn't actually supposed to be in this branch but a separate one but I guess it doesn't really hurt.

Anyway.

IMO, there's no point having the button_strip arrays (such as
$mod_buttons or $normal_buttons) in the templates. It makes more sense
to have them in their corresponding source files, as with the main menu
in 2.0. Themes rarely need to modify them and if they do, they can still
do so (changing the image instance (which doesn't actually do much, does
it?) and so on) by just using the "new" array.

Also made sure there are hooks for all of them. One may argue that some
of them probably will never be used, but I feel that the hook system
won't have reached its full potential until as much as possible is
editable via hooks, so why not play it safe?

Signed-off-by: Marcus Forsberg info@marcusforsberg.net

### CODE REVIEW

**Comment by mikemill** [comment]
In addition to the above the commits need to be signed-off to acknowledge that you agree to the DCO.

**Comment by marcusforsberg** [comment]
@emanuele45 Point taken on $context, obviously didn't think that one through :P Awesome that you added the hooks! I noticed you guys also added a few others that I wished for and stole my idea for loadStylesheet and loadJavascript (not that I ever _shared_ that idea :P)

@mikemill Just gonna figure out how to do that, then... :D

**Comment by mikemill** [comment]
To add the sign-off line you can use the -s command line option.
git commit -s

You can also just add the text to the commit message:
Signed-off-by: marcusforsberg info@marcusforsberg.net

Depending on your git client there may also be an option to add the sign-off line

**Comment by marcusforsberg** [comment]
Awesome. I noticed live did it in a comment on his pull request. I take it that's also acceptable or did I get something wrong? ;o

Signed-off-by: marcusforsberg info@marcusforsberg.net

**Comment by mikemill** [comment]
I think the SM devs are allowing the sign-of to appear in the pull request.  In the commit is the preferred location.  Interestingly enough, if it is in the commits GitHub will automatically add it to the pull request.

**Comment by marcusforsberg** [comment]
I'll remember to sign-off the commits as I make them in the future, if any. I use Github for Windows though and it doesn't seem to have any such option. Will refrain from using it when committing, then (or add it to the commit message). Thanks for the info, I'm starting to understand this thing now :D Will just have to come up with something a little more useful to contribute with next time ;)

**Comment by live627** [comment]
Just a friendly reminder -- passing by reference in the hooks is now deprecated as of PHP 5.4. They use call_user_func_array().

**Comment by norv** [comment]
I haven't used Github for Windows, however I remember reading that it is based on msysgit. Then, msysgit uses the user home directory for configuration options for git. If someone can check my memory on this: the home dir for git should contain the .gitconfig file or be able to read it if you create it. In which case, the alias procedure listed in the readme can be applied: define an alias for commit -s as noted there.
I'd appreciate if you try and let us know. We'd have to update the wiki (or readme) for an easy path on Github for windows. I expect many of those interested in the SMF community may find it first.

**Comment by norv** [comment]
live, could you please open an issue on passing by ref? I tend not to fix it for SMF 2.1, for backwards compatibility reasons and changes in steps, however if we are to discuss it, it doesn't affect only this pull request's commits.

**Comment by norv** [comment]
@marcusforsberg Please, consider at least to edit the _pull request message_, and add your sign-off there. I understand it's a little difficult to get hang of all git details in the first PR and one with several commits. I will accept a sign-off in the PR message for starters, even though it is not the procedure we recommend, and it is not the procedure we highly prefer the SMF development community to get used to (we prefer to use sign-offs on commits). However a sign-off in the _comment_ is different: and not acceptable, sorry.
Because, to my knowledge, it is github-only and it won't be merged in the repo.

**Comment by marcusforsberg** [comment]
@norv When you say edit the pull request, you refer to the original (first) comment, I take it?

I was going to try what you posted here: https://github.com/SimpleMachines/SMF2.1/pull/51#issuecomment-6653007
But that seems to add an entirely new commit instead of updating the original. Is that the desired behaviour?

I'll see if I can define an alias. I do also have TortoiseGit installed (since I was used to TortoiseSVN) but it didn't seem as comfortable as using the official GitHub client.

**Comment by norv** [comment]
Yes, the first "post": Some hook stuff. It's the PR message, and it gets merged in the repository - so it's saved, and accessible in any clone of the repo, so even no matter if one day we go away from github. It's simply not recommended procedure but accepted for starters.

It's not a problem that amend changes the commit hash, only the set of commits may then need to be rebased
(git rebase -i [commit_hash_from_which_to_start])

**Comment by emanuele45** [comment]
So, is this fine now?
Or are you still working on fix the sign-off?

**Comment by marcusforsberg** [comment]
I've edited the PR and added in the sign-off line which is okay according to Norv, so yes, it's fine! :)

**Pull request merged**
