### PR TITLE
Raise required PHP version to 5.4.45

### PR DESCRIPTION
**Pull request by Sesquipedalian**

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Just waiting to ensure there are no objections before merging.

**Review by colinschoen — APPROVED** [review]
LGTM

**Comment by NanoSector** [comment]
LGTM. The removed whitespace shouldn't matter.

**Comment by Sesquipedalian** [comment]
> The removed whitespace shouldn't matter.

That's just from my text editor automatically trimming it. :)

**Comment by NanoSector** [comment]
It's not an issue, it's nice to have these cleanups. :)

**Pull request merged**
