### PR TITLE
Fixes #3917

### LINKED ISSUE #3917: Double string in personal messages
The text «You have forwarded or responded to this message.» is displayed twice

double

### PR DESCRIPTION
**Pull request by frandominguezl**

### CODE REVIEW

**Comment by live627** [comment]
Error: End of File contains extra spaces in ./Themes/default/PersonalMessage.template.php

**Comment by frandominguezl** [comment]
I'm not experiencing that @live627

**Comment by Oldiesmann** [comment]
Your commit added an extra blank line after the closing PHP tag. That's why the Travis CI build is failing. You need to fix that as it can cause problems with mods that add stuff at the end of a file.

**Comment by frandominguezl** [comment]
It should be fixed now

**Comment by frandominguezl** [comment]
So no, it keeps rejecting me the changes although I've "deleted" the extra space after the closing tag two times...

**Comment by sbulen** [comment]
I think it's complaining about the cr (return), not a space.

**Pull request closed without merging**
