### PR TITLE
MariaDB group by quirk

### LINKED ISSUE #6309: MariaDB GROUP BY issue
#### Description
This occurs during exports

Forum post:
https://www.simplemachines.org/community/index.php?topic=575293.0

> I cannot export my profile data, maybe it's another error due to the conversion from MyBB  ;D

```
Type of error: Database
Error message:
Errore del Database: 'user_smf.pm2.from_name' isn't in GROUP BY
File: /home/public_html/Sources/News.php
Line: 2593
URL of page causing the error: https://site.com/cron.php
Backtrace information
#0: smf_db_error()
Called from /home/public_html/Sources/Subs-Db-mysql.php on line 489
#1: smf_db_query()
Called from /home/public_html/Sources/News.php on line 2593
#2: getXmlPMs()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 236
#3: exportXml()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 459
#4: exportHtml()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 117
#5: execute()
Called from /home/public_html/cron.php on line 233
#6: perform_task()
Called from /home/public_html/cron.php on line 127
```

### Environment (complete as necessary)
- Database Type: MariaDB

### Additional information/references
https://jira.mariadb.org/browse/MDEV-11588

https://github.com/SimpleMachines/SMF2.1/issues/6094

### PR DESCRIPTION
**Pull request by sbulen**
Fixes #6309 

Anybody have MariaDB who can test this?

### CODE REVIEW

**Comment by sbulen** [comment]
User on the site confirmed this works:
https://www.simplemachines.org/community/index.php?topic=575293.msg4072201#msg4072201

I have also done multiple tests on my own sites - comparing the output of the query before & after the change.  That also looked good.

**Comment by albertlast** [comment]
got someone a big enough dataset to test,
if performance changes are happening?

**Comment by sbulen** [comment]
I A/B'd the change on an account that had many thousands of PMs.  I didn't write down the #s, but there was basically no change using a limit of 5000.  Queries executed in a fraction of a second on my PC.

**Comment by albertlast** [comment]
technial it's huge change, the old version was possible power by the pk index the new one is based on the output...

**Comment by sbulen** [comment]
I don't have a fully loaded pg DB to test with.  

Know of a converter that actually works?

**Comment by albertlast** [comment]
the problem are the ip fields,
since they got varbinary coded in mysql...

**Comment by sbulen** [comment]
I converted my prod forum from mysql to pg to do this particular test.

Information on how the conversion was performed may be found here:
https://www.simplemachines.org/community/index.php?topic=575453.0

Although I do not have good diagnostics that provide a detailed measurement, the before & after here seem negligible in pg, even with very large datasets.

I think we're good on pg.

**Comment by albertlast** [comment]
So you did a 2.0 mysql to 2.0 pg conversion?

**Comment by sbulen** [comment]
No, a 2.1 mysql to 2.1 pg conversion.

I think the same utilities would work for 2.0, though.

**Comment by sbulen** [comment]
I just moved the topic on the SMF forum from 2.0 to 2.1...

**Comment by sbulen** [comment]
Regarding the conversion itself, quotes were a problem...

The bigger problem was fixing the sequence numbers after the import...  Nothing I found online worked for pg version 10 for my DB.  All the queries to find sequence tables & columns (usually via pg_class & pg_depend) failed.  I ended writing my own that approached it via pg_attrdef...

**Comment by albertlast** [comment]
sequence i will look in a minute, like i mention before, for me is the ip stuff the complexes one (reason why i look first into this).
your approache it's litte bit complex and only work with ipv4:
https://github.com/sbulen/sjrbTools/blob/0f542ae8a318dc239a48e0ce84622160e05aa09c/PGConverter.php#L124
since we got the same issue in smf 2.1 too,
i would recommand to use smf logic to some extend (feel free to drop the valid check):
https://github.com/SimpleMachines/SMF2.1/blob/493a4cb9c9e4c1a9f7c76b4c5fd78afe629d2e9e/Sources/Subs.php#L6096-L6108
inet_ntop is hero of this code.

**Comment by sbulen** [comment]
I think you're right - the conversion utility is only tested for ipv4.  I don't have ipv6 data to test with.

**_But for purposes of this PR,_** I think I found that even with a large dataset, the performance impact of the change is negligible.

**Comment by albertlast** [comment]
sure sure.
The sequence logic looks also a litte bit to mutch.

```

**Comment by sbulen** [comment]
Nothing I found online on the pg boards worked to correct sequences.  And all sequences were all at 1 after loading the data, resulting in many duplicate key issues...  

I had to roll my own.  

And it works.

**Comment by albertlast** [comment]
yeah i notive while writen the upper post,
that something is wront.
and i found the issue, the owned by is not setted to the sequence: https://github.com/SimpleMachines/SMF2.1/pull/6323

**Comment by albertlast** [comment]
> 
> 
> I converted my prod forum from mysql to pg to do this particular test.
> 
> Information on how the conversion was performed may be found here:
> https://www.simplemachines.org/community/index.php?topic=575453.0
> 
> Although I do not have good diagnostics that provide a detailed measurement, the before & after here seem negligible in pg, even with very large datasets.
> 
> I think we're good on pg.

use explain analyze vs the two version of the query to get some numbers.

**Comment by sbulen** [comment]
Interesting...  On pg, it's consistently a couple 1/1000ths of a second quicker.  I was not expecting that...

Before: 0.093 sec
After: 0.091 sec
limit 5000

**Comment by albertlast** [comment]
okay than it look like wrong "alarm",
it's hard to foresee the behavior.

just for my intress, could you past both explain output here: https://explain.depesz.com/
and provide the url, so that i can understand why the behav in this way.

**Comment by sbulen** [comment]
**_Before change - explain plan:_**
--
Merge Join  (cost=5411.81..7059.82 rows=3720 width=1068)
Merge Cond: (pm2.id_pm = pm.id_pm)
->  Limit  (cost=5411.52..5532.42 rows=3720 width=597)
->  GroupAggregate  (cost=5411.52..5532.42 rows=3720 width=597)
Group Key: pm2.id_pm, memf.real_name
->  Sort  (cost=5411.52..5420.82 rows=3720 width=48)
Sort Key: pm2.id_pm, memf.real_name
->  Hash Left Join  (cost=4892.08..5190.91 rows=3720 width=48)
Hash Cond: (pm2.id_member_from = memf.id_member)
->  Hash Join  (cost=3116.10..3405.16 rows=3720 width=43)
Hash Cond: (pmr.id_member = mem.id_member)
->  Hash Join  (cost=1340.13..1619.42 rows=3720 width=25)
Hash Cond: (pmr.id_pm = pm2.id_pm)
Join Filter: (((pm2.id_member_from = 4) AND (pm2.deleted_by_sender = 0)) OR ((pmr.id_member = 4) AND (pmr.deleted = 0)))
->  Seq Scan on smf_pm_recipients pmr  (cost=0.00..240.77 rows=14677 width=14)
->  Hash  (cost=1158.56..1158.56 rows=14525 width=23)
->  Seq Scan on smf_personal_messages pm2  (cost=0.00..1158.56 rows=14525 width=23)
Filter: (id_pm > 0)
->  Hash  (cost=1375.99..1375.99 rows=31999 width=22)
->  Seq Scan on smf_members mem  (cost=0.00..1375.99 rows=31999 width=22)
->  Hash  (cost=1375.99..1375.99 rows=31999 width=13)
->  Seq Scan on smf_members memf  (cost=0.00..1375.99 rows=31999 width=13)
->  Index Scan using smf_personal_messages_pkey on smf_personal_messages pm  (cost=0.29..1407.38 rows=14525 width=488)



**_After change - explain plan:_**
--
Merge Join  (cost=5411.81..7059.82 rows=3720 width=1068)
Merge Cond: (pm2.id_pm = pm.id_pm)
->  Limit  (cost=5411.52..5532.42 rows=3720 width=588)
->  GroupAggregate  (cost=5411.52..5532.42 rows=3720 width=588)
Group Key: pm2.id_pm, (COALESCE(memf.real_name, pm2.from_name))
->  Sort  (cost=5411.52..5420.82 rows=3720 width=546)
Sort Key: pm2.id_pm, (COALESCE(memf.real_name, pm2.from_name))
->  Hash Left Join  (cost=4892.08..5190.91 rows=3720 width=546)
Hash Cond: (pm2.id_member_from = memf.id_member)
->  Hash Join  (cost=3116.10..3405.16 rows=3720 width=43)
Hash Cond: (pmr.id_member = mem.id_member)
->  Hash Join  (cost=1340.13..1619.42 rows=3720 width=25)
Hash Cond: (pmr.id_pm = pm2.id_pm)
Join Filter: (((pm2.id_member_from = 4) AND (pm2.deleted_by_sender = 0)) OR ((pmr.id_member = 4) AND (pmr.deleted = 0)))
->  Seq Scan on smf_pm_recipients pmr  (cost=0.00..240.77 rows=14677 width=14)
->  Hash  (cost=1158.56..1158.56 rows=14525 width=23)
->  Seq Scan on smf_personal_messages pm2  (cost=0.00..1158.56 rows=14525 width=23)
Filter: (id_pm > 0)
->  Hash  (cost=1375.99..1375.99 rows=31999 width=22)
->  Seq Scan on smf_members mem  (cost=0.00..1375.99 rows=31999 width=22)
->  Hash  (cost=1375.99..1375.99 rows=31999 width=13)
->  Seq Scan on smf_members memf  (cost=0.00..1375.99 rows=31999 width=13)
->  Index Scan using smf_personal_messages_pkey on smf_personal_messages pm  (cost=0.29..1407.38 rows=14525 width=488)

**Comment by albertlast** [comment]
please use EXPLAIN ANALYZE and not explain only.

**Comment by sbulen** [comment]
Sorry, that's all I got...

**Review by live627 — APPROVED** [review]

**Pull request merged**
