### PR TITLE
Modifications for the sceditor - Quote looks as on the Forum 

### PR DESCRIPTION
**Pull request by PortaMx**
With this change, the sceditor becomes a better and clear look for quotes and eliminates errors on fault bbc codes (as Example LINK is removed, but DATE is filled)

**On the sceditor (WYSIWYG)**
image10

**On the Preview**
image11

### CODE REVIEW

**Comment by live627** [comment]
Hmm,  you have old files.

**Comment by PortaMx** [comment]
I don't know what you  mean ...

**Comment by live627** [comment]
I see lots of unrelated code changes.

**Comment by PortaMx** [comment]
I understand not what you mean. 
Well .. you can implement that, or not.
For me . .it's perfect and works perfect ...

**Comment by MissAllSunday** [comment]
He means you are using old files to create your PR.

Please create a new branch and pull the latest files from the release-2.1 branch and add your edits there.

**Comment by XinYenFon** [comment]
I think we need changes from here to make sure forum & sceditor (textarea) has same time display (style) others are done by me already.

**Comment by PortaMx** [comment]
This is what I have done..

Look at http://smf21devel.portamx.com/
also on
https://github.com/PortaMx/SMF2.1/tree/portamx

my_qoute_design

**Comment by Sesquipedalian** [comment]
I think this PR was rendered obsolete by #3446.

**Comment by XinYenFon** [comment]
@Sesquipedalian partly, we still need the changes from JS file to fix time stamp.

**Comment by MissAllSunday** [comment]
Again, wrong way to fetch current changes respecting everyone else commits.

**Pull request closed without merging**
