### PR TITLE
Enhance registration integration hooks

### PR DESCRIPTION
**Pull request by grangeway**
The existing hook integrate_register is described as being able to do further validation [http://wiki.simplemachines.org/smf/Integration_hooks#integrate_register]

However, it can not return errors to the user in the same way the registerMember function does ~20 lines above.

This patch is a modified version of the patch run locally that allows an integration hook to return an array of error messages to return to the user.

Secondly, this patch adds a post registration hook, that can be used to store the SMF member ID in a seperate system before the actual account is activated [i.e. integrate_activate is called]

This for example allows for the registration template to be customised to ask the user for custom information, and store that information for later review during the admin approval/activation process.

### CODE REVIEW

**Comment by live627** [comment]
I like your idea, but not the implementation. I don't think this lines up with the code logic. Despite what the wiki said (I  have no idea what is says  on this hook), integrate_register, IMO, should NOT do ANY validation. It should only  serve as an extender too the direct registration variable.

A different hook should be used for validation. Higher up in the function, $reg_errors is processed within a froeach loop, A validation hook should be right above that.

**Comment by live627** [comment]
This won't go into 2.1; change this request to ''development'', which is 2.2.

**Comment by grangeway** [comment]
Live627 - i've done an updated diff against the development branch  @ https://github.com/SimpleMachines/SMF2.1/pull/242 . See if that version makes more sense.

**Comment by live627** [comment]
Can you now close this PR? It is now ambiguous and no longer needed.

**Pull request closed without merging**
