### PR TITLE
Update hashing algorithm for passwords to BCrypt

### PR DESCRIPTION
**Pull request by Dragooon**
Previously hashes were computed as sha1(lower(username) . password), update this to add a layer of sha256 so that it becomes sha256(sha1(lower(username) . password) based on ideas by @jdarwood007.

The cookie password hash becomes sha256(password_hash . salt) instead of sha1(password_hash . salt), but the login hash remains same as before. This provides additional protection as someone with the hash from the database can't login directly simply by submitting that into the login form, they'd still need the original password to be able to login

EDIT: Updated this PR to move to entirely to bcrypt instead, and drop client side hashing. See commits for reasoning

Signed-off-by: Shitiz Garg mail@dragooon.net

### CODE REVIEW

**Comment by live627** [comment]
Shouldn't `strtolower()` be using `$smcFunc['strtolower']()` in order to allow for Unicode characters?

**Comment by Dragooon** [comment]
I'm not sure, it was strtolower all the places plus it's simply used to calculate the hash so it doesn't affect anything as such. I'd say leave it alone since it might break something? Or should we change it?

**Comment by live627** [comment]
I'm pretty sure it'll fix #1538

**Comment by Dragooon** [comment]
That is a whole rat's nest of issues, using $smcFunc doesn't really fix it, it breaks it for uppercase letters since the client side can't handle making them properly lower case (as we always hash on client side, the password is incorrect in case the user tries to enter upper case first letter or something). Using JS's toLowerCase + $smFunc['strtolower'] _might_ fix it but I'm not 100% certain, since the client side will do it correctly but on the off chance that the server doesn't have mb_strtolower, it becomes off on the server side.

**Comment by Dragooon** [comment]
Okay since we're moving away from sha1 anyway, I figured go full length and implement bcrypt instead. This requires to bump up the min. version to 5.3.7 but that's fine.

**Pull request merged**
