### PR TITLE
Force to be lowercase as only check lower case later in function scope

### PR DESCRIPTION
**Pull request by tinoest**
Signed-off-by: tinoest tinoest@gmail.com

### CODE REVIEW

**Comment by albertlast** [comment]
should you not fix the code, instead of repairing it in this functions?

**Comment by tinoest** [comment]
The fix would be to force it with a enum. But that’s not an option. Other option is to reject any invalid value. 

This is just sensible to make the input match the check.

**Comment by albertlast** [comment]
i mean the calling code to fix instead here.

**Comment by tinoest** [comment]
> i mean the calling code to fix instead here.

Yes, I understand and my original response answers that question. Best practice is an enum or to reject an invalid value.

This is imo the next best alternative, which doesn’t break existing behaviour.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
