### PR TITLE
Remove the toggle menu entri, it is a profile option, not something that...

### PR DESCRIPTION
**Pull request by emanuele45**
... should be changed every page load

Signed-off-by: emanuele emanuele45@gmail.com

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me. Had a thought about maybe extending the setting for tablets too. Thread in the dev board at SMF.

**Comment by emanuele45** [comment]
/me doesn't have a tablet, so no opinion. :P

Wait a bit to see for objections. :P

**Comment by jdarwood007** [comment]
This was introduced when Curve was developed.  If I remember right it was introduced as a transitional option for the menu design change.  So if it moves to a true profile option, I don't think anybody will miss it at this point.  Most have adjusted to the new menu or set their preference.  Others will setup their preference as needed.

**Comment by emanuele45** [comment]
It was already a profile option, in addition there was the button.
I just removed the button.

So that means this can be merged.

**Pull request merged**
