### PR TITLE
Replace "TFA" with "2FA"

### PR DESCRIPTION
**Pull request by m4z**
Currently, both are used inconsistently.

Note this only touches language strings, not code and comments, etc.

### CODE REVIEW

**Comment by XinYenFon** [comment]
You forgot to sign-off both of your PRs : ) you go agane...

**Comment by m4z** [comment]
Let me find out how to do that…

**Comment by XinYenFon** [comment]
I think best for you to learn basic authentication / local sign-off (SSH/GPG).

Step 1: https://help.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key
Step 2: https://help.github.com/en/github/authenticating-to-github/adding-a-new-gpg-key-to-your-github-account

then you can do local changes and sign off with -S

**Comment by Sesquipedalian** [comment]
I don't even bother with the GPG key. I just use `git commit -s` (note the lowercase) and get on with it.

**Pull request merged**
