### PR TITLE
Added ORDER BY to Subs-BoardIndex.php, hopefully fixes #887

### LINKED ISSUE #887: Boards/Categories sorted after upgrade
I upgraded my alpha build 3 times (2.0.x to 2.1 Alpha) - (2.1 Alpha to 2.1 Alpha) - (2.1 Alpha to 2.1 Alpha) and my boards/categories sorted differently from as it needs to be.

But if i edit a board (move up/down) everything fixes itself.

Apache version  2.4.7
PHP version     5.4.23
MySQL version   5.5.35-cll

### PR DESCRIPTION
**Pull request by margarett**
Added ORDER BY

As far as I've tested, this fixes:
- Wrong board order (different from admin)
- Wrong board order when adding local moderators
- Posts in child boards and empty parent do not show in Board Index

All tested with MySQL 5.6

Signed-off-by: margarett bruno.m.alves@gmail.com

### CODE REVIEW

**Comment by Oldiesmann** [comment]
While it does fix the issues, it's not really the best solution. See #858 for more info.

**Comment by margarett** [comment]
Looking at it, I think that we can just remove the moderators and group moderators tables, transforming those into text/varchar fields at the boards tables, ids separated by commas. 
Or is there a reason I'm missing for having dedicated tables?

This part (local moderators) seems pretty obvious to change, the rest of the huge query I'm not that sure. Everything there seems really necessary. 

I can also think about getting independent queries for the members table (in order to avoid that massive joins)

What do you think?

**Comment by Oldiesmann** [comment]
I honestly can't see any advantage to doing that, or even having a flag to indicate whether or not a board has moderators. Is saving a couple of queries (which, when split out from the big one, are actually pretty simple as far as queries go - pulling two columns and using an INNER JOIN and a WHERE) really that important?

It may be best to consult with Arantor on this and see if he can shed some more light on this situation.

**Comment by Dragooon** [comment]
This can be closed as it was deprecated by #1637

**Comment by Oldiesmann** [comment]
Deprecated by #1637

**Pull request closed without merging**
