### PR TITLE
Remove unneeded col alter of ip in log_online

### PR DESCRIPTION
**Pull request by albertlast**
To alter the column make no sense,
because later on we alter it again to inet and
this alter create a issue when you try to upgrade the upgrade.

In this case pg try to convert inet datatype of ip to bigint which is not possible.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Does a similar change need to be made in the MySQL file?

**Comment by albertlast** [comment]
I didn't found this,
Your could look too
If you find the line in mysql

**Comment by Sesquipedalian** [comment]
Looks like it, yes.

First time:
https://github.com/SimpleMachines/SMF2.1/blob/04cffc29c20e5cdde059434cbf2bdeeb9a3ab928/other/upgrade_2-1_mysql.sql#L2257-L2274

Second time:
https://github.com/SimpleMachines/SMF2.1/blob/04cffc29c20e5cdde059434cbf2bdeeb9a3ab928/other/upgrade_2-1_mysql.sql#L2318-L2335

The only difference is the comments.

**Comment by albertlast** [comment]
Well this is something different,
but yes we could remove this duplicate, too.

**Pull request merged**
