### PR TITLE
Add SMF_2-1_NEXT branch for next release

### PR DESCRIPTION
**Pull request by sbulen**
Allow for periodic updates of GH code over on CrowdIn.

This goes for weekly udpates.  It will update a new, separate branch, SMF_2-1_NEXT.

@jdarwood007 - My only question here is whether you need to specify the branch on your download.  If unspecified, it will probably download both branches, SMF_2-1 & SMF_2-1_NEXT, which might interfere with your process.

So please take a look!   THX....

### CODE REVIEW

**Comment by jdarwood007** [comment]
The generation will generate all of them based on how we export from Crowdin, but the package build process will only build from the "SMF_2-1" for the SMF 2.1 branch.  It also can build from the "SMF_2-0" into the SMF 2.0 branch if we import those.  All other folders would be ignored.

**Comment by sbulen** [comment]
If it helps, this is what builds/downloads would look like.  You only want the SMF_2-1 one.

DownloadBothBranches

**Comment by sbulen** [comment]
Based on the internal discussion, sounds like this is good to go!

**Comment by live627** [comment]
Ok then I'm going to merge this one now.

**Pull request merged**
