### PR TITLE
! fix for span. and change to div

### PR DESCRIPTION
**Pull request by hhy89**
i think div is better in here.

Signed-off-by: hhy89 hhy89@hotmail.com

### CODE REVIEW

**Comment by XinYenFon** [comment]
If I'm not seeing this wrong, that span missing closure. Its also missing on post & personalmessage templates as well.

**Comment by hhy89** [comment]
yeap span is missing closure. post & personalmessage templates' span are closed. look again :)

**Comment by XinYenFon** [comment]
I don't see any changes on post.template.php & personalmessage.template.php ? :/

**Comment by hhy89** [comment]
span is open but it doesnt closed in display.template.php
http://i.hizliresim.com/PEl7JN.png

but the other files span is closed.
http://i.hizliresim.com/NbZLR5.png
http://i.hizliresim.com/9pmYjk.png

in turkish:
zaten kapalı onlarda Mert :) ama display.template.php de kapatmayı unutmuslar.
öyle gözüme carptı düzelteyim dedim bi dl hatası vardı bi de bu span hatası vardı.

**Pull request merged**
