### PR TITLE
Lower the opacity on collapsed boards.

### PR DESCRIPTION
**Pull request by XinYenFon**
nimbus-record-video-2017-08-26-01-39-42

### CODE REVIEW

**Review by frandominguezl — APPROVED** [review]
Looks great!

**Comment by XinYenFon** [comment]
Forgot to mention huge thanks to @Yoshi2889 who wrote the code snip for me back in day.

**Review by Gwenwyfar — COMMENTED** [review]
Looks good! Maybe speed up the transition though? 0.4s maybe.

**Comment by XinYenFon** [comment]
It looks extra slow on GIF for some reason...

**Comment by NanoSector** [comment]
Gifs run slower than the real thing anyway. Also I don't remember providing the snippet but you're welcome xD

**Comment by Gwenwyfar** [comment]
Yeah, maybe the framerate. But I'm going by the 1s time on css, I never got any hover transitions to look very nice with anything over 0.5s. 1s mouse may even be long gone from the button.

Edit: Oh, nevermind that, 1s looks good for such a huge element :)

**Review by Gwenwyfar — APPROVED** [review]

**Comment by XinYenFon** [comment]
Don't take this as final form, in RC stage we can ask community related to those transition speeds so we can shape them little more.

**Pull request merged**
