### PR TITLE
More -utf8 suffix fixes

### PR DESCRIPTION
**Pull request by sbulen**
Addresses issues logged in:
Upgrader: Freezes, loses graphics, loses buttons, errors #3877

### CODE REVIEW

**Comment by sbulen** [comment]
_But without this PR, the upgrader does not run to completion._  Which makes it difficult for folks to test & contribute.

**Comment by frandominguezl** [comment]
Your last commit was already fixed and merged in #3892

**Comment by sbulen** [comment]
Oops, missed that...   Thanks d3vcho.   I'll remove it.

**Comment by frandominguezl** [comment]
No problem ;)

**Pull request merged**
