### PR TITLE
Update Subs-Db-mysql.php

### PR DESCRIPTION
**Pull request by Underdog-01**
- any modification or future SMF update that includes additions/changes for where clauses contained within the $user_info array (using the query_ prefix) will be included using this method.
- Imo this should also be applied to the SMF 2.0.15 update

Signed-off-by: -Underdog- github.underdog@gmail.com

### CODE REVIEW

**Comment by colinschoen** [comment]
Thanks for your `PR`. 

All commits must be signed off. You can run

`git commit --amend --signoff`

To sign off your previous commit.

**Comment by Underdog-01** [comment]
Oops.. forgot to sign off with the initial commit.. too used to editing my own repos.
I applied that command in my WIndows GitHub terminal & it pushed a new file... not sure if that was the proper way of doing it.

Travis CI is failing the check. Could this be due to the "no newline at end of file" flag?

**Comment by colinschoen** [comment]
The issue is that commits `129c2a7`, `edeb5b1` are not signed off. Sign off those and you should be passing travis. 

screen shot 2017-05-22 at 19 44 56

**Comment by colinschoen** [comment]
You don't want to push another commit that is signed off. You want to amend your old commits to include the `signed-off...` in the description.

**Comment by Underdog-01** [comment]
I am going to close this PR and do it anew to include the sign off in the comment.

**Comment by colinschoen** [comment]
Sounds good.

**Pull request closed without merging**
