### PR TITLE
+ Awesomely awesome progress bars. Animated, too!

### PR DESCRIPTION
**Pull request by marcusforsberg**
(Note: Have not actually tested the upgrade.php progress bars properly)

Preview
Preview

### CODE REVIEW

**Comment by DrDeejay** [comment]
I think they look great, much better than the current ones. :)

**Comment by marcusforsberg** [comment]
Thanks. They animate just beautifully, too, if I might say so myself! :)

**Comment by ghost** [comment]
The striped css3 background gradients are quite nice,been floating around on the net for a while. But how does it fare with non-supportive browsers?

**Comment by marcusforsberg** [comment]
The ones I've tested (mainly IE) fall back nicely enough, since there's also a background colour set for old timers to use. :)

**Comment by live627** [comment]
If I might chime in, I'd say the inner shadows are a tad big and dark.

**Comment by marcusforsberg** [comment]
Are you referring to those stripes, then? I can see where you come from on the size, I guess, and that's easily changed in the CSS, but I have tried to make them more subtle (lighter) and they just end up being almost invisible and just annoying cause you kinda have to make an effort just to see them properly.

**Comment by live627** [comment]
Nope! The candy striping looks perfect. I mean the grey shadow on the grey background.

**Comment by marcusforsberg** [comment]
Ooooh, I forgot that even existed! :D I do agree, will clean that up!

**Comment by Trekkie101** [comment]
Marcus out of curiosity what do they look like bright orange instead of green?

**Comment by emanuele45** [comment]
Sorry to bother, but after Ant's changes to index.css (that I merged thinking it was just Penguin removal lol), I'm not sure what I have to keep and what I have to drop here...could you please have a look?

**Comment by marcusforsberg** [comment]
Just had a quick look and it should still work just fine with the CSS in this one. Ant will probably end up changing them again though so it's up to you guys if there's any point in merging this one or not... :P

**Comment by Trekkie101** [comment]
Is it just me or does the green stick out a bit too much?

**Comment by norv** [comment]
A bit, maybe, yes. It's a little too powerful. :D

**Comment by matthew-kerle** [comment]
I agree. I like the idea, but maybe a different colour that fits our theme a little bit better.

**Comment by Oldiesmann** [comment]
Do we still want to try to pull this in/tweak it? So much stuff has been merged in since this commit that there's now a conflict, so that needs to be resolved if we want to try this.

**Comment by matthew-kerle** [comment]
Honestly the CSS3 isn't that difficult to write again. We can even look at the places he implemented it and then follow suit with a new PR. I think that's the best way to go at this point since SO much has indeed changed.

Plus, I do agree with the other previous comments that the colour of the animation should probably change slightly to fit in our theme a little bit better, therefore on top of the other reasons, a new PR seems quite reasonable.

**Comment by Oldiesmann** [comment]
Going to go ahead and close this then. Would still love to see something like this in SMF

**Comment by matthew-kerle** [comment]
Might be a good idea to create a new issue for this, referencing this particular issue. So we don't forget.

**Pull request closed without merging**
