### PR TITLE
! iPad autocomplete was replacing email address in account settings

### PR DESCRIPTION
**Pull request by AngelinaBelle**
Fake name and password fields prevent Safari and chrome from replacing email in account settings.

Signed-off-by: Angelina Belle angelinabelle1@hotmail.com

### CODE REVIEW

**Comment by AngelinaBelle** [comment]
Fixes #1757

**Comment by AngelinaBelle** [comment]
Please merge to work around the ios over eager autocomplete.  This PR makes SMF much friendlier to iPad users.

**Comment by Oldiesmann** [comment]
Won't those fake inputs be visible to the user?

**Comment by AngelinaBelle** [comment]
They are outside the visible window because of the absolute positioning.  If you use hidden, Safari is smart enough to ignore them.

**Pull request merged**
