### PR TITLE
Moderation center

### LINKED ISSUE #505: moderation center latest news
why do moderators need to know the latest news from smf? i think it would be more useful to add a block for unapproved posts/attachments instead, or even membership requests for those that can approve the requests

### PR DESCRIPTION
**Pull request by MissAllSunday**
Fixes #505 couldn't reproduce #635
- Puts the moderators notes outside the rest of blocks, uses all width available.
- Removes moderation settings for latest news and notes.
- Adds the time stamp to each note. Dunno whats the best place for it so I just put it at the beginning.

I know its a bit hackish, however, I wanted to avoid breaking as less things as possible.

Dunno if the latest news block will be used somewhere else, I just remove it.

### CODE REVIEW

**Comment by MissAllSunday** [comment]
Oh, I couldn't reproduce #635 because I have to enable the sidebar. didn't knew that. Oh well, theres a proposal to remove it anyways.

**Comment by live627** [comment]
But why remove the sidebar?

**Comment by MissAllSunday** [comment]
It is only a proposal.

**Comment by Arantor** [comment]
We did propose to remove the sidebar for a variety of reasons, not least solving some other issues (because it was already supposed to have been removed anyway by now)

**Pull request merged**
