### PR TITLE
Cherry pick

### PR DESCRIPTION
**Pull request by emanuele45**
A collection of cherry-picking from Spuds and eurich

### CODE REVIEW

**Comment by matthew-kerle** [comment]
Can't be merged because of the avatar CSS that I already tweaked in my CSS tweaks PR.

**Comment by Oldiesmann** [comment]
@emanuele45 Please fix the conflict so this can be merged in :)

**Comment by norv** [comment]
This is an useful collection of cherry-picks from the work done by Spuds, Ema and TE on Elk.

Just a simple suggestion: anyone can fix the conflicts. Either by cherry-picking these commits to a local branch, either rebase or merge them and fix in the process. It has already been quite a lot of work to review them, pick them together and I'm quite certain Ema already had to fix them in the process.

**Comment by Oldiesmann** [comment]
Norv, last time I went fixing a merge conflict, the changes went in as me rather than as the person who sent the initial PR. Is there a way to do it so that the changes needed to resolve the conflict get attached to the original PR?

**Comment by norv** [comment]
@Oldiesmann it should create a merge commit, and the merge commit would be yours. A thought: was it a single commit? I suspect so. Well, if it does, you can always commit the merge with:
git commit -s --author="name <email>"

**Comment by eurich** [comment]
Just a note: my code was made for ElkArte, so the copyright is "ElkArte forum contributors" ;) This should be added to the header of the related files ..

**Comment by emanuele45** [comment]
Up to @Oldiesmann or @Labradoodle-360 decide if they want:
1) add the entry to the header,
2) remove the commit https://github.com/emanuele45/playpen/commit/b4760a5981a587b39d7255073094bbbbbe8ebd25
3) close the PR and not merge it,
4) ignore the request.

Dunno what's @Spuds position on that.

Though, to be completely honest and objective (please note I'm not attacking your request, I'm just evaluating the situation outside the whole fuss of copyright and licenses, and for [Elkarte's own sake](http://www.elkarte.net/index.php?topic=349.0)), it's a quite borderline situation: two lines of code (of which one is an if with two comparisons that cannot be done in many alternative ways and one is an assignment) are hardly copyrightable as such.

**Comment by Kindred-999** [comment]
I am not certain that every single line of code needs individual attribution, even at the file level.
I believe that the contributors list, including ElkArte forum contributors as a contirbutor of code would be sufficient instead of adding X-teen lines of code to the header of a bunch of files for a single line or two which, as emanuele points out, really only has one decent way of being written in the first place.

**Comment by Spuds** [comment]
Dunno either .... 

I guess if it was a simple bug fix / css tweak then cherry pick away, those are common and will be found by anyone anyway.

If however it was more along a functional change / function add / performance improvement that would not have otherwise been changed, then that work should be attributed back to the project / author that it was copied from.

Although its quite fine and proper to copy / reuse code from another open source project, I feel there is a difference between when that code is CP'ed  vs PR'ed ... in terms of how the code is attributed ... Said differently, to me, if its a PR from the author then its a code "contribution", clearly given to the project by that author ...  If its CP'ed then its a reuse / based on should be in the file header, as in you are using code from another project.

Those are of course generalizations.

**Comment by eurich** [comment]
I really don't care about the typo fixes, but not all  commits are simple fixes, some add new graphics (quickbuttons), others add new "features" (e.g. the mediascreen support in index.css).. That work was done for Elk, not for SMF and should IMO be attributed back to the project / author that it was copied from.

**Comment by Kindred-999** [comment]
I agree. Work should be attributed.  However, is it necessary to attribute each bit of code individually? Isn't the point of the global attributions and contributions to cover it form having to mark each individual line and file?
I mean, it gets to be a vicious circle
SMF, based on elkarte, based on smf....  it could go on for several levels...

**Comment by emanuele45** [comment]
Okay.

**Pull request closed without merging**
