### PR TITLE
Move -you_sure- from javascript to class

### PR DESCRIPTION
**Pull request by XinYenFon**

### CODE REVIEW

**Comment by SychO9** [comment]
Perhaps we should also use `JavaScriptEscape()` on the other text strings used withing the `data-confirm` attribute while we're at it

**Comment by XinYenFon** [comment]
I'd much rather prefer to handle that issue in different PR by different person. The only reason I'm doing this so javascript ($li['javascript'] won't overwrite my custom class for quickbuttons).

**Comment by SychO9** [comment]
Fair enough :)

**Review by Sesquipedalian — APPROVED** [review]
The question is, why wasn't it already like this?

**Pull request merged**
