### PR TITLE
Issue: #338 - $user_info['id'] === $int;

### PR DESCRIPTION
**Pull request by matthew-kerle**
- $user_info['id'] and $context['user']['id'] are now cast to integers.

Thanks to @The-Craw for pointing this out.

Signed-Off: Matthew "Labradoodle-360" Kerle |
lab360@simplemachines.org

### CODE REVIEW

**Comment by ghost** [comment]
Yay. Now I'm not mad anymore. ;)

**Comment by live627** [comment]
And this isn't merged  because...?

**Comment by Oldiesmann** [comment]
@live627 There's a merge conflict. We're waiting for Lab to fix said conflict :)

**Comment by Oldiesmann** [comment]
Matt, are you going to fix the merge conflicts here? I'd like to get this in

**Pull request closed without merging**
