### PR TITLE
Merge branch 'release-2.1' of https://github.com/SimpleMachines/SMF2.1 i...

### PR DESCRIPTION
**Pull request by Arantor**
...nto release-2.1

Signed-off-by: Peter Spicer sleeping@myperch.org

### CODE REVIEW

**Comment by Arantor** [comment]
And every time I encounter this I'm convinced I'm using Git wrong.

**Comment by emanuele45** [comment]
I'm pretty sure you are right: you are using it wrong. :stuck_out_tongue: 
- pull (from the remote (i.e. SMF2.1/release-2.1)
- branch (i.e. **never** commit to your release-2.1)
- commit (do your changes on the branch)
- push (to your remote)
- PR (to SMF2.1)
- merge (into SMF2.1)
- start again.

If the branch becomes obsolete (i.e. you have conflicts): rebase is your friend, not merge.

In #916 you were working on release-2.1 and that messed up your repo.
But don't worry, you are not the only one doing it wrong: Oldiesmann too is doing the same mistake. Suki (even though she uses merge instead of rebase to get the branches up to par), live627 and Illori instead are doing it right.

**Comment by Arantor** [comment]
It's strange, I've been doing it the same way pretty much since day one and it's only today it actually got confused - I haven't done anything differently, and the conditions were not any different, but yet it still got screwed up.

As for branching, I really don't want to make branches for everything because I don't want a bajillion branches (because even the ones I already merged are still listed and updated and whatnot and never go away), which is why I haven't been doing it.

I think I'm probably safest just providing patches and letting other people do it because then at least it'll be something that isn't my fault for a change when it breaks.

**Comment by eurich** [comment]
You don't need to create a branch for every single commit.. create a branch "my_branch", commit several bugfixes to that branch, then push it to your remote and create a pull request.

once the branch is merged you can delete the remote branch via github gui and the local one via:
git branch -D my_branch

**Comment by Arantor** [comment]
Oh, I've been doing the multiple commits to be a single thing already. I just see the whole branching thing as a massive and unnecessary distraction to my workflow.

**Comment by Nao** [comment]
Lol. If it can help you feel better Pete, you're not the only one who has issues with branching. It's mostly useful for testing alternative ways of doing things. Years of svn tend to make you that way. You don't have to use branches, see them as alternate stashes for features you abandoned and want to keep around (bit like Wedge's attic).
And yes, rebasing is good but you have to be quick when doing that. SMF has multiple pushers so you also have a risk of breaking the repo if you don't fetch eight before pushing your rebased repo.

(At least git drama provides for some 'excitement' compared to how dull and straightforward svn was.)

**Comment by emanuele45** [comment]
Well, if you don't want to branch you can always push directly to SMF repo and not even pass through pull request.
It would be more or less like use SVN except that you'd have to fetch first, then do the commits and hope nobody else has changed anything before you push again (otherwise pull wouldn't be enough because it would break the commit series, you'd have then to branch, reset --hard master, pull the remote master, merge and push, unless...it may work: fetch remote and rebase remote/master...I never tried, I should! :angel: ).

Of course, if you are working alone (or mostly) is not such a big deal (I do it with my mods and/or sites I support).

**Comment by emanuele45** [comment]
> once the branch is merged you can delete the remote branch via github gui and the local one via:
>  git branch -D my_branch

You can delete the remote via cli too if you want:
git push origin :my_branch

:grin:

**Comment by Nao** [comment]
I meant 'right' above, not eight. I'm typing on my phone so it doesn't help.

Ema: without the space before the colon, of course. Phone typo too? ;-)

**Comment by emanuele45** [comment]
Nope, with the space...but maybe it works without too, never tried...

**Pull request merged**
