### PR TITLE
Updates for ShowAttachments, sceditor and smf_fileUpload

### PR DESCRIPTION
**Pull request by PortaMx**
I update the file, so all attaches are checked correct and stored in the cache for less DB queries and faster accsess. I tested this extensive and all works correct.

### CODE REVIEW

**Comment by MissAllSunday** [comment]
Thank you but the thing is, I'm still reviwing the changes you made at:

https://github.com/SimpleMachines/SMF2.1/issues/3381#issuecomment-208081759

and I'm not sure everything will be included, it will be far more easy if we can stay there.  Otherwise there would be merge conflicts.

**Comment by PortaMx** [comment]
I just pushed all things they I have changed and tested extensive.

**Comment by MissAllSunday** [comment]
Yes I know but I'm still in the process of reviewing those changes and added some more here: https://github.com/SimpleMachines/SMF2.1/pull/3377  since pretty much all of your changes are included over there, it will be easier for all of us to continue there

**Comment by PortaMx** [comment]
Well .. SMF can do what he want ..
I check all for correct work on all situations and make fixes if I found problems .. and I found many in the current release. Also I make corrections for "not looks good" things, like the qoute in the sceditor.
With a little bit thinking and more look and feel testing, anyone see that .. but not SMF (curiouse)..

**Comment by MissAllSunday** [comment]
yikes...

yes I know you made several fixes, I already included many of them.... what I'm saying is keep all these changes into one place. Thats all.

**Comment by PortaMx** [comment]
I think, here IS the right place to made fixes and updates, if anyon found them !
But I think, that SMF don't have any interest, that peoples like me work on this and send updates and fixes. I have posted a lot of them, but nothing was acceptet !
That let my thinking on SMF's phisosphie .. specially about my person !

**Comment by MissAllSunday** [comment]
OK, please pay attention because this is the only time I'm gonna say it.

I already said multiple times that the vast mayority of your changes **are already included** into another PR. Onces that PR gets merged YOUR changes are merged with it too.

Any code submitted needs to be reviewed, it doesn't matter if it is submitted by you or me or the founder of SMF, **all code needs to be reviewed**.   I'm really sorry that you confuse this normal, quasi defacto open source procedure with a lack of interest from us or worst, as an attack on your person.

The fact that I've been working with you, spending a few hours reviewing and merging YOUR changes is proof enough that WE DO CARE.

Please drop the attitude, no one is gaints you, no one is dismissing your contributions, no one have any issues with you.

I honestly thought we were working together just fine.

**Comment by live627** [comment]
> nothing was acceptet 

oh hey look https://github.com/SimpleMachines/SMF2.1/commits?author=PortaMx

**Comment by PortaMx** [comment]
Sorry live627 .. i understand nothing

**Comment by Sesquipedalian** [comment]
@PortaMx, they're saying:
1. They are interested in your code and the contribution is appreciated. @MissAllSunday is reviewing the code, just like every other pull request. 
2. You have included the same changes in more than one pull request. This makes it harder to do the code review. So, @MissAllSunday has asked you not to include the same code changes in more than one pull request in the future.

**Comment by PortaMx** [comment]
Hmmm .. I'm not expert on Git .. so I tell you how I work;

I have a local copy of the forked Github respoitory. 
On this local copy I work, make changes an test it.
If I mean it's good, I commit that on my PC und make a push to the forked Github repository.

Thats all .. I never create a Pull request on Gitgub.

If any fault on my steps ?

**Comment by PortaMx** [comment]
So .. I woked more on all the bug's if found ..
Now the IURL to ATTACH converting works correct, also in the editor.
Also now all inserted attaches are removed from attched file section, if is enabled.

If SMF have interest on my fixes, let me known ...

**Comment by XinYenFon** [comment]
You can actually read basics of Git, which is more than enough for starting. Branching is important because that'll avoid some conflicts in the future.

None is/was/will be against your contribution, we value your ideas/fixes/improvements but when your/mine/others changes already included inside other PR(s) that'll create "merge conflict". 

I suggest you to take a look: http://www.simplemachines.org/community/index.php?topic=525935.msg3849538#msg3849538

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/3390#issuecomment-213101674

**Pull request closed without merging**
