### PR TITLE
Fixes for top_info avatars

### PR DESCRIPTION
**Pull request by Gwenwyfar**
Fixes image scaling and #4343.

This is how it will display on images that fail to load:
broken-image

On some non-supporting browsers, nothing will show (the alt text will also remain hidden, to not break the layout).

Image used is my own.

### CODE REVIEW

**Review by frandominguezl — APPROVED** [review]

**Comment by XinYenFon** [comment]
I don't think adding yet another default (fallback) avatar is the solution, core system should be loading a default avatar when one does not exist.

**Comment by Gwenwyfar** [comment]
If the theme images folder is broken then the entire theme will be, not just avatars as is the case here. We could use the same image as avatarless members, but that would become hard to differentiate from broken avatars.

**Comment by XinYenFon** [comment]
If the image folder is broken, user needs to fix bigger problem. Such additions only required if there is no fallback to current solution.

**Comment by Gwenwyfar** [comment]
If this can be fixed another way then whoever can do that feel free to do so.

**Comment by jdarwood007** [comment]
Problem would be css does not know the avatars location, since that url is separate from the themes url.

**Comment by XinYenFon** [comment]
@Gwenwyfar there shouldn't be any need of any fix, the broken (non-existent etc...) avatars should fallback to default avatar, if default avatar does not exist in the situation that means either code lacks the fallback to default avatar or setup has issues related to locating the default avatar. What you are offering is actually a fallback for default avatar.

**Comment by Gwenwyfar** [comment]
Exactly. If the problem can be fixed with the default avatar fallback, then we don't need this fix.

I made this assuming the paths to avatars don't work (for whatever reason) and that this may be a common situation, but if the default avatar is already serving that purpose there is no need for this, if it can be made to work correctly in all cases (although keeping the transparent alt doesn't hurt in any case)

**Comment by colinschoen** [comment]
I agree with @Antes. If we are displaying this second-fallback image something is seriously wrong and it may create more confusion as to why or where this is actually loading from if all the paths are wrong.

**Comment by colinschoen** [comment]
Closing per rationale above.

**Comment by Gwenwyfar** [comment]
Ok. I'll submit the other fixes included in this in another PR.

**Pull request closed without merging**
