### PR TITLE
Improve error log

### LINKED ISSUE #6071: Error log display
#### Description
Something happened to the display of the error log, I hadn't seen this before.  The individual entries exceed the boundaries of the page.

### Steps to reproduce
1. Look at errors...

### Environment (complete as necessary)
- Version/Git revision:  Today
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version: 7.3

### Additional information/references
image

### PR DESCRIPTION
**Pull request by dragomano**
More one variant of the Error log. Without tables. With the code area.

Fixes #6071

Default view:
errorlog_new_view

Mobile view:
mobile_view

Signed-off-by: Bugo <bugo@dragomano.ru>

### CODE REVIEW

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]
I like that! Two requests: 
1. Change the “Code” label to “Error message” in the code block‘s header.
2. Move the last two lines (URL and file line number) into the entry header area. Conceptually, the URL should be grouped with the info about the user that triggered the error, and the file line number with the backtrace link.

**Comment by dragomano** [comment]
Done
new_view

**Review by MissAllSunday — APPROVED** [review]

**Review by Sesquipedalian — APPROVED** [review]

**Comment by MissAllSunday** [comment]
@dragomano I'm unable to fork the repo to resolve the conflicts, can you re add the PR or resolve the conflicts yourself so we can merge this please.

**Comment by dragomano** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/6303

**Pull request closed without merging**
