### PR TITLE
Enhance registration integration hooks

### PR DESCRIPTION
**Pull request by grangeway**
The existing hook integrate_register is described as being able to do further validation [http://wiki.simplemachines.org/smf/Integration_hooks#integrate_register]

However, it can not return errors to the user in the same way the registerMember function does ~20 lines above.

This patch is a modified version of the patch run locally that allows an integration hook to return an array of error messages to return to the user.

Secondly, this patch adds a post registration hook, that can be used to store the SMF member ID in a seperate system before the actual account is activated [i.e. integrate_activate is called]

This for example allows for the registration template to be customised to ask the user for custom information, and store that information for later review during the admin approval/activation process.

### CODE REVIEW

**Comment by live627** [comment]
Looks a lot better.

@emanuele45 I would like your comments on returning hook errors instead of passing $reg_errors as a second param.

**Comment by emanuele45** [comment]
Thanks for the contribution grangeway.

Looks good, there is already at least integrate_validate_login that does basically the same.

I'm really sorry to bother you grangeway, but there is just a small "bureaucratic" matter: the commit is not [signed-off](https://github.com/SimpleMachines/SMF2.1#how-to-contribute). I know, we should document that a bit better...sorry for all the complications.

**Comment by grangeway** [comment]
Well... I think I might have just messed this up ;/

The above shows just 1 commit with the correct information, however I believe I've reset the status of my local branch - did a forced commit to try and override the original -> so between the web interface above and the local git checkout i've got [which is now confused], I'm not 100% sure if it's safe to pull... Or i'll delete my fork and create a brand new change request...

**Comment by live627** [comment]
I see the commit in this PR is now signed off. So you did it right. :)

**Comment by emanuele45** [comment]
I think this one could go directly into 2.1...

If there are no objections I'll merge it into the other branch.

**Comment by emanuele45** [comment]
As noticed by Arantor this won't work because when there is an hook, call_integration_hook returns always a non-empty array.
loadUserSettings has an example of how to deal with such situation.

**Comment by live627** [comment]
So then should it be

call_integration_hook('integrate_register_validate', array(&$regOptions, &$reg_errors));

**Comment by Oldiesmann** [comment]
Also note that this PR is to put it in the development branch, which is not being used at the moment (though I have no idea why). If we want to get this in, it needs to go to the release-2.1 branch instead.

**Pull request closed without merging**
