### PR TITLE
Cleanup spacing / spelling / etc

### PR DESCRIPTION
**Pull request by Spuds**
Spaces, line endings, spelling, extra files, comments, etc 
All the pedantic things that keep us awake at night
Many files

### CODE REVIEW

**Comment by Fustrate** [comment]
If this is a cleaup pull request, why does it include everything to do with drafts and stuff like that?

**Comment by emanuele45** [comment]
Because I think he did what I did (and still do) several times:
- branch master
- do the feature => pull request
- merge the feature in master (or branch from the branch)
- do other things on master => pull request

I'm trying to pay more attention (i.e. keep master in-line with the current SM repo, branch always from master and send PRs), but still there are few PRs from be not exactly "clean"...

**Comment by Spuds** [comment]
what ema said, ... at least each thing is a separate commit, so in theory you could cherry pick what you want

**Comment by Fustrate** [comment]
We need to make sure pull requests only include the relevant commits in the future :)

**Pull request merged**
