### PR TITLE
! backport some SCeditor 1.4 fixes to 1.3.7

### PR DESCRIPTION
**Pull request by Spuds**
! Fix bug when pasting from Word
! Fixed bug causing scrollbar to change when inserting BBCode in source mode
! Fixed bug causing cursor position to be lost in FF when getting the editors value

Signed-off-by: Spuds spuds@simplemachines.org

### CODE REVIEW

**Comment by norv** [comment]
Thank you! By the looks of it, there may be some work at every update.

**Comment by Spuds** [comment]
Most likely yes ... Updates/fixes are only going in to the new 1.4 branch with is still under development.   Depending on when that goes final we can discuss if its right update 2.1 to the latest level or leave things alone.   Right now I'm thinking of waiting until the 1.4.1 branch is out which is supposed to provide a way to add events to the editor ... now what we have to do for this is ... well kind of ugly.

**Comment by emanuele45** [comment]
> now what we have to do for this is ... well kind of ugly.

Nothing new, I coded it! :P

**Comment by Spuds** [comment]
> Nothing new, I coded it! :P

Nah, that one is really the editors issue ... having to dig down to find the iframe which misbehaves anyway, is the ugly part ;)  Good enough for now, but when the editor itself supports event notifications things will be better (I hope)

**Pull request merged**
