### PR TITLE
Updates version to Beta 4

### PR DESCRIPTION
**Pull request by Sesquipedalian**
This may in fact become RC1, but we won't label it as such until it is ready to release.

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Nothing really to see, @colinschoen. Just want to make sure you sign off before it is merged.

**Comment by XinYenFon** [comment]
IMO, you guys should not be labeling versions which never gonna see a daylight. This probably create confusion in community and lead questions related "where is beta4", "what happened to beta4" etc...

**Comment by Sesquipedalian** [comment]
It hasn't been decided yet whether it will be a release candidate, but we need to update it to something higher than Beta 3 to avoid confusion in the meantime.

**Comment by XinYenFon** [comment]
I think its best to keep it as beta3 or Nightly, in an ideal development process version in the headers should be either Nightly-<latest_commit_number> or just Nightly. Versioning should be changed upon the release candidate (to avoid confusion I'm not meaning RC of final product) commit of that version.

IMO, its best time to bring the script written by @jdarwood007 into the action so nightly releases may be distinguished and distributed far more easily. With that possible change not only users can find nightly builds easier they also have static data related their nightly build so developers and support members can identify the problems (or solutions).

**Comment by Sesquipedalian** [comment]
If there is a better solution, I am open to it. We probably need to hear more from @jdarwood007 and @colinschoen at this point, since a bump to Beta 4 is what was decided in discussion on the forum.

**Comment by XinYenFon** [comment]
oh I see 😆 sorry some old habits still getting used to not seeing the team boards.

**Comment by Sesquipedalian** [comment]
Can you still not see the Development Contributors board? That's where we talked about this one.

**Comment by XinYenFon** [comment]
Nope.

**Comment by colinschoen** [comment]
Working on fixing that still.

**Comment by albertlast** [comment]
ther is now new feature planed, i see no reason to call this a beta.

**Comment by Sesquipedalian** [comment]
Saying that there are no new features *planned* is not the same as saying that we are declaring that no new features will be *accepted*, so I am not certain that we are officially in RC stage at this point.

**Comment by Sesquipedalian** [comment]
Also, I would suggest that even when we declare that we are officially in the RC stage, we allow minor additions like new integration hooks to be added right up until we officially release RC 1.

**Comment by albertlast** [comment]
Sure that are not features in my eyes so ther is no limitation on extension like this.

**Comment by Sesquipedalian** [comment]
BTW @jdarwood007 and/or @live627: It looks like Travis is broken again. :(

**Review by colinschoen — APPROVED** [review]
LGTM

**Comment by colinschoen** [comment]
@Antes You should have access to that board now.

**Pull request merged**
