### PR TITLE
Update smileys

### LINKED ISSUE #2985: Update smileys, maybe implement Unicode standart?
All of our 4 smiley sets are dated back to SMF 2.0 years. They look pretty old. What about updating them?

Maybe implement Unicode standart?

### PR DESCRIPTION
**Pull request by Gwenwyfar**
The two sets that were removed will be going into smiley packages at the mod site. The upgrader may need proper updating, and it's also worth taking a close look to see if the installer is running properly.

Here's the changed smileys for the remaining 2 sets, top row is old files, bottom row new files.

smileys
smileys black

Fixes #2985

### CODE REVIEW

**Comment by wintstar** [comment]
No change in Database at Upgrade?

**Comment by Gwenwyfar** [comment]
@Sesquipedalian did you check if the install/upgrade process is running correctly?

**Comment by wintstar** [comment]
Instalition is correct , but not Upgrade.

What about updating the smileys in the old posts? Changes made from. gif to. png?

smileys_broken

**Comment by Gwenwyfar** [comment]
Well, like I said in the PR, it may need updating... I don't know how the upgrader works and I decided not to meddle with it until it was discussed.

**Comment by Sesquipedalian** [comment]
Dang, I forgot to test the upgrader.

**Comment by albertlast** [comment]
No panic the fix you find in the pr #4532

**Pull request merged**
