### PR TITLE
Fixed missing JS files and added PM purge button

### LINKED ISSUE #1587: Saving PM as draft makes it impossible to send
After saving a PM as draft, TO place no longer recommending or adding someone and removes already added people/person.

pm-error-draft

### PR DESCRIPTION
**Pull request by Ant59**
Fixes #1587 due to missing JS imports

### CODE REVIEW

**Comment by XinYenFon** [comment]
you forgot to sign-off your commit :P

**Comment by Ant59** [comment]
Sorry! I'm still a Git noob :(

**Comment by Ant59** [comment]
That last commit fixes #1589, but I don't know how to make it a separate pull request?

(I worked out how to sign-off that one)

**Comment by Oldiesmann** [comment]
You committed it to the same branch as the first commit, which is why it got added to this PR. The only way at this point to make it separate is to revert the previous commit then either re-branch and commit it to a separate branch, or wait until this PR is merged in and commit it again.

**Comment by Ant59** [comment]
Ah okay, thanks Oldiesmann. So I create a new branch for every PR I want to create?

**Comment by Oldiesmann** [comment]
Either that or only work on one thing at a time and wait for each PR to be merged before starting on something else.

**Comment by Oldiesmann** [comment]
Since this has two unrelated commits attached to it and neither commit is signed off, I'm going to close this one. Feel free to re-submit each as two separate PRs with signed-off commits and we can merge them in :smile:

**Pull request closed without merging**
