### PR TITLE
Fix login times not being kept on failed logins

### PR DESCRIPTION
**Pull request by jdarwood007**

### CODE REVIEW

**Review by colinschoen — APPROVED** [review]
LGTM

**Comment by illori** [comment]
i dont see that these commits were signed off on.

**Comment by XinYenFon** [comment]
There is an issue from @jdarwood007 's side either forgot to use proper GPG key on repo or didn't upload his GPG key to GH yet.

**Comment by jdarwood007** [comment]
They are signed with GPG.  Even though the key didn't get a proper verification till now it was signed.

**Pull request merged**
