### PR TITLE
Select box sizes should not be an array

### PR DESCRIPTION
**Pull request by live627**
This error manifests itself in the page for the cache settings

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
It looks like this has the positions of `$config_var[4]` and `0` in the ternary backwards.

**Comment by live627** [comment]
In ManageServer, find

		array('cache_accelerator', $txt['cache_accelerator'], 'file', 'select', $detected),

and replace with

		array('cache_accelerator', $txt['cache_accelerator'], 'file', 'select', 44,

**Comment by Sesquipedalian** [comment]
Never mind. I missed the `!` when I was looking at this before. :)

**Comment by live627** [comment]
cheers

**Pull request merged**
