### PR TITLE
Theme adjustments (revised #5461)

### PR DESCRIPTION
**Pull request by SychO9**
See #5461 

This PR
* Fixes some minor issues
* Adjusts some of the CSS

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Please merge the release-2.1 branch into this PR. That should fix the error that is currently causing causing the Travis checks to fail.

**Comment by SychO9** [comment]
done

**Comment by live627** [comment]
@SychO9 is this ready to go? I'm ready to merge this.

**Comment by SychO9** [comment]
*inserts "always has been" meme*

Yes.

**Comment by DiegoAndresCortes** [comment]
Happy birthday? 😄

**Pull request merged**
