### PR TITLE
Bunch of stuff.

### PR DESCRIPTION
**Pull request by matthew-kerle**
This is basically a redo of my "Massive commit" that I submitted a couple of months ago. I went through and fixed the issues that still existed in this branch and updated a couple that could have been done better than I did them in my previous PR.

### CODE REVIEW

**Comment by emanuele45** [comment]
You still haven't signed-off any of the commits.

**Comment by matthew-kerle** [comment]
I sent you a message about the sign-off's on Google.

**Comment by emanuele45** [comment]
Since my previous comment was out of context and it was prone to misinterpretations, I've replaced it with this one that should be more clear.

Everything can forget a sing-off, it's not a drama. I did it me too.

Kindred said it is fine because you signed a CLA.
Fine. I signed one me too.
Though I'm convinced that have different standards is the way to make legal (and technical) messes arise: if a standard is defined (i.e. all the commit must be signed-off) for everybody we should stick to that standard.

**Comment by mikemill** [comment]
> Kindred said it is fine because you signed a CLA.

Just a note: Kindred doesn't have standing to make that call.  The board decided in June to stop using the CLA for new submissions.  As such all new submissions need to follow the DCO.

**Comment by mikemill** [comment]
Here is a quick and easy way that I use to do sign-offs:  Navigate to the repository and run this command `git config alias.ci "commit -s"` then whenever you do a commit use `git ci` instead of `git commit`.  And now it is signed.

If you mainly work on repos that require sign-off you can use `git config --global` so it'll be available on all repos.

**Pull request closed without merging**
