### PR TITLE
Revert "! Stats could be interestingly incorrect."

### PR DESCRIPTION
**Pull request by live627**
Reverts SimpleMachines/SMF2.1#1329

Looks like this old commit made the topic count wrong. Please test.

### CODE REVIEW

**Comment by live627** [comment]
Correction:   Still off by one, but at least now I don't get any fake unapproved topic notices.

Also, the code is ugly as hell.

**Comment by margarett** [comment]
Indeed :tongue: 
I would much prefer to have that section rewritten...

I'll test your branch shortly ;-)

**Comment by FearThe1337** [comment]
Just wondering, is there a reason the branch still exists in the SMF2.1 github? :)
Was already wondering why there was a random branch suddenly in the main repo, before I ever saw this PR.

https://github.com/SimpleMachines/SMF2.1/tree/revert-1329-release-2.1

**Comment by live627** [comment]
Ugh, I hate GHs's embedded tools.

**Pull request closed without merging**
