### PR TITLE
PHP 7.4 Deprecations

### LINKED ISSUE #5888: Tons of errors with PHP 7.4
#### Description
Getting spammed daily with errors regarding deprecated functions.

### Steps to reproduce
1. Use PHP 7.4
2. Use SMF

### Environment (complete as necessary)
- Version/Git revision: 0009c2d
- Database Type: mysql
- Database Version: 5.7.28
- PHP Version: 7.4

### Additional information/references

### PR DESCRIPTION
**Pull request by jdarwood007**
This will need some testing because it changes a lot of curly braces usage.

This will fix #5888 when merged

### CODE REVIEW

**Comment by jdarwood007** [comment]
SMF 2.0 has a lot of these as well.
Also I used this to locate and replace the curly braces:
Search: \$([A-Za-z0-9_]+){\$([A-Za-z0-9]+)}
Replace: $\1[$\2]

Also searched for and found a few more: \$([A-Za-z0-9_]+){

**Comment by ghost** [comment]
Another thing :

```
Trying to access array offset on value of type bool

/Sources/Subs-Attachments.php (Line 516)
```

**Comment by ghost** [comment]
if (isset($context['valid_image_types'][$size[2]]))

No idea how to re-rewrite it in a PHP 7.4 compatible way.

Also I'm running this PR on my forum.

**Comment by jdarwood007** [comment]
I won't have time till the weekend to look at that but where is that?  Thats valid code and not deprecated.

**Comment by ghost** [comment]
> I won't have time till the weekend to look at that but where is that? Thats valid code and not deprecated.

/Sources/Subs-Attachments.php (Line 516)

With the following PHP error generated : 

`Trying to access array offset on value of type bool`

**Comment by Loggan08** [comment]
Running this PR + https://github.com/SimpleMachines/SMF2.1/pull/5891/commits/6932c67fefbdb204bdb97172ff343321524e09ba

on my forum now, will see if anything pops up.

**Comment by ghost** [comment]
One more :

/Sources/ManageErrors.php (Line 168)
Trying to access array offset on value of type null

**Comment by jdarwood007** [comment]
This was already fixed in another PR.  Update your stuff.

As well merge this PR into your code if your testing PHP 7.4.  It should be compatible.

**Comment by ghost** [comment]
main branch + this, is that what was required ?

Done anyway, only seeing approve_query message now. (php error)

**Comment by Sesquipedalian** [comment]
Is this ready to merge, @jdarwood007?

**Comment by albertlast** [comment]
For porpuse of testing would be this pr very important,
got many depraction "notice".

**Comment by albertlast** [comment]
Run this command
```
forfiles /s /p F:\github\SMF2.1\ /m *.php /c "cmd /c D:\Programme\wamp64\bin\php\php7.4.1\php.exe -l @file" > 7.4.check.txt
```
result is that no syntax error was found.

When i do vs the main i found many depracted notice

**Comment by jdarwood007** [comment]
@Sesquipedalian It is other than the possible issue reported by the deleted account.  I haven't verified it.  But this could merge knowing that and give us time to test it more.

**Comment by mobasuite** [comment]
Yo, It's me, I'm in sync with main branch + this.

No issues (so far)

**Comment by mobasuite** [comment]
Type of error: Undefined
8: Undefined variable: approve_query https://mobasuite.com/forum/index.php?action=search2
/home/lolupdat/public_html/forum/Sources/Search.php (Line 1715)

**Comment by albertlast** [comment]
this was not touched by this pr

**Comment by mobasuite** [comment]
@albertlast 

True, just notifying.

**Comment by MissAllSunday** [comment]
Will go ahead and merge, we still have time to do more testing

**Pull request merged**
