### PR TITLE
Ports some error handling improvements from 2.0.16

### PR DESCRIPTION
**Pull request by Sesquipedalian**
This is part of porting over some recent changes in 2.0.x to 2.1.

### CODE REVIEW

**Comment by live627** [comment]
You sure hiding deprecation warnings  is a good idea?

**Comment by Sesquipedalian** [comment]
In production, yeah.

**Comment by Sesquipedalian** [comment]
I updated the logic in order to more intelligently choose whether to report deprecation notices. In SSI.php and index.php, deprecation notices are reported if $db_show_debug is true. In install.php, they are shown for pre-release versions of SMF but not release versions. In upgrade.php, they are shown if $db_show_debug is true or if SMF is a pre-release version. Does that look good to you, @live627?

**Comment by live627** [comment]
Yes. That's quite neat, actually. Andi I now know of another PHP function.

**Pull request merged**
