### PR TITLE
Calls to mysqli_insert_id require the connection, not the result set.

### PR DESCRIPTION
**Pull request by gizmo71**

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
@albertlast

**Review by albertlast — APPROVED** [review]

**Comment by jdarwood007** [comment]
The $rs variable is named badly but it should contain the resource identifier.  If none is specified it falls back to the db_connection.

**Comment by albertlast** [comment]
When you look,
the method is used only in upgrade script 1.1 and 2.0.
And on both places without var,
sooo i think we only clean up.

**Comment by jdarwood007** [comment]
Then it would be ok I guess,  Going off the php docs for mysql_insert_id is what tells me what should be there.

**Pull request merged**
