### PR TITLE
Improvements on mobile

### LINKED ISSUE #3903: Scroll don't work on small screens
```
@media (max-width: 480px) {
	/* Stay where you are in mobile popup enabled */
	body {
		overflow: hidden;
	}
```
Why scroll disabled here? Forum unusable on small screens.

### PR DESCRIPTION
**Pull request by XinYenFon**
fixes #3903 
closes #3923

### CODE REVIEW

**Comment by XinYenFon** [comment]
@jdarwood007 seems Travis fails on GPG Sign-off's as well 😆

**Comment by jdarwood007** [comment]
I haven't tested GPG signed stuff, But I was looking into using GPG myself.
Seems my debugger code is faulty and didn't capture the secondary message so I don't know why its still failing.

**Comment by Oldiesmann** [comment]
Looks like it's failing because there's no "signed-off-by" line in the commit when you use GPG signing. There is a `verify-commit` flag for git, but I don't know if we can have Travis run `git verify-commit` for us.

**Comment by jdarwood007** [comment]
Travis runs a git clone command, so it should be easily done to run a git verify-commit.  It needs the actual commit though which is what is currently failing here I think.  The commit has parents (from the merges) which contain the sign off message.  So I think I need to rebuild the code to find all parents and verify if any of them have signed off.

**Pull request merged**
