### PR TITLE
Delete alerts

### PR DESCRIPTION
**Pull request by MissAllSunday**
Adds some new functions to showalerts page:
- Delete and mark as un/read buttons for every alert.
- Mass delete or un/read alerts
- Pagination

Also adds some generic functions on Profile-Modify.php

### CODE REVIEW

**Comment by Dragooon** [comment]
Does this fix the issues Bigguy's been having?

**Comment by smfbigguy** [comment]
I have not tried this yet but will be doing an update of my site in the next couple days. So we will see by then. I hope it does.

**Comment by MissAllSunday** [comment]
Nope, not really, it just adds a way to delete alerts.

**Comment by Oldiesmann** [comment]
Is this good to go now?

**Comment by MissAllSunday** [comment]
yes

**Pull request merged**
