### PR TITLE
Add some more hooks

### PR DESCRIPTION
**Pull request by jdarwood007**
Some additional hooks and changes to hooks to make more use of the hooks system.

### CODE REVIEW

**Review by MissAllSunday — APPROVED** [review]

**Comment by SychO9** [comment]
I was gonna say about those hooks after looking into the AntiSpamLinks mod, we might need more from what I've seen

**Comment by jdarwood007** [comment]
@SychO9 Yea these are all from converting the Anti-Spam Links mod.

This part of SMF code is not very friendly to work with.  But I've come up with something that seems to work.

**Comment by SychO9** [comment]
nice, let me know how it goes and if you need help with it

**Comment by jdarwood007** [comment]
I've sent you info with the link to the code.  Try it out.
I may add more to this for some other mods, but it can be pulled at any time.  Will do more PRs if needed.

**Pull request merged**
