### PR TITLE
No remote bot attack  - Empty array shouldn't allow access, Test with un...

### PR DESCRIPTION
**Pull request by butchs**
...set($user_info) prior to change.

### CODE REVIEW

**Comment by mikemill** [comment]
Per the readme file PR aren't be accepted into the master branch.  Please use the release-2.1 branch

**Comment by butchs** [comment]
Thanks for the KISS.  I was trying to help. If I do not find the link to what you are talking about the fix will only be at my site.

**Comment by emanuele45** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/new/SimpleMachines:master...butchs:patch-1

And change it to release-2.1

You cannot expect to have simple things when potentially many people are involved.
To contribute there are just very few rules:
1) sign-off commits,
2) send the pull request to the proper branch
I don't think it's _so_ complex. ;)

**Comment by butchs** [comment]
Good grief.  I tried what you say.  Not sure how to sign off on comments. Maybe I did anyways...  ;)

**Comment by eurich** [comment]
a sign-off needs the -s parameter.
git commit -s ...

**Comment by emanuele45** [comment]
Duplicate of #193

**Pull request closed without merging**
