### PR TITLE
Don't notify the message poster if they did a thing on their own post

### LINKED ISSUE #5858: When I myself move or sticky a topic, I get notified (alert + mail)
#### Description
For details on my notification settings, please see the [original report here](https://www.simplemachines.org/community/index.php?topic=569575.0).

### Steps to reproduce
1. Move or sticky a topic
2. Receive alert and notification email

### Environment (complete as necessary)
- Version/Git revision: GH version from ~2019-10-10
- Database Type: Postgres but probably any
- Database Version: 9.6ish
- PHP Version: 5.6ish

### PR DESCRIPTION
**Pull request by live627**
Affected actions:
- move
- sticky
- unsticky
- lock
- unlock
- remove
- mention (I think)

Fixes #5858

### CODE REVIEW

**Comment by SychO9** [comment]
This doesn't fix it for mentions though, because before the query is executed the `$posterOptions['id']` value is already in the `$members` array from line 73

**Review by Sesquipedalian — APPROVED** [review]

**Comment by Sesquipedalian** [comment]
Merged this for now. Care to tackle mentions (and quotes) in another PR, @live627?

**Comment by live627** [comment]
Sure. Will do it in a few days.

**Comment by Sesquipedalian** [comment]
Thanks!

**Pull request merged**
