### PR TITLE
Fix installer from escaping quotes in DB password. Fixes issue #2896

### PR DESCRIPTION
**Pull request by colinschoen**

### CODE REVIEW

**Comment by XinYenFon** [comment]
You forgot to sign-off :(

**Comment by colinschoen** [comment]
Whoops, thanks @Antes. Commit updated.

**Comment by Oldiesmann** [comment]
Unfortunately there's now a merge conflict after I merged in other installer-related fixes.

**Comment by colinschoen** [comment]
I'll look into it.

**Comment by live627** [comment]
@colinschoen   I'll merge this as soon as you can fix the conflict.

**Comment by colinschoen** [comment]
Alright merge conflicts should now be fixed. @live627

**Pull request merged**
