### PR TITLE
Removed Template Eval

### PR DESCRIPTION
**Pull request by albertlast**
Could fix issue: #4677 
but eaven it not fix this.
The whole eval stuff is slow, error mesage are garbage and debugging sucks -> see no reason to keep this.

btw. The helptext is wrong (direct opposite is the right case).

### CODE REVIEW

**Comment by albertlast** [comment]
@Arantor antes mention that you got reason why eval is ther.

**Comment by albertlast** [comment]
The response from the issue #4677 shows that eval create a fog around the real issue.
When the eval keep in, the support team of sm.org get a hard time when some one got a issue,
where eval is included.

**Comment by Arantor** [comment]
The reason for template eval is that if a template has a fatal error at the parse stage, it can be caught and a usable error can be shown to users.

I know that people have trouble with template eval, though honestly for someone competent, it's at worst a few minutes extra detective work. The line number is guaranteed correct by the Zend engine, but the file will be wrong... though it's hardly a difficult process to identify which file it will be in almost every case.

**Comment by albertlast** [comment]
For caught error we don't need eval,
we already did this on other places where such behavior is needed,
that we change temp the error handler of php/smf in a more strict one.
exp. https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Post.php#L628

> Parse error: in /home/bae/app/Sources/Load.php(3055) : eval()'d code on line 51

doesn't help any one.

**Comment by Arantor** [comment]
The idea is to cope if index.template.php has a syntax error. Back in 2003 it seemed like a good idea. But it's your call if you want to remove it, don't drag me into it.

**Comment by Sesquipedalian** [comment]
Given what the PHP manual page for eval() says, I'm inclined to agree with @albertlast on this. In 2003 it probably was a good idea. I'm not sure that it still is helpful in 2018.

**Review by Sesquipedalian — APPROVED** [review]

**Comment by Sesquipedalian** [comment]
Any thoughts to share, @colinschoen? If not, I'm inclined to merge this.

**Comment by Sesquipedalian** [comment]
Comments from @MissAllSunday would also be welcome. :)

**Review by colinschoen — APPROVED** [review]
LGTM

Times have changed.

**Pull request merged**
