### PR TITLE
Menu shenanigans

### PR DESCRIPTION
**Pull request by live627**
- Profile alerts should not use warning_moderate (although same icon is used)
- Allow regular images in teh main menu ($settings['theme_dir'] . '/images/' . $button['icon'])

### CODE REVIEW

**Comment by XinYenFon** [comment]
Changes on Subs-Menu actually breaks things on admin home.

`<span class="large_support"></span>`

**Comment by XinYenFon** [comment]
Main menu cannot get the direct image.

``

**Comment by live627** [comment]
Fixed

**Comment by XinYenFon** [comment]
seems not to me ?

**Comment by XinYenFon** [comment]
uhm @live627 this breaks the admin_large_icons on Admin Center
and main menu cannot get the icon from main images folder.

**Pull request merged**
