### PR TITLE
fix the rest of #2318 editing/deleting comments in reports

### PR DESCRIPTION
**Pull request by illori**
Signed-off-by: Illori illori@simplemachines.org

### CODE REVIEW

**Comment by NanoSector** [comment]
Confirmed working.

**Comment by Oldiesmann** [comment]
The problem is this now also makes it such that anyone with moderate_forum can edit comments made by other users. While the moderate_forum permission isn't a light one, I'm not entirely sure we should do this. If we do want to do it that way, then we don't need to check admin_forum because anyone who has admin_forum will also have moderate_forum.

**Comment by illori** [comment]
It had half of that already. I just made it work.

**Comment by illori** [comment]
we already had 

```
'can_edit' => allowedTo('admin_forum') || (($user_info['id'] == $row['id_member']) && allowedTo('moderate_forum')),
```

which allowed users with moderate_forum to see the buttons but they did nothing as the rest did not allow it. do we want to allow it or not? i dont see it as a major issue either way.

**Comment by Oldiesmann** [comment]
The existing code limited users to editing their own comments if they had moderate_forum. Your change makes it so that they can edit ANY user's comments with the moderate_forum permission.

**Comment by NanoSector** [comment]
It doesn't show the edit button for someone else's comments.

**Comment by illori** [comment]
Yes it does show for anyone with that permission. I did not pick that one
to be used if you really don't like it we can change it but I don't think
it needs to be.

**Pull request merged**
