### PR TITLE
make lngfile shorter so as not to exceed max index bytesize limit

### LINKED ISSUE #6163: quanda table lngfile key too long
#### Description
for MySQL in utf8mb4, the lngfile column is set to 255 which causes issues on saving due to the way utf8mb4 requires more storage than utf8 or latin
### Steps to reproduce
1. use a MySQL utf8mb4 db
2. use the quanda feature

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: MySQL
- Database Version: > 5.7 
- PHP Version:

### Additional information/references

Not every install can use inno to enable innodb_large_prefix so the only feasible solution is to limit the lngfile column to 250 length

Ref: https://www.simplemachines.org/community/index.php?topic=573832.msg4061249#msg4061249

### PR DESCRIPTION
**Pull request by live627**
fixes #6163

### CODE REVIEW

**Comment by albertlast** [comment]
why 30?

**Comment by MissAllSunday** [comment]
I would leave it a 249, it doesn't hurt the index and we never know if sometime in the future we need to actually use a ridiculous long filename

**Review by Sesquipedalian — CHANGES_REQUESTED** [review]
> I would leave it a 249, it doesn't hurt the index and we never know if sometime in the future we need to actually use a ridiculous long filename

**Comment by live627** [comment]
Now it matches the members table.

**Comment by MissAllSunday** [comment]
If we are going to pair both quanda and members table lngfile column I would set it up higher than 30, the index on both tables isn't involved in any complex queries and it will still fix the main issues reported.

**Pull request closed without merging**
