### PR TITLE
Uses $context['posting_fields'] for all fields in post form header

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Benefits:

1. The logic for setting up these fields is handled in source rather than in the theme
2. It is easier to ensure uniform formatting for all fields
3. Mods can add custom fields above, below, or between standard fields using nothing but the 'integrate_post_end' hook
4. Every dt/dd pair in the list is automatically assigned a unique `pf_*` CSS class

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
How does this look to you, @Antes?

**Comment by XinYenFon** [comment]
Well, putting those DL/DD/DT in source not a huge deal but putting img/icons to source will limit the theme authors especially the people who is using font icons in their themes.

**Comment by Sesquipedalian** [comment]
> but putting img/icons to source will limit the theme authors especially the people who is using font icons in their themes.

How so? They can edit the icons using the `integrate_load_message_icons` hook, just as before. Or if that isn't enough, they can completely rebuild `$context['posting_fields']['icon']` to be whatever they want using the `integrate_post_end` hook.

**Comment by XinYenFon** [comment]
Do they require extra modification to integrate the hooks? If your answer is yes then my answer is no.

**Comment by Sesquipedalian** [comment]
No, no extra mods besides the theme itself would be necessary. For example, if a theme author didn't want to use the standard message icon select menu contained in `$context['posting_fields']['icons']['dd']`, she could either (a) include a hooked function in the theme's files to replace it with whatever she wanted, or (b) just process the content of `$context['posting_fields']['icons']` however she liked directly in her Post.template.php. Everything is just in $context, after all. Since themes can define and use hooks just like any other mod, all the necessary code can be included in the theme package regardless of which of these methods a theme author might prefer.

**Comment by Sesquipedalian** [comment]
Clearer explanation:

If a theme author wants to do things the old way, they are completely able to do that. This PR doesn't take anything away. It just adds more info to $context. If a theme wants to ignore it, change it, or use it, is entirely up to the theme author. If the theme author wants to change it, she can either include a hooked function in her theme's files to do so, or she can do it directly in her theme's custom version of Post.template.php. In short, this PR is just giving more options and flexibility; it doesn't take anything away.

**Comment by XinYenFon** [comment]
Fine enough for me, but surely requires some documentation.

**Comment by Sesquipedalian** [comment]
Documentation added.

**Pull request merged**
