### PR TITLE
Minor stuff reported posts

### LINKED ISSUE #1248: No way to edit/delete moderator comments
If you comment on a report, there's no way to edit your own comments, and no way to delete them either.

I'm thinking normal moderators should be able to edit/delete their own comments (only), while admins should be able to edit/delete any comments. Very reluctant to add permissions to this more than necessary and more than own/any in this fashion seems overkill.

### PR DESCRIPTION
**Pull request by MissAllSunday**
Sooooooo this took longer than I expected but here it is. This PR adds some new functionalities to the reported posts page:
- Separates the whole page from Sources/ModerationCenter.php file.
- Adds the ability to delete/edit moderator comments, only admins and the comment author can edit/delete a comment this fixes #1248
- Adds some html improvements on how moderator comments are displayed.
- Separates queries into a Subs-ReportedPosts.php file
- Adds tokens for all CRUD actions.
- Replaces a couple of onClick actions with jQuery on.() method.
- Adds a confirmation message for all moderator comments and report CRUD actions.
- Uses {literal} where applicable.
- Some other minor stuff.

I also added some new txt strings so the usual check must be done. I tested as much as I could but chances are I'm still missing something.

### CODE REVIEW

**Comment by Xarcell** [comment]
@MissAllSunday Thanks.

**Comment by XinYenFon** [comment]
One thing i noticed "recent topic reports" are missing ^^

**Comment by MissAllSunday** [comment]
I'll take a look.

**Comment by Oldiesmann** [comment]
Also note that because of Antes' CSS fix there's now a merge conflict here due to changes in ModerationCenter.template.php.

**Comment by XinYenFon** [comment]
Can't see the result, is the conflict resolved? @MissAllSunday

**Comment by MissAllSunday** [comment]
It appears so, yes.

**Comment by XinYenFon** [comment]
Awesome :paw_prints:

**Comment by Oldiesmann** [comment]
Unfortunately I didn't think to pull this in before making changes to allow you to report member profiles, so we're now at merge conflicts again. At this point it would probably be best to re-do all the changes based on the current code (and apply similar changes to the "report member" stuff as needed). I made a lot of changes, so I'm not sure how much I broke, and the reported profiles code is similar to reported posts in most areas (I basically copied reported posts and modified it for reported profiles). I do apologize for breaking such a huge PR though. If I had thought about it I would have pulled this in before I started on my changes.

**Comment by MissAllSunday** [comment]
There wasn't any major changes, the only issues I found where the SendTopic.template file been deleted and git telling me it needed to be merged and the stuff on ModerationCenter and of course usual annoyance of dealing with the command line :tongue: 

I didn't test it, just fixed the merge conflicts.

**Comment by MissAllSunday** [comment]
Since I didn't test it, I'm starting to think there is more stuff to do than just fixing the merge conflicts but those can be solved way easier on a separate branch once this gets merged in.

**Comment by Oldiesmann** [comment]
SendTopic.template.php was actually renamed to ReportToMod.template.php, except I just renamed it in Windows thinking Git would pick it up. For SendTopic.php, I renamed it through TortoiseGit. There are probably other changes, but I'll go ahead and pull this in and we can figure out the rest later :smile:

**Pull request merged**
