### PR TITLE
Add Cloudflare IP Support to the auto detection

### PR DESCRIPTION
**Pull request by albertlast**
I like the idea from https://www.simplemachines.org/community/index.php?topic=532453.0
feel free to decide if this is right or not.

### CODE REVIEW

**Comment by tinoest** [comment]
Would it not make more sense to have a integration hook for any potential future change then a mod for the custom implementations others use?

**Comment by albertlast** [comment]
query string is called very early,
to add here hooks is dangerous.

And cloudflare by his own is very big,
so it's the most common one here.

**Comment by jdarwood007** [comment]
Check a bit further down in the code, we have support for proxy headers there.

**Comment by VBGAMER45** [comment]
I think this is a great idea. People will use that service often. And it is great to have support out of the box.

**Comment by Kindred-999** [comment]
According to Arantor, 2.1 already HAS this capability with a switch in the admin/security section

**Comment by albertlast** [comment]
but it miss on the auto detection.

**Comment by vort7u** [comment]
Has anyone tested this commit?
With SMF RC4 all messages have the ip address of Cloudflare.

**Comment by Sesquipedalian** [comment]
> With SMF RC4 all messages have the ip address of Cloudflare.

Please open a new issue for this. Comments on closed issues and PRs are easily overlooked.

**Pull request merged**
