### PR TITLE
Removed db_insert_sql

### PR DESCRIPTION
**Pull request by albertlast**
I didn't understand the idea behind the function AND
can't finde any use in the code--> remove

### CODE REVIEW

**Comment by jdarwood007** [comment]
Its actually only used in the tool to convert from sqlite to mysql far as I can tell.  But in that case the function is overridden for a localized version.

**Comment by Oldiesmann** [comment]
It's left over from when you could backup your database from the admin center (in SMF 1.x and early versions of 2.0 - it was ultimately removed because it didn't work very well and there are better options for backing up your database). I guess the code for that was never removed.

**Comment by equinoxmatt** [comment]
If it has no use, I think it is worth removing it.

**Review by colinschoen — APPROVED** [review]
LGTM, approval

**Pull request merged**
