### PR TITLE
Fixes for updateSettingsFile

### LINKED ISSUE #5934: Settings.php blanked out after running upgrade.php
#### Description

after running upgrade.php both Settings.php and Settings_bak.php are blanked out

### Steps to reproduce
1. upgraded to latest code in this repo
2. ran upgrade.php via CLI
3. Settings.php was blanked out as well as Settings_bak.php

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

i dont want went wrong here but the files are empty except for 
?>

### LINKED ISSUE #5938: Installer - infinite loop, can't get past db settings
#### Description
Keep going back to the welcome screen

### Steps to reproduce
1. Install

### Environment (complete as necessary)
- Version/Git revision: Current as of this moment...
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
Getting further than I was earlier!
I've seen this before...  Can't recall where...

### LINKED ISSUE #5939: updateSettingsFile() had a a bruh moment
My code

		$this->configVars = array(
			array('mtitle', 'maintenance_subject', 'file', 'text', 36),
			array('enableCompressedOutput', 'enableCompressedOutput', 'db', 'check', null, 'enableCompressedOutput'),
		);
		$_POST = array(
			'mtitle' => 'value',
			'enableCompressedOutput' => '1'
		);
		$token_check = createToken('admin-ssc');
		$_POST[$token_check['admin-ssc_token_var']] = $token_check['admin-ssc_token'];
		$token_check = createToken('admin-dbsc');
		$_POST[$token_check['admin-dbsc_token_var']] = $token_check['admin-dbsc_token'];
		saveSettings($this->configVars);

Settings.php before

```
<?php
$db_type = 'mysql';
$db_name = 'smf21';
$db_user = 'root';
$db_passwd = '';
$db_server = 'localhost';
$db_prefix = 'smf_';
$db_show_debug=true;
$cookiename = 'SMFCookie574';
$db_port = '3307';
$boardurl = 'http://localhost/SMF2.1';
$boarddir = 'C:\\wamp64\\www\\SMF2.1';
$sourcedir = 'C:\\wamp64\\www\\SMF2.1/Sources';
$cachedir = 'C:\\wamp64\\www\\SMF2.1/cache';
$packagesdir = 'C:\\wamp64\\www\\SMF2.1/Packages';
$tasksdir = 'C:\\wamp64\\www\\SMF2.1/Sources/tasks';
$mbname = 'My Community';
$language = 'english';
$image_proxy_secret = '49933237e8ae60456661';
$image_proxy_enabled = 0;
$db_character_set = 'utf8';
$webmaster_email = 'live627@gmail.com';
$cache_enable = 0;
$cache_accelerator = 'smf';
$cache_memcached = '';
$upgradeData = '';
$image_proxy_maxsize = 5190;
$maintenance = 0;
$mtitle = '';
$mmessage = 'Don\'t worry, we will be back shortly with an updated forum.  It will only be a minute ;).';
$db_error_send = 1;
?>
```

Settings.php after

```
<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC1
 */

########## Database Info ##########
/**
 * The database type
 * Default options: mysql, postgresql
 *
 * @var string
 */
$db_type = 'mysql';
/**
 * Database username
 *
 * @var string
 */
$db_user = 'root';
/**
 * Path to the Sources directory.
 *
 * @var string
 */
$sourcedir = 'C:\\wamp64\\www\\SMF2.1/Sources';
/**
 * Path to the tasks directory.
 *
 * @var string
 */
$tasksdir = 'C:\\wamp64\\www\\SMF2.1/Sources/tasks';
/**
 * Email address to send emails from. (like noreply@yourdomain.com.)
 *
 * @var string
 */
$webmaster_email = 'live627@gmail.com';
820592552b4a7b10cc4cb101ee21cd78

?>
```

Also, if `$cache_memcached = '';` is removed, the function complains about it missing on line 918. I only know this because I had to add it in. To test this further, I removed `$upgradeData = '';` since fresh installs won't have it IIIRC. Same result.

Related to #5934

### LINKED ISSUE #5943: Upgrade broken in new SMF
#### Description
Get main branch set-up
Then apply : https://github.com/SimpleMachines/SMF2.1/pull/5940

Produces two errors :

1. Undefined index: utf8 in /home/lolupdat/public_html/forum/Sources/Subs-Admin.php on line 794

2. Also apparently the UpdateSettingsFile() is messing up the settings.php

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mysql
- Database Version:
- PHP Version: 7.4

### Additional information/references

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #5934
Fixes #5938
Fixes #5939
Partially fixes #5943

Please test this PR on your machines, @live627, @sbulen, @illori, @mobasuite.

EDIT:
Closes #5950
Closes #5951

### CODE REVIEW

**Comment by sbulen** [comment]
**_Installer on WAMP_** - runs to completion and the forum appears to work OK, but settings.php looks a little funky...  (This has been edited a couple times, sorry...)
image

**_Upgrade from 2.0 to 2.1 on WAMP_** - 

_Problem 1:  I am getting lots of undefined index errors, for cache settings.  (These settings are new in 2.1...)  Some examples:_
```
Notice
: Undefined index: cache_accelerator in
D:\EasyPHP\van2021\Sources\Subs-Admin.php
on line
941

Notice
: Undefined index: cache_enable in
D:\EasyPHP\van2021\Sources\Subs-Admin.php
on line
941

Notice
: Undefined index: cache_memcached in
D:\EasyPHP\van2021\Sources\Subs-Admin.php
on line
941

```
_Problem 2:  Infinite loop...  Getting kicked back to the login after entering the upgrade options.  Note $upgradeData is not in Settings.php, I don't think that fix has kicked in._

_Problem 3:  Still lots of weird substitutions:_
image

**Comment by sbulen** [comment]
I haven't yet tested linux or upgrades from 1.x.

**Comment by sbulen** [comment]
Another note from 2.0 to 2.1 upgrade...  Note the comments are pretty different between 2.0.x and 2.1, so, you see a lot of strange stuff like this after the substitutions:
image

**Comment by mobasuite** [comment]
Still truncating the settings.php file, will test one of the other PR's

**Comment by mobasuite** [comment]
Settings.php is still being truncated

**Comment by sbulen** [comment]
@mobasuite - I am not seeing truncation at all.  More info would be helpful.

E.g., - linux or windows?   Browser or cli?  Install or upgrade or simply refreshing files?  What action were you doing?

**Comment by sbulen** [comment]
@Sesquipedalian - to be quite honest...  I don't recommend adding new comments _at all_...

**Comment by mobasuite** [comment]
@sbulen 

upgrade, erased all files from webserver, uploaded new zip (with this PR applied).
Did my Settings.php options (boardname, databasename, password etc)

deleted install.php and its .sql files.

Ran upgrade.php .

`[12-Jan-2020 16:49:52 UTC] PHP Parse error:  syntax error, unexpected 'f10ebb4602d4245ceab27ab003f5b0' (T_STRING) in /home/lolupdat/public_html/forum/Settings.php on line 229



Blanks out after Step 2, also is truncating Settings.php

`

**Review by jdarwood007 — DISMISSED** [review]
My Settings.php does not blank after this.  Even some custom code I have in the Settings.php is retained.

**Comment by jdarwood007** [comment]
Not sure if related to this, but now Settings.php isn't removing the upgradeData.  I could swear it would do that upon hitting the last step, but I don't see the code in there anymore.

**Comment by sbulen** [comment]
@jdarwood007 - What kind of upgrade did you run?  2.1 to 2.1?  

I can't get a 2.0 to 2.1 upgrade to run at all...

**Comment by jdarwood007** [comment]
@sbulen 2.1 to 2.1
Is the Settings file a 2.0 version?

**Comment by sbulen** [comment]
Yes.  Have you tried a 2.0 to 2.1?  Everything I note above is a problem.

(Note - I am going to change my install notes though...)

**Comment by sbulen** [comment]
@mobasuite - I cannot duplicate anything you're seeing.  

I have some questions about your process - 
   What version are you upgrading from?  
   Where did you get the .zip?  Is it the latest github code?
   How did you apply the PR?
   Why did you have to delete install.php?   

The fact that you had to delete install.php really confuses me...

**Comment by mobasuite** [comment]
@sbulen 

install.php has no interest for me.
That's how I've done my upgrades before.

Latest git .zip
applied patch with `git apply 5953.patch`

Upgrading from RC2

**Comment by sbulen** [comment]
> @sbulen
> 
> install.php has no interest for me.
> That's how I've done my upgrades before.
> 
> Latest git .zip
> applied patch with `git apply 5953.patch`
> 
> Upgrading from RC2

Where did you get the zip?

Downloading from gh, install.php isn't in the forum root, it's off in the /other folder & can be left alone, you don't need to delete it.  I don't know of any source of the current GH where install.php is in the forum root...

**Comment by mobasuite** [comment]
@sbulen 

Takes me back to step 1

At 2nd/3d attempt it truncates the Settings.php

I'm on commit https://github.com/SimpleMachines/SMF2.1/commit/29321d4c3d58e57419f52fb6e4e0f826dc3d161d

a
b
c
d
e
f
g

**Comment by jdarwood007** [comment]
Your right, 2.0 to 2.1 is breaking things


( ! ) Notice: Undefined index: cache_accelerator in /Sources/Subs-Admin.php on line 941
( ! ) Notice: Undefined index: cache_accelerator in /Sources/Subs-Admin.php on line 949
( ! ) Notice: Undefined index: cache_accelerator in /Sources/Subs-Admin.php on line 972
( ! ) Notice: Undefined index: cache_accelerator in /Sources/Subs-Admin.php on line 974

Repeat this for cache_enable, cache_memcached, image_proxy_secret, image_proxy_maxsize.  Image Proxy is technically in 2.0 but was added late.

```
			// We don't save objects in Settings.php.
			if (is_object($config_vars[$var]))
```

To
```
			if (!isset($config_vars[$var]))
				$config_vars[$var] = '';
			elseif (is_object($config_vars[$var]))
```


Its stuck in a loop because any missing variables are not being added.

**Comment by sbulen** [comment]
> @sbulen
> 
> Takes me back to step 1
> 
> At 2nd/3d attempt it truncates the Settings.php
> 

Ah, important details.  Yes, I've seen the loop.  I give up after one or two loops thru though, which is probably why I have never seen the file truncation.

**Comment by mobasuite** [comment]
I mean forum is still up, however the ability to upgrade the database-entries are not.

**Comment by Sesquipedalian** [comment]
Well, I guess the best course of action is to revert #5815 and take another run at it. I still want to use `var_export()` instead of manually escaping values and to use the new atomic write method, so I'll put together something to do that.

**Comment by sbulen** [comment]
I feel this is close.  The structure is solid.  I'd suggest a couple simplifications: 
 - no comments
 - simple substitutions only
 - one simple check/substitution for the logic portion.

Then we keep the new lock logic.

**Comment by illori** [comment]
what is the status on this? i see this PR as closed and this problem is still happening.

**Pull request closed without merging**
