### PR TITLE
Delimit id_redirect_topic so upgrade.php doesn't fail. Signed-off-by: Trekkie101 graeme@simplemachines.org

### PR DESCRIPTION
**Pull request by Trekkie101**

### CODE REVIEW

**Comment by norv** [comment]
Cool! Welcome around, Trekkie One. :)

As you saw, using Github even from the web interface is possible and easy. Although, you have then, to sign-off manually (by including the sign-off line).
If you were using an actual Git client, you could do it in the commit itself by an -s switch, or a checkbox, to have it insert your signature.

**Comment by norv** [comment]
Speaking of which. To keep things closer to a standard way of signing-off, you could still do it in the pull request, but then in the body of the request, not the title.

Yet again, the standard way is still to sign-off the commit, each commit. Which isn't a problem from a Git client, but from the web interface it can't be done. Personally, when I happen to commit from the web interface (yep, I'm lazy like that for a small tweak or something), I go back afterwards, in the Git client, and run git --amend -s on the commit. This will amend the commit adding signature to it. Then push it out again. Kinda funny, but it works as expected. ;)

**Comment by norv** [comment]
You could now, even, amend the commit, add signature, and push it out again. The pull request will still be there, and can be added to, modified, etc, for the tweaks needed per the repo guidelines, until it is accepted in.

**Comment by Trekkie101** [comment]
Ill attempt it now?

Ill got find a client to try with :P

**Comment by norv** [comment]
In the stickies in dev boards, I must have linked a topic where people were proposing and discussing Git clients.

**Comment by Trekkie101** [comment]
Got SourceTree for the Mac now, trying to work out how to amend or even change the commit message.

**Comment by norv** [comment]
Mean. /settled

**Comment by Trekkie101** [comment]
Thanks for letting me play along :D

**Comment by norv** [comment]
Hey, look:
https://github.com/Spuds/playpen/blob/master/other/upgrade_2-1_mysql.sql

> > 4 contributors

Now you're an actual contributor to SMF software, Trekkie One, you're doomed. :D
Welcome under my dark rulez!

**Pull request merged**
