### PR TITLE
Tidy the UI structure's css code

### PR DESCRIPTION
**Pull request by SychO9**
@Gwenwyfar check it out when you got time

### CODE REVIEW

**Review by XinYenFon — APPROVED** [review]

**Review by Gwenwyfar — APPROVED** [review]
For whatever this is worth... Looks fine from a glance at the code. No longer have SMF to test on though.

**Comment by pouvik** [comment]
This works fine however for keeping code clean  would it not be better for the existing #footer in responsive.css to become

```
#footer {
		padding: 10px;
		text-align: center;
	}
```

saves space and will do the same thing also stop duplication

**Comment by SychO9** [comment]
no because the #footer you are referring to is not in the same media query block, so not the same scope.

**Comment by pouvik** [comment]
was just a suggestion man thats all :)

**Pull request merged**
