### PR TITLE
Remove all traces of the defunct WAP code

### PR DESCRIPTION
**Pull request by live627**
Because progress!

### CODE REVIEW

**Comment by XinYenFon** [comment]
Something I support but I'm not sure. Opera Mini does not support HTML5/CSS3 yet it offers compressed web-mode which saves dozens of data.

**Comment by live627** [comment]
Turbo mode?

**Comment by Rupurudu** [comment]
Opera mini is used on very low end dumb phones. These devices need several seconds to render pages. On big pages with heavy css and giant images, these devices generally crash.

Opera turbo per-renders pages on opera servers, speeding up the rendering on the phone.

Personally, I'm opting for removing the wap code, since these devices are very rare.

**Comment by live627** [comment]
I was asking for clarification on the mention of Mini's "compressed" mode which sounds like turbo. Anyway, it does not use WAP but magic on their proxy servers.

http://www.opera.com/turbo

**Pull request merged**
