### PR TITLE
Displays the number of posts by reference to the list of posts

### PR DESCRIPTION
**Pull request by Pavel-II**
This simple changes for displays the number of posts by reference to the list of posts

### CODE REVIEW

**Comment by Pavel-II** [comment]
It's again not signed?

**Comment by XinYenFon** [comment]
nope you need to sign-off the commit.

**Comment by Pavel-II** [comment]
and now?

**Comment by XinYenFon** [comment]
nope check this PR. https://github.com/SimpleMachines/SMF2.1/pull/3245

If you are using Windows I suggest using Git-SCM easy to do everything.

**Pull request closed without merging**
