### PR TITLE
Improves performance in normalization polyfills

### LINKED ISSUE #7570: Unicode normalization performance could be improved
The performance of our Unicode normalization functions could be improved by implementing the Unicode ["Quick Check" algorithm](https://www.unicode.org/reports/tr15/#Detecting_Normalization_Forms).

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #7570

Unit test: https://gist.github.com/Sesquipedalian/b0870a303967002adc9db93fc48cd919

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Any chance that this could be merged soon? It's not a big deal, but it would help me keep my local dev environment tidy.

**Comment by jdarwood007** [comment]
@Sesquipedalian This is a fairly big looking commit, although not much changed in existing files.  What is the risk if this is included in a patch releases?

**Comment by Sesquipedalian** [comment]
Negligible risk. These changes simply perform some tests before executing the full Unicode normalization process on a string, and skips the full process if the string is already normalized. 

You can use the unit test that I provided to confirm this. It runs the complete suite of normalization tests provided by the Unicode Consortium itself.

**Comment by Sesquipedalian** [comment]
If you're interested in more information on how these tests work, see https://unicode.org/reports/tr15/#Detecting_Normalization_Forms.

**Comment by jdarwood007** [comment]
I think thats good enough to say it should be safe for release.  Along with the unit test, it proves far as we know it shouldn't break anything.

**Review by jdarwood007 — APPROVED** [review]

**Pull request merged**
