### PR TITLE
Release 2.1

### PR DESCRIPTION
**Pull request by ghost**
alligning copyright

### CODE REVIEW

**Comment by Arantor** [comment]
Um, what's with the merge pull request?

**Comment by ghost** [comment]
no clue ... git confuses me ... 776ee6d is real one

**Comment by Arantor** [comment]
Yeah, I know it is. What you've done is pulled in all the other changes before making the push. If in doubt, don't try to sync or anything before making a PR and just submit the PR as is because now it's pulled in _everything else for several days_ as part of it.

**Comment by PhuriousGeorge** [comment]
Score 1 Git!

**Comment by Arantor** [comment]
Well, as much as I'd normally be hating on Git, this one is user error for Git workflow, though that doesn't say a lot about Git workflow :tongue: I've done this myself by accident in the past and learned from it.

**Comment by ghost** [comment]
so close this then remake the request?

**Comment by Arantor** [comment]
Well, either that or I could just commit the one line change myself?

**Comment by ghost** [comment]
do that then ill close this now :)

**Pull request closed without merging**
