### PR TITLE
! The beginnings of a conversion to HTML5. About time we did this, reall...

### PR DESCRIPTION
**Pull request by Arantor**
...y.

Signed-off-by: Peter Spicer sleeping@myperch.org

### CODE REVIEW

**Comment by matthew-kerle** [comment]
Not sure why you just didn't fix the conflict issue with my Pull Request because it did all of this and WAY more. Fixed a ton of inline CSS. Added a backwards compatibility doctype and script for older browsers. And fixed hundreds of instances of invalid HTML5.

**Comment by Arantor** [comment]
I have my reasons. Let's just leave it at that.

**Comment by AaronVanGeffen** [comment]
@Xarcell Looking at Arantor's changes, IE8 will render these pages just fine. You'll only need the 'HTML5 shim' JavaScript bit if you're using elements that are new in HTML5 (e.g. nav, section, header), which is not (yet) the case here.

**Comment by Arantor** [comment]
There are some things that need fixing for validation purposes but I wasn't planning on a complete tag conversion just yet.

**Pull request merged**
