### PR TITLE
Fixed!

### PR DESCRIPTION
**Pull request by emanuele45**
Is it correct this line below?

Signed-off-by: emanuele emanuele45@gmail.com

### CODE REVIEW

**Comment by Spuds** [comment]
The signed off by looks fine ...... you may want to use your smf org email though

**Comment by emanuele45** [comment]
Don't have one, never asked for...and I'm not going to ask for one now, I already have too many of these things! :P

**Comment by Spuds** [comment]
Neither do I, you can still use it though :P ... let someone else have the spam

**Comment by norv** [comment]
You can have one as a forwarder only. :)

**Comment by emanuele45** [comment]
gmail handles pretty well spam...except a couple of mails every month that are not spam... :P

**Pull request merged**
