### PR TITLE
Italicize hidden users

### LINKED ISSUE #3933: who's online page hidden user
on the who's online page, it does not clearly tell you if someone is hidden or visible as it does on the list in the info center. if you inspect the source on a user that should be hidden you see there is a <span class="member hidden"> but no css that goes along with it. i think we should add that it is italics to match the info center format.

### PR DESCRIPTION
**Pull request by colinschoen**
Fixes #3933 

Signed-off-by: Colin Schoen <cschoen@berkeley.edu>

### CODE REVIEW

**Comment by XinYenFon** [comment]
@illori can you confirm this is better to separate the hidden & non-hidden users on who's online page?

**Comment by illori** [comment]
i have not applied the fix myself but it looks like it should do the trick yes.

**Comment by colinschoen** [comment]
@illori Please let me know if you give approval on this. I'd like a second set of eyes prior to merging even if it is a small change.

**Comment by illori** [comment]
applied the fix, it had no effect. the class has a space in the name, so in this case it still has no effect. i changed
`<span class="member', $member['is_hidden'] ? '_hidden' : '', '">` in who.template.php and changed the . to _ and then it worked without issue.... also required to disable Minimize css and JavaScript files as the change was not being seen as the minimized file was not being updated fast enough [when does it get updated?]

**Comment by XinYenFon** [comment]
You should disable minimization on dev-branch its not really effective for development (or testing PRs).

**Comment by illori** [comment]
I ended up doing that for testing which was helpful. The issue here needs a
little bit more work.

**Comment by XinYenFon** [comment]
It is working as expected in my local environment. Try hard refresh on the page or validate your index.css via visiting inside your browser and check the added class in it.

**Comment by illori** [comment]
I got it to work with the changes I posted. I don't have time to retest
right now. If you say it works that is good enough for me.

**Comment by XinYenFon** [comment]
@colinschoen is there anything specific we are awaiting for to merge this ?

**Pull request merged**
