### PR TITLE
#3032 fix. Signed off by me. You know who I am (and have probably frequently reg…

### PR DESCRIPTION
**Pull request by StealthWombat**
…retted it).

antechinus@simplemachines.org

So there.

Happy now? :D

Ok so:

Signed-off-by: Antechinus antechinus@simplemachines.org

### CODE REVIEW

**Comment by XinYenFon** [comment]
Good question, is this a valid sign-off ? :/ (Really have no idea if this is valid or not).

**Comment by StealthWombat** [comment]
Should be, since everyone knows who I am anyway, and SMF username is in the email address.

**Comment by StealthWombat** [comment]
Really it wouldn't do to be too worried about this stuff. After all, you have no real way of checking any names or email addresses that are given anyway. I could sign up as Murgatroyd Mugthumper, with an email address of winkiepoodles@frogpond.com, and who would know if it was legit or not?

**Comment by Rupurudu** [comment]
It's not a valid sign-off. Here are how to do it.
1. Sign-offs must be in `Signed-off-by: Name <mail@example.com>` format.
2. Name must be your real and full name.
3. Providied e-mail must be contactable.

However, like you said it's not very important. Even most of the developers are not properly doing it.

Here are some pickups from the latest merges.

Valid ones:
`Signed-off-by: Michael Eshom <oldiesmann@oldiesmann.us>`
`Signed-off-by: Mustafa Can Elmacı <mustafacan@elmaci.net>`
`Signed-off-by: John Rayes <live627@gmail.com>`

Invalid ones:
`Signed-off-by: Antes <antes@simplemachines.org>`
`Signed-off-by: Suki <suki@missallsunday.com>`

Both are not containing real names. They should be in this format:
`Signed-off-by: Mert Alınbay <antes@simplemachines.org>`
`Signed-off-by: Jessica González <suki@missallsunday.com>`

**Comment by live627** [comment]
In Sourcetree, the option to add a sign is in the droppy thing named  "Commit Options".

**Comment by StealthWombat** [comment]
And how do you know the "real names" are actually real names anyway? Fine if you already know the person in question, but you have no hope if you're opening code submissions to anyone who has  GitHub account.

Are you actually checking all the emails to see if they are contactable?*

In reality, the policy is pointless.

*Incidentally the one I gave is legit, even if I never use it. I'm hardly likely to put one of my primary emails where it's going to be open to harvesting by spammers. Waste of time, from my perspective.

**Comment by StealthWombat** [comment]
Ok, so I edited the OP. I'm not going to try and reverse the commit and do it all over again. Tried that last night, and ended up finding it more convenient to just nuke the repo and make another. :P

That's fine occasionally, but the novelty is going to wear off pretty fast.

If what's in the OP still isn't good enough just kill this PR. I'll leave my repo as it is and just get on with more coding, and someone else can handle this issue.

**Comment by MissAllSunday** [comment]
@MustafaCan  It only matters if the license you are agreeing to has some kind of limitation or otherwise needs more from you than simple "acknowledging the license and its terms".  SMF doesn't have that limitation due to the license it chose, the only important thing here is that you are fully aware with the terms and conditions of the BSD 3-Clause license SMF is using. The sign off needs a name and an email address but thats about it, no need to be any real stuff on it.

The only important thing here is that you sign off the commit properly via -s or -S in the CLI or GUI, you cannot just add a name and mail address on a PR on github, the sign off must be done in the commit message itself.  Most GUIs for git has a quick and easy way to add a sign, The default gui for git, Git Gui, has buttons ordered in the way you will be using them.

**Comment by Oldiesmann** [comment]
Closing as this has already been fixed as part of #3075.

**Pull request closed without merging**
