### PR TITLE
update rtl.css

### PR DESCRIPTION
**Pull request by islam2hamy**
delete , edit , and adding some lines to make it work with the smf2.1 ,During using RTL language

Signed-off-by: islam info@smfarabic.com

### CODE REVIEW

**Comment by illori** [comment]
you need to sign off your commit or we can not merge it https://github.com/SimpleMachines/SMF2.1#notes

**Comment by XinYenFon** [comment]
yeap (unfortunately), and please for consistency use 

.my_class {

not

.my_class
{

**Comment by illori** [comment]
the commit has to be signed off not the PR

**Comment by islam2hamy** [comment]
ok,

i will do it now

**Pull request closed without merging**
