### PR TITLE
Fix undefined index `sa`

### LINKED ISSUE #7640: Accessing The Ban List Produces Undefined Array Key "sa"
#### Description
Get 4 errors in error log when trying to access the ban list.

### Steps to reproduce
1.  Fresh Install of 2.1.3
2.  Access the Ban List from the "Administration Center"  This only happens when using the icon on the "Administration Center" page.
3.  Check error log after and see 4 errors. 2: Undefined array key "sa"

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.3
- Database Type: MariaDB
- Database Version: 8.0.23
- PHP Version: 8.0.23

### Additional information/references
#0: smf_error_handler()
    Called from [C:\xampp8.0\htdocs\smf\Sources\ManageBans.php on line 72](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXE1hbmFnZUJhbnMucGhw;line=72)
    #1: Ban()
    Called from [C:\xampp8.0\htdocs\smf\Sources\Admin.php on line 499](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXEFkbWluLnBocA==;line=499)
    #2: AdminMain()
    Called from [C:\xampp8.0\htdocs\smf\index.php on line 191](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxpbmRleC5waHA=;line=191)

### LINKED ISSUE #7641: Undefined array key "sa" - navigating to the Ban List via the Administration Center
#### Description
This only happens when using the icon on the "Administration Center" page.

image

From the forum:
https://www.simplemachines.org/community/index.php?topic=584388.0

### Steps to reproduce
1.  This only happens when using the icon on the "Administration Center" page.

### Environment (complete as necessary)
- Version/Git revision: 2.1.3
- Database Type: MySQL
- Database Version: 8.0
- PHP Version: 8.1

### Additional information/references
The workaround is to navigate there via Admin | Members.

### PR DESCRIPTION
**Pull request by live627**
Signed-off-by: John Rayes <live627@gmail.com>

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
Wasn't it changed because of this? https://github.com/SimpleMachines/SMF/issues/7380

**Comment by DiegoAndresCortes** [comment]
So other sections are good, just this one? I recall asking Sesq about ManageBans too, so I guess something was indeed off.

**Comment by sbulen** [comment]
@live627 - please provide reference info to the issue/bug or forum post.  

Preferably also test evidence!

Reference:  https://www.simplemachines.org/community/index.php?topic=583951.msg4138767

**Comment by live627** [comment]
> Wasn't it changed because of this? #7380

Yes. This does not re-introduce that. The hook still comes before the fallback check.

**Comment by Sesquipedalian** [comment]
If the hook is called before the menu is created, then the hooked function will not be able to add a tab to the menu.

I suggest that instead of moving these lines up, we should just remove the `is_selected` bits from the initial menu creation and instead set `is_selected` to true on the relevant tab in a separate line after the call to the hook.

**Comment by sbulen** [comment]
@live627 - do you have time to look into Sesq's recommendation above?

**Comment by live627** [comment]
no,, sorry

**Comment by jdarwood007** [comment]
#7703 fixed this using the alternative approach.

**Pull request closed without merging**
