### PR TITLE
Make the hidden members visible in the online list

### LINKED ISSUE #7543: Hidden members hide names for admins
https://github.com/SimpleMachines/SMF/blob/aee494fe17322c24c2076cc084b3f4559e61db5b/Themes/default/Who.template.php#L68

When members are hidden and a admin browses action=who, their username does not show at all, just their IP.

This is because of a .hidden generic css we have: https://github.com/SimpleMachines/SMF/blob/aee494fe17322c24c2076cc084b3f4559e61db5b/Themes/default/css/index.css#L4030-L4032

There is a more specific CSS already: https://github.com/SimpleMachines/SMF/blob/aee494fe17322c24c2076cc084b3f4559e61db5b/Themes/default/css/index.css#L3922-L3924   which was added in #3949

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Fixes #7543

### CODE REVIEW

**Comment by jdarwood007** [comment]
I look at my own suggestion now and think its a poor one.  Maybe it would be better if the template did: `$member['is_hidden'] && !$user_info['is_admin']`?  Implying it would only apply the hidden class to those who are hidden and the user viewing this is not an admin.

**Comment by DiegoAndresCortes** [comment]
Not sure I get that, it already skips the hidden users if you can't see them.

I think it's this condition?
```
if (!allowedTo('moderate_forum'))
		$conditions[] = '(COALESCE(mem.show_online, 1) = 1)';
```

**Comment by jdarwood007** [comment]
I was thinking from the template:
https://github.com/SimpleMachines/SMF/blob/aee494fe17322c24c2076cc084b3f4559e61db5b/Themes/default/Who.template.php#L68

So then it wouldn't apply the hidden css class.

**Comment by DiegoAndresCortes** [comment]
So we would be removing the visual hint that they are hidden?
Also it'd be `!allowedTo('moderate_forum')` because that's what the query uses, so not only admins can see hidden users, apparently.

**Comment by jdarwood007** [comment]
Oh, I guess the hint would be appropriate.  I thought about the fact that we are using a .hidden and it is using a css display property to make it visible.  Ignore and continue.

**Comment by DiegoAndresCortes** [comment]
Alright so I suppose the single commit is the easiest approach to fix this

**Review by sbulen — APPROVED** [review]
LGTM

**Pull request merged**
