### PR TITLE
Everybody loves DLs

### PR DESCRIPTION
**Pull request by MissAllSunday**
Some dirty old dev removed our precious definition lists, some even older dev got really upset for some reason... 

Suffice to say, this is top priority!11!eleventeen!1!!

Signed-off-by: Jessica González <suki@missallsunday.com>

### CODE REVIEW

**Comment by XinYenFon** [comment]
Hi,

Just confused why you are using double dd under dl tag, I thought it requires dt/dd to be valid?

thanks for the fix.

**Comment by MissAllSunday** [comment]
Modification credits do not have a term/name like the other credits does so using a definition list for them doesn't make much sense. I would use a ul/li combo here but the old dev was too concern about his precious dls so I put them back. 😏 

edit, typos

**Comment by XinYenFon** [comment]
Fine by me 😆

**Comment by MissAllSunday** [comment]
I can change the PR as needed, just need to know what should be done.

- keep on using dls and insert a blank dt to validate againts html 5
- use ul/li
- use br

**Comment by Sesquipedalian** [comment]
A ul list makes sense to me.

**Comment by XinYenFon** [comment]
+1 on ul/li

**Comment by Oldiesmann** [comment]
I agree with using ul/li as well

**Pull request merged**
