### PR TITLE
Integrate Rank Image Drop Down, move stars to images/membericons

### PR DESCRIPTION
**Pull request by NanoSector**
Signed-off-by: Rick Kerkhof rick.2889@gmail.com

### CODE REVIEW

**Comment by matthew-kerle** [comment]
Thanks for this commit, Rick. I'll try to get it into SMF 2.1 on my next commit. As I discussed with you, there'll be some changes though.

**Comment by NanoSector** [comment]
No problem Matthew :)
The second commit is a fix for the Integration Hooks Management problem I posted earlier.

**Comment by matthew-kerle** [comment]
They need to be separate Pull Requests then if they do different things. One is a bug and one is a feature.

**Comment by NanoSector** [comment]
I wanted to submit a separate Pull Request for it, but I couldn't, looks like it got added here instead.

**Comment by matthew-kerle** [comment]
That's the problem. This Pull Request isn't going to be merged directly. I'm going to basically fork this repo from you, make the necessary changes to Integrate Rank Image Drop Down and then that Pull Request form me can be merged if it's ready.

You need to make a different branch per issue you address. Obviously if two things are directly related it will be the same branch.

**Comment by NanoSector** [comment]
Okay, sorry I'm a noob to all that git stuff. Didn't know you had to create a separate branch :)

**Comment by matthew-kerle** [comment]
It's fine, there's a lot to learn here. It takes time.

You don't _have_ to create a separate branch, but that allows you to submit separate PR's.

**Comment by emanuele45** [comment]
What's missing exactly?

Yoshi if you want, you can revert (I'm not sure what client you are using, generally it could be `git revert b3cf48c30cf49fd8cfee73bcdcf83872fafc0ba4` where the last bit is the hash of the commit) the integration hooks commit and continue work on that other part. :)

**Comment by NanoSector** [comment]
I'm using git CLI. The first commit is complete IMO but Labradoodle is doodling around with it.
I'll clone the repo on my laptop again and then I'll revert the commit. Thanks :)

**Comment by emanuele45** [comment]
Arg, sorry Yoshi!!
I didn't check close enough the first time, stars have been renamed a while ago to icons...would you mind renaming the directory?
Otherwise I can send you a PR with the changes.
/me feels guilty... :blush:

**Comment by NanoSector** [comment]
It's fine, give me a moment, I'll send 'nother pull request to this one :)

**Pull request merged**
