### PR TITLE
Supports URLs with spaces in BBC params

### LINKED ISSUE #7441: Spaces in URLs cause issues
#### Description
Note this works fine in 2.0.  Not sure what changed.

This has been reported multiple times in the forum.  This can also affect migrated forums, e.g., pix that displayed fine in 2.0 simply disappear in 2.1 (if there was a space in the name).  

Note that spaces in _directories_ has been reported as well.

### Steps to reproduce
1. Add a link to an image that has a space in the filename.  It is not displayed in 2.1.

e.g.,:
`[img]https://blahblah.com/forum/pix/Another Night Task.jpg[/img]`

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=582068.0

Note similar issue with directories:
https://www.simplemachines.org/community/index.php?topic=580741.0

### PR DESCRIPTION
**Pull request by Sesquipedalian**
... despite proper standards and all better judgement. 😒

Fixes #7441

### CODE REVIEW

**Comment by sbulen** [comment]
I am having some serious issues testing this...  (php 8.0, mysql 8.0)

First problem:
image

(Note I did have a language installed (albanian)...)

So I figured maybe I installed the patch wrong?  So I did a fresh install from current GH and got this.  The installation couldn't complete...
image

I was debating opening other issues, but these touch on the very functions in question here (iri_to_url).

**Comment by sbulen** [comment]
I think the const usages in class-Punycode.php need to reference self::, e.g., self::IDNA_ERROR_LABEL_TOO_LONG.

I have confirmed if you make those changes to class-Punycode.php, links with spaces now work.

**Comment by Sesquipedalian** [comment]
Better now, @sbulen?

**Comment by sbulen** [comment]
Yes, all errors appear to have been addressed, and URLs with spaces now work fine.

**Review by sbulen — APPROVED** [review]
Works now.

**Pull request merged**
