### PR TITLE
[WIP] Fixes spell check

### LINKED ISSUE #4702: Spell check
As of this post I have upgrade to the latest GH ver. Please see post at SMF. Spell check does not work right

https://www.simplemachines.org/community/index.php?topic=542792.msg3968271#msg3968271

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #4702 (or rather, it will when done)

### CODE REVIEW

**Comment by jdarwood007** [comment]
@Sesquipedalian 

Is this ready?

**Comment by smfbigguy** [comment]
I just added this code to the file and now my spell check works perfectly. This fixed it for me.

**Comment by smfbigguy** [comment]
Now that I have been using it a bit it does act a bit weird. When you click the spellcheck button and the window pops up it toggles the source view on the editor in the background. You can see the editor change. Not sure if it supposed to do that. The post is ok and gets posted fine.

Also, when you are done with spell check and the little window pops up to tell you spellcheck is complete. There is a ok button there. When pressed the spellcheck window stays open. I thought it used to close when you pressed that ok button.

**Comment by smfbigguy** [comment]
I was just thinking...if this code fixes spellcheck and it was thought the original problem was the youtube code, why is the youtube code being removed if spellcheck is fixed. I saw a post here somewhere saying it was going to be removed. Does it really have to be. ??

**Review by NanoSector — APPROVED** [review]
LGTM

**Pull request merged**
