### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by RainRat**
signed-off-by Rainrat ( rainrat78@yahoo.ca )

also, because the changes are trivial, i do not claim any ownership.

### CODE REVIEW

**Comment by live627** [comment]
Thanks. Will consider for 2.2.

**Comment by live627** [comment]
Can you modify your commit to include signed-off-by?

**Comment by RainRat** [comment]
just write signed-off-by? ok.

**Comment by Sesquipedalian** [comment]
Unfortunately, merely putting the signed-off-by message in the description of the pull request here on GitHub isn't sufficient.

The commit message *itself* needs to include `Signed-off-by: Your Name <youremail@example.com>`. Please see the repository's readme for an explanation of why.

You can add the necessary sign-off to the commit message automatically by running the following command:

```
git commit --amend -s
```

Then you can force-push the commit to your PR.

In the future, you can save yourself some effort by always using `git commit -s` rather than just `git commit`. The readme includes some hints for one way to make it more convenient to do that on a consistent basis.

**Review by m4z — APPROVED** [review]

**Comment by m4z** [comment]
I hope my approval wasn't premature? Not sure what that triggers.

**Comment by Sesquipedalian** [comment]
It doesn't trigger anything in particular. It just informs everyone that you approve.

**Comment by RainRat** [comment]
Amended the commit.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
