### PR TITLE
! Missing argument fixed

### PR DESCRIPTION
**Pull request by hhy89**
http://i.hizliresim.com/B98md9.png

Undefined index problem will be fixed like this.

### CODE REVIEW

**Comment by live627** [comment]
How to reproduce this?

**Comment by hhy89** [comment]
i try to pm to anyone and then error_log is created byself.
and i think it will be fixed like this. and error_log is gone byself :)

**Comment by illori** [comment]
i cant reproduce this.

**Comment by hhy89** [comment]
pm preview is enabled in my site. i tried and it created error_log like this.
the code is in Post.php for preview. i copied there and pasted in PersonalMessage.php.

**Comment by illori** [comment]
pm is always enabled, i did a preview and there was no errors.

**Comment by hhy89** [comment]
pm page
http://i.hizliresim.com/LoZWP0.png
error_log page
http://i.hizliresim.com/rd6oLa.png

if u want, i would love to capture video.

**Comment by XinYenFon** [comment]
are you sure you are using the latest build w/o any modification and not the other branches such as development etc... ? I don't have any error in my log too.

**Comment by hhy89** [comment]
yeap im sure. i try to my seo mod but nothing else. seo mod didnt change any file.
and before i used seo mod, error is created. nothing change.

as i said, the code is in post.php for preview error.

**Comment by XinYenFon** [comment]
I updated my build to latest, I still can't reproduce this, can you try this on stock (no mod) install of SMF 2.1? (release-2.1 branch).

Oh also this commit (PR) not signed-off.

**Comment by hhy89** [comment]
http://i.hizliresim.com/B98md9.png
it is in my first message with no mods.

in turkish: Mert ilk mesajda verdiğim resim zaten hiçbir mod kurulmadan çektiğim resimdi. zaten yukarıda dediğim gibi eklediğim kod post.php'den alınan kod. aynı sistemi özel mesaj için de ekleyince aynı kodu eklemek gerekiyor. eklemeyince hata mesajı oluşturuyor.

**Pull request closed without merging**
