### PR TITLE
Fixes #2766 and #3340

### LINKED ISSUE #2766: incorrect text in edit membergroup
You can upload custom images to the default theme directory to be able to select them here.

this text is not correct, the image must be in the images/membericons folder for each theme that is being used, not just the default theme.

### PR DESCRIPTION
**Pull request by frandominguezl**

### CODE REVIEW

**Comment by Oldiesmann** [comment]
I would suggest having this fall back to default_theme_dir. That way if someone wants to use the same icons regardless of the theme, they don't have to copy the files to every theme.

**Comment by Oldiesmann** [comment]
Ignoring the failed Travis check. When I resolved a merge conflict it didn't sign off the commit (nor was there an option to do so). I just removed a blank line from after the ?> in ManageMembers.english.php (not sure why that was causing a conflict though).

**Comment by XinYenFon** [comment]
Just close this and make a clean one.

**Comment by colinschoen** [comment]
Travis failing on master for failed sign off check too

https://travis-ci.org/SimpleMachines/SMF2.1/jobs/196395983

**Comment by Oldiesmann** [comment]
@Antes I don't see a need to redo the entire PR because of that one minor issue.

@colinschoen SleePy is working on debugging that

**Comment by frandominguezl** [comment]
I accidentally pushed the wrong commit, so I'll be closing this and opening a new PR luckily with no build fails.

**Pull request closed without merging**
