### PR TITLE
Just a bit of a visual indicator that user is logged in.

### PR DESCRIPTION
**Pull request by SSPMark**
Seems like the going trend these days is to put the users avatar next to their username in the top menu bar (just like here on GitHub) when the user is logged in. It gives a bit more of a visual appearance that the user is in fact logged in where they might not catch it with just text.

Just a thought.

### CODE REVIEW

**Comment by SSPMark** [comment]
Here's a visual reference.

top-bar-avatar

**Comment by SSPMark** [comment]
Better alignment of the avatar.

top-bar-avatar-adjusted

**Comment by Dragooon** [comment]
I like it

**Comment by live627** [comment]
The avatar is also in the user menu. Should that stay or go?

**Comment by SSPMark** [comment]
I was on the fence on that. It's redundant, but still fits as it's not visible all the time.

**Comment by SSPMark** [comment]
Okay, after messing around with it a bit more, I went ahead and removed the avatar from the user menu.

top-bar-avatar-no-avatar-popup

**Comment by Oldiesmann** [comment]
I personally liked it better the way it was before. Plus, we already have a visual indicator that the user is logged in - their username.

**Comment by SSPMark** [comment]
I know, but switching welcome text with username text and your average user may not catch that they are, in fact, logged in or even worse, logged in as someone else on a shared computer. With the avatar, it pops out more. A lot of sites these days make your avatar ever present when you're logged in. See GitHub, Facebook, Disqus, Google, Xbox.com, Playstation website, etc. so people are likely used to it.

The ones who don't do this, such as Twitter and Dropbox for example, serve a completely different page and look to you when you're not actually logged in versus when you are so it's easier to catch.

**Pull request merged**
