### PR TITLE
Fix upgrade problem on qanda table

### PR DESCRIPTION
**Pull request by albertlast**
see http://www.simplemachines.org/community/index.php?topic=549730.0

Signed-off-by: albertlast albertlast@hotmail.de

### CODE REVIEW

**Comment by rturja** [comment]
Continuing my upgrade saga on Postgres, now qanda table is done:

```
Nov  4 20:08:02 cerebro postgres[65866]: [3-1] ERROR:  argument of WHERE must be type boolean, not type integer at character 63
Nov  4 20:08:02 cerebro postgres[65866]: [3-2] STATEMENT:  
Nov  4 20:08:02 cerebro postgres[65866]: [3-3]                          UPDATE verstas_pm_recipients
Nov  4 20:08:02 cerebro postgres[65866]: [3-4]                          SET in_inbox = 1
Nov  4 20:08:02 cerebro postgres[65866]: [3-5]                          WHERE FIND_IN_SET(-1, labels)
```

Just did a quick fix by changing the {int:minusone} to 'true'

**Comment by albertlast** [comment]
Addded changes to the other pr: https://github.com/SimpleMachines/SMF2.1/pull/3662/commits/8eeab9b6f919163003f0849b9fb823aa6681cf66

**Comment by rturja** [comment]
Thanks again. Now we're nearly there. Got to 90% and got hit by this:

```
Nov  4 20:54:02 cerebro postgres[74780]: [3-4] STATEMENT:  CREATE OR REPLACE FUNCTION migrate_inet(val IN anyelement) RETURNS inet
Nov  4 20:54:02 cerebro postgres[74780]: [3-5]  AS
Nov  4 20:54:02 cerebro postgres[74780]: [3-6]  $$
Nov  4 20:54:02 cerebro postgres[74780]: [3-7]  BEGIN
Nov  4 20:54:02 cerebro postgres[74780]: [3-8]     RETURN (trim(val))::inet
Nov  4 20:54:02 cerebro postgres[74780]: [4-1] ERROR:  syntax error at or near "EXCEPTION" at character 1
Nov  4 20:54:02 cerebro postgres[74780]: [4-2] STATEMENT:  EXCEPTION
Nov  4 20:54:02 cerebro postgres[74780]: [4-3]     WHEN OTHERS THEN RETURN NULL
Nov  4 20:54:02 cerebro postgres[74780]: [5-1] ERROR:  unterminated dollar-quoted string at or near "$$ LANGUAGE plpgsql" at character 1
Nov  4 20:54:02 cerebro postgres[74780]: [5-2] STATEMENT:  $$ LANGUAGE plpgsql
```

**Comment by rturja** [comment]
I think once the whole shebang seems to be working, I do clean update with database backup from yesterday and do a "clean run" on data just to be sure. By the way - seems there is some real nifty postgres work you have done in SMF :)

**Comment by albertlast** [comment]
Please try this changes: https://github.com/SimpleMachines/SMF2.1/pull/3662/commits/c1fd762a4ba78d7a04d70b4a37442a6ee76640df

**Pull request merged**
