### PR TITLE
Integrate personal message

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by emanuele45** [comment]
Just a thought on that one: I see you have changed the hook position from before sending the PM to after.
I think it would be best to have both: the current one changing only the $from['username'], and add another one like integrate_personal_message_send or integrate_sent_personal_message.

**Comment by ghost** [comment]
Nervermind.

**Comment by emanuele45** [comment]
I like it, I was just suggesting something in addition to that, nothing more. If you disagree with my suggestion and think that your solution is more appropriate a small explanation would be enough, I could very likely have missed something. ;)

**Comment by ghost** [comment]
I was on my phone and couldnt write properly..

I will start my repo all over gain and will send it again.

**Comment by emanuele45** [comment]
Ahh..okay, sorry for the misunderstanding then! ;D

**Pull request closed without merging**
