### PR TITLE
Add a ignore file

### PR DESCRIPTION
**Pull request by jdarwood007**
I added a git ignore file to ignore some files that we shouldn't commit.  These include our local Settings.php file, Cache files, Package backups and Packages temp directory.

While we most likely wouldn't accidentally commit these, it helps prevent the mistake from occurring.  I would imagine this would most likely occur when a massive amount of new files are added and a bash script is used to easily add all files and they get added without notice.

### CODE REVIEW

**Comment by emanuele45** [comment]
you can:
`git reset --hard HEAD~2`

in your master branch to remove the last two commits. They will still be available in the other branch. And:
`git push -f`

to force the update of the master branch here at github.

**Comment by jdarwood007** [comment]
Thanks, that did it :)

I was also thinking we may want to add _._~  Which should cover any backup files by PacMan.

**Comment by emanuele45** [comment]
yups...a bit too fast...
Yes, probably the .~ would be nice to have too.

**Comment by jdarwood007** [comment]
Cool, well instead of pushing another pull request I just modified the file directly.

**Pull request merged**
