### PR TITLE
Fix overlapping text in the error log

### PR DESCRIPTION
**Pull request by NanoSector**
Signed-off-by: Yoshi2889 rick.2889@gmail.com

### CODE REVIEW

**Comment by live627** [comment]
There's a conflict here.

**Comment by NanoSector** [comment]
And I have no idea how to resolve it. If only Github had decent documentation on it...

**Comment by NanoSector** [comment]
Let me try this again.

**Comment by NanoSector** [comment]
Seems this was already fixed. Ups.

**Pull request closed without merging**
