### PR TITLE
Update Security.php

### PR DESCRIPTION
**Pull request by VBGAMER45**
Save extra queries on page load rebuildModCache(); does not need to be called by guests.

### CODE REVIEW

**Comment by live627** [comment]
Commit needs to be signed off.

**Comment by jdarwood007** [comment]
While usually true live627, I think we can let ones like this in.  The amount of code added/changed is fairly small and fairly difficult to copyright a simple if statement.

**Comment by VBGAMER45** [comment]
What is the process for signed off? You can use any of my code for SMF 2.1
and any future version under any license.

On Wed, May 28, 2014 at 10:40 AM, Jeremy D notifications@github.com wrote:

> While usually true live627, I think we can let ones like this in. The
> amount of code added/changed is fairly small and fairly difficult to
> copyright a simple if statement.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SimpleMachines/SMF2.1/pull/1690#issuecomment-44423859
> .

## 

---

Free Forum Hosting for your community needs
http://www.createaforum.com
Community and Forum Solutions
http://www.ezcommunitysuite.com

**Comment by Oldiesmann** [comment]
The process for signing off varies depending on what you're using to commit the code. For command line, just add the -s flag to the commit command (git commit -asm "message"). For graphical clients (TortoiseGit, SourceTree, GitHub for Windows, etc.) there's usually a box you can check to do it.

**Comment by VBGAMER45** [comment]
So what's next. Should I download this repo and go for there?

I don't see a way in the web interface to signoff...

**Comment by VBGAMER45** [comment]
I am going to withdraw this one...Looks like that function is required to be called/loaded by guests but will summit a different patch to reduce the querys used.

**Pull request closed without merging**
