### PR TITLE
Stop Tracking Minified Files in Git

### PR DESCRIPTION
**Pull request by colinschoen**
Signed-off-by: Colin Schoen <cschoen@berkeley.edu>

### CODE REVIEW

**Comment by XinYenFon** [comment]
? https://github.com/SimpleMachines/SMF2.1/pull/3776 ?

**Comment by colinschoen** [comment]
Adding a file to `.gitignore` does no good if it is already being tracked by the repository from an earlier commit. This removes the files from the repository. Essentially undoing 4d5138c. Not sure why they were added in the first place.

**Comment by XinYenFon** [comment]
hmm... I think you should reset your local repo to SMF2.1/release-2.1.

git reset --hard should help you on that.

**Comment by colinschoen** [comment]
Why would I `git reset` What am I resetting to? `HEAD`? The minified files currently exist in the `HEAD` of `release-2.1`. This commit removes the blank versions of the minified files which shouldn't be necessary since they are created automatically.

**Comment by XinYenFon** [comment]
If I recall correctly there are certain cases SMF cannot create those files, that's reason those files created in the first place.

Ref: https://github.com/SimpleMachines/SMF2.1/issues/3498

**Comment by colinschoen** [comment]
Hmm annoying. Then I suppose there will always will be the issue of modified tracked files that we don't care about, unless there is some other git trickery that I don't know of.

**Comment by colinschoen** [comment]
This might work: 

https://git-scm.com/docs/git-update-index

`git update-index --skip-worktree Themes/default/scripts/minified.js`
`git update-index --skip-worktree Themes/default/css/minified.css`

**Comment by XinYenFon** [comment]
There won't be if you disable minimizing on localhost or just reset to SMF2.1/release-2.1 (not HEAD), btw HEAD is not this repo's HEAD its your origin repo's HEAD. That's why your resets won't fix it.

If you add this in your .git/config

```
[remote "upstream"]
   url = git://github.com/SimpleMachines/SMF2.1.git
   fetch = +refs/heads/*:refs/remotes/upstream/*
   fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
```

This will enable this repo as your upstream (less trouble), then you can use following code to reset your local repo to latest build in this repo;

```
git reset --HARD upstream/release-2.1
git push -f origin release-2.1
```

**Comment by colinschoen** [comment]
I was talking about `HEAD` prior to committing. I don't want to have to reset every time I load the forum. The solution I posted above works. Closing this pull request.

**Comment by XinYenFon** [comment]
You should not be resetting your repo unless something bad happens, you just pull & push without committing to your origin/release-2.1, for PRs you use branching. Just typing it here so if someone reads in future to solve similar problem can use either of the methods.

**Comment by colinschoen** [comment]
No, I'm not ever running `git reset`, but I would have to use that or `git stash` without using my other solution in order to stop have git showing the minified files were changed after loading any forum page. Changing the upstream won't change which files are tracked by git so I don't see how that would fix the issue.

**Pull request closed without merging**
