### PR TITLE
Only disable bbc when its not a message

### LINKED ISSUE #7404: Setting for signatures affects the `url` BBC in entire posts
#### Description
This was reported on the Bug Reports board (relevant details are on page 4):
https://www.simplemachines.org/community/index.php?topic=580848.60

If you disable `url` BBC, all links in topics stop working and not just in the signature:
Capturar

So signatures should be separate from posts when it comes to the `url` BBC.

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Fixes #7404

### CODE REVIEW

**Review by jdarwood007 — APPROVED** [review]
Logic looks good, but didn't test.  $message === false, is when we are testing what BBC is available.

**Comment by DiegoAndresCortes** [comment]
These were the results, I posted them somewhere else by mistake.

**Disabled:**
Screenshot_12
Screenshot_11

**Enabled**
Screenshot_14
Screenshot_13

**Comment by sbulen** [comment]
LGTM.  Thanks for the test pix.  Really helps.

Ready to merge?

**Comment by BrickOzp** [comment]
Can you reproduce the original issue if removing my fix?

Otherwise I think your fix looks good.

**Comment by DiegoAndresCortes** [comment]
I didn’t test for it, I assume your fix is still needed because nothing changed prior as far as I could tell.

**Pull request merged**
