### PR TITLE
 Simplifies min/max version range for search and cache APIs

### LINKED ISSUE #5558: Searching in SMF Admin gives error in log
RC2 

Searching in SMF Admin gives me a error in log, but the search still works.

Type of error: Critical 							
The selected search API the forum is using is out of date - falling back to standard search. Please check file SearchAPI-Standard.php.							 http://localhost/testrc2/index.php?action=admin;area=search
--

### PR DESCRIPTION
**Pull request by Sesquipedalian**
The previous way required us to update the `$version_compatible` strings in Class-SearchAPI.php and Class-CacheAPI.php with every release, in a misguided and ineffective attempt to future-proof against API changes.

Fixes #5558

### CODE REVIEW

**Comment by live627** [comment]
Should the version strings be constants?

**Comment by Sesquipedalian** [comment]
> Should the version strings be constants?

To clarify, do you mean changing the `$version_compatible` and `$min_smf_version` variables into constants?

**Comment by live627** [comment]
yes

**Comment by Sesquipedalian** [comment]
Hm... probably not, no. It is possible that mods might need to change those values when extending the class. 

For example, maybe a change in SMF 2.1.7 will break the Sphinx search mod in a way that requires two versions of the Sphinx mod to be released: Sphinx_A that is compatible with 2.1 RC1 through 2.1.6, and Sphinx_B that is compatible with 2.1.7 through 2.1.999. That's not a very likely scenario, but not an impossible one.

**Comment by MissAllSunday** [comment]
But they can redefine the constant if they extend the class and we use "static" when referencing those constants.

Now, I can argue than those vars are suppose to be changed, in that case a constant isn't the best case for that, better put some getters and setters for those vars to allow  configuration by whoever needs it.

**Review by live627 — APPROVED** [review]

**Pull request merged**
