### PR TITLE
Fix query error on background task

### LINKED ISSUE #5703: alert_count Invalid value inserted or no type specified
#### Description
Getting this in the error log
```
Type of error: Critical 
Invalid value inserted or no type specified.
Function: alert_count
http://.../cron.php
.../Sources/Profile-Modify.php (Line 2412)
```

https://github.com/SimpleMachines/SMF2.1/blob/3428c48f144566b25b3ac0f97aa6cb505ebba264/Sources/Profile-Modify.php#L2403-L2412

### Steps to reproduce
The errors gets logged often from the cron jo, but you can manually trigger it aswell:
1. Using two accounts, lock a topic that the other account is following
2. you should see the error logged, but you might have to retry a few times

### Environment (complete as necessary)
- Version/Git revision: 3428c48f1

### Backtrace Information
```
#0: smf_db_error_backtrace()
Called from ...\Sources\Subs-Db-mysql.php on line 190
#1: smf_db_replacement__callback()
Called from unknown on line -1
#2: preg_replace_callback()
Called from ...\Sources\Subs-Db-mysql.php on line 404
#3: smf_db_query()
Called from ...\Sources\Profile-Modify.php on line 2412
#4: alert_count()
Called from ...\Sources\Subs.php on line 394
#5: updateMemberData()
Called from ...\Sources\tasks\CreatePost-Notify.php on line 357
#6: execute()
Called from ...\cron.php on line 216
#7: perform_task()
Called from ...\cron.php on line 110
```

### PR DESCRIPTION
**Pull request by SychO9**
Fixes #5703

### CODE REVIEW

**Comment by smfbigguy** [comment]
I was just testing this and I get an error:

Undefined index: can_manage_boards

in cron.php. It could be just my board though and not SMF but I thought I would post anyway.

**Comment by SychO9** [comment]
what's the full error message ? and backtrace ?

**Comment by smfbigguy** [comment]
Sorry was an old copy of cron.php Disregard this please.

**Comment by SychO9** [comment]
alright, thanks for checking though :)

**Comment by smfbigguy** [comment]
Does this have anything to do with it:

Screenshot_2019-07-18 Error Log

Screenshot_2019-07-18 Backtrace

**Comment by SychO9** [comment]
I can't reproduce the issue, did you update all of your installation to the latest GitHub version before applying this PR's changes ?

**Comment by smfbigguy** [comment]
No I did not. Also, this error keeps coming back for some reason. The member that produced it has not been on site since yesterday but it says it was generated today. If it can not be reproduced than it is my install of 2.1 and not GH.

**Pull request merged**
