### PR TITLE
responsiveness plus minor fixes

### PR DESCRIPTION
**Pull request by SychO9**

### CODE REVIEW

**Comment by XinYenFon** [comment]
Your PR is good to go but line-endings is the issue :)

**Comment by SychO9** [comment]
Sorry, I'm not used to this

**Comment by XinYenFon** [comment]
Your line-endings are problematic due to your editor you are using. Its not missing any line or anything.

**Comment by SychO9** [comment]
How about now? I was using Github online editing, now I'm using my editor with EOL setting (Gh desktop)

**Comment by frandominguezl** [comment]
Looking good now, thanks.

**Comment by XinYenFon** [comment]
LGTM.

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/4624

This is undoing this previous commit.  Is this intended or was the previous commit wrong?

**Comment by SychO9** [comment]
That's confusing, the label literally says "New Message", that PR makes it take you back to the inbox, what Illori probably addressed was the fact that the dropmenu's title "Messages" takes the first item's link, which was "new msg page", that PR changes "New Message" link thus affecting "Messages", 
so in this case either reorder the items and fix the link, or remove links from dropmenu titles like in 2.0

I made the changes for the first option, if you see fit

pm sa send

**Review by jdarwood007 — APPROVED** [review]

**Pull request merged**
