### PR TITLE
PMs, Alerts & few GenericLists Responsiveness adjustments

### PR DESCRIPTION
**Pull request by SychO9**
Mostly Tables

### CODE REVIEW

**Comment by SychO9** [comment]
total_num

Is this intended or should I add a fix here ?

**Comment by Gwenwyfar** [comment]
I'm not sure, what is the second number for?

**Comment by XinYenFon** [comment]
first one is for error log second is users needs approval

**Comment by SychO9** [comment]
The first is for error log, the second is for member approval

**Review by Gwenwyfar — COMMENTED** [review]
I don't think we should be using "mobile_hidden" classes, but instead giving a name to each item if they don't have a identifying class/id yet. Not only because this adds a useful class for both desktop and mobile, but it is more semantic and it makes it clear what you are hiding (if you choose to), and easier to modify at will or hide content in different size sets.

**Comment by SychO9** [comment]
I assumed it'd be fine since there's the "hidden" class which hides some elements under 720px screen view, but I'll edit all of this and use specific classes instead, should I remove remove instances where I used the hidden class as well ?

**Comment by Gwenwyfar** [comment]
The responsive file hasn't been worked much in a while, it still needs a major revision (work has been focused in the other files). If there's other hidden classes doing the same they shouldn't be there either.

I'll have to check to confirm, but I'd think so. We may need to go over the ones already being used in another PR as well if that's the case.

**Comment by jdarwood007** [comment]
The "hidden" class is to hide it always.  Its a shortcut to writing style="display: none;" in our code and then having javascript toggle it as needed.  This is generally for elements that again we are using javascript to toggle them on or off.

**Comment by SychO9** [comment]
Should be good now

**Review by Gwenwyfar — APPROVED** [review]

**Pull request merged**
