### PR TITLE
NO HTML allowed :P

### LINKED ISSUE #1548: karma labels should not accept html
it can cause issues...

### PR DESCRIPTION
**Pull request by XinYenFon**
fixes #1548
Signed-off-by: Antes antes@simplemachines.org

### CODE REVIEW

**Comment by emanuele45** [comment]
I think you should do that before saving the value into the database (and definitely not in the template ;)).

**Comment by XinYenFon** [comment]
that would be better ofc, but i didn't find any clue about it (Took a look at how its done in board names).

**Comment by Oldiesmann** [comment]
Karma is probably going to be removed at some point anyway, but this needs to be done when we're saving settings, not when the setting is loaded in the templates.

**Comment by matthew-kerle** [comment]
Since when is it cool to use htmlspecialchars in a template?

**Comment by matthew-kerle** [comment]
You can always modify it in the source file and then the template can grab it.

$modSettings['varOne'] = $smcFunc['htmlspecialchars']($modSettings['varOne'], ENT_QUOTES);

That in the source, and then just use the var in the template and it's clean.

**Comment by XinYenFon** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/1556 ?

**Comment by matthew-kerle** [comment]
Ah my bad. Good to see. :)

**Pull request closed without merging**
