### PR TITLE
edit fixes JS error/warning

### PR DESCRIPTION
**Pull request by Underdog-01**
Signed-off-by: -Underdog- github.underdog@gmail.com

### CODE REVIEW

**Comment by live627** [comment]
Can I ask how to reproduce the error?

**Comment by Underdog-01** [comment]
I adjusted the edit.

I use Komodo editor which has a syntax checker. 
The file parameter is set to javascript and then flags all the errors within the file (red underline). 
I think it flagged the warning because event had to be defined as something previously in the onset of the function (not a new var) and the condition is checking if it is false then assigning it as another value. var is only used when assigning a new undefined var.

It also shows other warnings in the file about anonymous functions returning no value whereas a return false; at the end of them fixes it.

**Comment by NanoSector** [comment]
Komodo flags them as strict warnings. They're not required to fix. http://i.imgur.com/WWF3BDD.png

**Comment by Underdog-01** [comment]
I was not sure which misdemeanor warnings are ignored for JS and suppose it depends on each dev's preference. .

**Comment by live627** [comment]
False flag.

**Pull request closed without merging**
