### PR TITLE
Remove the option to use the full editor on quick reply

### PR DESCRIPTION
**Pull request by live627**

### CODE REVIEW

**Comment by XinYenFon** [comment]
uh?

**Comment by live627** [comment]
you saying you don't like this?

**Comment by XinYenFon** [comment]
Quick reply is for quick typing (so I'm not against) but could be nice to know the reasons (or I'm probably missing the discussion :P).

**Comment by live627** [comment]
I'm trying to find Arantor's report

**Comment by live627** [comment]
#1380
http://www.simplemachines.org/community/index.php?topic=524417.0

**Comment by illori** [comment]
there was no other way to fix the issue then to remove the full editor in quick reply?

**Comment by illori** [comment]
also since i had this set before your change... the buttons are still showing as if you changed nothing.

**Comment by AngelinaBelle** [comment]
This topic has a confusing title. Several people have read it to mean the full editor on quick reply has gone away.
It really means that full editor is always on quick reply.

**Comment by Oldiesmann** [comment]
Isn't there a way we can fix the issues without forcing everyone to use full editor on quick reply? There are plenty of people who would prefer to keep quick reply the way it's always been without the editor.

**Comment by Oldiesmann** [comment]
This has now been reverted in #2011 (though the top bar where the buttons would normally go is still showing with the editor disabled), but spell check and auto-saving of drafts still seem to work fine even with the full editor disabled.

**Comment by illori** [comment]
did you test with your developer tools open and using the console to check for errors?

**Comment by Oldiesmann** [comment]
Just tested it again with dev tools open this time. No errors and both spell check and auto-saving of the draft work fine still.

**Comment by illori** [comment]
i am not getting any errors either. is it expected that we still see the full set of buttons as if the editor is still full?

**Comment by Oldiesmann** [comment]
Yes

**Comment by illori** [comment]
then i guess the issue is resolved

**Pull request merged**
