### PR TITLE
Hardcoded text is bad (mostly fixes #6521)

### LINKED ISSUE #6521: Error hard coded Text
#### Description
SMF RC3 Current build

Found hard coded Error text. This can not translated

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Boards.php#L875
trigger_error('createBoard(): **One or more of the required options is not set**', E_USER_ERROR);

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Boards.php#L878
trigger_error('createBoard(): **Target board is not set**', E_USER_ERROR);

### PR DESCRIPTION
**Pull request by Oldiesmann**
This fixes all the hardcoded text in various trigger_error calls, except for any "Hacking attempt..." messages (not sure if we can/should handle those as well?)

Signed-off-by: Michael Eshom <oldiesmann@gmail.com>

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Not sure why the Errors language file is causing the check to fail. None of my editors are showing anything after the closing PHP tag.

**Comment by live627** [comment]
I believe it's because a blank line must be above the closing tag.

**Comment by Oldiesmann** [comment]
I'll try that when I get home tonight

**Comment by Oldiesmann** [comment]
That fixed it. Thanks!

**Pull request merged**
