### PR TITLE
SMF Error's during clean SQLite3 install (#1740)

### PR DESCRIPTION
**Pull request by tinoest**
Added check for if the $handle is a object

### CODE REVIEW

**Comment by Oldiesmann** [comment]
You forgot to sign off. Also, there shouldn't be a new line at the end of the file.

**Comment by tinoest** [comment]
Removed that line, its automatically added when I use vim. 

By sign off I guess you mean the following? 

Signed-off-by: tinoest

**Comment by tinoest** [comment]
Grrrrrr, its being added automatically every time I use the github client I have. Its not vim as  I thought it was.

**Comment by Oldiesmann** [comment]
No, I mean actually signing off the commits, in the GitHub client. Generally you can check a box to do it, or you can just type "Signed-off-by: <username> email@adddress.here" in the commit message. I'll accept the commits this time but in the future things need to be signed off properly.

**Pull request merged**
