### PR TITLE
Update $smcFunc['random_int'] of upgrade fixes #5251

### LINKED ISSUE #5251: Call to undefined function random_int() in upgrade.php on line 564
#### Description
Upgrade.php fails when running due to no fallback code for non php 7 sites to quote oldiesmann
"random_int doesn't exist prior to PHP 7, but the way the code is written there's supposed to be a compatibility function in Sources/Subs-Compat.php"

### Steps to reproduce
1.  Run upgrade.php

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

### PR DESCRIPTION
**Pull request by albertlast**
issue #5251

### CODE REVIEW

**Comment by wintstar** [comment]
- Version/Git revision: Pull Request 5620
- Database Type: MySQL
- Database Version: 5.6.42-log
- PHP Version: 7.1.22


if I use the fix, I get further error messages

> Notice: Undefined index: random_int in C:\xampp\htdocs\smfbeta\Sources\Security.php on line 744
> 
> Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\smfbeta\Sources\Security.php:744 Stack trace: #0 C:\xampp\htdocs\smfbeta\upgrade.php(872): createToken('login') #1 C:\xampp\htdocs\smfbeta\upgrade.php(302): WelcomeLogin() #2 {main} thrown in C:\xampp\htdocs\smfbeta\Sources\Security.php on line 744

**Comment by albertlast** [comment]
So than take the other route,
i corrected the information in the upgrader.
When you to this changes pleae watch out that i revert the remove of the old commit.

**Comment by wintstar** [comment]
Works. Thanks.

**Comment by sbulen** [comment]
Tested good here, too.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
