### PR TITLE
Old icon cleanup

### PR DESCRIPTION
**Pull request by XinYenFon**
I left last icon part for compat but not sure if I should because anyone using old PNG request should update to class...

### CODE REVIEW

**Comment by live627** [comment]
Not so sure this is RC material...

Should this be saved for a future version (like 2.2 idk)?

**Comment by XinYenFon** [comment]
I think this can slip into RC2, but its your call. You can use it whenever you want with or without credit. I'm only interested in helping and building :)

**Comment by Gwenwyfar** [comment]
I don't see any problem with it, though it would need further adjustments.

**Comment by Sesquipedalian** [comment]
I like this, since it allows themes more control over their choice of icons. But I'll leave it up to @Gwenwyfar to decide when/if to approve it. I've tentatively added the PR to the Final milestone for now, pending her decision.

**Comment by XinYenFon** [comment]
oh btw I made a mistake and pushed a fix here... I should be doing it in another PR :| sorry.

**Comment by XinYenFon** [comment]
this is no longer valid PR, some parts already merged and some are unnecessary.

**Pull request closed without merging**
