### PR TITLE
Handle version_comment better

### PR DESCRIPTION
**Pull request by albertlast**
Should evade the bug from https://www.simplemachines.org/community/index.php?topic=557286.0

### CODE REVIEW

**Review by sbulen — CHANGES_REQUESTED** [review]
Unfortunately, the MySQL folks are rethinking how this works...   This will be deprecated in 5.7.6, in favor of the performance schema:
https://dev.mysql.com/doc/refman/5.7/en/performance-schema-variable-table-migration.html

We should think about some fallback logic.

**Comment by albertlast** [comment]
Or we raise the min version of mysql to 5.0.22 / 5.1.10,
than is the bug fixed and we don't need change anything.

btw 5.0.22 was released in the year 2006...

**Comment by sbulen** [comment]
I believe this change already went in with PR #4392.   This is a dupe.

**Comment by albertlast** [comment]
Yes and no.
Yes the change already is inlcuded,
but since no one is awnser >my< question about the future of mysql version in the dev board,
i can't finish this pr.

**Pull request closed without merging**
