### PR TITLE
!disregard message confusing to users

### PR DESCRIPTION
**Pull request by AngelinaBelle**
Clarify what disregard/ignore actually means

Signed-off-by: Angelina Belle angelinabelle1@hotmail.com

### CODE REVIEW

**Comment by illori** [comment]
i think this version still needs some work, it has removed the part of the message that lets the user know this applies to all moderators. users in 2.0 have had issues with not knowing this.

**Comment by Oldiesmann** [comment]
I think "Moderators will not see any future reports ..." would be better than "No moderator will see any future reports".

**Comment by AngelinaBelle** [comment]
Howzzat?

**Comment by Oldiesmann** [comment]
Sounds good :+1:

**Pull request merged**
