### PR TITLE
Responsive Tables

### LINKED ISSUE #5587: Who's online and IPV6 (mobile)
When viewing 'who is online' on mobile and someone online has a long IPV6-adress, you're not able to see the action of the online users/guests.

Possible fix: break IP after "x" characters.

### LINKED ISSUE #5594: Unresponsive tables
a reminder to look at a few more unresponsive tables in the admin section
* hooks
* langs
https://www.simplemachines.org/community/index.php?topic=567096.msg4015563;topicseen#new

### PR DESCRIPTION
**Pull request by XinYenFon**
fixes #5594 
fixes #5587

### CODE REVIEW

**Comment by SychO9** [comment]
please not display block table cells, they increase the height of the page a lot and don't really look good imho, we should just stick to removing some cells so that tables can nicely crop

**Comment by XinYenFon** [comment]
This is the only viable solution to many issues. IMO, side effect is acceptable at this stage. Choice is yours : )

**Comment by XinYenFon** [comment]
If this is going to be added to core, needs to be done in RC3, this is not a small change (maybe in a code but not in reality). Needs testing during last RC period.

**Comment by SychO9** [comment]
Rip :(

**Pull request merged**
