### PR TITLE
Change mods column in members to nullable

### PR DESCRIPTION
**Pull request by albertlast**
search all columns in members which got no default value and are not nullable and are not smf default columns and
changed them to be nullable.

to catch issues like this https://www.simplemachines.org/community/index.php?topic=564951.0

atm is the pr not tested

### CODE REVIEW

**Comment by VBGAMER45** [comment]
Maybe also do the same for other tables i saw this one in messages table
https://www.simplemachines.org/community/index.php?topic=564909.msg4006012#msg4006012

**Comment by MissAllSunday** [comment]
Since we do not know what tables can be modified by a mod, perhaps it will be good to do a mapping for all of them and apply the change to each.

**Comment by albertlast** [comment]
Would be nice if someone can test this first

**Comment by live627** [comment]
If anyone decides to merge this in and things randomly break, I will not shy away from general nastiness (aka "I told you so")

**Comment by albertlast** [comment]
Since the fields are already nullable,
only no one did tell this mysql (the old mysql version ignore this information),
did i see no problems.

On the other hand i see no other solution.

**Comment by sbulen** [comment]
Pretty much any table could be modded...  

We either need to go all-in or all-out...   Either this expands to do ALL tables, or, we get rid of STRICT.

**Comment by albertlast** [comment]
for me it's soudn random to go the "all way" and this is not strict mode,
this is the default mode.

**Comment by sbulen** [comment]
I tested this & it hangs on my WAMP forum during the install on this step:
image

**Comment by albertlast** [comment]
Maybe the sql error was the problem.

**Comment by sbulen** [comment]
For the record, I took a vanilla 2.0 forum, installed the adkportal, & looked at the columns that meet your criteria (default NULL, not nullable, not PRI) and there are 41 columns that meet the criteria.   So, once your logic executes, it will be altering other existing columns in members, boards & topics:
image

**Comment by albertlast** [comment]
when you look at the code,
i always blacklist some columns: 
https://github.com/SimpleMachines/SMF2.1/blob/73c5ae85c1183d8f7077c31661476c35f6a00d52/other/upgrade_2-1_mysql.sql#L2944

**Comment by sbulen** [comment]
Just pointing out that it's not all of them...

EDIT:  Is there a reason you didn't blacklist message_labels, openid_uri?

**Comment by albertlast** [comment]
When you look at you screenshot,
in members table only three columns(massage_labels,openid_uri and adk_...) get fixed,
which looks right to me.

**Comment by sbulen** [comment]
I don't understand why you would blacklist some vanilla SMF columns but not others?

**Comment by albertlast** [comment]
because the vanilla are right,
only the mod column are wrong.

**Comment by sbulen** [comment]
message_labels, openid_url are vanilla columns...

**Comment by albertlast** [comment]
they are not part of the 2.1 setup any more

**Comment by sbulen** [comment]
Got it.  In fact, they are removed during the upgrade.  Good.

**Pull request merged**
