### PR TITLE
adjust bitmask & get_html_translation_table output

### PR DESCRIPTION
**Pull request by Underdog-01**
- the function of get_html_translation_table actually filters spaces to the entity of & # 39; (without the 0) so this has to be added to the replacement array
- the default document charset encoding varies dependant on PHP version and should be specified 

Signed-off-by: -Underdog- github.underdog@gmail.com

### CODE REVIEW

**Comment by Underdog-01** [comment]
I just noticed that ENT_HTML5 was only introduced in PHP 5.4.0+
Shall I remove that bitmask parameter?
What is the minimal PHP version to use SMF 2.1 now? Is it 5.4 whereas I can leave that part as is?

**Comment by MissAllSunday** [comment]
Its 5.3.8

**Comment by Underdog-01** [comment]
Suki,
Thank you.

I have removed the edit for the bitmask parameter as it is only compatible with PHP 5.4.0+
If the SMF 2.1 minimal PHP version is bumped up at some point in time for whatever reason I will reintroduce that specific bitmask parameter.

**Comment by Underdog-01** [comment]
perhaps more is required here.
Please note that function also performs different default encoding dependent on PHP version.
PHP 5.4.0+ encodes it as UTF-8 while anything prior to that encodes it at ISO-8859-1.
That encoding paramter can be put within the function to override the default behavior.

**Comment by MissAllSunday** [comment]
SMF uses $context['charset'] to overwrite whatever default charset a function has.

**Comment by Underdog-01** [comment]
Then that should also be added to this function which I will do right now..
Do note that it is $context['character_set']

**Comment by Underdog-01** [comment]
If you look at the reference for that function (supported charsets):
http://php.net/manual/en/function.get-html-translation-table.php#refsect1-function.get-html-translation-table-description

.. you will see that only certain ones are accepted else it will go the the default and display an error. 

Would it be prudent to perhaps fill an array with the accepted charsets and if the current smf charset setting is not in that array then force it to default to UTF-8 ?? 

This will thwart any possible errors if other charsets are allowed/possible for SMF 2.1

**Comment by MissAllSunday** [comment]
As far as I know, all the charsets SMF uses are included on that list since we haven't see any mayor issue (I remember a few, isolated ones on mantis, cannot remember them all) on previous versions and usage of  htmlspecialchars() which was used on several places pretty much rawly.

**Comment by Underdog-01** [comment]
I will leave this PR as is then since I see no further necessary edits to it.
This fix is required for use of the un_htmlspecialchars function. 
Tested while installing mods that use it whereas it flagged an error which is what drew my attention to the issue. 
Regards.

**Pull request merged**
