### PR TITLE
Remove lang_spelling

### PR DESCRIPTION
**Pull request by sbulen**
Based on an internal discussion.

Having this optional string for translation made things look incomplete & incorrect on CrowdIn.

Given it was optional, little-used, and that the spellcheck feature itself has been disabled, it can go...

Initially, was going to remove the lang_dictionary string also, but it is used in the editor & for the wiki help links as well.  So I kept lang_dictionary.

### CODE REVIEW

**Comment by sbulen** [comment]
@live627 - changes OK for the editor? (Any indirect impacts...?)

**Review by live627 — APPROVED** [review]
Yes. Originally, the editor used `lang_locale`.

**Comment by wintstar** [comment]
Have you forget to delete $txt['languages_dictionary'], $helptxt['languages_dictionary']?

https://github.com/SimpleMachines/SMF2.1/search?q=languages_dictionary

**Comment by sbulen** [comment]
No.  As noted above:

> Initially, was going to remove the lang_dictionary string also, but it is used in the editor & for the wiki help links as well. So I kept lang_dictionary.

**Comment by wintstar** [comment]
Sorry, I had overlooked.

**Pull request merged**
