### PR TITLE
Release 2.1

### PR DESCRIPTION
**Pull request by tinoest**
Fixes Issue discovered during upgrade.php with PostgreSQL https://github.com/SimpleMachines/SMF2.1/issues/2904

Signed-off-by: tinoest tinoest@gmail.com

### CODE REVIEW

**Comment by tinoest** [comment]
Sorry, I can't seem to remove the last PHP ?> change for some reason within vim or the OS:X github client

**Comment by XinYenFon** [comment]
You need to sign-off (each commit) btw.

() = edit part.

**Comment by tinoest** [comment]
That's just sign-off @tinoest isn't it?

**Comment by tinoest** [comment]
I don't really want the second commit :  3accd67 in there, but can't see how to remove it. It's just me pulling changes from upstream SMF into my local repository, so that I was in sync to push the second commit.

**Pull request closed without merging**
