### PR TITLE
Slightly larger checkboxes. WIP - Feedback requested.

### PR DESCRIPTION
**Pull request by SSPMark**
Okay, so, this one is another one of those "let me know what you think and I'll work on it more" things. :stuck_out_tongue:
1. The checkboxes feel really small to me. I don't know if it's the new theme overall, or just the styled text inputs that are being used. So increased the size ever so slightly.
2. Should we clear the browser default styling and customize it to look more like the text inputs? i.e. white bg and black thin border?

### CODE REVIEW

**Comment by XinYenFon** [comment]
I didn't notice any difference?

**Comment by SSPMark** [comment]
Doh, that's what I get for not cross browser testing right out the gate. They stay the same in Firefox because in Firefox they're larger already. So, this really just fixes Chrome which renders them a few pixels smaller.

Before: checkboxes-before After: checkboxes-after

Interesting note, in IE, they're the same size as Firefox with no CSS, but add my CSS and they are even larger.

Will have to test more thoroughly if it's decided as a good change.

**Comment by XinYenFon** [comment]
Seems nice especially for people like @Kindred-999 :D :D

**Comment by colinschoen** [comment]
Agreed, this seems like a useful tweak.

**Comment by SSPMark** [comment]
Okay, I'll finish it up and mark it when I'm done.

**Comment by live627** [comment]
Mark, any news?

**Comment by SSPMark** [comment]
I'm terribly sorry, but time just got away from me. Feel free to merge it
in and pick up where I left off. What I've got so far at least makes it so
that the size of the checkboxes in Chrome match that of Firefox and
Internet Explorer. Otherwise I can try to finish it up (i.e. full testing)
later this week, or at the lest, this weekend.

**Pull request closed without merging**
