### PR TITLE
Does a better job of ensuring $cachedir is defined and writable

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Also improves path checking in Settings.php.

### CODE REVIEW

**Comment by sbulen** [comment]
Any time you change Settings.php these days, you must also change the $settingsArray in upgrade.php.

**Comment by sbulen** [comment]
I don't think we wanted the !is_dir checks on $sourcedir, etc...   I think you meant is_file...

**Comment by Sesquipedalian** [comment]
> I don't think we wanted the !is_dir checks on $sourcedir, etc... I think you meant is_file...

Oh yeah, forgot about symlinks.

**Comment by Sesquipedalian** [comment]
#5948

**Pull request merged**
