### PR TITLE
Error in RepairBoards.php

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
So apparently the description for the category is not being added and it causes the task to crash before it can fix and repair the problems caused by missing subjects, messages, topics, boards, etc.

If there's a better fix I don't mind this being dismissed.

Regards

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
I also added a small fix for the GenericList.template.php

**Comment by frandominguezl** [comment]
Tests throw an error because of the end of file extra spaces. Can you remove them?

**Comment by DiegoAndresCortes** [comment]
So I accidentally removed the fork, do I send a new pr?

**Comment by colinschoen** [comment]
Yeah we will close this PR once you submit the new one.

**Pull request closed without merging**
