### PR TITLE
Suppress PHP warnings for memcache connection

### PR DESCRIPTION
**Pull request by Underdog-01**
Suppress PHP warnings for checking memcache connections

Signed-off-by: Chen Zhen <github.underdog@gmail.com>

### CODE REVIEW

**Comment by Underdog-01** [comment]
It shows "passed" on my account/patch with Travis CI.
I don't know why the check mark does not appear here.

**Comment by live627** [comment]
Someone with admin access should check that.

**Comment by Underdog-01** [comment]
It shows it here:
https://github.com/Underdog-01/SMF2.1/runs/728690276

**Comment by Underdog-01** [comment]
.. found a better option & posting a new PR.

**Pull request closed without merging**
