### PR TITLE
Update Themes/default/css/index.css

### PR DESCRIPTION
**Pull request by ghost**
Rounding 6px panel gave it too much on the 3, and the shadow of the links is not needed, now counts minimalism

### CODE REVIEW

**Comment by emanuele45** [comment]
I'll leave that to someone with more theme experience than me... :angel: 

Just a note, when you commit your changes, could you please [sign-off](https://github.com/SimpleMachines/SMF2.1#how-to-contribute) your commits? (It's as easy as write `signed-off by nick <email>` in the commit message ;))
Thanks!
Thanks! :D

**Comment by ghost** [comment]
OK. My English is poor. I think it would be better all the way to rewrite without the graphics.
This mass of buttons leads to chaos and to be straight.
I create themes for FluxBB - see nick 123, so I know a bit about design and I know that I do not know everything, but the style is too much distracting from the content elements. Refine the style fits.

**Comment by emanuele45** [comment]
Yups.
No problem about language! ;)

My design skills are mostly inexistent, that's why I prefer not to touch the design and let others with more good tastes put their hands in it. lol

**Comment by ghost** [comment]
Remember style is a shadow, and you have to focus on the content of style ModernUI see in my repo, for something like that I mean, the style is not conspicuous is the background for the content

**Comment by matthew-kerle** [comment]
For the text-shadow, it's using rgba, and the level is 0.4 so hardly there. I'll have to test this out, will do here shortly.

Make sure to sign off your commits like emanuele said, otherwise we can't pull it either way. Furthermore, make sure your line-endings are correct. Your commits are now adding a line to the base of the function.

**Comment by ghost** [comment]
Simplicity is the goal. 

Sorry for my english heh

**Comment by matthew-kerle** [comment]
I went ahead and tried these changes locally, and to be completely honest I think it looks a lot better how it is currently.

I'm going to go ahead and close this Pull Request, please remember in the future to Sign-Off your commits so that they have the potential to be merged if we do decide we want to merge them.

I look forward to seeing future contributions from you :)

**Pull request closed without merging**
