### PR TITLE
Htmlspecialchars

### LINKED ISSUE #330: Convert instances of htmlspecialchars
As per the topic on SMF (http://www.simplemachines.org/community/index.php?topic=497179.0) there are still remaining instances of the raw htmlspecialchars(); without a character set being passed as an additional argument. $smcFunc['htmlspecialchars'](); was designed to take into account character sets and therefore _most_ instances of htmlspecialchars(); should be replaced with $smcFunc['htmlspecialchars']();.

### PR DESCRIPTION
**Pull request by MissAllSunday**
Fixes #330 Convert instances of htmlspecialchars

### CODE REVIEW

**Comment by live627** [comment]
You've been busy!

**Comment by MissAllSunday** [comment]
> You've been working part-time only!
> 
> —
> I corrected that for you :P

**Comment by live627** [comment]
heheheh

But seriously, nice job there. :)

**Comment by deliciousbamboo** [comment]
Good &deity; this PR is horrendous, did u actually look at the code or just use editor to search and destroy? Did you check if that smcfuncy thing was required everywhere instead of a basic htmlspecialchar?

**Comment by Arantor** [comment]
If you bothered to look at our code base - which clearly you didn't - you'd understand that $smcFunc is pretty much needed everywhere instead of the basic form.

**Comment by deliciousbamboo** [comment]
Thanks need to look at that function, True I no look at the code .. but then this PR no work anyway.

**Comment by NanoSector** [comment]
How does this PR not work? Saying "it does not work" doesn't help any of us.

**Comment by live627** [comment]
Case of classic trolling.

**Comment by MissAllSunday** [comment]
mmm, while I tried to do a proper merge conflict resolution, I was unable to do so. So I just did some weird stuff so this PR can be automatically merged again.

**Comment by Arantor** [comment]
Is this all done? Good to merge? At a glance it looks like everything was fixed.

**Comment by MissAllSunday** [comment]
Well I did another round just to check and I wanted to also make un_htmlspecialchars() a lambda but there is (was?) some issues with using static vars inside lambdas so I wasn't sure

**Comment by Arantor** [comment]
I'd leave un_htmlspecialchars alone for the time being but if that's the only thing that's questionable, that seems to me like it should be merged.

**Pull request merged**
