### PR TITLE
fixed the "black background" problem on Firefox

### PR DESCRIPTION
**Pull request by PortaMx**
add a background:#ffff to jquery.sceditor.default.css

Signed-off-by: PortaMx suport@portamx.com

### CODE REVIEW

**Comment by ghost** [comment]
kinda cant replicate this :/

**Comment by Oldiesmann** [comment]
None of us have been able to replicate it. Illori even tested FF22 in XP (on a virtual machine).

**Comment by matthew-kerle** [comment]
Even if this was merged, we'd probably want it to be: background: #fff; instead.

**Comment by PortaMx** [comment]
Well .. after long search, I found the problem .. it was a old css class from a theme was I have long time ago installed on my FF ... (gruble) .. so forgott this.

But .. I found a other problem ..
make a code area with long lines they not break.
If you now scroll the code area, the background for the code stopped on the right edge of the editor range.
This can by simple fixed with change the .code css from display:block to display:inline-block.
Now this will show correctly ...

**Comment by Oldiesmann** [comment]
I'll go ahead and close this one then. We can submit a separate PR for the code issue.

**Pull request closed without merging**
