### PR TITLE
Post Moderation should obey amount of messages per page

### PR DESCRIPTION
**Pull request by NanoSector**
As reported here:
http://www.simplemachines.org/community/index.php?topic=504033.msg3546394#msg3546394

Hereby a fix is provided.

### CODE REVIEW

**Comment by NanoSector** [comment]
Ugh. I hate Git, it has no logic. If added can you please apply the _second commit only_ only in a new commit? Thanks.

**Comment by emanuele45** [comment]
This is not enough.
Changing this you just change the paginations, but not the amount of "rows" showed.
To completely fix the issue, you have also to change the query few lines below the one you changed, in particular:

```
LIMIT ' . $context['start'] . ', 10',
```

to something like:

```
LIMIT ' . $context['start'] . ', ' . !empty($options['messages_per_page']) ? $options['messages_per_page'] : $modSettings['defaultMaxMessages'],
```

even though ti would be much nicer to fix that query to use the the array to pass values...

**Comment by NanoSector** [comment]
This okay? :)

**Comment by emanuele45** [comment]
Much better, yes.

**Comment by NanoSector** [comment]
I'll fix it up for a merge tomorrow.

**Comment by Oldiesmann** [comment]
Yoshi, to remove the unwanted commit from this, switch to the branch and run this command:

```
git revert --no-edit -s 1e1a893
```

**Comment by NanoSector** [comment]
resubmitting.

**Pull request closed without merging**
