### PR TITLE
Various password recovery fixes. (Fixes #2848)

### LINKED ISSUE #2848: Password recovery by email broken when a user has recovery questions.
Recovery by email seems to redirect to the same page without sending an email and the selection choice text header is broken (Not sure how to call it, it used to say something like choose an recovery option).

2015-05-02 20_51_03-authentication reminder

### PR DESCRIPTION
**Pull request by FearThe1337**
- Allow users to recover their account using their secret question if no email is set.
- Default to secret question if the user has no email address yet has recovery questions.
- Allow users to get their password emailed if they have a secret question.

Signed-off-by: FearThe1337 git@fearthe1337.com

### CODE REVIEW

**Comment by illori** [comment]
in what cases would a user not have an email address? in SMF users are required to have an email address.

**Comment by FearThe1337** [comment]
Good point, however in the case it does occur, should we not just allow them to recover using their recovery questions?
It seems weird to just deny recovery, even if there are recovery options available.

Also, I guess it might be perhaps possible from migrated forums?

**Comment by illori** [comment]
IMO even a forum migrated to SMF would have email. 

if it were to fail, maybe going back to the idea of a contact form would be a better idea.

**Comment by FearThe1337** [comment]
Adjusted.

**Comment by illori** [comment]
if this has been resolved, the issue should be closed.

**Pull request merged**
