### PR TITLE
Post buttons 2.0 order, tabindex matches visual order

### PR DESCRIPTION
**Pull request by AngelinaBelle**
Signed-off-by: Angelina Belle angelinabelle1@hotmail.com

### CODE REVIEW

**Comment by live627** [comment]
Oh, it says there's a conflict and thus won't let me merge.

**Comment by AngelinaBelle** [comment]
What is the conflict?
Is it unhappy I changed the order of draft and PM draft?
Any chance you could take a copy of 
https://raw.githubusercontent.com/AngelinaBelle/SMF2.1/20dc258e1b3bb9868cd82b0bc92cc80112ad4593/Themes/default/GenericControls.template.php

**Comment by live627** [comment]
GitHub doesn't say.

**Comment by AngelinaBelle** [comment]
Oh snap!  How did you do that?

**Comment by live627** [comment]
Do what?

**Comment by AngelinaBelle** [comment]
Resolve the conflict.  I got up this morning and did the work again myself.

**Comment by live627** [comment]
I merged your branch into mine, told SourceTree tor resolve the conflicts.

**Pull request merged**
