### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by Oldiesmann**
Various fixes to the docblock comments to make [apiGen](https://github.com/ApiGen/ApiGen) work properly. See http://www.oldiesmann.us/smfdocs/ for an example of the output and individual commits for more info.

This is still a WIP and more commits might be coming as I have more time to play with ApiGen

### CODE REVIEW

**Comment by jdarwood007** [comment]
@uses is supposed to be valid: https://docs.phpdoc.org/references/phpdoc/tags/uses.html

**Comment by Oldiesmann** [comment]
@jdarwood007 It is valid - just not the way we're using it.

**Comment by jdarwood007** [comment]
Can we fix it properly by referencing things the right way then?

**Comment by Oldiesmann** [comment]
> Can we fix it properly by referencing things the right way then?

Completely forgot about this until now. I'll play around with it again soon when I have time and see what I can do.

**Comment by Oldiesmann** [comment]
Closing this one out as it's outdated. A lot has changed in the past year. Will resubmit a newer one when I have time.

**Comment by live627** [comment]
Well, most of your changes were still valid.

**Pull request closed without merging**
