### PR TITLE
Sets more pleasant CSS padding values on editor's textarea

### PR DESCRIPTION
**Pull request by Sesquipedalian**

### CODE REVIEW

**Review by XinYenFon — APPROVED** [review]
While this is a small change, its like a cold water after a very hot day.

**Comment by frandominguezl** [comment]
Talking about the editor, the Smiley's row looks kinda misplaced, maybe you can add something to this PR to fix that? ^^

**Comment by Sesquipedalian** [comment]
> Talking about the editor, the Smiley's row looks kinda misplaced, maybe you can add something to this PR to fix that? ^^

Done.

**Comment by Sesquipedalian** [comment]
I've also switched the font in the textarea to monospace in order to give the user a clear visual indication of when they are working in source mode rather than WYSIWYG.

**Review by frandominguezl — APPROVED** [review]

**Pull request merged**
