### PR TITLE
Duplicated class .generic_icons.warning_watch

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Signed-off-by: Diego Andrés diegoandres_cortes@outlook.com

### CODE REVIEW

**Comment by illori** [comment]
but the commit was not signed off... just the PR. next time sign off the commit.

**Comment by live627** [comment]
it was. I checked before merging.

**Comment by illori** [comment]
strange, it looked like it was not signed off when i looked at it before.

**Comment by XinYenFon** [comment]
I already fixed that with my commit on #2139 
https://github.com/SimpleMachines/SMF2.1/pull/2139/files#diff-c5ef6bd5b5f64bcfc3d4647ac7c33792L1907

**Pull request merged**
