### PR TITLE
Error when modifying a post

### PR DESCRIPTION
**Pull request by ThomasFok**
When modifying a post, I got this error.

Only variables should be passed by reference
Sources/Drafts.php 
Line:468

The argument of censorText() is a reference. It causes error when the return value of a function is passed to it directly.

### CODE REVIEW

**Comment by XinYenFon** [comment]
You have to sign-off each commit, otherwise we can't accept it.

**Comment by ThomasFok** [comment]
Signed-off-by: Thomas Fok <thomas@melody-soft.com>

**Comment by Oldiesmann** [comment]
You have to sign off on the commits themselves, not the PR

**Comment by live627** [comment]
Sign added to squashed commit.

**Pull request merged**
