### PR TITLE
fix bounds check for page index

### LINKED ISSUE #7522: Pagination error
while cleaning up some spam, I noticed that some page numbers seemed wrong

see where it says `1.95` instead of  `1`

https://www.simplemachines.org/community/index.php?topic=582201.40

Seems to me that this only happens when manually fiddling with the numbers.

Marking as `Serious bug` with **high priority** because it should load the last page of posts, not be empty.

### PR DESCRIPTION
**Pull request by live627**
- fix #7522

### CODE REVIEW

**Comment by jdarwood007** [comment]
It might also make sense to force cast this to an int.

**Comment by live627** [comment]
cast `$start`?

**Comment by jdarwood007** [comment]
Correct.  Just to ensure it should always be a int and not a decimal.

**Review by sbulen — APPROVED** [review]
LGTM.

Note recasting to int isn't necessary, because php mod math casts to int.

I tested & confirmed it fixes my page decimal issue as well (#7389 ).

**Pull request merged**
