### PR TITLE
Use the correct icon for profile link in pm's

### LINKED ISSUE #7425: Wrong profile_sm icon in PMs
#### Description
This was reported on the Bug Reports board:
https://www.simplemachines.org/community/index.php?topic=581800.0

The profile_sm icon is a bit too small to the rest of the icons when viewing PMs:

### Environment
- Version: 2.1.1 default theme

main_icons profile_sm

### PR DESCRIPTION
**Pull request by DiegoAndresCortes**
Fixes #7425

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
Tested disabling the bbc for the signatures only, seems that it now works as expected.

Screenshot_11
Screenshot_12

**Comment by DiegoAndresCortes** [comment]
And enabled:

Screenshot_14
Screenshot_13

**Review by jdarwood007 — APPROVED** [review]

**Comment by sbulen** [comment]
Ready to merge?

**Comment by DiegoAndresCortes** [comment]
Yup all recent three can be merged 👍

**Pull request merged**
