### PR TITLE
Handles unsupported strftime formats more robustly

### PR DESCRIPTION
**Pull request by Sesquipedalian**
This seems to work well on my *nix systems. I don't have Windows, though, so if someone (maybe @albertlast?) could test it there, that'd be good.

### CODE REVIEW

**Comment by jdarwood007** [comment]
Since this doesn't even need to be done on every page load.  Could this be cached up for a day?

**Comment by Sesquipedalian** [comment]
> Since this doesn't even need to be done on every page load. Could this be cached up for a day?

Good idea.

**Comment by albertlast** [comment]
here some time about Page created:
with cache 1sec 
without cache 1.4 sec

left cache right without
grafik


The existing version (with replace otherwise doesn't work for me): 0,37 sec
grafik

in my eyes is the using of caching here realy wrong.

**Comment by Sesquipedalian** [comment]
What do your tests show now, @albertlast?

**Comment by albertlast** [comment]
Looks perfect from runtime:
left your version right my old
grafik
And i can't see any bad behavior of smf.

**Comment by Sesquipedalian** [comment]
Excellent.

**Pull request merged**
