### PR TITLE
Supplies expected keys in 2nd arg of integrate_load_permissions hook

### LINKED ISSUE #8007: [3.0]: Actions\Admin\Permissions::$permission_groups
### Basic Information

This is referencing the permissions hook issue originally brought up by @dragomano here:

https://github.com/SimpleMachines/SMF/pull/7931#issuecomment-1886241722

Possibly caused by missing 'membergroup' key
`	public static array $permission_groups `

I'm assuming that previously there was a 'membergroup' key present...

### Steps to reproduce

1.
2.

### Expected result

_No response_

### Actual result

_No response_

### Version/Git revision

Most recent revision

### Database Engine

MySQL

### Database Version

_No response_

### PHP Version

_No response_

### Logs

```shell
Listed in linked reply
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #8007

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
@dragomano, please verify that this fixes the issue.

**Comment by dragomano** [comment]
You can't forget about self::$permission_groups['membergroup'] either:
```php
self::$permission_groups['membergroup'] = &self::$permission_groups['global'];
$permissions_by_scope['membergroup'] = &$permissions_by_scope['global'];
```

However, I'm already just using [such a condition](https://github.com/dragomano/Light-Portal/blob/9653a898d3af1516a6eee4831eee951724ba3866/src/Sources/LightPortal/Integration.php#L305) in my code:
```php
$scope = isset($permissionList['global']) ? 'global' : 'membergroup';
```

Convenient, and no need to copy arrays :)

**Review by dragomano — APPROVED** [review]

**Comment by Sesquipedalian** [comment]
> You can't forget about self::$permission_groups['membergroup'] either:
> 
> ```
> self::$permission_groups['membergroup'] = &self::$permission_groups['global'];
> $permissions_by_scope['membergroup'] = &$permissions_by_scope['global'];
> ```

Oops! Thanks for that.

> However, I'm already just using [such a condition](https://github.com/dragomano/Light-Portal/blob/9653a898d3af1516a6eee4831eee951724ba3866/src/Sources/LightPortal/Integration.php#L305) in my code:
> 
> ```
> $scope = isset($permissionList['global']) ? 'global' : 'membergroup';
> ```
> 
> Convenient, and no need to copy arrays :)

It's just a reference, not a copy, so I'm not worried about it.

FYI, I suggest that you update your code to use the new integrate_permissions_list hook instead. It is the recommended way to work with permissions in SMF 3.0. The integrate_load_permissions, integrate_load_illegal_permissions, and integrate_load_illegal_guest_permissions hooks are now deprecated and will be removed in a future version.

**Comment by dragomano** [comment]
I've seen the new hook, but it will only work in 3.0, plus show me an example of how to use it to do the same thing I'm doing now.

**Comment by Sesquipedalian** [comment]
> show me an example of how to use it to do the same thing I'm doing now.

Obviously I have not tested the following code, but here is the requested example.

Find:
```
	public function loadIllegalGuestPermissions(): void
	{
		Utils::$context['non_guest_permissions'] = array_merge(
			Utils::$context['non_guest_permissions'],
			[
				'light_portal_manage_pages_own',
				'light_portal_manage_pages_any',
				'light_portal_manage_pages',
				'light_portal_approve_pages',
			]
		);
	}

	public function loadPermissions(array &$permissionGroups, array &$permissionList, array &$leftPermissionGroups): void
	{
		Lang::$txt['permissiongroup_light_portal'] = LP_NAME;

		$scope = isset($permissionList['global']) ? 'global' : 'membergroup';

		$permissionList[$scope]['light_portal_view']          = [false, 'light_portal'];
		$permissionList[$scope]['light_portal_manage_pages']  = [true, 'light_portal'];
		$permissionList[$scope]['light_portal_approve_pages'] = [false, 'light_portal'];

		$permissionGroups[$scope][] = $leftPermissionGroups[] = 'light_portal';
	}
```

Replace:
```
	public function permissionsList(array $permissions): void
	{
		Lang::$txt['permissiongroup_light_portal'] = LP_NAME;

		$permissions['light_portal_view'] = [
			'view_group' => 'light_portal',
			'scope' => 'global',
		];

		$permissions['light_portal_manage_pages_own'] = [
			'generic_name' => 'light_portal_manage_pages',
			'own_any' => 'own',
			'view_group' => 'light_portal',
			'scope' => 'global',
			'never_guests' => true,
		];

		$permissions['light_portal_manage_pages_any'] = [
			'generic_name' => 'light_portal_manage_pages',
			'own_any' => 'any',
			'view_group' => 'light_portal',
			'scope' => 'global',
			'never_guests' => true,
		];

		$permissions['light_portal_approve_pages'] = [
			'view_group' => 'light_portal',
			'scope' => 'global',
			'never_guests' => true,
		];
	}
```

Note that this example only shows how to reproduce what you are doing now. However, by using integrate_permissions_list, you could also get access to other functionality that the existing hooks cannot provide. For example, you could set a `group_level` for your custom permissions in order to have them included in the predefined permission profiles. The full list of possible options is available here:

https://github.com/SimpleMachines/SMF/blob/655fcfe3272162bd75c10cdbb5cb7829acfe86dd/Sources/Actions/Admin/Permissions.php#L188-L233

**Comment by dragomano** [comment]
Already interesting, but still lacks the functionality I need. I reproduced your example and this is what I got:

sshot-10

**Comment by Sesquipedalian** [comment]
```
public function permissionsList(array $permissions): void
{
	Lang::$txt['permissiongroup_light_portal'] = LP_NAME;

	\SMF\Actions\Admin\Permissions::$permission_groups['global'][] = 'light_portal';
	\SMF\Actions\Admin\Permissions::$left_permission_groups[] = 'light_portal';

	$permissions['light_portal_view'] = [
		'view_group' => 'light_portal',
		'scope' => 'global',
	];

	$permissions['light_portal_manage_pages_own'] = [
		'generic_name' => 'light_portal_manage_pages',
		'own_any' => 'own',
		'view_group' => 'light_portal',
		'scope' => 'global',
		'never_guests' => true,
	];

	$permissions['light_portal_manage_pages_any'] = [
		'generic_name' => 'light_portal_manage_pages',
		'own_any' => 'any',
		'view_group' => 'light_portal',
		'scope' => 'global',
		'never_guests' => true,
	];

	$permissions['light_portal_approve_pages'] = [
		'view_group' => 'light_portal',
		'scope' => 'global',
		'never_guests' => true,
	];
}
```

**Comment by dragomano** [comment]
Great, now it works as it should. However, if this hook is not added in 2.1.5, we will still have to wait for 3.0 to be released before using it. And there's a lot more code here than in those 2 previous hooks.

**Comment by Sesquipedalian** [comment]
The new hook will only appear in 3.0. The old hooks will remain available in 3.0, but they will be removed in a future version.

You know your own project better than I do, of course, so make your decisions as you see fit. 🙂

**Comment by dragomano** [comment]
I noticed one problem - in the settings, when permissions are specified in `$config_vars` via ['permissions', 'bla-bla-bla'], the `'never_guests' => true` property does not work.

sshot-6

**Comment by dragomano** [comment]
The same behavior with calendar permissions:

```php
'calendar_edit_own' => [
	'generic_name' => 'calendar_edit',
	'own_any' => 'own',
	'view_group' => 'calendar',
	'scope' => 'global',
	'group_level' => self::GROUP_LEVEL_MODERATOR,
	'never_guests' => true,
],
'calendar_edit_any' => [
	'generic_name' => 'calendar_edit',
	'own_any' => 'any',
	'view_group' => 'calendar',
	'scope' => 'global',
	'group_level' => self::GROUP_LEVEL_MAINTENANCE,
	'never_guests' => true,
],
```

sshot-10

If these permissions are inherently prohibited for assignment to guests, then why is the "Guests" item isn't hidden?

**Comment by Sesquipedalian** [comment]
That would be a bug.

**Pull request merged**
