### PR TITLE
added mem.real_name to group by

### LINKED ISSUE #7508: Can't sort Sent PM's by User
#### Description
https://www.simplemachines.org/community/index.php?topic=582802.0

### Steps to reproduce
1.  Go to the pms > Sent items
2. Attempt to sort by user

### PR DESCRIPTION
**Pull request by albertlast**
extraced the group by logic in a own var,
with the hope that it better is to read,
instead of compress more logic into this inline.

fixes: #7508 

tested in pg

### CODE REVIEW

**Comment by live627** [comment]
What are your thoughts on changing the sort to `pm.from_name` and leaving the `GROUP BY` alone? This way I think it can sort guests, too.

**Comment by albertlast** [comment]
dunno from ux side,
on programm side we could drop the join in this case, i guess.
so would be faster.

**Comment by live627** [comment]
sounds  good

**Comment by sbulen** [comment]
I have tested this & it works.  

I actually don't think the idea of using pm.from_name will work, because depending on whether you're looking at the inbox or the sent folder, the join to mem is different...  It's not the from_name when looking at the sent folder, which is what is failing here.

Make sense?

**Review by sbulen — APPROVED** [review]
I think this is good to go.

**Pull request merged**
