### PR TITLE
Adds ability to skip DB change substeps in the upgrader

### PR DESCRIPTION
**Pull request by Sesquipedalian**
If a PHP code block within one of the upgrade*.sql files sets $upcontext['skipStep'] to true, then the rest of the substeps within the current main step of the database changes will be skipped. Once the upgrader reaches the next main step (meaning, a line formatted like `--- Adding new settings...`), $upcontext['skipStep'] will be set back to false, and the upgrader will continue normally. This is especially useful for conducting sanity checks before applying changes.

### CODE REVIEW

**Comment by albertlast** [comment]
well it look like some bugs exists,
on the one hand i think you need define the $upcontext in eval call to be global too,
like $smcfunc etc.
and for some reason the $upcontext['skipStep'] value get lost between the substeps.

**Comment by Sesquipedalian** [comment]
Thanks. I'll try to take a look tonight. In the meantime, can I get you to add $upcontext to the eval() in your local test environment and then test with the "Output extra debugging information" setting both on and off?

**Comment by albertlast** [comment]
I added already upcontext to the globals of eval,
but like i said the information get lost somewhere than after this.

**Comment by Sesquipedalian** [comment]
Try now, @albertlast.

**Pull request merged**
