### PR TITLE
Avoids slow query looking up gender statistics

### LINKED ISSUE #6954: Slow stats query
#### Description
```
            SELECT COUNT(*) AS total_members, gender
            FROM (
               SELECT mem.id_member, COALESCE(t.value, 'None') AS gender
               FROM smf_members AS mem
               LEFT JOIN smf_themes AS t ON (
                  mem.id_member = t.id_member AND
                  t.variable = 'cust_gender' AND
                  t.id_theme = 1
                  )
               WHERE is_activated = 1
            ) AS a
            GROUP BY gender
         ORDER BY null
   in /Sources/Stats.php line 192, which took 10.86450696 seconds at 0.08292794 into request.
```

id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | mem |   | ref | is_activated | is_activated | 1 | const | 278193 | 100.00 | Using index; Using temporary
1 | SIMPLE | t |   | eq_ref | PRIMARY,ID_MEMBER | PRIMARY | 96 | const,forum.mem.id_member,const | 1 | 100.00 | Using where

### LINKED ISSUE #6955: Gender stats labels
#### Description
This is happening on sm website

Gender stats:None: 430266
Male: 11011
Female: 1418
{gender_2}: 5
{gender_1}: 23

### LINKED ISSUE #6977: Gender default has spaces
#### Description
From upgrade_2-1_mysql.sql
```
('cust_gender', '{gender}', '{gender_desc}', 'radio', 255, '{gender_0}, {gender_1}, {gender_2}', 5, 'nohtml', 1, 1, 0, 'forumprofile', 0, 1, 0, 0, 'None', '<span class=" main_icons gender_{KEY}" title="{INPUT}"></span>', 1);
```

Should not have spaces between the options
```
('cust_gender', '{gender}', '{gender_desc}', 'radio', 255, '{gender_0},{gender_1},{gender_2}', 5, 'nohtml', 1, 1, 0, 'forumprofile', 0, 1, 0, 0, 'None', '<span class=" main_icons gender_{KEY}" title="{INPUT}"></span>', 1);
```

Any spaces are treated as apart of the value.
The install and postgresql have the same issues.

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #6954
Using INNER JOIN instead of LEFT JOIN means we only retrive rows for members who have selected a gender. Then we just add the number of members who did not select a gender at all to the default gender's total.

Fixes #6955
Fixes #6977

### CODE REVIEW

**Comment by jdarwood007** [comment]
Confirmed works.

**Review by jdarwood007 — APPROVED** [review]

**Comment by Sesquipedalian** [comment]
Converted to draft because I plan to add a fix for #6977 and a few other minor issues I've found regarding gender strings.

**Comment by live627** [comment]
Du you think the outer query could be       dropped now that the  `LEFT JOIN` has been changed to `INNER JOIN`?

				SELECT COUNT(*) AS total_members, value AS gender
				FROM {db_prefix}members AS mem
					JOIN {db_prefix}themes AS t ON (
						t.id_member = mem.id_member
						AND t.variable = {string:gender_var}
						AND t.id_theme = {int:default_theme}
					) 
				WHERE is_activated = {int:is_activated}
				GROUP BY value

**Comment by Sesquipedalian** [comment]
> Du you think the outer query could be dropped now that the `LEFT JOIN` has been changed to `INNER JOIN`?
> 
> ```
> 			SELECT COUNT(*) AS total_members, value AS gender
> 			FROM {db_prefix}members AS mem
> 				JOIN {db_prefix}themes AS t ON (
> 					t.id_member = mem.id_member
> 					AND t.variable = {string:gender_var}
> 					AND t.id_theme = {int:default_theme}
> 				) 
> 			WHERE is_activated = {int:is_activated}
> 			GROUP BY value
> ```

Why yes, we can. Good call, @live627.

**Review by jdarwood007 — APPROVED** [review]
Sorry, I looked at these last night.  They look good.
I implanted the query already on sm website, but nothing else.

**Pull request merged**
