### PR TITLE
Fixes #3723

### LINKED ISSUE #3723: Quick edit post
**message**

Quick edit -> save

### PR DESCRIPTION
**Pull request by frandominguezl**
Thanks to albertlast for the fix

### CODE REVIEW

**Comment by ThomasFok** [comment]
Should all `php_to8bit()` function call be removed?

**Comment by albertlast** [comment]
The problem with php_to8bit() is that we don't know,
what there task was.
So maybe be some alternative code is needed to do this work what the php_to8bit() do before.

**Comment by Oldiesmann** [comment]
The function is supposed to "convert a string to an 8 bit representation (like in PHP)" based on the comment right before it's defined in script.js. I have no idea what that means specifically or why that's even necessary.

**Comment by albertlast** [comment]
d3vcho try this with chines symbole and keep working

**Comment by frandominguezl** [comment]
@Oldiesmann This is ready to merge. Travis fails because instead of "Signed-off-by" I wrote "Signed-off by". Should I push a fix to that?

**Comment by albertlast** [comment]
when i see correctly you do the end of line thing again

**Comment by frandominguezl** [comment]
@albertlast that's not the error Travis is throwing

**Comment by jdarwood007** [comment]
FYI, You don't need to specify manually the signed off by in your message.  Most UI clients have a checkbox or option called "Sign off" and from the command line you add -s or --signoff

**Pull request closed without merging**
