### PR TITLE
Quickbuttons to Generic Icons

### LINKED ISSUE #2628: language icon in admin menu changed
the icon was this

and now is a different icon. i think this one did not end up in the latest sprite.

@antes can you look into this?

### PR DESCRIPTION
**Pull request by XinYenFon**
needs testing ! 

fixes #2628

### CODE REVIEW

**Comment by live627** [comment]
This totally borked all the icons.

**Comment by XinYenFon** [comment]
uh how? it shouldn't :P

**Comment by live627** [comment]
derp... facepalm

I failed at the most basic task and got pwned by  the cache

**Comment by live627** [comment]
Seems like everything's in order.

**Pull request merged**
