### PR TITLE
Revert "Fix missing $db_persist global, fixes #4516"

### LINKED ISSUE #4516: Persistent connection issue (2.0 & 2.1)
This was reported by the forum user nend earlier, but I think it's important enough to put here.   

$db_persist is not declared as a global in smf_db_query, and it is needed to support persistent connections:
```
		// Fall back to the regular username and password if need be
		if (!$db_connection)
		{
			if (empty($db_persist))
				$db_connection = @mysqli_connect($db_server, $db_user, $db_passwd);
			else
				$db_connection = @mysqli_connect('p:' . $db_server, $db_user, $db_passwd);
		}
```

In a related issue, sessionWrite ends up creating new db connections using this logic, since the connection seems to be getting closed before the session is written.  Persistent connections may help reduce the # of db connections.  (I have confirmed this in 2.0, I believe it will be an issue in 2.1 as well.)

### PR DESCRIPTION
**Pull request by colinschoen**
Reverts SimpleMachines/SMF2.1#4517

### CODE REVIEW

**Comment by sbulen** [comment]
Something about needing to work for DBs not described in settings.php.    Also not liking the reconnect logic.

Apparently "working" is insufficient these days.

**Comment by colinschoen** [comment]
@Sesquipedalian Discussion here: #4517

**Comment by Sesquipedalian** [comment]
I meant, why was 43ad686 (#4515) reverted? It doesn't have anything to do with the database connection issue.

**Comment by colinschoen** [comment]
Weird, I don't know why that was added to this history, but if you actually look at the files changed it was not reverted. Here is the relevant file and line at `release-2.1` HEAD: 

https://github.com/SimpleMachines/SMF2.1/blob/ac85d8c0fb1b070aaabfe622cf02839682c7eafb/Sources/Subs.php#L2264

**Comment by Sesquipedalian** [comment]
That is odd. But at any rate, that answers my question.

**Pull request merged**
