### PR TITLE
Change colum alter api of nullable

### PR DESCRIPTION
**Pull request by albertlast**
By looking at this code: 
```
$column = array(
	'name' => 'join_reason',
	'type' => 'tinytext',
);

$smcFunc['db_add_column']('{db_prefix}members', $column);
```
https://www.simplemachines.org/community/index.php?topic=568346.msg4022474#msg4022474

i came to the result that the mod author did everything right,
since in mysql and pg is the default behavior that  columns are nullable by default: https://www.db-fiddle.com/f/hATtEpH78Qw3eWsA3DR3JT/0

So when the author did nothing wrong,
than the db api of smf do it wrong.

The behavior is that every column is by creation not nullable AND
got no default value.
On the other hand in postgres is the default behavior that every column is nullable,
because of a coding error.

Based on this i changed the api,
first i changed 'null' to 'not_null' because this is the behavior of sql,
you don't say when you want null you say when you want not_null.

Secondly i changed the pg code in a away that it's behave now in the same way like mysql.

By afraid that the upgrade.php and maybe some mods really use 'null' i added the information back,
but without mention this in the function api.

Would be nice if this change get also into 2.0.x

### CODE REVIEW

**Comment by MissAllSunday** [comment]
I'm kinda worry about this change, specially for backward compatibility.

**Comment by albertlast** [comment]
Can you be more precisly?

**Comment by MissAllSunday** [comment]
Thats the thing, I can't. It's just a gut feeling about this change being too drastic.

**Comment by albertlast** [comment]
Because the mod author never want a not null without default value,
i see not the problem.

**Comment by MissAllSunday** [comment]
Let's tag it for final and see its behavior.

**Review by MissAllSunday — APPROVED** [review]

**Pull request merged**
