### PR TITLE
Update Recent.php as per http://www.simplemachines.org/community/index.p...

### PR DESCRIPTION
**Pull request by live627**
...hp?topic=533183.msg3794178#msg3794178

### CODE REVIEW

**Comment by bperry921** [comment]
Sorry, dealing with a great many things myself, it can wait?

Too damn bad if not. I am totally alone in this mess. SORT OF!! My dog died
a couple weeks ago...

Best Regards,
Bob 

Proprietor of
Web Presence Consulting (WPC)
@ http://www.rjventure.com http://www.rjventure.com/ 

At the foot of the Great Smoky Mountains in Knoxville, TN

(man I love MS Outlook as my email client, you? It makes MANAGING your
emails soo much easier and less time consuming)

-----Original Message-----

**Comment by bperry921** [comment]
I am a former US Marine, if that helpsya...

Best Regards,
Bob 

Proprietor of
Web Presence Consulting (WPC)
@ http://www.rjventure.com http://www.rjventure.com/ 

At the foot of the Great Smoky Mountains in Knoxville, TN

(man I love MS Outlook as my email client, you? It makes MANAGING your
emails soo much easier and less time consuming)

-----Original Message-----

**Comment by live627** [comment]
Um , whaaaat?  :o

**Comment by bperry921** [comment]
umm, ok. Seriously, OK? 

Best Regards,
Bob 

Proprietor of
Web Presence Consulting (WPC)
@ http://www.rjventure.com http://www.rjventure.com/ 

At the foot of the Great Smoky Mountains in Knoxville, TN

(man I love MS Outlook as my email client, you? It makes MANAGING your
emails soo much easier and less time consuming)

-----Original Message-----

**Pull request merged**
