### PR TITLE
BBC Button Status (sceditor)

### PR DESCRIPTION
**Pull request by mcblaber**
Addressing Issue #787

Thanks emanuele

### CODE REVIEW

**Comment by Oldiesmann** [comment]
You need to sign-off your commit. You should be able to do this for your previous commit by issuing the command `git commit --amend -s` from the shell/command line.

**Comment by NanoSector** [comment]
Hello mcblaber, can you sign off your commit please so we can add it in? :)

**Comment by mcblaber** [comment]
I'm such a newb here. Are there specific instructions on how to sign-off the commit? Couldn't find anything in the readme about doing this, I'm in terminal on OSX and I installed the proper git packages. Now what? 0.0

Keep on reaching this message:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by emanuele45** [comment]
Two ways:
- `git commit -sm "Commit message"` (or other variants)
- In the commit message add a line with `Signed-off-by: something <something@something.smg>`
  Anyway even graphical UI should have a way to sign commits... somewhere.

> Keep on reaching this message:
> fatal: Not a git repository (or any of the parent directories): .git

You are probably not in the directory of the repository.

**Comment by Arantor** [comment]
Being dealt with by #951

**Pull request closed without merging**
