### PR TITLE
Settings Blanking Fix

### LINKED ISSUE #5943: Upgrade broken in new SMF
#### Description
Get main branch set-up
Then apply : https://github.com/SimpleMachines/SMF2.1/pull/5940

Produces two errors :

1. Undefined index: utf8 in /home/lolupdat/public_html/forum/Sources/Subs-Admin.php on line 794

2. Also apparently the UpdateSettingsFile() is messing up the settings.php

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mysql
- Database Version:
- PHP Version: 7.4

### Additional information/references

### PR DESCRIPTION
**Pull request by jdarwood007**
This may fix: #5943, #5939, #5938 and #5934

### CODE REVIEW

**Comment by XinYenFon** [comment]
Applied both this & #5949 but upgrade.php now redirecting me back to login (step1).

**Comment by sbulen** [comment]
I've been looking at it when I have time...

I have solutions to a couple of the problems:
https://github.com/SimpleMachines/SMF2.1/pull/5951

**Comment by sbulen** [comment]
You know - all 3 PRs seem to work on the installer...  #5949 #5950 #5951 .  Teamwork!

Biggest problem I see is lots of duplication of _comments_ in the settings file itself:
image

**Comment by mobasuite** [comment]
Applied the 3 patches above described by sbulen.

Here's my Log :

`[11-Jan-2020 18:18:15 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 56
[11-Jan-2020 18:18:15 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 60
[11-Jan-2020 18:18:15 UTC] PHP Notice:  Undefined variable: sourcedir in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:15 UTC] PHP Warning:  require_once(/QueryString.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:15 UTC] PHP Fatal error:  require_once(): Failed opening required '/QueryString.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:18 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 56
[11-Jan-2020 18:18:18 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 60
[11-Jan-2020 18:18:18 UTC] PHP Notice:  Undefined variable: sourcedir in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:18 UTC] PHP Warning:  require_once(/QueryString.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:18 UTC] PHP Fatal error:  require_once(): Failed opening required '/QueryString.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:22 UTC] PHP Warning:  require_once(/home/lolupdat/public_html/forum/Settings.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 46
[11-Jan-2020 18:18:22 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/lolupdat/public_html/forum/Settings.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 46
[11-Jan-2020 18:18:23 UTC] PHP Warning:  require_once(/home/lolupdat/public_html/forum/Settings.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 46
[11-Jan-2020 18:18:23 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/lolupdat/public_html/forum/Settings.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 46
[11-Jan-2020 18:18:38 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 56
[11-Jan-2020 18:18:38 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 60
[11-Jan-2020 18:18:38 UTC] PHP Notice:  Undefined variable: sourcedir in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:38 UTC] PHP Warning:  require_once(/QueryString.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:38 UTC] PHP Fatal error:  require_once(): Failed opening required '/QueryString.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:40 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 56
[11-Jan-2020 18:18:40 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 60
[11-Jan-2020 18:18:40 UTC] PHP Notice:  Undefined variable: sourcedir in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:40 UTC] PHP Warning:  require_once(/QueryString.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:40 UTC] PHP Fatal error:  require_once(): Failed opening required '/QueryString.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:40 UTC] PHP Warning:  require_once(/Subs-Auth.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/upgrade.php on line 652
[11-Jan-2020 18:18:40 UTC] PHP Fatal error:  require_once(): Failed opening required '/Subs-Auth.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/upgrade.php on line 652
[11-Jan-2020 18:18:43 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 56
[11-Jan-2020 18:18:43 UTC] PHP Notice:  Undefined variable: boarddir in /home/lolupdat/public_html/forum/index.php on line 60
[11-Jan-2020 18:18:43 UTC] PHP Notice:  Undefined variable: sourcedir in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:43 UTC] PHP Warning:  require_once(/QueryString.php): failed to open stream: No such file or directory in /home/lolupdat/public_html/forum/index.php on line 66
[11-Jan-2020 18:18:43 UTC] PHP Fatal error:  require_once(): Failed opening required '/QueryString.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/lolupdat/public_html/forum/index.php on line 66
`

Also its still truncating the Settings.php file

**Comment by sbulen** [comment]
What were you attempting - an upgrade, install or???

**Comment by mobasuite** [comment]
> What were you attempting - an upgrade, install or???

upgrade

**Comment by sbulen** [comment]
I have been focusing on the installer.  I'll look at the upgrader next.

For the moment, I'm focusing on getting it to run, & not really looking at duplicate comments, etc...

**Comment by mobasuite** [comment]
yeah, at least the forum can run (without doing the upgrade), so that's cool.

Will still do the upgrade later-on,

**Comment by sbulen** [comment]
I also have this weird fragment in the middle of the file check after installation:
image

**Comment by sbulen** [comment]
Yep, the upgrader still has a bunch of different issues...
As pointed out above, you get kicked back to the login screen.  The settings file is mangled.  
I suspect there is an issue adding the $upgradeData to settings.php.

**Comment by jdarwood007** [comment]
@sbulen I was seeing duplication of comments as well.
I noticed while working on this PR that sometimes the substitutions where not working and this PR fixed that.  So I wonder if it was just a failed substitution causing that and we need a clean Settings.php to correctly test this?  Considering this was merged in-between RC releases, we don't need to support a dirty upgrade caused by the regression.

**Comment by sbulen** [comment]
I restore before tests, trying to emulate real upgrades.  So it is definitely still proliferating comments.  

I have some free time Sunday & will peek at the upgrader.  

Testing this, I am not sure what we should really be doing with the comments.  What if an admin wrote some helpful comments to document a setting?  Will they be lost?  

Note the comments look very different in 1.0, 1.1, 2.0 & 2.1...   I think this is confusing this logic.

**Review by Sesquipedalian — COMMENTED** [review]
These changes are syntactically invalid. They appeared to work in the test case only because they were breaking the regex entirely. But don't worry about it. I'll be submitting a fix for this shortly.

**Pull request closed without merging**
