### PR TITLE
Fix news queries fixing #6198

### LINKED ISSUE #6198: Database error during run of cron.php
#### Description
dberror

### Steps to reproduce
1. Open website on browser and wait for cron.php to be called by the javascript.

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest
- Database Type: mysql
- Database Version: Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
- PHP Version: PHP 7.4.8

### Additional information/references
My forum was converted from 1.1.21 to 2.1 latest (github version).

I'm unsure if the upgrade script didn't rename a column correctly or what.  Either way I know it's a bug that needs fixed since my 1.1.21 forum worked fine now has an error every 5 minutes or so from cron.php.

Can someone let me know if this is a common bug that hasn't been fixed?

### PR DESCRIPTION
**Pull request by albertlast**
Do two things,
first fixes #6198
secondly re order the on statement to this schema  (base_table.col_name = join_table.col_name)
this standard in the sql world...

### CODE REVIEW

**Comment by live627** [comment]
>  this standard in the sql world...

Link?

**Comment by albertlast** [comment]
https://www.postgresql.org/docs/12/tutorial-join.html
https://dev.mysql.com/doc/refman/5.7/en/join.html
https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/intro/src/tpc/db2z_innerjoin.html
https://docs.microsoft.com/en-us/sql/relational-databases/performance/joins?view=sql-server-ver15

Do you need more?

**Comment by MissAllSunday** [comment]
Agree on the schema change but I rather prefer to see it on another PR and leave this one for the fix only.

**Comment by albertlast** [comment]
i split the both changes.

**Review by live627 — APPROVED** [review]

**Pull request merged**
