### PR TITLE
Clean up the CSS a bit, removing prefixed entries where not needed.

### PR DESCRIPTION
**Pull request by NanoSector**
Also added an IE compatibility stylesheet. A different mechanic is needed to actually load it.

Signed-off-by: Yoshi2889 rick.2889@gmail.com

### CODE REVIEW

**Comment by XinYenFon** [comment]
No point to do this. IE8/9 doesn't support linear-gradient. Also you are just removing the -ms- prefix from one place and create new file to use it. http://caniuse.com/css-gradients

**Comment by XinYenFon** [comment]
Actually it would be awesome if you add white (#FFFFFF) fallback to those gradients

**Comment by Oldiesmann** [comment]
Looking at the "icanuse" site, it looks like dropping the -webkit-linear-gradient declarations would actually be a bad idea, as the following still need it:

Safari on iOS 6.1 or earlier (probably not many iOS 6.1 devices still in use, but you never know)
Default Android browser except on Android 4.4 (this covers all but a small percentage of devices)
Opera Mobile (latest version)
Default BlackBerry browser (as of BB 10 at least)

**Comment by XinYenFon** [comment]
probably my changes created the conflict. :/ #2054

**Pull request closed without merging**
