### PR TITLE
Small improve in ScheduledTasks

### PR DESCRIPTION
**Pull request by albertlast**
get sql align (removed inner)
replace delete from with truncate
removed old db checks

### CODE REVIEW

**Comment by jdarwood007** [comment]
What would the difference between JOIN and INNER JOIN be here?

**Comment by albertlast** [comment]
it's the same -> no different
one of the reason why i said this are small changes.

**Comment by jdarwood007** [comment]
Well then to keep consistent I think we should either keep everything with INNER JOIN or remove INNER from all queries everywhere.

I would think that specifying INNER makes it clearer what type of join is being performed, even if we know the default is INNER.

**Comment by albertlast** [comment]
i hat this discussion...
"inner join" is redundancy,
like "dead corpse", it's clear that the corpse is dead we don't need add "dead" in front of this.

And when i take you logic for different topic like "if" which you can write in "if(){} else {}" or "( ? : )",
would you now start to write every short version to the long version (= if(){} )?

**Comment by jdarwood007** [comment]
I was more saying we should do it consistently rather than just to ScheduledTasks.php.  We should correct all queries to follow this.

**Comment by Sesquipedalian** [comment]
LGTM. Do you want me to merge this now, @albertlast, or are you planning to replace `INNER JOIN` with just `JOIN` everywhere?

**Comment by albertlast** [comment]
the inner join stuff i only replace when i touched the file,
when you like to keep every where the same i could try to make a own pr with the target to change this in whole project.

**Comment by Sesquipedalian** [comment]
Okay. In that case, I'll go ahead and merge this now.

**Pull request merged**
