### PR TITLE
Info center

### PR DESCRIPTION
**Pull request by XinYenFon**
infocenter
Signed-off-by: Antes antes@simplemachines.org

### CODE REVIEW

**Comment by ghost** [comment]
I'd have to agree with Arantor on this, I'd prefer it the way it currently is.

**Comment by Arantor** [comment]
No, that's not what I meant. This commit is to fix the broken styling of the headers but the way it does it is not the way we'd planned to do it.

**Comment by ghost** [comment]
Regardless i think there is way to much gold/yellow in the 'info center' there, it's just too in your face, almost emphasises it over the actual board listings.

**Comment by illori** [comment]
also this does not fix this issue in all the other locations were it happens

**Comment by XinYenFon** [comment]
may i ask what route you want to use @Arantor ?
@illori other locations :( (stats page?)

**Comment by Arantor** [comment]
The problem is that the info center - and plenty of other places - are all reusing the h3 and h4 catbg/titlebg classes and just adjusting them on demand.

What we should be doing is creating new classes and replacing those ones.

**Pull request closed without merging**
