### PR TITLE
Fixing theme install that is based on another theme

### PR DESCRIPTION
**Pull request by live627**
I don't really have a theme to test it with (manually doing it would eat up too much time!) so instead I wrote a unit test that i could quickly run every time I made a change:.
```
> php  vendor/phpunit/phpunit/phpunit --debug

PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.10
Configuration: C:\Users\John\repos\SMF2.1\phpunit.xml
Error:         No code coverage driver is available

Test 'PHPTDD\ThemeTest::testThemeInfo' started
Test 'PHPTDD\ThemeTest::testThemeInfo' ended
Test 'PHPTDD\ThemeTest::testGetSingleTheme' started
Test 'PHPTDD\ThemeTest::testGetSingleTheme' ended
Test 'PHPTDD\ThemeTest::testGetSingleThemeNotExists' started
Test 'PHPTDD\ThemeTest::testGetSingleThemeNotExists' ended
Test 'PHPTDD\ThemeTest::testInstallCopy' started
Test 'PHPTDD\ThemeTest::testInstallCopy' ended
Test 'PHPTDD\ThemeTest::testInstallDuplicateCopy' started
Test 'PHPTDD\ThemeTest::testInstallDuplicateCopy' ended
Test 'PHPTDD\ThemeTest::testInstallCopyWithNoName' started
Test 'PHPTDD\ThemeTest::testInstallCopyWithNoName' ended
Test 'PHPTDD\ThemeTest::testInstallDependentTheme' started
Test 'PHPTDD\ThemeTest::testInstallDependentTheme' ended
Test 'PHPTDD\ThemeTest::testUpdateDependentTheme' started
Test 'PHPTDD\ThemeTest::testUpdateDependentTheme' ended
Test 'PHPTDD\ThemeTest::testRemoveDependentTheme' started
Test 'PHPTDD\ThemeTest::testRemoveDependentTheme' ended
Test 'PHPTDD\ThemeTest::testRemoveTheme' started
Test 'PHPTDD\ThemeTest::testRemoveTheme' ended
Test 'PHPTDD\ThemeTest::testGetAllThemes' started
Test 'PHPTDD\ThemeTest::testGetAllThemes' ended
Test 'PHPTDD\ThemeTest::testGetInstalledThemes' started
Test 'PHPTDD\ThemeTest::testGetInstalledThemes' ended


Time: 535 ms, Memory: 8.00 MB

OK (12 tests, 65 assertions)
```

### CODE REVIEW

**Comment by albertlast** [comment]
Why you use literal?
And what is difference to string?

**Comment by live627** [comment]
no  difference to the generated query

**Comment by albertlast** [comment]
so literal is for static text?

**Comment by live627** [comment]
yes

**Pull request merged**
