### PR TITLE
Operator not supported for PHP 7.1

### LINKED ISSUE #4145: PHP 7.1 Search Method [] operator not supported for strings
Affects SMF 2.1 Beta 3 and SMF 2.0.x
After changing the Search Method to Fulltext the error '[] operator not supported for strings' is thrown whenever the 'Search Methods' menu is selected.

The fix is as follows:
In ./Sources/ManageSearch.php
Find:
Code: [Select]

        $context['fulltext_index'] = '';
        if ($request !== false || $smcFunc['db_num_rows']($request) != 0)

Replace With:
Code: [Select]

        $context['fulltext_index'] = array();
        if ($request !== false || $smcFunc['db_num_rows']($request) != 0)

I've confirmed this issue also affects SMF 2.1 Beta 3 - error log info is as follows:
[21-Jun-2017 02:23:37 UTC] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php:826
Stack trace:
#0 /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php(219): detectFulltextIndex()
#1 /home/abcdefg/public_html/forum_21B3/Sources/Subs.php(4584): EditSearchMethod()
#2 /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php(77): call_helper('EditSearchMetho...')
#3 /home/abcdefg/public_html/forum_21B3/Sources/Admin.php(495): ManageSearch()
#4 /home/abcdefg/public_html/forum_21B3/index.php(152): AdminMain()
#5 {main}
  thrown in /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php on line 826

https://www.simplemachines.org/community/index.php?topic=554723.

### PR DESCRIPTION
**Pull request by frandominguezl**
Fixes #4145 
edit: also updating contributors.txt

### CODE REVIEW

**Comment by albertlast** [comment]
ther are many places where $context['fulltext_index'] = ''; is done or something simliar,
should be this not changed too?

**Comment by frandominguezl** [comment]
I've tested just changing the one mentioned in the issue and it works well. I'll do a deeper test later today, just in case.

**Comment by albertlast** [comment]
the key issue is in my eyes is that $context['fulltext_index'] is sometimes an array sometimes a string.
to get all in line(everything should be array) would be a good idea

**Comment by frandominguezl** [comment]
As far as I can see, it only needs to be changed to an array in ManageSearch.php Line 311

**Comment by jdarwood007** [comment]
See #4145 for more info

**Comment by frandominguezl** [comment]
With that last commit I think this PR is ready.

**Comment by Sesquipedalian** [comment]
Just to clarify, am I correct in understanding that as of 029a169 you've changed all instances of `$context['fulltext_index']` so that it is always an array, @d3vcho?

**Comment by frandominguezl** [comment]
Yes, that's right @Sesquipedalian

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
