### PR TITLE
Update SCEditor to 1.4.7 

### LINKED ISSUE #2466: Still badly is shown cursor in qucik reply (IE11)
Yo, I recently reported bug with cursor, which isn't show in write window. Just next to emoticons. Bug still is in quick reply.

quickreply

Are you able to do something with it or not? Don't close issue until it won't be checked.

### PR DESCRIPTION
**Pull request by live627**
Fixes #2466

### CODE REVIEW

**Comment by XinYenFon** [comment]
So far I didn't see any problem (is it only me or wysiwyg mode is way more better now?).

edit: anyone can test new version with https://github.com/SimpleMachines/SMF2.1/issues/2466 ? 

cc: @jsgrom

**Comment by margarett** [comment]
I tested this shortly (not exactly sure what to test :tongue: )
Overall looks to work fine. I can't reproduce #2466 

There's just something annoying: 
a) out of wysiwyg, the cursor shows correctly in the top of the "box". In wysiwyg it starts a bit lower (more in FF than in IE)
b) out of wysiwyg, the insert URL/mail, etc, buttons trigger a popup. In wysiwyg it's a popup but that popup has the "INSERT" text too much dislocated down (doesn't look that good :tongue: )

**Comment by jsqx** [comment]
The cursor in IE11 still isn't shown in place. The cursor is flashing beside last emoticon. If you refresh the site the cursor will be flashing in this place.

bad

In the basic editor the cursor is showing in right place in text editor, but if a site is refreshing in browser than this cursor is showing beside this emoticon but back on it place to writing editor.

**Comment by live627** [comment]
>  a) out of wysiwyg, the cursor shows correctly in the top of the "box". In wysiwyg it starts a bit lower (more in FF than in IE)

I switch modes in FF and see no movement in the text.

>  b) out of wysiwyg, the insert URL/mail, etc, buttons trigger a popup. In wysiwyg it's a popup but that popup has the "INSERT" text too much dislocated down (doesn't look that good :tongue: )

Fixed

**Comment by live627** [comment]
> anyone can test new version with #2466 ? 

Yep, this patch definitely fixes it.

**Comment by XinYenFon** [comment]
I didn't notice any weird thing on Spartan as well, one thing "enter" button moving space to upwards not downwards (Spartan's bug ?).

**Pull request merged**
