### PR TITLE
Fix undefined variable: approve_query

### LINKED ISSUE #5877: Search.php: 8: Undefined variable: approve_query
#### Description
Originally reported [here](https://www.simplemachines.org/community/index.php?topic=570651.0): Since ~2019-10-10, the GH version produces the following errors when using the search function:

```
Code: [Select]
Type of error: Undefined
8: Undefined variable: approve_query
 http://localhost:8080/smf/index.php?action=search2
 C:/wamp64/www/smf/Sources/Search.php (Line 1715)

Type of error: Undefined
8: Undefined variable: approve_query
 http://localhost:8080/smf/index.php?action=search2
 C:/wamp64/www/smf/Sources/Search.php (Line 1828)
```
These lines were last changes 6 months ago ([L1715](https://github.com/SimpleMachines/SMF2.1/blame/0009c2d072ef77f8f8f869def5986d7a9449e2b1/Sources/Search.php#L1715), [L1828](https://github.com/SimpleMachines/SMF2.1/blame/0009c2d072ef77f8f8f869def5986d7a9449e2b1/Sources/Search.php#L1828)), but I didn't see this before 2019-10-10 in my installs (but I didn't explicitly test the search function and my users don't seem to use it much). Also just confirmed this in a freshly updated nightly build from 15 minutes ago.

### Steps to reproduce
1. Install from/update to a recent version 
2. Search something (posting from entire forum or current board, or a member) in the top-right search bar
3. if the search has no result, only the first error occurs; if it has one, both appear

### Environment (complete as necessary)
- Version/Git revision: HEAD
- Database Type: any? (confirmed on psql, assume sm.org reporter uses mysql)
- Database Version: any?
- PHP Version: any?

### PR DESCRIPTION
**Pull request by live627**
- use the mod cache instead of a whole new query
- Redoing the comments because how does English work?

Fixes #5877

### CODE REVIEW

**Comment by sbulen** [comment]
live - Is this for #5877?   
If so, could you put that in your initial description?  That way the issue & pr are linked.

**Comment by live627** [comment]
they are linked via the commit  which is enough for github

**Comment by sbulen** [comment]
Yeah, but not for us suckers trying to manually maintain the "has fix" tags.  

Can you tag them?

Or at least make them easier to find?

**Review by Sesquipedalian — APPROVED** [review]

**Comment by XinYenFon** [comment]
may i ask why this marked for final? Its a common error users can face, better suited for upcoming RC.

**Comment by sbulen** [comment]
The cat in a tie is correct.
I was able to reproduce the issue & confirm this addressed it.

**Comment by m4z** [comment]
I concur, no more errors. ❤️

**Pull request merged**
