### PR TITLE
Remaps \SMF namespace to forum's root directory

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Any objections?

### CODE REVIEW

**Comment by jdarwood007** [comment]
I'm not certain why. It doesn't need to match our folder structure.  @Tyrsson any thoughts?

**Comment by Sesquipedalian** [comment]
Part of the reason is explained in https://www.simplemachines.org/community/index.php?msg=4176355, but more generally, the thinking was that this would allow us to bring ./index.php, ./cron.php, ./Themes, etc., into the SMF namespace.

**Comment by tyrsson** [comment]
> Part of the reason is explained in https://www.simplemachines.org/community/index.php?msg=4176355, but more generally, the thinking was that this would allow us to bring ./index.php, ./cron.php, ./Themes, etc., into the SMF namespace.

Why would one want to namespace files that do not define a class or function?

I'm not sure what this is meant to accomplish or what issue its intended to mitigate..

**Comment by jdarwood007** [comment]
Ahh, I hadn't stepped onto the site, been busy.

I can see why the idea comes up.  We could still move the Maintenance folder outside of the sources.  We would just have a call for our autoloader to start somewhere different when the SMF\Maintenance namespace is reached.  The root files should if they have to have a namespace, be just SMF.  They shouldn't since its the entry point into the program.

Themes make sense in high lever terms, but I think implementation gets a bit difficult.  Currently, SMF just checks for the files existent when loading another theme and if it doesn't, resorts to the default theme file.  For a class and/or namespace system, we would have to track that to make the correct calls.  I think procedural themes are easier for the theme system than having it class and/or namespaced.

**Comment by Sesquipedalian** [comment]
Hm. Yeah, fair point.

**Pull request closed without merging**
