### PR TITLE
Antz moving forward! with kitteh

### LINKED ISSUE #3041: Deprecated CSS - .align_top & .align_bottom
Ran a recursive search for these on all files in 2.1. The only places these two classes show up is in index.css and rtl.css. Can't see they're doing much good sitting in the CSS all by themselves.

index.css

```
.align_top a, .align_bottom a {
    margin: 0 12px 0 0;
}
```

rtl.css

```
/* the active one */
.align_top a, .align_bottom a {
    margin: 0 0 0 12px;
}
```

Can kill, yes? :)

### LINKED ISSUE #3043: 30% reduction of message index CSS (you know you want it)
I'll just leave this here and you can implement it when you feel like it. Went through the message index section of index.css and trimmed it substantially without changing the look. Also improved RTL support and slightly reduced markup at the same time. Code changes are simple.

So old CSS was this:

```
/* MessageIndex */
/* Topic list */
#topic_container .windowbg, #topic_container .windowbg2 {
height: 4em;
border: 1px solid #ddd;
border-top: none;
}
#topic_header .board_icon, #topic_header .info, #topic_header .board_stats, #topic_header .lastpost, #topic_header .moderation {
height: 2em;
font-weight: bold;
font-size: 1em;
margin-top: 3px;
margin-bottom: 0;
padding: 0;
}
#topic_header.title_bar {
margin: 0px;
border-radius: 0;
}
#messageindex .board_stats, #recent .board_stats {
text-align: center;
}
#topic_header input {
margin-top: 5px !important;
}
.moderation {
float: right;
width: 35px;
margin: 5px 0 0 0;
}
#topic_container .board_icon, #topic_container .info, #topic_container .windowbg2, #topic_container .windowbg, #topic_container .board_stats, #topic_container .lastpost {
box-shadow: none;
border-radius: 0;
padding: 0;
margin: 0;
overflow: hidden;
height: 3.5em;
}
#topic_container .icons span {
margin: 2px 0 0 5px;
}
.icon img, .moderation input {
margin-top: 15px;
}
.info .icons, #messageindex .board_stats p, .lastpost p, #unread .board_stats p, #unreadreplies .board_stats p {
margin-top: 5px;
border: none;
}
/* Start with description and other things */
#description_board {
padding: 8px 10px 8px 10px;
border-bottom-left-radius: 0;
border-bottom-right-radius: 0;
border-bottom: 0;
box-shadow: none;
}
.lastpost span.last_post {
float: right;
margin: 4px;
}
select.qaction {
padding: 0;
}
#quick_actions {
padding-right: 4px;
margin-top: 5px;
}
.qaction_cell .button_submit {
margin: 2px 4px 0 4px;
}
#topic_icons {
margin-top: 10px;
float: left;
width: 100%;
}
#topic_icons .information {
border-radius: 7px;
}
#topic_icons p {
line-height: 2em;
}
#topic_icons p.floatleft {
padding: 0 12px 2px 0;
}
/* Just to correct Fred there without requiring an extra image. Should make a new Fred with clear padding. */
#topic_icons p.floatleft img:first-child {
padding: 0 2px;
}
#message_index_jump_to_select {
font-size: 1em;
padding: 2px;
}
#message_index_jump_to .button_submit {
padding: 4px 6px 2px 6px;
}
```

You can replace that with this for extra coolness:

```
/* MessageIndex */
/* Start with description and other things */
#description_board {
    padding: 8px 10px;
    border-radius: 6px 6px 0 0;
    border-bottom: none;
    box-shadow: none;
}
#description_board h3, #description_board p {
    display: inline-block;
}
#description_board h3:after {
    content: ' - ';
}
/* Topic list */
#topic_header {
    margin: 0;
}
#topic_header div {
    height: 2em;
    font-weight: bold;
    padding: 0;
}
.moderation {
    display: table-cell;
    width: 35px;
    vertical-align: middle;
}
#topic_container .windowbg, #topic_container .windowbg2 {
    height: 4em;
    border: 1px solid #ddd;
    border-top: none;
}
#topic_container .windowbg, #topic_container .windowbg2 {
    box-shadow: none;
    border-radius: 0;
    padding: 0;
    margin: 0;
}
#topic_container .windowbg>div, #topic_container .windowbg2>div {
    padding-top: 0;
}
#topic_container .board_stats p {
    margin: .5em 0 -.5em;
}
/* Quick moderation selects and submit */
#quick_actions {
    padding: 4px 0;
}
.qaction {
    padding: 0;
}
/* Investigate default select and button sizing. Something is slightly off there.*/
.qaction.button_submit {
    margin: 1px 4px 0 4px;
}
/* Icons and jump to */
#topic_icons:before {
    display: block;
    height: 8px;
    clear: both;
    content: '';
}
#topic_icons .information {
    font-size: .9em;
    border-radius: 4px;
}
#topic_icons p {
    padding: 0 12px 0 4px;
    line-height: 2em;
}
/* Should lose this before RC1. It's a kludge. Can be fixed by new image */
#topic_icons .floatleft img:first-child {
    padding: 0 2px;
}
#message_index_jump_to_select {
    font-size: 1em;
    padding: 0;
}
/* This is a bit of a kludge too */
#message_index_jump_to .button_submit {
    margin-top: 3px;
    padding: 1px 6px;
}
```

When testing this for RTL I found that there's a little trap later in the file too. The .title_bar class has a text-align: left; declaration, which does nothing except screw RTL. That should be removed. Change to:

```
/* TitleBar & SubBar */
.title_bar {
    border-right: 1px solid #ddd;
    border-left: 1px solid #ddd;
    border-top: 2px solid #ff9400;
    border-bottom: 2px solid #bf6900;
    background: #fff;
    color: #666;
    border-radius: 2px 2px 0 0;
    margin: 5px 0 0 0;
}
```

Markup changes are really basic. I just ditched the floatleft on the description_board h3 and set it and the paragraph to inline-block for auto RTL. Also moved the hyphen and spaces to a pseudo in case any themers want to change those easily.

```
    <div id="description_board" class="generic_list_wrapper">
        <h3>', $context['name'], '</h3>
```

Then I removed the floatright class from the five generic_icons spans (watch, lock, sticky, move, poll) and put it on their parent .icons div to save some markup and CSS.

MessageIndex.template.php

```
            // Now we handle the icons
            echo '
                            <div class="icons floatright">';
            if ($topic['is_watched'])
                echo '
                                <span class="generic_icons watch" title="', $txt['watching_this_topic'], '"></span>';
            if ($topic['is_locked'])
                echo '
                                <span class="generic_icons lock"></span>';
            if ($topic['is_sticky'])
                echo '
                                <span class="generic_icons sticky"></span>';
            if ($topic['is_redirect'])
                echo '
                                <span class="generic_icons move"></span>';
            if ($topic['is_poll'])
                echo '
                                <span class="generic_icons poll"></span>';
            echo '
                            </div>';
```

Also needs that tweak in Recent.template.php. Exactly the same change in both function template_unread() and function template_replies()

```
            // Now we handle the icons
            echo '
                                <div class="icons floatright">';
            if ($topic['is_locked'])
                echo '
                                    <span class="generic_icons lock"></span>';
            if ($topic['is_sticky'])
                echo '
                                    <span class="generic_icons sticky"></span>';
            if ($topic['is_poll'])
                echo '
                                    <span class="generic_icons poll"></span>';
            echo '
                                </div>';
```

Merry Christmas n stuff.

ETA: Meh, GitHub makes an awful mess of code. :P I'll post it in code tags on SMF so it can just be copy/pasted without having to reformat it.

### PR DESCRIPTION
**Pull request by XinYenFon**
Read the commit messages or commits to get better idea :feet: 

cc: @StealthWombat @MustafaCan @live627 

Ref: http://www.simplemachines.org/community/index.php?topic=539574.0
Ref2: http://www.simplemachines.org/community/index.php?topic=539570.0

Signed-off-by: Antes antes@simplemachines.org

fixes #3041 
fixes #3043

### CODE REVIEW

**Comment by live627** [comment]
I'm working on a grid system to help witth the stufffr that

**Comment by XinYenFon** [comment]
why ?

**Comment by live627** [comment]
I'm working on a grid system to help with the stuff that @StealthWombat is grumbling at and to   reduce unnecessary styles.

**Comment by StealthWombat** [comment]
What is StealthWombat grumbling at now? :D

**Comment by live627** [comment]
pancakes :P

**Comment by live627** [comment]
Are you done here? Can I merge it in?

**Comment by XinYenFon** [comment]
Sure go for it.

**Comment by StealthWombat** [comment]
Actually I've just left a comment on #3043. ;)

**Pull request merged**
