### PR TITLE
Updates the credits for RC 1

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Everyone please check this to make sure that your name is listed in the correct location and in the form that you prefer.

### CODE REVIEW

**Comment by SychO9** [comment]
Can you please change **Sych0** to 
**Sami "SychO" Mazouz**

Thanks

**Comment by Kindred-999** [comment]
Change the two entries for me... (former PMs and support)

Will "Kindred" Wagner

**Comment by MechDR** [comment]
The lead support should be changed, Lex is now the lead ;).

GigaWatt

**Comment by Sesquipedalian** [comment]
> The lead support should be changed, Lex is now the lead ;).

He's already listed as the lead. :wink:

**Comment by frandominguezl** [comment]
Please update *d3vcho* to *Francisco "d3vcho" Domínguez*

Thank you :)

**Comment by MechDR** [comment]
> He's already listed as the lead. wink

Then I obviously don't know how to work GitHub :D.

**Comment by Sesquipedalian** [comment]
> Then I obviously don't know how to work GitHub :D.

When viewing changes, the red highlighting shows what is being removed, and the green shows what is being added. To know what the new version of the file will look like, only look at the white and green lines.

**Comment by Sesquipedalian** [comment]
@frandominguez03, 830104f adds a function and some strings to allow an array of strings to be converted into grammatically correct list for any given language. I hope that the comments I put into index.english.php explain clearly how translators should work with this strings. If it still isn't clear or if you have any questions, please let me know.

**Comment by frandominguezl** [comment]
Seems pretty clear to me. We'll see if translators know how to deal with it as well, or I might need to create a simple how-to in the proper board. Thank you.

**Pull request merged**
