### PR TITLE
SQLite update to go with #4446

### PR DESCRIPTION
**Pull request by tinoest**
Update the Cache to work with the changes introduced by @albertlast 

Slightly different mechanism as with testing the different between creating a new one and deleting was marginal.

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Your changes remove the closing php tag in each of the files you modified. This needs to be fixed before we can merge this.

**Comment by Sesquipedalian** [comment]
Need to trim off the line break after the closing PHP tag.

**Comment by tinoest** [comment]
There isn’t a line break showing in my editor. So no idea how I remove it

**Comment by frandominguezl** [comment]
That happened to me in some previous Pull Requests. Try pushing the changes by saving the files wirh Notepad++.

Are you using GitHub Desktop?

**Comment by tinoest** [comment]
I’m using macOS and Vim. I pushed with github desktop though.

**Comment by frandominguezl** [comment]
Using GH Desktop, when you're about to commit you can see the changes made to that file. Try unchecking the line break by clicking on the blue box right to it, then commit, and discard the linea break changes after it.

**Comment by jdarwood007** [comment]
If your using VIM: https://stackoverflow.com/questions/1050640/vim-disable-automatic-newline-at-end-of-file

**Comment by Sesquipedalian** [comment]
For a quick fix, `perl -0777 -pi -e 's/\?>\n$/\?>/' file.php` should do the job.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
