### PR TITLE
Undo renaming of "smfAnnouncements" div to avoid breaking the news

### PR DESCRIPTION
**Pull request by Oldiesmann**
Signed-off-by: Michael Eshom <oldiesmann@oldiesmann.us>

### CODE REVIEW

**Comment by albertlast** [comment]
i "forced" oldy to give a proper describtion,
here it is:

The javascript to display the SMF news in the admin center expects the div to have an ID of "smfAnnouncements". By default that div displays a text string saying "You are unable to connect to simplemachines.org's latest news file.". The JavaScript replaces that text with the appropriate news that it gets from simplemachines.org
So if the div is named "smf_news" instead of "smfAnnouncements", the JavaScript won't work

**Comment by Gwenwyfar** [comment]
And this is why I hate doing changes without testing everything first... but oh well. 

The javascript was also renamed, are you sure this fixes it?

https://github.com/SimpleMachines/SMF2.1/pull/5264/files#diff-b67fb0c40e61a708da98389c4692c021L124

Edit: Just tested it and it doesn't. Must be something else in the javascript.

**Comment by Oldiesmann** [comment]
I'm not sure what that change does exactly, but the JavaScript to actually display the news items is pulled directly from simplemachines.org, so we'd have to change it on that end for this renaming to work. That JS expects it to be smfAnnouncements.

**Comment by Oldiesmann** [comment]
Didn't see the comment about the JS being renamed until @SychO9 pointed out the changes... Latest commit should take care of those as well

**Comment by jdarwood007** [comment]
Note, its not that we can't change it, but this change has to go through approval from the lead developer and Site team (Me).  My handling will be needing to update the javascript code to both support all editions properly.  Typically this is something we should do early on in the development process.

**Pull request merged**
