### PR TITLE
Run cache check only when enabled

### PR DESCRIPTION
**Pull request by albertlast**
I try to do some performance optimization,
this is one of the results.

This pr is done.

### CODE REVIEW

**Comment by jdarwood007** [comment]
Can it check to make sure override is false still?  I added that as a future thing for customizations or complicated workarounds.

**Comment by albertlast** [comment]
You mean?
``if (empty($cache_enable))`` --> ``if (empty($cache_enable) && empty($overrideCache))``

**Comment by jdarwood007** [comment]
Yes, or I guess is_null since that is what is the default value.

Just ensuring if we are attempting to override the normal, that we can bypass the check.

**Comment by albertlast** [comment]
When  null and false are the same,
than it's smf coding standard to use empty.

**Review by jdarwood007 — APPROVED** [review]

**Pull request merged**
