### PR TITLE
Check old_url before using it

### PR DESCRIPTION
**Pull request by BrickOzp**
Signed-off-by: Oscar Rydhé oscar.rydhe@gmail.com

### CODE REVIEW

**Comment by jdarwood007** [comment]
Can we add a return so its not up against the previous statement.

**Comment by BrickOzp** [comment]
The redirect was just added in 41268e31 so there should be no problem in continue executing.

**Comment by live627** [comment]
don't needed it because it always exits as the name suggests

**Comment by BrickOzp** [comment]
I got the error when trying to login as a banned user.
You can force it by going to index.php?language=<lang> in a new browser

**Comment by jdarwood007** [comment]
I can reproduce the error as well.

1. Log in as banned user
2. Navigate too ?language=
3. Navigate too ?langauge=english

Don't know if step 3 was needed, but I got the error.  I suspect the true issue is because the ban process is destroying session data.  It isn't worth trying to fix it up to keep that session data and just check that the session is there to be safe.

**Pull request merged**
