### PR TITLE
createList FTW!! :P

### PR DESCRIPTION
**Pull request by emanuele45**
Improved createList providing a new function to check the results and define a class/style for the row based on that

converted the list of a user's attachments to createList

Signed-off-by: emanuele emanuele45@gmail.com

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Looks good, but I think it would be best to keep the styles in the CSS files as much as possible. Otherwise we're making it harder for themes to change things.

**Comment by emanuele45** [comment]
Yes, that's true. Or at least give the theme/s some kind of way to define their preferred styles.

**Comment by live627** [comment]
> Otherwise we're making it harder for themes to change things.

Why would a theme want to change a column width?

> Or at least give the theme/s some kind of way to define their preferred styles.

I thought they already could...

**Comment by emanuele45** [comment]
Yes of course they can.
In that particular case (and in general in createList) the style is/can be defined in the source and cannot be overridden by the theme (i.e. in-line styles like column widths).

> Why would a theme want to change a column width?

Yes, in general a column width is not that important, but when I pushed that branch, me and Norv were joking (well...Norv was not joking that much...) about rewriting the display (and maybe boardindex...and maybe anything that is a kind of list) with createList. In similar cases we'd be very careful in use any kind of in-line style...

But for now it's not a big issue.

**Comment by live627** [comment]
Ooh, the message index is a perfect candidate for the generic list! Not quite so sure on the board index, but maybe my fears there have no ground..

**Comment by Oldiesmann** [comment]
> Why would a theme want to change a column width?

I couldn't tell you, but we should make it easy to change things like that just in case someone does want to change them.

**Comment by emanuele45** [comment]
> Ooh, the message index is a perfect candidate for the generic list! Not quite so sure on the board index, but maybe my fears there have no ground..

ohh even message index would be scary to convert! Though it would also be funny...
Yes, the board index would be rather difficult, probably easier to deal with the display page (apart from the fact that it currently uses the callback...).

**Comment by live627** [comment]
Whatever is decided, do not disturb the callback, else memory will go through the roof.

**Comment by joshuaadickerson** [comment]
Which callback?

**Comment by emanuele45** [comment]
prepareDisplayContext

**Comment by joshuaadickerson** [comment]
Show me some kind of benchmark which proves that. From what I've seen, it is pointless. Mistake by Unknown.

**Pull request merged**
