### PR TITLE
Avoid id conflicts between mobile and desktop versions of main menu

### LINKED ISSUE #3463: many duplicate ID's give error on validate html
Because the mobile menu is loaded allways (even it's not a mobil device) on Validation it gives many, many errors on duplicate id's.
Whey not check (with php) if a mobile device detected ?
It's very simple to do that .. I can spend the code for that ;-)

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #3463

### CODE REVIEW

**Comment by XinYenFon** [comment]
I think its better solution to remove IDs and use classes. Too many new phones coming out to market, I'm not really sure if mobile-detector can hold up with it. Also Curve2 is not a mobile theme, its a responsive theme so solutions should be at responsive stage.

**Comment by Sesquipedalian** [comment]
Removing ids could work too, yes. Even so, this solution is a responsive one rather than a browser detection solution.

**Comment by XinYenFon** [comment]
@Sesquipedalian https://github.com/Antes/kittenground/commit/d04c4b041beec6b08453662e7ca2515416550e39

**Comment by Sesquipedalian** [comment]
That's fine with me. Go ahead and submit that as a PR and close this one.

**Pull request closed without merging**
