### PR TITLE
Themes upload

### PR DESCRIPTION
**Pull request by emanuele45**
People will never complain again (hopefully) because they cannot install a theme! (when they are uploading the new theme through the package manager instead of the theme manager)

### CODE REVIEW

**Comment by DrDeejay** [comment]
Sounds nice! :) So it means the theme install page will be removed, right?

**Comment by emanuele45** [comment]
Not by me. :P
This just means that if people will try to upload a theme from the package manager they will not get an error, but they will find the theme installed.
Of course the preferred way is still from the theme manager.

**Comment by live627** [comment]
Only one interface should be allowed. No ambiguity whatsoever. Else this will be a hot support issue as people WILL  get confused  "Where do I upload my theme?"

**Comment by emanuele45** [comment]
Yeah, I know...
I'd love to see a single interface to upload all the "packages" (mods, themes, languages).

The "theory" of this PR is that many people are already confused by the presence of multiple interfaces. I've seen several people asking "Why can't I upload this theme?", and the usual answer is "are you using the package manager? If so go to...blabla".

As I said I'd love to see a single interface for everything (even though there are slight differences) and I see this as a (first?) step towards that goal. The next step in my head (and the one I was thinking to play with the next days) was to allow upload languages pack (as they are now, so without any ".xml") from the package manager too.

Anyway that's a proposal, if you think is too confusing, no problem. ;)

**Comment by live627** [comment]
I agree it iis a first step. I'm just sending my opinions :)) and hopefully giving a warning, however pragmatic, about the problem I see.

**Comment by ghost** [comment]
It'd be great, as we're talking about new themes, that you could include a new feature which allows admins to apply installed mods to themes too, in that way people won't have to manually install all mods in the new theme

**Comment by jdarwood007** [comment]
Well this commit looks fine.  Its simply trying to predict what the user has done.  We can't exactly resend the request since it has an attachment, so this is the next best thing.  I wouldn't want to save the file and handle it another way as it could get nasty to ensure security.

**Comment by emanuele45** [comment]
> Its simply trying to predict what the user has done.

No, not only. That commit is probably doing what you wouldn't do, because if it finds that a package is a theme it moves to the "theme install", see: https://github.com/emanuele45/playpen/commit/9f34c46261e42f558e7644e7ed5cebe8cdd5d21c#L0R654

**Comment by emanuele45** [comment]
So, the end of the story is that is better not to merge this one due to all the concerns?

**Comment by Spuds** [comment]
I still really like it as a first step ... sure lots more can be done to consolidate the install area(s), that sounds like a nice new feature for 2.2, the revenge of pacman.

As my random thought for this AM, you could also add a (redirect = false) or something like that (/me no good with names :P ) as  ThemeInstall(redirect = false); and then decide to bypass that checkSession('request') when called from pacman or not in that function.  Of course you may have added that elsewhere but that would require me to look and that goes against my laziness :P

**Comment by emanuele45** [comment]
Thinking about it I'll drop this one.
There is already the warning in place, we can work on harmonisation of pacman in the next release.

I'll save only the use of xmlArray, but since that PR is messed up with several other things I'll do a new one.

Edit: lol it was already there from somewhere else...that PR was really a bloody mess!!

**Pull request closed without merging**
