### PR TITLE
Update Memberlist.template.php simple improving

### PR DESCRIPTION
**Pull request by Pavel-II**
Displays the number of posts by reference to the list of posts

### CODE REVIEW

**Comment by Oldiesmann** [comment]
The commit needs to be signed off or we can't use it.

**Comment by XinYenFon** [comment]
is it valid ? I mean, anyone can see memberlist can also see post-list of that user ?

**Comment by Pavel-II** [comment]
I'm dont know how to sign it.
Antes, you mean the code is correct or not? I'm create simple mod, and install it on my forum.

**Comment by XinYenFon** [comment]
Code is correct, what i asked is under any circumstances is this code works or any chance it may return error -no access- ?

**Comment by Pavel-II** [comment]
If the user does not have permission to view the message, it can not open the link.
I check it out for guests.

**Comment by Pavel-II** [comment]
How to sign off commit?

**Comment by XinYenFon** [comment]
http://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

**Pull request closed without merging**
