### PR TITLE
More upgrader fixes

### LINKED ISSUE #8197: [3.0]: Upgrade breaks after backup due to User::$me not being initialized
### Basic Information

When running upgrade.php, you get a blank screen when you click "Continue" after the backup completes.

### Steps to reproduce

1. Have an SMF3 board from prior to the recurring events changes
2. Run upgrade.php

### Expected result

Upgrade completes succesfully

### Actual result

```
PHP message: PHP Fatal error: Uncaught Error: Typed static property SMF\\User::$me must not be accessed before initialization in /.../Sources/Db/APIs/MySQL.php:258
```

Note that there is another issue that will occur once this one is fixed (this one doesn't apply to PostgreSQL but the other one applies to both), but I'll file a separate issue for that.

### Version/Git revision

76f5ccf

### Database Engine

All

### Database Version

10.11.7-MariaDB-1:10.11.7+maria~ubu2204

### PHP Version

8.3.6

### Logs

_No response_

### Additional Information

This is probably related to #8196 since I didn't have this problem while testing the other upgrade fixes last night.

### LINKED ISSUE #8198: [3.0]: New columns not being added to tables
### Basic Information

When running upgrade.php, you will run into an error when you hit the db_fetch call on line 1933 of upgrade.php because we're trying to pull id_event and uid from the calendar table but no uid column has been added at that point

### Steps to reproduce

1. Try upgrading a forum on PostgreSQL (this should affect MySQL as well but #8197 is preventing it from getting that far at that point)
2. Blank screen after backup because there is no "uid" column in the calendar table

### Expected result

Expect upgrade to run smoothly

### Actual result

```
Fatal error: Uncaught TypeError: SMF\\Db\\APIs\\PostgreSQL::fetch_assoc(): Argument #1 ($result) must be of type object, false given, called in /.../upgrade.php on line 1933
```

### Version/Git revision

76f5ccf

### Database Engine

PostgreSQL

### Database Version

PostgreSQL 14.11

### PHP Version

8.3.6

### Logs

_No response_

### Additional Information

Screenshots showing that the new columns haven't been added to the calendar table in either MySQL or Postgres:
image
image

### LINKED ISSUE #8199: [3.0]: Calling pg_version() with default connection is depracated as of PHP 8.1
### Basic Information

Found this while going through my error log to debug the PostgreSQL upgrade:
```
AH01071: Got error 'PHP message: PHP Deprecated: pg_version(): Automatic fetching of PostgreSQL connection is deprecated in /.../upgrade.php on line 75
```

Per the PHP manual, in 8.1 and up, you should pass an explicit instance of the [PgSql\Connection](https://www.php.net/class.pgsql-connection) class instead of using the default connection. It could be a while before this functionality is completely removed but now is the time to fix it

### Steps to reproduce

1. Connect to a PostgreSQL database
2. Call pg_version() with no arguments

### Expected result

_No response_

### Actual result

_No response_

### Version/Git revision

76f5ccf

### Database Engine

PostgreSQL

### Database Version

14.11

### PHP Version

8.3.6

### Logs

_No response_

### Additional Information

[PHP: pg_version - Manual](https://www.php.net/pg_version)

### PR DESCRIPTION
**Pull request by Sesquipedalian**
Fixes #8197
Fixes #8198
Fixes #8199

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
@Oldiesmann, please test to confirm that upgrading now works in both the browser and on the command line.

**Comment by Oldiesmann** [comment]
Upgrade went smoothly with MySQL via the browser. Will test with PostgreSQL on command line shortly.

**Comment by Oldiesmann** [comment]
Upgrade went fine in the shell as well but I still got a deprecation warning for pg_version() even after making the changes, this time on line 75 of upgrade.php.

**Comment by Sesquipedalian** [comment]
Latest commit should fix that, @Oldiesmann. Can you please test on PG one more time?

**Comment by Oldiesmann** [comment]
New problem this time.

```
PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, false given in /.../Sources/QueryString.php:70
Stack trace:
#0 /,,,/Sources/QueryString.php(70): strpos()
#1 /.../upgrade.php(848): SMF\QueryString::cleanRequest()
#2 /.../upgrade.php(241): loadEssentialData()
#3 {main}
  thrown in /.../Sources/QueryString.php on line 70
```

The problem is that $_SERVER['QUERY_STRING'] is never set when running via CLI (since there is no query string as we're running the file directly through the PHP interpreter). Best option would be to just check whether we're running from the command line and skip that check if so. I'm not sure why I didn't run into this last time, unless I just wasn't paying attention.

**Comment by tyrsson** [comment]
Normally, and this is just a general observation. QueryString will pretty much mirror argv. If the browser script is supporting params being passed the same options should "generally" be passable via argv in shell should they not?

**Comment by Oldiesmann** [comment]
The code in question is simply checking whether someone is trying to be funny by sticking a URL in the query string. Completely irrelevant when upgrading via CLI.

```php
		// It seems that sticking a URL after the query string is mighty common, well, it's evil - don't.
		if (strpos($_SERVER['QUERY_STRING'], 'http') === 0) {
			Utils::sendHttpStatus(400);

			die;
		}
```

**Comment by Sesquipedalian** [comment]
> New problem this time.
> 
> ```
> PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, false given in /.../Sources/QueryString.php:70
> Stack trace:
> #0 /,,,/Sources/QueryString.php(70): strpos()
> #1 /.../upgrade.php(848): SMF\QueryString::cleanRequest()
> #2 /.../upgrade.php(241): loadEssentialData()
> #3 {main}
>   thrown in /.../Sources/QueryString.php on line 70
> ```
> 
> The problem is that $_SERVER['QUERY_STRING'] is never set when running via CLI (since there is no query string as we're running the file directly through the PHP interpreter). Best option would be to just check whether we're running from the command line and skip that check if so. I'm not sure why I didn't run into this last time, unless I just wasn't paying attention.

It's strange that I don't receive any such errors in my tests. But at any rate, try now.

**Comment by Oldiesmann** [comment]
Latest attempt...
```
PHP Deprecated:  pg_version(): Automatic fetching of PostgreSQL connection is deprecated in /.../Sources/Db/APIs/PostgreSQL.php on line 1113
 * Updating Settings.php... Successful.
 *  done.
 Successful.
 *  +++  Adding a new column "version" to messages table done.
 +++  Adding a new column "version" to personal_messages table done.
 Successful.
 *  +++  Add duration, rrule, rdates, and exdates columns to calendar table done.
 +++  Set duration and rrule values and change end_datePHP Fatal error:  Uncaught TypeError: SMF\Db\APIs\PostgreSQL::fetch_assoc(): Argument #1 ($result) must be of type object, false given, called in /.../upgrade.php(2467) : eval()'d code on line 9 and defined in /.../Sources/Db/APIs/PostgreSQL.php:350
Stack trace:
#0 /.../upgrade.php(2467) : eval()'d code(9): SMF\Db\APIs\PostgreSQL->fetch_assoc()
#1 /.../upgrade.php(2467): eval()
#2 /.../upgrade.php(1884): parse_sql()
#3 /.../upgrade.php(371): DatabaseChanges()
#4 {main}
  thrown in /.../Sources/Db/APIs/PostgreSQL.php on line 350
```

**Comment by Sesquipedalian** [comment]
Er, are you sure you tested with the correct commit checked out? The connection is provided on line 1113.

**Comment by Oldiesmann** [comment]
I'll double check. I may have forgotten to update that file.

**Comment by Oldiesmann** [comment]
That got rid of the deprecation error. It still dies with the other error though.

**Comment by Oldiesmann** [comment]
Further digging reveals that the query beginning on line 129 of upgrade_3-0_PostgreSQL.sql is failing because there is no longer an end_time column in the calendar table (since that was dropped during a previous run of the upgrader). We either need to check whether that column exists first or add a setting indicating we've already completed that part previously and then skip the event conversion stuff if so.

**Comment by Sesquipedalian** [comment]
Hopefully the latest commit will finish it.

**Comment by Oldiesmann** [comment]
> Hopefully the latest commit will finish it.

Unfortunately not.
```
 +++  Set duration and rrule values and change end_datePHP Parse error:  Unclosed '{' on line 2 in /.../upgrade.php(2467) : eval()'d code on line 46
```

**Comment by Oldiesmann** [comment]
It's because the "{" in the if statement on line 128 of upgrade_3-0_PostgreSQL.sql is never closed. I'm just not sure where to add it.

**Comment by Sesquipedalian** [comment]
Bleh. I must have made the same mistake there that I made earlier in the MySQL file. Not sure why I didn't catch it when I checked after finding the one in the MySQL file.

**Comment by Oldiesmann** [comment]
Everything completed successfully this time, though it did show `Clean up "Cleanup"` twice for some reason.

**Pull request merged**
