### PR TITLE
fix SQL Syntax in recent and remove replacments in pg subs #3261

### PR DESCRIPTION
**Pull request by albertlast**
Fix the error in the sql syntax
see: https://github.com/SimpleMachines/SMF2.1/issues/3261

### CODE REVIEW

**Comment by socram8888** [comment]
This AFAIK will fail, as DISTINCT works with tuples: if somebody posts two messages on the same thread, it'll be shown twice in the "Updated topics" section (vs once as it does currently).

What I had done was replacing the `DISTINCT` by a `GROUP BY t.id_topic`, and was testing it in my server before doing a PR.

**Comment by albertlast** [comment]
Nope this will not double the rows,
reason both columns are from the same table.

here a smale exp: http://sqlfiddle.com/#!9/035bf/1/0

and other columsn shouldn't use because the postgresql sql was hardcoded vs the one column(t.id_last_msg),
so this problem would raise up earlier.

**Comment by socram8888** [comment]
Okay, suppose in your example, "a" is thread ID, and "b" is last post ID.

In current implementation, it would return only "1". Using your modification, note it returns "1,2" and "1,3". This is, it returns thread 1 twice.

**Comment by albertlast** [comment]
Yes but id_topic is primary key, 
so you will never seen 1,2 and 1,3 exists at the same time.

**Comment by socram8888** [comment]
Oh derp, you're right, sorry!

**Pull request merged**
