### PR TITLE
Update Help.english.php

### PR DESCRIPTION
**Pull request by m4z**
PostgreSQL also has FTI.
I don't know if the technical details all apply, though.

### CODE REVIEW

**Comment by m4z** [comment]
Apparently the GH WebUI inserts a trailing newline.

**Comment by SychO9** [comment]
Yea you have to use a different editor, also you should probably include all edits in one single PR

**Comment by m4z** [comment]
Ok, will do.

**Comment by m4z** [comment]
I will roll this into a new PR sometime next week.

**Pull request closed without merging**
