### PR TITLE
* Reworking the page index to be formatted by the template

### PR DESCRIPTION
**Pull request by live627**
- Document the function more
- Fix page indexes in RTL mode (Antes! Bad kitty! >:D
- Jaavascript won’t work right. The event doesn’t seem to update. I can expand the first 50 pages, but the next click adds the first 50 again. Help? :D

### CODE REVIEW

**Comment by Dragooon** [comment]
Fun question, why not move the whole thing to templates itself? It's simply a page index, doesn't have any significance to source whatsoever.

**Comment by Arantor** [comment]
Oh but it does, incidentally. It has a fun and exciting side property that it sanitises the values being imported. For example, if you're doing something that's 20 per page and you supply a start of 15, constructPageIndex is the one that will be sanitising the value to be at a page boundary rather than an arbitrary start point.

As for styling, moving it to templates is fine for the purposes of offering up better styling - but if sufficient markup is provided, so that most things can be done with CSS, wouldn't that be enough too?

**Comment by live627** [comment]
> Fun question, why not move the whole thing to templates itself?

Wedge did that. IMO, it was a mistake...

**Comment by Arantor** [comment]
I seem to recall I did it. I came to realise it wasn't ideal for this reason. But with suitable classes and whatnot, would that not be enough anyway?

**Comment by live627** [comment]
Maybe it could be rewritten as a class in 3.0, if someone gets tit going.

**Comment by Arantor** [comment]
Don't look at me.

**Comment by live627** [comment]
Definitely not you.

**Comment by Arantor** [comment]
That's a good thing, I don't want the job anyway :tongue: Yes, it probably should be in a class or something in 3.0. Or at least sanely introduced into however the input sanitisation works rather than having two separate jobs done by one thing.

**Comment by live627** [comment]
I know.

**Comment by Dragooon** [comment]
Fair enough I guess, merging this

**Comment by live627** [comment]
Now fix the JS, m'kay?

**Pull request merged**
