### PR TITLE
Stops us from trying to hash validate a directory.

### PR DESCRIPTION
**Pull request by jdarwood007**
I don't see it as worth it to try to generate a hash for a directory to validate, just check the id

### CODE REVIEW

**Comment by Sesquipedalian** [comment]
Will the package validation service accept a request without a hash?

**Comment by jdarwood007** [comment]
It will be ignored and continue to check the others like package id.

We could try to hash a folder, but something as simple as a added file or file ending difference could cause a different hash.

**Comment by Sesquipedalian** [comment]
> It will be ignored and continue to check the others like package id.

Fair enough.

> We could try to hash a folder, but something as simple as a added file or file ending difference could cause a different hash.

Looks like just the opposite, actually. In my tests, I've found that *every* directory produces exactly the same hash, regardless of its name or content: `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`. This is the same hash that is generated by `hash('sha256', '')`, which makes sense, since a directory doesn't have any file content of its own.

**Comment by jdarwood007** [comment]
There are methods to hash a directory: https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents/545413
But in all its similar, you hash all contents one way or another.

**Pull request merged**
