### PR TITLE
Set $upgradeData to null after successful upgrade

### PR DESCRIPTION
**Pull request by sbulen**
To fix this issue:   Upgrader - : unserialize(): Error at offset 0 of 15 bytes in ... upgrade.php on line 125 #3841

### CODE REVIEW

**Comment by jdarwood007** [comment]
Its actually supposed to be removed (the entire line).  I wonder if something else broke elsewhere.

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/41ec30d7a54edf399c67ab21a1cf76ef51bef6b6#diff-cccb32785017365b9e98cf35be9ed3dfL1627

That commit there removed the code that handled this.

@live627

**Comment by sbulen** [comment]
I could not find current code to remove the line, or I would have gone that route.

Setting it to null works, and gets rid of the error ("unserialize(): Error at offset 0 of 15 bytes in upgrade.php on line 125").

**Comment by sbulen** [comment]
FYI, I'm pretty sure this is the only instance of #remove# in SMF.   If this were used elsewhere, we should definitely add that old code back.  But if it's not needed elsewhere, & null works, I'd say let's keep it simple.  

Make sense?

**Comment by live627** [comment]
> 41ec30d#diff-cccb32785017365b9e98cf35be9ed3dfL1627
>
> That commit there removed the code that handled this.

That was when I wanted to recycle that function. Didn't notice it removed stuff.

**Comment by sbulen** [comment]
FWIW, I really think we should not have put the #remove# in there, even temporarily, due to this syntax error.  

It causes different issues for different folks, depending on the contents of their settings.php file.

**Pull request merged**
