### PR TITLE
More fixes to the alerts code

### LINKED ISSUE #5323: Wrong alerts count
#### Description
The count does not restart from 1 once the notifications are read but continues...

### Steps to reproduce
1. Mark read alerts
2. The next alert will have the number 2 and not 1
3. Mark read alerts
4. The next alert will have the number 3 and not 1
5. And so on ...

### Environment (complete as necessary)
- Version/Git revision: RC1 / 4a751c639634055c63dc8440b4963331577024b1
- Database Type: All
- Database Version: All
- PHP Version: All

### Additional information/references

### PR DESCRIPTION
**Pull request by Sesquipedalian**
A follow-up to #5193 that addresses a few more issues with the alerts code. Primary changes are:

1. Aligns what alert_count() reports with what fetch_alerts() actually retrieves.
2. Fixes a problem that could prevent alerts from showing up as browser notifications.
3. If the value of the 'alerts' column in the members table somehow gets messed up, it will be corrected on the fly when the user opens the alerts popup.
4. Fixes #5323

### CODE REVIEW

**Comment by albertlast** [comment]
How often is fetch_alters and count_alerts called?
Is that called only by cron job or everytime a user call a page?

**Comment by Sesquipedalian** [comment]
The fetch_alerts() function is called very often. In contrast, alert_count() is called rarely.

**Comment by vort7u** [comment]
@Sesquipedalian 
Browser notifications are not send to mobile browser, correct?
Thanks

**Comment by Sesquipedalian** [comment]
It depends on which mobile browser you use. Safari on iOS, no. For other mobile browsers, it varies.
https://caniuse.com/#search=push%20API

**Comment by vort7u** [comment]
Thanks for your reply @Sesquipedalian 
I tried again with the latest versions of Opera Mobile, Chrome for Android and Firefox for Android but I do not receive notifications. All browsers have permission to receive notifications from the site with SMF 2.1 (Version https://github.com/SimpleMachines/SMF2.1/commit/8eeff0432c727a35a21491266d6ca37531042be8)

Tested on Huawei Mate 20 Lite (android 8), Honor 6X (android 7), Samsung Tab A (android 8.1), Samsung J5 (android 7)

No problem with desktop version browsers.

Thanks.

**Pull request merged**
