### PR TITLE
Fix #4897: Implement jQuery smiley selector

### LINKED ISSUE #4897: Smileys followup
This is a bit of a placeholder...   

After recent smiley set issues (#4773 & #4767 ) it was decided to rewrite the smiley set code to make it more efficient.  There is a temporary solution out there (#4772 ) that does not address all presentations of smileys, e.g., user selection still doesn't properly display non-png smileys:
image

### PR DESCRIPTION
**Pull request by NanoSector**
This selector iterates over the most common file extensions to find one that's available. Worked in my testing with Firefox.

Signed-off-by: NanoSector <rick.2889@gmail.com>

### CODE REVIEW

**Comment by NanoSector** [comment]
Did I miss any common extensions? BMP maybe?

**Review by jdarwood007 — APPROVED** [review]

**Comment by jdarwood007** [comment]
I'm not going to worry about bmp.  I don't think they should be a supported extension.

**Comment by sbulen** [comment]
I think there was at least one more location...    The editor?

**Comment by NanoSector** [comment]
I forgot SVG in the extensions list.

@sbulen: I think that's a whole different problem and has to be dealt with in another way. Perhaps we can reuse some of this code.

**Comment by sbulen** [comment]
Ok.  I'll log the editor issue.

**Pull request merged**
