### PR TITLE
Added bottom margin to #topic_header columns css

### PR DESCRIPTION
**Pull request by tekkla**
.info col had a different margin setting than the rest. This does not matter as long a you use the default css. But if you change box sizing for all elements with \* { box-sizing:content-box; } the .info column of the first row after heading will be pushed to the right.

Signed-off-by: Michael 'Tekkla' Zorn tekkla@tekkla.de

### CODE REVIEW

**Comment by Oldiesmann** [comment]
Was the bootstrap theme file supposed to be part of this PR or not?

**Comment by tekkla** [comment]
Was not. Verdammt. Sorry. :)

**Comment by tekkla** [comment]
I hope this works. I'm still learning and fighting with eGit in Eclipse.

**Comment by XinYenFon** [comment]
Better close this, create new branch do changes and push :P

**Comment by tekkla** [comment]
Why a new branch?

**Comment by XinYenFon** [comment]
because it allows you to do multi taks, if you keep working only on release-2.1 you may have that type of accidents in future as well :( more importantly if you work on two different parts, either you push all to one branch or separate them into two branch not to wait for others to merge.

**Comment by tekkla** [comment]
Check

**Pull request closed without merging**
