### PR TITLE
The basic user info edit

### PR DESCRIPTION
**Pull request by snrj**
uniform appearance

### CODE REVIEW

**Comment by XinYenFon** [comment]
I clearly say no to this.

**Comment by Oldiesmann** [comment]
@snrj  What's wrong with the current layout, and how does this improve it?

**Comment by snrj** [comment]
before
http://i.imgur.com/i3hwovV.png
after
https://github.com/SimpleMachines/SMF2.1/commit/84c1e5ccc8ce2909fe4503a66fa516fc0ec53513
fix

**Comment by XinYenFon** [comment]
Update your build, there was an error in old build.

**Comment by Oldiesmann** [comment]
The changes made in 84c1e5c will fix the issue you pointed out in the image. An earlier change I'd made that I thought would improve things actually broke several things.

**Pull request closed without merging**
