### PR TITLE
Correct SQL for gender count

### PR DESCRIPTION
**Pull request by albertlast**
issue: https://www.simplemachines.org/community/index.php?topic=575645.0

### CODE REVIEW

**Review by BrickOzp — COMMENTED** [review]
LEFT JOIN will catch all members without a value for cust_gender and display an empty label like
Male: 2
: 2

**Comment by BrickOzp** [comment]
That could be fixed by importing the default value for those who hasn't set any value.
That seems correct since the default value is shown in the profile.

SELECT COUNT(id_member) as total_members, gender FROM (
    SELECT mem.id_member, COALESCE(t.value, (
        SELECT default_value FROM {db_prefix}custom_fields WHERE col_name={string:gender_var})) AS gender
    FROM {db_prefix}members AS mem
    LEFT JOIN {db_prefix}themes AS t ON (
    mem.id_member = t.id_member AND t.variable = {string:gender_var} AND
    t.id_theme = {int:default_theme}) 
   WHERE is_activated = {int:is_activated}) as a
GROUP BY gender

**Comment by albertlast** [comment]
Well since the query is very heavy,
I would fav to make a pre query for default and
add a coalesce,
________________________________
Von: BrickOzp <notifications@github.com>
Gesendet: Donnerstag, 19. November 2020 14:09
An: SimpleMachines/SMF2.1
Cc: albertlast; Author
Betreff: Re: [SimpleMachines/SMF2.1] Correct SQL for gender count (#6347)


That could be fixed by importing the default value for those who hasn't set any value.
That seems correct since the default value is shown in the profile.

SELECT COUNT(id_member) as total_members, gender FROM (
SELECT mem.id_member, COALESCE(t.value, (
SELECT default_value FROM {db_prefix}custom_fields WHERE col_name={string:gender_var})) AS gender
FROM {db_prefix}members AS mem
LEFT JOIN {db_prefix}themes AS t ON (
mem.id_member = t.id_member AND t.variable = {string:gender_var} AND
t.id_theme = {int:default_theme})
WHERE is_activated = {int:is_activated}) as a
GROUP BY gender

**Comment by BrickOzp** [comment]
I think you need that sub query as well. Other wise you could end up with two default value entries, one for those who has selected the default value and one for those who hasn't selected anything.

**Comment by albertlast** [comment]
well in the execution side it make a bit different if the sub query is in the from or select field.
but the behavior in general i testet atm if this on every db so.

okay tested in sqlite, mysql and pg, all behave the same: https://www.db-fiddle.com/f/93Xhi11jceMQy5XdM69RY6/0

**Comment by albertlast** [comment]
Just for my fun,
i tested my and @BrickOzp  version
my https://explain.depesz.com/s/DVqZ
his https://explain.depesz.com/s/IlEW

noteable both run similiar,
because postgres use in his version a initplan (a static sub query).

but i would be not 100% sure if our mysql version 5.0 also got this kind of tricks.

**Comment by smfbigguy** [comment]
Works great. Thank you

**Review by BrickOzp — APPROVED** [review]
Tested and it works

**Review by MissAllSunday — APPROVED** [review]

**Comment by MissAllSunday** [comment]
Hi @albertlast  can you fix the conflicts so this can be merged, please.

**Comment by albertlast** [comment]
done

**Review by MissAllSunday — APPROVED** [review]

**Pull request merged**
