### PR TITLE
Lang tweak

### PR DESCRIPTION
**Pull request by Oldiesmann**
Tweak the area description

### CODE REVIEW

**Comment by live627** [comment]
The 'tism is real!

**Comment by Oldiesmann** [comment]
For future reference, how exactly do we edit files on GitHub without it adding a blank line at the end? I finally had to check out the branch locally and edit the file with phpStorm to get rid of it.

**Comment by albertlast** [comment]
Maybe this could fix it: https://help.github.com/articles/dealing-with-line-endings/

**Comment by Sesquipedalian** [comment]
> For future reference, how exactly do we edit files on GitHub without it adding a blank line at the end? I finally had to check out the branch locally and edit the file with phpStorm to get rid of it.

I don't know of any good way using GitHub's web editor interface. I always work in my text editor.

> Maybe this could fix it: https://help.github.com/articles/dealing-with-line-endings/

Unfortunately not. That describes how to force all files in a repository to use Linux (\n) or Windows (\r\n) line endings, not how to convince GitHub web editor to stop adding a final new line at the end of our files.

**Comment by albertlast** [comment]
When you look at the commit https://github.com/SimpleMachines/SMF2.1/pull/5201/commits/61df0008290739cda19acc3f515922733b6dc833
he didn't add a new line,
he "only" changed the format of the eol.

by thie config this behavior could be changed in the right direction.

**Pull request merged**
