### PR TITLE
Uses redirectexit and fixes #3798

### PR DESCRIPTION
**Pull request by colinschoen**
Use redirectexit instead of manually changing headers. Fixes #3798 

@jdarwood007

### CODE REVIEW

**Comment by colinschoen** [comment]
Fixing indentation, one moment...

**Review by live627 — CHANGES_REQUESTED** [review]
`redirectexit()` calls `obExit()`, and the both of them combined are laced with arsenic and eat the image alive.

**Comment by colinschoen** [comment]
Working locally. What goes wrong when using them?

**Comment by live627** [comment]
iDunno

- Delete the image, refresh page
- use image larger than threshold

**Comment by colinschoen** [comment]
Image larger than threshold is working. I'll try the other tomorrow

**Comment by colinschoen** [comment]
Deleting the image and refreshing the page is also working when checking out this PR locally. Not able to replicate any issues. @live627

**Comment by colinschoen** [comment]
iuemzpzeg7

**Review by live627 — APPROVED** [review]
Derp. I was testing against the wrong version.

**Comment by colinschoen** [comment]
No worries. Thanks for reviewing.

**Pull request merged**
