### PR TITLE
Fix PM SubMenu

### LINKED ISSUE #4141: "New message" doesn't appear in "Message" menu
As a regular member, the "New message" and "Show draft" items don't appear in the "Message" menu. You can only create a new pm or see draft buy using the links in the window from "My Messages" on the top bar.

Permitions are set rights. 
image
Regular user permitions

Menu as admin : 
image

Menu as regular member : 
image

The item appears for administrator.

If i change these permissions to false, items appear. It should be the opposite : 
image

Can someone confirm this?

### PR DESCRIPTION
**Pull request by BloberSh**
permissions for the sub menu set in the Sources/PersonnalMessage.php line 239 and 252 should be respectively `'pm_send'` and not `allowedTo('pm_send')` and `'pm_draft'` and not `allowedTo('pm_draft')`.

Fix #4141 

Signed-off-by: Blober <contact@blober.net>

### CODE REVIEW

**Comment by BloberSh** [comment]
Travis doesn't like this end of file.

Do you know how i can remove this end line when i commit?

**Comment by colinschoen** [comment]
`head -n -1 PersonalMessage.php > PersonalMessage.php.tmp ; mv PersonalMessage.php.tmp PersonalMessage.php`

**Comment by colinschoen** [comment]
Or you just open it with another file editor that doesn't hide the trailing ending line and delete it.

**Comment by colinschoen** [comment]
Any luck?

**Pull request merged**
