### PR TITLE
! comma_format was not formating numbers at all 

### PR DESCRIPTION
**Pull request by live627**

### CODE REVIEW

**Comment by emanuele45** [comment]
In [Load.php line 1653](https://github.com/SimpleMachines/SMF2.1/blob/master/Sources/Load.php#L1653) the $txt is re-set, but only if $txt['number_format'] is empty.
Additionally in [ManageSettings.english.php line 25](https://github.com/SimpleMachines/SMF2.1/blob/master/Themes/default/languages/ManageSettings.english.php#L25) the same index ('number_format') is set to a proper string (to be used as description in ManageSettings.php).

I think some more changes are needed:
1) the index of $txt['number_format'] (the one containing the format) should be something not already used for a label of a setting;
2) the $modSettings should be the first choice (over the $txt) if it is set, something like:
`$txt['number_format'] = empty($modSettings['number_format']) ? $txt['number_format'] : $modSettings['number_format'];`

Does it make sense?

**Comment by live627** [comment]
3My goal here is to have the language files set a default format. I was on a French SMF once, and all the numbers were formatted the French way, even though I used English.

> Additionally in ManageSettings.english.php line 25 the same index ('number_format') is set to a proper string 

Is that a problem? It iis only overridden in the admin panel. Are there numbers in it? Might be prodent to change the index, so as to prevent conflicts...

**Comment by emanuele45** [comment]
I guess you are right (it does make sense to have the setting already there), though that means the admin option becomes completely useless (the admin option is applied only if the time format is not set into the language file).

So or it is removed or it is "reworked" somehow...

**Comment by live627** [comment]
Yes, it does render the admin option somewhat useless. We can remove it for now and if people want it back, we can restore it.

**Comment by emanuele45** [comment]
Or they can just edit the language file. :P

**Pull request closed without merging**
