### PR TITLE
fixing missing id in input

### PR DESCRIPTION
**Pull request by illori**
this should be correct, i did not test all of them.

Signed-off-by: Illori illori@simplemachines.org

### CODE REVIEW

**Comment by live627** [comment]
HTML ID cannot have brackets. Use underscore instead.

**Comment by illori** [comment]
well it did validate for me with the brackets in place on 2.0 using a html5 theme.

**Comment by emanuele45** [comment]
I think they are at least "annoying" to use in javascript, but I may be wrong.
Also:

```
 id="customfield[' . $row['col_name'] . ']"' . ($true ? 'checked="checked"
```

will generate invalid HTML when checked because it will result in:

```
 id="customfield[something]"checked="checked"
```

without space between the two.
Same for the type text and the textarea.

**Comment by Oldiesmann** [comment]
I did find one site that said brackets weren't valid for IDs, but I can't find any official reference to that. However, because brackets have special meaning in CSS (see http://www.w3.org/TR/CSS21/selector.html#attribute-selectors), I think it would be best to use underscores instead.

**Comment by live627** [comment]
w3 trollfest! hahaa :P

**Comment by emanuele45** [comment]
http://www.w3.org/TR/html5/dom.html#the-id-attribute

> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.
> 
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

**Comment by Arantor** [comment]
That's HTML5. We're not using HTML5 yet, therefore the rules from XHTML 1.0 take precedence which are not the same and derive from XML

As per http://www.w3.org/TR/REC-xml/#sec-attribute-types an id must match the Name production which is defined in http://www.w3.org/TR/REC-xml/#NT-Name - and [ and ] are not on the list of NameChars or the NameStartChar.

So finding an alternative it is.

**Comment by emanuele45** [comment]
I thought the doctype was changed a while ago when Lab was working on moving to html5, sorry. ;)

**Comment by Arantor** [comment]
It has occurred to me to do so, however.

**Comment by Arantor** [comment]
Well, now we're using an HTML5 doctype, we can fix this.

**Pull request merged**
